src/scenegraph/Billboard.cpp, src/scenegraph/Billboard.h, src/scenegraph/Group.cpp, src/scenegraph/LOD.cpp, src/scenegraph/Label3D.cpp, src/scenegraph/Label3D.h, src/scenegraph/MatrixTransform.cpp, src/scenegraph/Model.cpp, src/scenegraph/Model.h, src/scenegraph/ModelNode.cpp, src/scenegraph/Node.cpp, src/scenegraph/Node.h, src/scenegraph/StaticGeometry.cpp, src/scenegraph/Thruster.cpp, src/scenegraph/Thruster.h
Cache VertexBuffer buffers for most of the SceneGraph node types that can render.
This is intended to fix #3296 which several people have commented on. @walterar you should be able to see a big improvement with these changes.
Andy
=> Optimise VertexBuffer usage for SG Nodes.

src/ShipCpanelMultiFuncDisplays.cpp, src/graphics/Drawables.cpp
Check we've got verts before drawing and regenerate the scanner properly after loading.
I noticed this was asserting because it was trying to build buffers with zero vertices and draw them.
=> Fix scanner drawing post-load.

src/GameLog.cpp, src/GameLog.h, src/Pi.cpp, src/gui/GuiLabel.cpp, src/gui/GuiLabel.h, src/gui/GuiLabelSet.cpp, src/gui/GuiLabelSet.h, src/gui/GuiScreen.cpp, src/gui/GuiScreen.h, src/gui/GuiTextEntry.cpp, src/gui/GuiTextEntry.h, src/gui/GuiTextLayout.cpp, src/gui/GuiTextLayout.h, src/text/TextureFont.cpp, src/text/TextureFont.h, src/ui/Label.cpp, src/ui/Label.h, src/ui/TextLayout.cpp, src/ui/TextLayout.h
Create and reuse VertexBuffer objects wherever we can for text rendering.
The idea being that this should be faster than the existing code which creates, renders then destroys a great many `VertexBuffer` objects per-frame.
This actually seems slower at the moment, it is a work-in-progress.
Andy
=> Faster text buffer rendering

src/scenegraph/Animation.cpp, src/scenegraph/Animation.h
'Animation::Interpolate' was being run even though the animation time hadn't been changed which is an expensive call. Increasing the number of ships caused it to appear heavily in the profiling.
Doing this here instead of #3320 as that has several optimisations one of which is causing issues.
=> Animation interpolation optimisation

src/Ship.cpp
Base the length of time the ship thrusts for when launching on it mass. 
Limited to max & min.
Should be a temporary kludge to fix [issue raised on forum](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=307).
=> Ship launch thrust timer fix

win32/vc2013Express/modelcompiler.vcxproj, win32/vc2013Express/pioneer.vcxproj
Stop using the whole program optimisation to reduce the build problems for VS2013.
VS2013 only issue, sometimes when building it would fail due to pch and whole program optimisation issues.
I can't see any performance difference so just disabling it to make life more pleasant!
=> Stop vs2013 using the whole program optimisation

src/gui/GuiToolTip.cpp
Update the text layout when we change the text / size so that it creates the text buffer for rendering.
Fix #3322 in the process.
=> Update the ToolTip text layout

.travis.yml, Makefile.am, configure.ac, scripts/nightly-build.pl, src/CargoBody.cpp, src/Game.cpp, src/LuaRef.cpp, src/LuaRef.h, src/LuaSerializer.cpp, src/LuaSerializer.h, src/Makefile.am, src/PropertyMap.cpp, src/PropertyMap.h, src/graphics/WindowSDL.cpp
Bit of a grab bag here. I started thinking that it was the GL linkage that was stopping the modelcomiler running headless, and just kept running with it.
The first thing is to no longer require linking the GL remderer. That happened because we had to link `Pi.cpp` to get `Pi::luaSerializer` for `LuaRef`, which is used in the scenegraph. Its just a bit of refactoring to pass serializer context around where needed. After that the modelcompiler is able to compile without the GL renderer.
So even after that, it still didn't run on a headless machine. That's because SDL couldn't create a GL-enabled window - apparently even SDL's dummy driver still tries to do real GL work. The "right" way to fix this would be to both to a dummy window class and to move the GL setup down into the GL renderer. …
=> modelcompiler no GL, no SDL, build support for compiled models

src/Background.h
The title may be confusing.
Some time ago we switched to having the stars baked into the skybox texture. This is great, it allows for a lot more artist control.
On the downside however is that you can get smearing, stretching and deformation of the skybox image which means that stars being point sources don't always have a constant size.
This is a proposed change to use the skybox for just the galaxy image and have the stars drawn using points. To get a similar look to the skybox only approach we must increase the number of stars by **at least** 10 times. From 10,000 to 100,000 points specifically.
Please test, compare, contrast and let me know what you think as this is more of an artistic / design issue. Do mention however if you suffer from poor performance when using it compared to the …
=> Many point stars on starless galaxy

SAVEBUMP.txt, src/CargoBody.cpp, src/LuaBody.cpp, src/LuaObject.cpp, src/LuaObject.h, src/LuaRef.cpp, src/LuaRef.h, src/LuaSerializer.cpp, src/LuaSerializer.h, src/LuaSystemPath.cpp, src/Makefile.am, src/PropertyMap.cpp, src/scenegraph/LuaModelSkin.cpp
This is fully decoupling the Lua serialization setup from the game proper. The big problem is that LuaSerializer has special knowledge of Lua class wrappers. These should have been hidden away inside the wrappers proper.
So now any class wrapper that wants to be serializable registers a serializer and deserializer with LuaObject. LuaSerializer calls into LuaObject for those. Its all very nice.
And then, if you need to take LuaSerializer as a dependency (eg for simple programs like uitest), you don't need eg Body unless you take LuaBody. And since that depends on Game, you don't need that either :)
I've been careful to keep the savefile format the same. There's a single line we can clean up at next savefile bump. Its noted in SAVEBUMP.txt.
After this, I've got a single commit which will …
=> LuaSerializer refactor

win32/vc2013Express/pioneer.vcxproj
Fix the libcurl linking for Profile, PreRelease and Debug
I hadn't updated the link libraries for those configurations.
=> Fix the libcurl linking for Profile, PreRelease and Debug

src/collider/GeomTree.cpp, src/graphics/Graphics.cpp
I noticed that the modelcompiler had been broken due to some of the optimisation and dummy renderer commits recently.
This fixes up the exporter/importer values for the number of vertices and dummies the renderer setup to avoid calling an uninitialised window pointer.
=> Fix modelcompiler

src/CameraController.cpp, src/CameraController.h, src/ShipCockpit.cpp, src/ShipCockpit.h, src/ShipController.cpp, src/WorldView.cpp
This add mouselook for the internal camera. Intended to be used with the cockpit, but works without too.
Doesn't have any rotational bounds so the cockpit model will probably need to be updated.
Could use more testing too.
=> Mouselook for internal camera

data/shaders/opengl/FresnelColour.vert, data/shaders/opengl/attributes.glsl, data/shaders/opengl/gassphere_base.vert, data/shaders/opengl/geosphere_terrain.vert, data/shaders/opengl/multi.frag, data/shaders/opengl/multi.vert, data/shaders/opengl/shield.vert, src/MathUtil.cpp, src/MathUtil.h, src/graphics/opengl/MaterialGL.cpp, src/graphics/opengl/Uniform.cpp, src/matrix3x3.h
This bug fixes #3366 and cleans up the attributes for `uNormalMatrix` and promotes `a_uv0` too a full `vec4` as it should have been already.
It adds some new utility functions to the MathUtil namespace that I needed during debugging and it seems we should have for greater flexibility anyway.
@nozmajner good catch on this, thank your student for me!
Andy
=> Fix missing specular highlights

src/collider/Geom.cpp, src/collider/GeomTree.cpp, src/collider/GeomTree.h, src/graphics/VertexArray.cpp, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h, win32/vc2013Express/collider/collider.vcxproj, win32/vc2013Express/galaxy/galaxy.vcxproj, win32/vc2013Express/gameui/gameui.vcxproj, win32/vc2013Express/graphics/graphics.vcxproj, win32/vc2013Express/gui/gui.vcxproj, win32/vc2013Express/jenkins/jenkins.vcxproj, win32/vc2013Express/json/json.vcxproj, win32/vc2013Express/lua.vcxproj, win32/vc2013Express/newmodel/newmodel.vcxproj, win32/vc2013Express/pioneer.sln, win32/vc2013Express/terrain/terrain.vcxproj, win32/vc2013Express/text/text.vcxproj, win32/vc2013Express/ui/ui.vcxproj
Profiling was not setup correctly under the visual studio build so it would not capture everything that happened during a frame. I've had some of these fixes locally for a while but always mixed in with other experiments.
This separates out the profiling fixes, removes some pointless profiling calls and removes some unused functions/methods.
=> Fix VS2013 profiling configuration

data/shaders/opengl/planetrings.vert
This fixes #3369 which was caused by the change of `a_uv0` from `vec2` to `vec4`
=> Fix compilation of planetrings shader

.tx/config, data/lang/quitconfirmation-core/en.json, data/ui/MainMenu.lua, data/ui/QuitConfirmation.lua, data/ui/Settings.lua, src/GameConfig.cpp, src/LuaEngine.cpp
Add confirmation for quitting the game, in 17 flavours.
A little homage to great game devs of the 90s like ID Software and Apogee (Doom 1-2, Spear of Destiny, Wolfenstein 3D), by having random confirmation questions. It can be disabled, which is perhaps useful when testing and developing.
This probably isn't the right place to put this option, please advice:
=> Add confirmation for quitting the game

src/CameraController.cpp, src/CameraController.h, src/ShipCockpit.cpp
This fixes #3377 by removing the "cached" values and just converting the actual values using 'DEG2RAD' that are correctly calculated.
I also noticed that some bad formatting had crept in so just blanket reformatted the files involved.
=> Fix #3377 - broken cockpit rotations using headlook.

src/galaxy/StarSystemGenerator.cpp
It seems that I got my maths a little wrong when placing multiple orbitals originally.
This now distributes them evenly around a whole orbit which is still very artificial (hah!) however it does look better than only doing it over half of the available orbit.
Should fix #3388 and I will create a new feature request for the other items listed in it.
=> Calculate the distribution correctly for placing orbitals.

src/galaxy/StarSystemGenerator.cpp
Allow up to 3 orbits a spacestation can occupy, perturb their orbits gently for visual effect.
This is to fix #3390 though it really only satisfies the variation part of it. Actually checking that stations won't collide with other things is mostly taken care of before we reach the relevant methods.
This adds some variations to the orbits of each station which hopefully doesn't mean they will collide, I guess I'll wait for the bug reports to see how that goes ;)
Andy
=> Allow up to 3 orbits a spacestation can occupy.

src/graphics/VertexArray.h, src/scenegraph/Label3D.cpp
Fixes #3391.
This does not solve the underlying problem that we can't render Chinese characters on 3D models. For that we will need to implement on-demand SDF glyph generation. It looks like there's some code to do this in [freetype-gl](https://github.com/rougier/freetype-gl), which we should be able to use.
=> Fix crash when using Chinese languge

src/posix/OSPosix.cpp
You cannot modify dereferenced FILE, this is UB. FILE may also be
opaque type so this code may not compile (and in fact it doesn't
compile on DragonFlyBSD). freopen is quite enough to do the thing.
=> Fix stderr redirection

data/modules/TradeShips.lua, src/LuaStarSystem.cpp
For the problem reported in #3387.
=> Fix inconsistent types for 'imports' and 'exports' variables in TradeShips.lua

src/GeoPatch.cpp, src/GeoPatch.h, src/GeoSphere.cpp
Call CalculateMaxPatchDepth at start of BuildFirstPatches method.
Rename some old methods.
This should fix the case where the terrain doesn't seem to generate enough detail when the game first starts.
=> Fix terrain max depth calculation.

src/libs.h
Proposed fix for the MINGW32 issues found with Windows 8, 8.1 & probably 10 in #3409
For some reason I named the branch "fix3344", just ignore that it was a brain fart.
=> Proposed fix for the MINGW32 issue #3409

src/GeoPatch.cpp, src/GeoPatch.h, src/GeoSphere.cpp, src/GeoSphere.h
To follow #3419 (Numerous Optimisations)...
This delays submissions of the terrain generation requests in order to gather them up, sort them by distance from the camera, then submit them.
This is so that they are hopefully processed by those nearest to the camera first.
=> Sort terrain gen

data/lang/equipment-core/en.json, data/libs/Equipment.lua
I'll make use of #3396 soon enough*, but for now, we don't need to see it in the equipment market.
The code that was there was for testing purposes.
__EDIT:__ (*) https://github.com/impaktor/pioneer/tree/scout-mission
=> Rename bodyscanner, and set it as not purchasable for now,

src/gui/GuiTextLayout.cpp
replace == with is_equal_exact test to silence gcc warning
=> replace == with is_equal_exact test to silence gcc warning

src/gui/GuiTextLayout.cpp
Labels with some empty words set their colour to black. This avoid this
behaviour, just checking if the word is empty. Only if not, the color
is updated.
=> Fixed color of labels starting with empty strings

src/WorldView.cpp
When the ship is docked, the orbit is null, even if the docking object has an orbit. This avoids showing a nan value in first person view.
=> Fixed nan on burn indicator

src/SystemView.cpp
The offset variable was added two times within an expression.
=> Fixed math typo

src/SystemView.cpp
Just a minor fix for the vs2013 build.
Cannot use `constexpr`, just use `const` also usage of `or`, `and`, `not` etc doesn't work in vs2013.
=> Changed/removed some non-portable C++11 usage.

data/shaders/opengl/gassphere_base.frag, data/shaders/opengl/gassphere_base.vert, data/shaders/opengl/geosphere_sky.frag, data/shaders/opengl/geosphere_terrain.frag, data/shaders/opengl/geosphere_terrain.vert, src/BaseSphere.h, src/GasGiant.cpp, src/GasGiant.h, src/GeoSphere.cpp, src/GeoSphere.h, src/TerrainBody.cpp, src/galaxy/StarSystem.h, src/graphics/opengl/GasGiantMaterial.cpp, src/graphics/opengl/GasGiantMaterial.h, src/graphics/opengl/GeoSphereMaterial.cpp, src/graphics/opengl/GeoSphereMaterial.h
Eliminate the scaling of planets since we're using a logarithmic z-buffer for rendering.
This is so that we can batch up the drawing of objects in the scene according to their type (eg: opaque/transparent) sort them so that they render correctly and avoid needless state changes.
Presently this isn't possible because the depth buffer is cleared whenever a shrunken planet is rendered.
This also simplifies the shaders a little which should make them easier to understand :)
=> Remove planetary scaling during rendering.

src/Background.cpp
The latest version, 20150904, fails to build with clang compiler on OS X platform:
```
Undefined symbols for architecture x86_64:
"Background::Starfield::BG_STAR_MAX", referenced from:
Background::Starfield::Fill(Random&) in Background.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The culprit was `BG_STAR_MAX` (and probably `BG_STARMIN` too) were declared `static const` member of the class in the header, but not defined in the source as [stackoverflow](http://stackoverflow.com/questions/4891067/weird-undefined-symbols-of-static-constants-inside-a-struct-class) may describe.
I have no clear idea why it worked with no problem in the previous version, given that the variables have existed for a quite …
=> Fix undefined symbols for static const members

data/shaders/opengl/geosphere_terrain.frag
Should fix #3451 by using `texture` keyword instead of `texture2D` which has been deprecated and which Intel appears to enforce, on Windows, not on Linux or OSX though... hooray for consistency.
=> Resolve Detail Texturing abort

src/Background.cpp, src/Background.h
Fed up with static const compile problem, make C-style defines since Linux/OSX/VS2013 all seem to have differing issues with them. Just switch to using define's that always work everywhere! (for this usage).
Should fix #3454, if you could test this branch @joonicks that'd be very helpful as I cannot repeat the problem you are having compiling using VS2013.
Andy
=> Fix compilation issue due to BG_STARS_MAX/MIN

src/Orbit.cpp, src/Orbit.h, src/SystemView.cpp
Orbit fading have been designed to show the direction of the orbit. This should help the user to better understand the layout of a system without using the time controls.
Here a simple screenshot. For now, I hardcoded when the fading starts, but it could be put inside the options. Now... we have got a problem:
As you can see, when two orbits overlap, things start going crazy. Ideas? Probably, the best one is the check for the same orbits before calling `SystemView::PutOrbit`, but, for now, `Orbit` instances of two bodies that occupy the same orbit but not the same space **are** different.
I was working in my spare time on a completely different system to handle orbits, using the *patched conic approximation* model, but it is taking much more time that I expected, and I have been quite …
=> Orbit fading

data/modules/CrewContracts/CrewContracts.lua
Fixes #2636: The advert list was created by appending **first** the persistent candidates, **then** the nonpersistent ones, thus botching the table keys to remove the nonpersistent candidates, now the nonpersistent candidates gets added **first**, maintaining the correct table key order, **then** the persistent gets added, since they don't have to be removed from any list.
=> Fixes #2636: Crew-for-hire duplicate/disappear

src/SystemView.cpp, src/SystemView.h
This is really 3 changes. 2 minor and one a little bigger.
The bigger change is avoiding the allocation and deletion of the former 'colors' buffer per-orbit / per-frame.
This is now a member variable that is initialised to the maximum number of vertices during construction. I also replaced the 'vts' array with a similar arrangement. The buffer is allocated once, fixed in size, and the code just uses as much of it as it needs.
The other 2 changes are that I've shortened the distance before the orbit fades out from 25% of the orbit to 15% and then I've made it fade to a much darker colour.
Personally I think that this looks much nicer and shows the direction thanks to the fading much better.
=> Fade orbits faster and darker

COMPILING.txt
Per request of #3443, description for building and installing pioneer using [Homebrew](http://brew.sh/) package manager on Mac OS X is added.
By the way, `pioneer` package is not merged to the public yet, waiting for CI test. Also a new formula for the latest version (20150904) is on waiting for submission. I'll ping this thread once all done.
=> Add description for Homebrew on OS X

data/shaders/opengl/FresnelColour.frag, data/shaders/opengl/FresnelColour.vert, data/shaders/opengl/billboard_sphereimpostor.frag, data/shaders/opengl/billboard_sphereimpostor.vert, data/shaders/opengl/gassphere_base.frag, data/shaders/opengl/gassphere_base.vert, data/shaders/opengl/geosphere_sky.frag, data/shaders/opengl/geosphere_sky.vert, data/shaders/opengl/geosphere_terrain.frag, data/shaders/opengl/geosphere_terrain.vert, data/shaders/opengl/multi.frag, data/shaders/opengl/multi.vert, data/shaders/opengl/planetrings.frag, data/shaders/opengl/planetrings.vert, data/shaders/opengl/shield.frag, data/shaders/opengl/shield.vert, data/shaders/opengl/skybox.frag, data/shaders/opengl/skybox.vert, data/shaders/opengl/starfield.frag, data/shaders/opengl/starfield.vert, data/shaders/opengl/ui.frag, data/shaders/opengl/ui.vert, data/shaders/opengl/vtxColor.frag, data/shaders/opengl/vtxColor.vert, src/graphics/opengl/Program.cpp
This is a primitive, slightly hacky even, `#include` preprocessor for the shader files.
Currently when building a shader we add the other included glsl files for attirbutes, logz and library methods in hardcoded calls even for shaders that will not use them.
In future therefore when we add GPU noise shaders and their support functions everything would include those as well.
Supporting a simple `#include` macro means that each shader can include only what the shaders author wants including.
I have added the necessary `#include` to each file, probably unnecessary ones too as I just copied and pasted the three usual suspects into each file.
I've been a little lazy with the filename construction and used an `sprintf` which I should probably tidy up but it's late and I couldn't think straight …
=> GLSL preprocessor includes

data/libs/Equipment.lua, data/ui/StationView/EquipmentTableWidgets.lua
step 2 would be to alter the ship mechanic to actually being able to
purge it from the ship if the player so wished...
=> Make trade analyzer module into a non-removable module

data/libs/Equipment.lua, data/ui/InfoView/ShipInfo.lua, src/LuaShip.cpp, src/Ship.cpp, src/Ship.h, src/SystemView.cpp, src/WorldView.cpp
This should fix issue #3477 where the jump range was miscalculated as it did not account for the mass of the fuel aboard the ship.
Also takes into account the fuel for the hyperspace duration.
Changed `totalMass` to `staticMass` since it represents the unchanging mass of the ship rather than the dynamic mass of the fuel which will change through usage.
I have kept the old value of `totalMass` around for backwards compatibility with mods and forks of Pioneer like Scout+/Paragon/etc.
Thanks @joonicks for finding the issue and suggesting the fix.
=> Account for the fuel mass in hyperspace range calculation.

src/Body.cpp, src/SpaceStation.h, src/WorldView.cpp, src/terrain/TerrainHeightBarrenRock.cpp
This was a pain to diagnose but this PR should fix #3441
Unlike all of the other terrain generation values the final value of `n` was being calculated like this:
`n = m_maxHeight*2.0*n*n;`
Which seems to have been producing values which caused us NOT to transition to the correct `Frame` as we approached the planet.
The planet is still as flat as a pancake though, it's very odd and I'm wondering if the fractals are behaving as expected or if something is broken with them.
=> Bad Terrain, no cookie!

src/Game.cpp
This allows forced time acceleration (Ctrl + click on respective time acceleration) in cases where ships are close but are not firing. Before, forced time acceleration was only allowed if close to bodies other than ships. With this enabled we can work on missions where ships travel together (wingmen, etc.).
=> Fix forced time acceleration

src/graphics/opengl/RendererGL.cpp
This should help fix #3494
Recently I have noticed that we've had an increase in the number of players asking why the game won't run. I think that this is partly down to the current message saying that something has failed but without giving any explanation.
This new message should be clearer and present the only possible solution, updating their GPU driver.
=> Present a clearer warning to the user if OpenGL fails to initialise.

data/shaders/opengl/eclipse.glsl, data/shaders/opengl/gassphere_base.frag, data/shaders/opengl/geosphere_sky.frag, data/shaders/opengl/geosphere_terrain.frag
This moves most of the code for the Eclipse stuff into a separate `eclipse.glsl` library file that can be included with our `#include` macro.
Eventually I would like to change this to use [OpenGL Uniform Buffers](https://www.opengl.org/wiki/Uniform_Buffer_Object) but that's a more extensive rewrite and this is just a neat cleanup to make that future work easier.
All functionality should be exactly the same.
Andy
=> Eclipse tidy

src/ShipCpanel.cpp, src/ShipCpanel.h, src/ShipCpanelMultiFuncDisplays.cpp, src/WorldView.cpp, src/utils.cpp, src/utils.h
I would like to add a latitude/longitude display to the player hud. This will be useful for any mission that requires finding or returning to a specific location on a planet. Currently, I use lat/lon for my search & rescue mission script where ships have crashed and the player is asked to go to the crash site and rescue personnel, deliver fuel, etc.
I need some feedback on where the lat/lon info should be placed. Lat/Lon info is shown whenever the player is close enough to a planet to also show altitude. This pull request puts it in two places (just for testing) - centrally above the scanner, and on the right of the screen right above the panel (see screenshots below). The position above the scanner is problematic though because the relative speed info can run into it (see second …
=> WIP: show latitude/longitude

src/Game.cpp, src/Space.cpp, src/Space.h, src/SpaceStation.cpp
This fixes #3493 but it does so by modifying the generation of new positions for stations which could have wide ranging (_affects **ALL** stations everywhere_) consequences.
This will need testing quite a lot and will invalidate all existing save games.
=> Station placement

data/lang/module-fuelclub/en.json, data/modules/FuelClub/FuelClub.lua
Adds three new fuel clubs (we only had one):
- _The Federal Fuel Foundation_ 400 credits/y, (spawn rate in fed space: 40%)
- _The Confederate Fuel Union_ 300 credits/y, (spawn rate in CIW space: 40%)
- _Haber Propellant and Perishables Division_ 600 credits/y, (spawn rate in Haber space: 100%)
Now we can specify how common (spawn probability) each flavour is depending on faction.
The three new fuel clubs only exist in their own faction space. For other factions they get Interstellar Pilots' Fuel Co-operative (40%).
(In current master, it's Interstellar Pilots' Fuel Co-operative (30%) for all BBS's)
In some SolFed and CIW space, some stations can have two fuel clubs, the other being Interstellar Pilots' Fuel Co-operative. However, Interstellar Pilots' Fuel Co-operative spawns 0% in Haber …
=> Introduce faction specific fuel clubs

data/lang/ui-core/en.json, data/libs/Equipment.lua, data/libs/SpaceStation.lua, data/libs/autoload.lua, data/ui/StationView/EquipmentMarket.lua, data/ui/StationView/Lobby.lua, src/LuaObject.cpp
Here I go again with one of my "limit game content exposure to player", but I'm very happy with this one as it really improves the game I think, making each station a bit more unique. This implements what I discussed in the top post on the dev-forum [Tech Levels for ship equipment](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=235), by giving each station a tech level, with some distribution (the [convolution](https://en.wikipedia.org/wiki/Convolution) of two square waves), which then influences what equipment is supported (bought/sold) on in the equipment market. (Note: this does not affect the Second Hand market module on the BBS, which I think is as it should be).
Tech levels lead to more interesting game play I think (pretty much exactly like in Frontier):
- "Oh, this was a …
=> Introduce Tech Level to stations - makes them more unique

src/ShipCpanelMultiFuncDisplays.cpp
Separate the missile icons by a fixed size if using the compact scanner for equally compact equip usage page.
Inspired by seeing how fulgy it currently is, also fixed some indentation.
=> Compact Use Equip Widget

data/modules/CargoRun/CargoRun.lua
When landing first check what mission cargo should be unloaded,
before trying to load potential new mission cargo.
Should solve issue described at [SSC](http://spacesimcentral.com/ssc/topic/5282-announcement-big-update-adventurous-test-pilots-needed/#entry55869):
> 8. Almost forgot. It'd be nice if starports first unloaded all mission wares before attempting to load new ones. For example, if I'm due to pick up 5t of cargo on station A, but arrive there short a couple tonnes of space, they will say "come back when you have space". But I might be carrying mission cargo to that station A at the same time. So they unload me, cargo hold frees up, but now I have to undock/dock (and pay the fees again!) only to be able to load those 5t.
__NOTE:__ I have not tested this, other than in my head.
=> Fix CargoRun stuffing.

src/BaseSphere.cpp, src/BaseSphere.h, src/scenegraph/Billboard.cpp
There are a lot of places where we use the `VertexArray` class as an intermediary buffer whilst building the geometry that we wish to display. 
This is really helpful in some places, such as string buffers, however it can come with some downsides such as:
* Rendering requires `VertexBuffer` objects which must be created, populated, rendered & destroyed per-frame.
* Needless copying, we fill one buffer then copy it straight to another.
* Missed optimisation opportunities, there's a lot of places where we could be using `PointSprites` or other ways of grouping billboard type objects.
There's probably more too, some of these go through multiple stages which could be applied more directly and thus more efficiently.
So far I've identified this lot to change:
Andy
=> Direct buffer population

win32/vs2015/modelcompiler.vcxproj, win32/vs2015/pioneer.vcxproj
I have been busy updating some of the libs to be built against Visual Studio 2015 so that you don't need VS2013 to be installed when building Pioneer on windows, just 2015.
I don't think that I've gotten them all yet due to some ... fun with zlib and libcurl but I'm nearly there.
This must be merged at the same time as the [PR on pioneer-thirdparty](https://github.com/pioneerspacesim/pioneer-thirdparty/pull/17)
=> Updated vs2015 libraries and DLLs

data/shaders/opengl/attributes.glsl, data/shaders/opengl/multi.frag, data/shaders/opengl/multi.vert, src/graphics/Material.cpp, src/graphics/Material.h, src/graphics/Types.h, src/graphics/VertexArray.cpp, src/graphics/VertexArray.h, src/graphics/opengl/MultiMaterial.cpp, src/graphics/opengl/Program.cpp, src/graphics/opengl/Program.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/VertexBufferGL.cpp, src/graphics/opengl/VertexBufferGL.h, src/scenegraph/BaseLoader.cpp, src/scenegraph/BinaryConverter.cpp, src/scenegraph/Loader.cpp, src/scenegraph/LoaderDefinitions.h, src/scenegraph/Parser.cpp, src/scenegraph/StaticGeometry.cpp
Updated (*optional*) normal mapping based on work that Luomu did several years ago.
To use normal mapping on an object just open it's `.model` file and add a line like `tex_norm NormalMap.dds` too it and of course the normal map with that name.
Job done, object is now normal mapped.
To test this you can delete the `wave.sgm` file within `data/models/ships/wave` and then try my [wave-normap-map.zip](http://quantum-thoughts.net/Pioneer/wave-normal-map.zip) mod which looks really ugly and will prompt @nozmajner into an artist frenzy :P
Andy
=> Normal Mapping for objects (ships, stations etc)

src/JobQueue.h
Usage of `std::move` was being warned against in one place as an anti-optimisation so I have removed it. Which fixes #3523 again :P
=> Fix the last real Clang warning

COMPILING.txt, contrib/miniz/miniz.h, osx/SDLMain.h, osx/SDLMain.m, osx/install_ports.sh, osx/package/Distribution.xml, osx/package/pioneer.plist, osx/pioneer.xcodeproj/project.pbxproj, osx/pioneer.xcodeproj/project.xcworkspace/contents.xcworkspacedata, osx/pioneer.xcodeproj/xcshareddata/xcschemes/GenGitVersion.xcscheme, osx/pioneer.xcodeproj/xcshareddata/xcschemes/pioneer.xcscheme, osx/pioneer.xcworkspace/contents.xcworkspacedata, osx/pioneer.xcworkspace/xcshareddata/pioneer.xccheckout, osx/pioneer/pioneer-Info.plist, src/graphics/opengl/LineMaterial.cpp
Hi guys,
this is my first commit to Pioneer so feel free to hit me with your comments and requests if I did something the wrong way. 
The main goal of this commit is to update the project file for XCode on Mac OS X. The old version was clearly outdated as several files that were listed in the project were missing from the file system, and vice-versa. I've spent some time fixing the project by synchronising it with the file system, upgrading references to the latest version of the relevant libraries, etc.
The project now builds without errors on Mac OSX 10.10 (Yosemite) and XCode 6. The resulting App runs smoothly and seems even better than the official Mac OS X build that I have downloaded from the web site, since the compiled version does not crash if I try to start from a station …
=> Fixed XCode Project file

src/ShipType.cpp
The Lua code used the name `cockpit` to define what cockpit model to load but in the change to the JSON format it was altered too `cockpit_model` only none of the JSON files used that!
So I've reverted it to `cockpit` and now everything should work as intended.
I've also disabled the `ALLOW_LUA_SHIP_DEF` code since all of our ships and models are now in JSON format.
=> Fix cockpit loading

data/facegen/readme.txt, src/FaceParts.cpp
Two code changes (hacks) to make life a bit easier for our character artist Evarchart:
* No need to duplicate part files to make a male and female copy. For heads, eyes, noses, mouths and hairstyles, a file name of the form `head_0.png` (ie, just containing one number) will be treated as "can work with any gender". A file name of the form `head_0_1.png` (ie, containing two numbers) will be treated as working with being specific to a single gender (indicated by the first number in the filename -- in this example, gender 0).
* No need to crop and offset individual character parts. If a part image is the full size (exactly 295x285 pixels) then it will be used with no offset applied. So you don't have to work out where to crop the different layers to place them correctly.
Technical note: This …
=> FaceParts improvements

data/libs/Legal.lua
Avoid game crash because of no station in system.
=> No law enforcing station in system

src/GameConfig.cpp, src/Pi.cpp, src/ui/Box.cpp, src/ui/Box.h, src/ui/Context.cpp, src/ui/Context.h, src/ui/Image.cpp, src/ui/Image.h, src/ui/Margin.cpp, src/ui/Margin.h, src/ui/Table.cpp
Old UI used a uniform 800x600 unit design grid, which meant that if you had more pixels everything would be stretched to fit. New UI uses a fluid layout system and pixel units, which is more flexible but results in some UI components being very small when shown on a high DPI display.
New UI already has some support for applying uniform scaling in the UI 'Skin'. This is principally used to cope with displaying the user interface on low resolution screens -- squeezing the UI if the game window is smaller than 1027x768. This PR extends that scaling support to apply the scaling factor to more things, and to allow it to be set in the pioneer config.ini.
=> New UI scaling (HiDPI) support

contrib/pcg-cpp/pcg_extras.hpp, contrib/pcg-cpp/pcg_static_arbitrary_seed.hpp
The implementation of static_arbitrary_seed uses the __DATE__ and __TIME__ macros. These macros prevent ccache from caching any file that includes pcg_extra.hpp (which is most of our codebase).
I want ccache to work, and we don't use static_arbitrary_seed, so let's just pull it out into a separate header that we can ignore.
=> Extract pcg static_arbitrary_seed to a separate header

src/Pi.cpp
#3552 introduced a regression for new-ui layout on small displays. As reported by magagnarata on IRC, it looks like this:
Previously, new-ui would automatically use a scale factor less than 1 for displays smaller that 1024x768, but because #3552 made the scale factor explicitly configurable this broke the auto-scale.
This PR forces a more useful scaling factor for small displays (ignoring the UIScaleFactor config value).
=> Fix UI scaling for small displays (under 1024x768)

data/lang/module-searchrescue/en.json, data/modules/SearchRescue/SearchRescue.lua
If a mission requires you to come back to the station after meeting with the target ship (i.e. to rescue stranded passengers) this information will be shown in the mission screen. Compare both screenshots below for a mission that does not and one that does require you to come back.
This is in response to this issue raised: #3559.
=> Add return location to mission screen for Search & Rescue missions

src/GeoPatch.cpp, src/GeoPatch.h, src/GeoPatchContext.cpp, src/GeoPatchContext.h, src/GeoSphere.cpp, src/GeoSphere.h
To avoid costly checking and maintenance of the state of neighbouring GeoPatches I have removed that information from them. This means that each patch only knows about it's parents and it's children.
This simplifies the creation of the GeoPatchContext indices but makes filling each patches vertexbuffer a little more complex. It can probably all be simplified further in the future.
NB: Just realised that it already adds them to a queue and sorts them by distance, and who wrote that? ... I did!
=> Remove the neighbour system from GeoPatch

data/systems/00_sol.lua, src/text/TextureFont.cpp
Based on [this SSC thread](http://spacesimcentral.com/ssc/topic/5282-announcement-big-update-adventurous-test-pilots-needed/?p=56349).
I also found a bad NaN which caused the string to inf-loop.
=> Deimos Seed

data/lang/ui-core/en.json, data/libs/Ship.lua, data/ui/InfoView/EconTrade.lua, src/LuaShip.cpp
This PR adds a pump down button the EconTrade screen.
The player can pump fuel to the cargo slot to save fuel for a return route or jettison fuel to reduce mass if gravity is to high to land.
=> Added pump down button to the EconTrade screen

data/modules/CargoRun/CargoRun.lua
This fixes the behaviour that the player couldn't take a cargorun pickup mission if he hasn't enough free cargo space at the moment. laarmen advised me to use the equipment API but until the volume/mass thing is improved this PR seems to be the only practical solution IMHO.
=> Flying empty fix

osx/pioneer.xcodeproj/project.pbxproj
The Mac OS X / xCode project has been updated so as to include our own version of the OpenSSL library directly into the Pioneer App. This is necessary because with the latest OS X v.10.11 (El Capitain) Apple removed the libssl headers entirely, making it much harder to use the OpenSSL shared library, which was deprecated since 10.7.
Further information is available here:
https://forums.developer.apple.com/thread/3897
http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html
Note that this PR also resolves the latest feedback reported in #3560
=> Fixed xCode project to deal with the OS X 10.11 / OpenSSL issue

src/Pi.cpp, src/Pi.h
Whilst investigating #3574 I noticed that the DetailLevel struct was not being fully initialised so I've changed it too a class and fully initialise all members to `0` within the default constructor.
=> Make DetailLevel a class and initial all members by default.

data/lang/core/en.json, src/LuaGame.cpp
Make the GAME_LOAD_CANNOT_OPEN error message more useful. The error message mentions permissions, but 99.99% of times the problem is that the requested file doesn't exist.
For #3576.
=> Improve the error message when a save game cannot be opened

osx/pioneer.xcodeproj/project.pbxproj
Some recent comments to #3560 made it necessary to edit the xCode project to make the application fully compatible with Mac OS X 10.11 El Capitan. 
The current version embeds all the libraries that had been deprecated in a previous version of Mac OS X and are not further distributed with the OS, starting with 10.11.
=> Extra fixes to the xCode project for Mac OS X 10.11 (El Capitan)

data/systems/custom/00_barnard_s_star.lua, data/ui/MainMenu.lua
This is an update to Barnard's star, I've already posted on the dev forum a couple of weeks or so ago.
Small system compared to Sol, with 5 planets and a bunch of moons. Some of them have settlements, OPLI branches, and an orbital station orbiting the sole gas giant. The two high security prisons are in the L4 and L5 points of the gas giant (faked of course), with the same orbit they had before.
The bodies are named after the twelve causes of suffering, from Buddhism, and the settlement names are on the same line of thought as the two High Security Prisons.
The first two planets are ocassionally inside the habitable zone of the star (according to Universe Sandbox 2, where I designed the system mostly.)
I've kept the original system description, only updated the line about it being empty, …
=> Barnard's star update

data/lang/ui-core/en.json, data/ui/Settings.lua, src/GameConfig.cpp, src/LuaEngine.cpp, src/ModelViewer.cpp, src/Pi.cpp, src/graphics/Graphics.h, src/graphics/Texture.h, src/graphics/TextureBuilder.cpp, src/graphics/TextureBuilder.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h, src/graphics/opengl/TextureGL.cpp, src/graphics/opengl/TextureGL.h, src/modelcompiler.cpp
This adds (_optional_) [Anisotropic Texture Filtering](https://en.wikipedia.org/wiki/Anisotropic_filtering) so that our texture remain crisp and beautiful as the day our hardworking artists crafted them despite viewing them from shallow angles.
This is optional because on my little Linux test machine it reduces the framerate from __20 fps__ to __11 fps__ which some people may not enjoy.
=> Anisotropic Texture Filtering

src/GasGiant.cpp, src/graphics/opengl/RendererGL.cpp, src/text/TextureFont.cpp
TextureDescriptor usage updated to fix off-by-one initialisation problems caused by anisotropic filtering feature.
This should fix #3590
=> TextureDescriptor usage updated

src/ModelBody.cpp
Always supply a light to avoid dereferencing invalid memory.
Allows us to view objects like stations and ships within ObjectViewer again.
Andy
=> Fix ObjectViewer crash/hang

contrib/profiler/Makefile.am, contrib/profiler/Profiler.h
The idea here is to make std::chrono available for use in the builtin, intrusive, Profiler we use within Pioneer.
This helps us to get rid of the x86 specific assembler code which makes 64-bit Pioneer easier for all platforms and it means we can build on non-x86 processors. In this case I've tested it by building for my Raspberry Pi 2 - __NB:__ don't get excited, `building` doesn't mean `working`- it's just one more obstacle removed from the road.
From my initial testing it seems that the way I'm using std::chrono might impose a tiny bit more overhead, and possible be a tiny bit less accurate. However all of the measurements are relative to one another and so the overall usability for profiling purposes seems to be unaffected.
Andy
=> Optional use of std::chrono for Profiler

src/scenegraph/BinaryConverter.cpp, src/scenegraph/BinaryConverter.h, src/scenegraph/Loader.cpp
Fail-back to the model definition files with a warning when we hit a bad SGM file instead of throwing an exception.
As we change the __SGM_VERSION__  we don't want to break mods and other things that can be simply updated or fixed. Especially when we have all the data we need to keep running in the original `.model`, `.dae` and other files present.
So instead of raising and exception we first try to fail-back and load the original data, only if that fails will we raise an exception.
Andy
=> SGM graceful failure

contrib/vcacheopt/vcacheopt.h, src/GasGiant.cpp, src/GeoPatchContext.cpp, src/GeoPatchContext.h, src/SpeedLines.cpp, src/collider/GeomTree.cpp, src/collider/GeomTree.h, src/graphics/Drawables.cpp, src/graphics/Drawables.h, src/graphics/VertexBuffer.h, src/graphics/dummy/VertexBufferDummy.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/VertexBufferGL.cpp, src/graphics/opengl/VertexBufferGL.h, src/gui/Gui.cpp, src/scenegraph/BinaryConverter.cpp, src/scenegraph/CollisionGeometry.cpp, src/scenegraph/CollisionGeometry.h, src/scenegraph/CollisionVisitor.cpp, src/scenegraph/CollisionVisitor.h, src/scenegraph/Loader.cpp, src/scenegraph/Model.cpp, src/scenegraph/StaticGeometry.cpp
Currently we're limited to 65536 vertices in a models mesh due to using 16-bit indices.
This PR changes the rendering to use 32-bit (_unsigned_) indices which allows for many more vertices in a single mesh.
Andy
=> Convert geometry to use 32-bit indices

data/ui/InfoView/ShipInfo.lua
Sometimes the model spinner shows the wrong ship painting on the ship info screen. This should fix it.
=> Show the correct pattern on the ship info screen

src/posix/OSPosix.cpp
The "domain" field of struct utsname is a GNU extension. OS X is not the only system which does not have the "domain" field (actually, almost no systems do). So, it makes more sense to check if we're GNU-like instead.
=> Fix #ifdef to allow compilation on various BSDs.

data/modules/SearchRescue/SearchRescue.lua
During the last update to the script I realized that aircontrol characters were never saved. Fixing this surfaced an old bug with the original script that was hidden before (using station object as table key instead of station.path object).
This should fix  #3606 and allow saving the game again.
=> Search&Rescue Script: fix serialization issue (#3606)

src/ui/TextLayout.cpp
Rebuild the vbuffer if the vertex count doesn't match new and old text.
Hopefully this should fix #3609 although I couldn't reproduce it myself.
If @walterar could take a look that would be great!
=> Fix for console window crash.

contrib/vcacheopt/vcacheopt.h
Thanks to @salborrelli spotting these (#3610) type narrowing conversions I've figured out the cause and fixed them.
=> Fix the vcacheopt type narrowing conversions that I caused.

data/libs/SpaceStation.lua
@clausimu  pointed out this bug.
Police were spwning in opposite probability as they should, with respect to `lawlessness`.
Just to check sanity: here is the new _average_ number of spawned police ships for a stion with five pads, and a station with nine or more (caped). x-axis stops at 0.99, thus not shown is `lawlessnss=1`, in which case no police will be spawned.
=> Fix number of police ships not being spawned in right amount

data/libs/Character.lua, data/libs/Ship.lua
This is a fix for the Ship:GenerateCrew() method - and the game crash if Character.lua is imported by Ship.lua
Character.lua was importing Ship.lua but didn't use it. Instead, Ship.lua needed to import Character.lua for its Ship:GenerateCrew() method. But importing Character.lua there would cause the game to crash (circular reference...). 
I don't know why this was never noticed before - I guess nobody every used Ship:GenerateCrew(). It is working now.
=> Fix Character.lua / Ship.lua import relationship

src/LuaConsole.cpp, src/Pi.cpp, src/Pi.h, src/ShipCpanel.cpp, src/ShipCpanel.h, src/UIView.h, src/ui/Context.cpp, src/ui/Context.h
This request is the natural follow-up to a discussion we recently had in the Dev forum, namely:
http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=385
In short: so far the effect of pressing the ESC key has been to pause the game and open the Settings View, regardless of the context we are in at the moment. I have changed this so as pressing the ESC button is now someway closer to what normal users might expect, and probably more useful as well.
Please review the attached Excel file for a description of the new effect of pressing the ESC key depending on the current context. Let me know if you find any problem or bug in the implementation.
[esc_key.xlsx](https://github.com/pioneerspacesim/pioneer/files/112465/esc_key.xlsx)
=> New behaviour of ESC button

data/modules/SearchRescue/SearchRescue.lua
This is a fix for the SAR (Search and Rescue) mission script where partially completed missions were treated as completed by the target ship (wrong!) without properly closing the mission and paying the player (right!). Taken together, this could lead to missions that the player cannot complete and never close.
This fix does not address the issue where fuel can't be transferred to target ships even though the player has enough on board. I still can't reproduce that bug on my system.
=> SAR - fix termination of mission for partially completed missions

src/graphics/opengl/RendererGL.cpp
Warn about possible cause of a 'GL_INVALID_OPERATION' for Windows platform.
This is in response to #3619 and #3478 which can be a nightmare to diagnose remotely - it does not fix #3478 though which is a separate issue that manifests in a similar way.
=> GL_INVALID_OPERATION warning (win32)

src/GeoPatch.cpp
Offset the skirts by the lowest patch height keep them as small as possible, reduces fillrate needs for shaders hopefully improving fps.
=> Reduce size of terrain patch skirts.

src/BaseSphere.cpp, src/BaseSphere.h, src/GasGiant.cpp, src/GeoPatch.cpp, src/GeoSphere.cpp, src/ShipCockpit.cpp, src/graphics/Drawables.cpp, src/graphics/Drawables.h, src/graphics/VertexArray.cpp, src/graphics/VertexArray.h, src/graphics/opengl/VertexBufferGL.cpp, win32/vs2015/pioneer.vcxproj
I took a break from my current multi-month projects to profile some performance, this the resulting PR.
The main one on the list is the replacemant in 'BaseSphere' of the many tiny pieces of atmosphere geometry with a single call to 'Sphere3D' which puts a solid sphere with no culling around the whole planet. 
It removes 20+ buffer mappings, VertexBuffer updates and rendering with a single draw call of a static chunk of data.
Have now tried a few other worlds and everything looks fine :)
Andy
=> Rendering cleanup, possible perf improvements.

src/SystemInfoView.cpp
This should fix the #3631 crash which was caused by it dereferencing a nullptr.
=> Only get the SystemBody pointer on system bodies and NOT on ships.

src/ModelViewer.cpp
Commit: `A more flexible use of tag_gun_ to support any number of gun mount points.`
The only ship setup to use the experimental, `modelviewer` only, `tag_gun_` is the `dsminer` and it got the names wrong in the `.dae` file :) probably due to an exporter/converter issue.
It was doing an exact match on the names `tag_gun_left` & `tag_gun_right` which were both suffixed with `001` in the `.dae` meaning that it didn't work anymore (_if it ever did_).
I was doing something else when I figured this out, it remains a good example of attaching/removing objects to a ships scenegraph at runtime. This may also be a good base for adding externally visible weapons etc.
=> gun locator tag fix

src/LuaPlayer.cpp
This is for @walterar, the game can set combat and nav targets to `nullptr` to disable them, so the Lua should be able too as well.
=> Ability to set Combat and Nav targets to null validly.

scripts/ShipPlanner015.py
I thought I update that ship stat planner addon I made for Blender a while ago with the changes in the equipments. I also gave it another go with the export functionality, and it seems to be working, so here it comes.
It should be pretty straightforward to use (at least I hope). It can be found in the Scene settings in the Properties window.
You can set up everything in it, no need to edit the output.json apart from renaming it if name's not good.
It calculates accelerations with full and empty ship, and also calculates deltaV.
For most of the equipments it only includes them in the file if they aren't on their default values. I kept some lines around even if they are at their default though, like cargo capacity and so.
I did some testing and it worked fine for me, but I guess I made some …
=> Ship stat planner addon for Blender. Exports ship.json

src/ModelViewer.cpp
Redirect stdio output for errors and out to output.txt file so that errors and warnings can be found after it shuts down.
=> Redirect stdout for modelviewer mode

data/ui/FileDialog.lua, src/ui/LuaWidget.cpp
This PR has three purposes:
1. Show that I'm still alive.
2. Remove code that I think is redundant
3. an excuse to poke at @johnbartholomew, and see if he still lives :smile:
So on point 3: In October 2013 you added an additional way to disable/enable buttons, with `button:SetEnabled(bool)` @bc73254f0252c855751e56fe4532d46be8518020 but I don't see how that method adds anything that isn't already there with `button:Disable()`, and `button:Enable()`. Sure, that method saves you the need to wrap the Disable/Enable in an if-statement in some cases, but two different API functions for doing the same thing seems odd to me, just for that one-line trick in Lua. I could be completely wrong of course.
=> Remove redundant LuaAPI function for Disable/Enable buttons.

src/Pi.cpp
I maaged to get this crash where `tname` was somehow `nullptr`, I think this depends on you switching from the `objectviewer` mode straight into one of the `F2` subscreens.
Never could reproduce it but this was an obvious crash and an easy fix.
=> Fix rare crash.

src/vector2.h
I had a need/use for the vector2f class with double precision so I updated this to be template based and then defined `vector2f` and `vector2d`.
Then decided that since the branch won't be ready for a while it would be worth bringing the change over to master separately.
=> vector2 template class

data/ui/StationView/CommodityMarket.lua, src/ui/Button.cpp, src/ui/LuaWidget.cpp, src/ui/Skin.cpp, src/ui/Skin.h, src/ui/SmallButton.cpp, src/ui/Widget.cpp, src/ui/Widget.h
At the moment disabled buttons are always grey. This implements a state where disabled buttons just "blend" into the background. This is needed to make the suggested PR #3603 look like @nozmajner's mockups in #3602.
(applied to #3603 )
No more than 3 brain cells were harmed during this implementation. It's a pure copy-paste-rename operation on the `Disabled()` state of `ui/Widget.{cpp,h}`, in the most stupid way possible.
Now Invisible state is done by not having the widget being a `BorderedRectBox` but a  `Color` instead.
Like I said, it works, but feels as wrong as those funny feelings you had when seeing that distant hot cousin each Christmas. so I think this should be considered before merge:
_PS. I don't have any cousins, but it's better this way_
=> Invisible disabled button for commodity market

data/shaders/opengl/multi.frag, osx/pioneer.xcodeproj/project.pbxproj
Replace old shader method `texture2D` call with `texture`, update XCode project with missing files.
Fixes #3651
=> Fix OSX shader compilation

osx/pioneer.xcodeproj/project.pbxproj
The modelcompiler is now automatically built during the Pioneer OS X build in Xcode. The executable is intended to be added to the OS X installer package along with the generated SGM files.
This PR resolves issue #3630
=> Include modelcompiler in OSX build

src/ModelViewer.cpp, src/RandomColor.cpp, src/gameui/Face.cpp, src/ui/Image.cpp
Couple of minor warnings, one serious. There are still some -Wold-style-cast and -Wswitch warnings being generated by src/RandomColor.cpp, which I can't be bothered to fix right now.
```
../../pioneer/src/RandomColor.cpp: In static member function ‘static int RandomColorGenerator::RandomColor::PickSaturation(int, RandomColorGenerator::Luminosity, RandomColorGenerator::ColorScheme)’:
../../pioneer/src/RandomColor.cpp:90:10: warning: enumeration value ‘LUMINOSITY_RANDOM’ not handled in switch [-Wswitch]
switch ( luminosity )
^
../../pioneer/src/RandomColor.cpp: In static member function ‘static int RandomColorGenerator::RandomColor::PickBrightness(int, int, RandomColorGenerator::Luminosity)’:
../../pioneer/src/RandomColor.cpp:114:10: warning: enumeration value ‘LUMINOSITY_BRIGHT’ not …
```
=> Fix some GCC build warnings

data/ships/kanara_civ.json
I made a mistake back then when I resized the Kanara, and updatet its stats. For some reason I set the price to 1, and it used the police model. So here's the fix. Not the price of the civilian Kanara is somewhere between the Lunar Shuttle and the more hefty Bowfin. And points to the proper model which uses patterns and doesn't have the police logo.
=> Fixing the civilian Kanara price and model

src/gui/GuiTextEntry.cpp
This should fix #3655 and #2043 (which I think are duplicates?).
However, it's 100% untested (faith-based programming ftw?). So... it would be good if someone could test this before it's merged. If I can remember how to input an accented character on my computer I'll test it myself... :-/
=> Make GuiTextEntry handle UTF-8 multibyte chars for backspace and delete

src/graphics/TextureBuilder.h, src/scenegraph/BaseLoader.cpp
This PR avoid compressing normal maps that are not already in DDS format.
DXTn is pretty bad at handling normal maps and so for now we will simply sidestep the issue and use them without it.
Add TextureBuilder::Normal which will not compress a texture if it isn't already compressed.
Use it for all normal maps, existing DDS normal maps will still be compressed.
ping @nozmajner
=> Don't compress normal maps

src/ModelViewer.cpp, src/ModelViewer.h
Request a model, don't just switch and destroy the UI whilst we're in it's processing stage.
This fixes a crash that I frequently see when the UI is destroyed as a result of `SetModel` calling the `onModelChanged.emit()` as a result of a UI list being handled.
Now I can change models until the cows come home.
=> Fix ModelViewer crash

src/GasGiant.cpp, src/GasGiant.h, src/GeoSphere.h, src/TerrainBody.cpp
Gas Giants lacked the `OnChangeDetailLevel()` method and their `Reset()` was empty so you could not make any changes within the `ObjectViewer` and see them.
To access the `ObjectViewer` just target a gas giant, for example F2->F7->click on Jupiter then press CTRL+F10.
You cna now change the seeds and see it regenerate.
=> Fix editing the gas giants in ObjectViewer editor mode

contrib/json/JsonUtils.cpp, src/Game.cpp, src/LuaSerializer.cpp, src/Space.cpp, src/matrix3x3.h, src/matrix4x4.h, src/utils.cpp, src/utils.h
As pointed out in #3680 our save game files are huge, often on the order of 30MiB.
They also take a noticeable amount of time to save/load even on a good machine.
This PR attempts to address both issues using several methods.
With the latest VS2015.2 (_that's update 2_) I was able to get the Hex floats using `%a` or `%la` to work, however they produce noticeably larger files. Instead I changed the `FloatToStr` and `DoubleToStr` functions to use a union with the appropriate unsigned integer type to avoid all those memcpy calls and stuck that minor modification of the existing conversion.
We previously (de)serialised Vectors and Matrices by writing out each component individually and giving it a separate slot in a Json Array. 
This was horribly inefficient, instead I now just (de)serialise …
=> Saving changes

src/LuaSpace.cpp
Use the target bodies velocity, if it's a ship then it will inherit their velocity, otherwise the behaviour is the same as it currently is.
@walterar this is how I'd prefer to fix what you suggested in #3669, alternatively it could take an extra parameter to specify the velocity if you like.
=> SpawnShipNear velocity matching

src/WorldView.cpp, src/graphics/Renderer.h, src/graphics/opengl/MaterialGL.cpp, src/graphics/opengl/MultiMaterial.cpp, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h, src/graphics/opengl/TextureGL.cpp, src/graphics/opengl/UIMaterial.cpp, src/graphics/opengl/VtxColorMaterial.cpp, src/text/TextureFont.cpp
When we get errors we get an unstoppable flood of them, this is of no use to anybody.
Users have to force kill the game and developers get bombarded with repeated asserts and dialogs which hinder testing/fixing/development.
Only fire the warning dialog **IF** the previous OpenGL error was different from the current one.
Also attempt to log some more useful information like the funciton name and line number.
**EDIT:** I should have done this ages ago!
=> Fire once warnings

src/Body.h, src/SystemInfoView.cpp
This fixes #3698 that @aloyisiusp found earlier.
We could dereference a null pointer as we only checked that we had a `NavTarget` and not that it had a valid `SystemBody`.
=> Fix ship systeminfo crash

data/libs/Equipment.lua
The most useful piece of equipment in the game, essential for all newbie players, and for some rason we make it a pain to find?
That's dumb in fact I don't think it should even be equipment, just something that any ship can always do but that's debateable.
=> Make Autopilot purchasable from everywhere.

src/graphics/Renderer.h, src/graphics/dummy/RendererDummy.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h, src/libs.h
Complete usage of override and final keywords in the renderer.
Remove near/far undef/define from libs and renderer.
Enable the depth test before clearing the buffer.
=> Internal renderer cleanup

data/modules/SearchRescue/SearchRescue.lua
This does three things :
- use nil instead of "NIL"
- release any discarded_ships when entering or leaving a system
- check that we have a target before trying to use it
The first is just me being pedantic, the second I think fixes the problem but may have side effects, and the third stops it crashing which is one of the side effects.
@clausimu this is your baby I just got distracted by it so if you could take a look and tell me what you think then that'd be great :)
=> Release discarded_ships on entering or leaving systems

src/WorldView.cpp
Remove bogus assert, it is not necessary to check that the player is alive.
This fixes #2116
=> Fix crash when player explodes in-dock.

data/libs/SpaceStation.lua
It was not really possible to make the whole module stateless.
Furthermore, I kind of like the idea of doing that in our own modules,
since it shows potential modders (and our future selves) that THOU SHALT
SUBSCRIBE TO onShipDestroyed* FOR THINE SHIP REFERENCES. Nanmého.
(*) OK, and maybe the one for the ships leaving the system, depending on
the context
Fixes #3512
=> Clean up the police tables on ship destruction

data/shaders/opengl/gassphere_base.frag, data/shaders/opengl/geosphere_sky.frag, data/shaders/opengl/geosphere_terrain.frag, src/graphics/opengl/GasGiantMaterial.cpp, src/graphics/opengl/GasGiantMaterial.h, src/graphics/opengl/GeoSphereMaterial.cpp, src/graphics/opengl/GeoSphereMaterial.h
Calculate the inverse of the radius to avoid some divisions within the shaders.
Minor optimisation.
=> Optimise Eclipse Calculations

data/ui/GalacticView.lua
Prevent the galaxy map from crashing if in hyperspace using @walterar suggest fix.
Fixes #3713 
Thanks @walterar
=> Prevent the galaxy map from crashing if in hyperspace.

src/win32/OSWin32.cpp
Enable using dedicated nVidia GPUs in Windows laptops with Optimus.
This only affects Windows laptops with nVidia GPUs.
Previously I was seeing that we're always picking the Intel GPU in laptops with an integrated Intel GPu and a dedicated nVidia GPU. 
There are ways around this, like forcing _everything_ to use the nVidia GPU, but that's not ideal.
=> Enable using dedicated nVidia GPUs in Windows laptops with Optimus.

src/Background.cpp, src/HyperspaceCloud.cpp, src/Planet.cpp, src/perlin.cpp, src/perlin.h
Removed the component-wise noise and just pass the vector3d directly by reference.
Some other changes which make minor differences to runtime performance.
The effect of this PR could be a bit chaotic as it risks changing the results we get back from the noise library. However I have explicitly **avoided** making any changes which affect the actual values returned for a given input so hopefully that won't be the case.
=> Minor Noise library improvements.

src/win32/OSWin32.cpp
This is equivalent to the nVidia flag added in #3715 earlier today, that causes it to use the dedicated GPU in laptops with multi-gpu setups.
=> Add AMD Power Xpress performance flag keyword and value.

data/shaders/opengl/eclipse.glsl, data/systems/01_epsilon_eridani.lua, src/Camera.cpp, src/Camera.h, src/graphics/Material.cpp, src/graphics/Material.h, src/graphics/opengl/GasGiantMaterial.cpp, src/graphics/opengl/GasGiantMaterial.h, src/graphics/opengl/GeoSphereMaterial.cpp, src/graphics/opengl/GeoSphereMaterial.h
Re-write the way the shader is setup to avoid using uniforms to control the number of iterations for the loops. This allows it to avoid the problems of #2176.
Also `Mar 31, 2013` it's taken more than 3 years to get this fixed and the MESA "fix" was supposedly imminent all the way back then... (╯°□°）╯ ┻━┻
This means generating the shader several times, once for each variant.
It is a little unintuitive to do this manually.
I've pulled in a change to the `01_epsilon_eridani.lua` seed that puts `Itzalean` back on the equator but I think it needs yet another seed to actually get all 4 stations into their intended locations.
There's some unfinished stuff in here.
Andy
=> Eclipse r600

data/lang/ui-core/en.json, data/ui/StationView/ShipMarket.lua
The loaded cargo disappears if the player buys a new ship.
The player loses the money and if there is an active mission with already loaded custom cargo the mission cannot succeed.
This PR should solve this problems.
=> Keep cargo if buying a new ship

data/ui/MainMenu.lua, src/Game.cpp, src/Game.h, src/LuaGame.cpp
Add method to test if a save game file exists for loading. Use it in the main menu.
Should fix #3727
=> Disable Continue button if no saved game to load.

data/modules/BreakdownServicing/BreakdownServicing.lua
This PR was going to fix #3722 (yes github, please auto-close it on merge of this).
The issue was that the intro message of "breakdown and service" offers to repair drive "none" for 0 credits.
This module already has a "You don't have a drive" string, which I think is shown when you actually try to repair the non-existing drive (I'm currently unable to run pioneer, so working in the blind here). Anyway, the module does handle the case of no hyperdrive, so that's fine.
We could show that message as intro message, but I think the current way we have it now, where the player is greeted by a flavoured sales pitch is much nicer.
Also, I kind of don't feel it warranted to duplicate all these flavour introduction strings in a version for those without a drive. If you don't have a drive, then …
=> Don't hard code strings we already have in translation system

data/libs/Equipment.lua, data/ui/StationView/EquipmentTableWidgets.lua
Re-enable selling of Trade analyzer. As I mentioned in #3742:
> It was implemented by someone who had the distinct idea that this must be "software", and that you can't sell software back. I say: it could be a cartrige, or license, or subscription, or whatever. I want it to have the same behavior as other equipment, just like it used to be. I don't see how the game becomes more "fun" by not being able to sell some equipment that you've bought.
Since this touches some equipment philosophy, ping @laarmen
=> Make trade analyzer removable again. Undo #3474, close #3742

src/LuaShip.cpp
Don't use LuaVector instead just return a table with x,y,z components for GetVelocity and GetPosition.
This works should let people actually use these functions now.
=> Swap LuaVector for a table

src/utils.cpp
After a bit of fiddling around I discovered than using `itoa` was about 4 times faster than `sprintf` for integer to string/char[] conversion.
Also `atoi` is roughly 5.6 times faster than `sscanf` for the inverse.
Of course we're still coping lots of strings around which probably dominates the actual operations but one thing at a time! Plus this silences a large number of warnings under GCC.
Andy
=> Faster float convert

src/utils.cpp
Revert my changes to use atoi and atoll as these do not give the correct results.
Use sscanf as this correctly reads the string, fixes #3752
poke @walterar
=> Revert my changes to use atoi and atoll

data/lang/module-cargorun/en.json
The [Translations guide](http://pioneerwiki.com/wiki/Translations) says translations should go through Transifex, but the error is in the original English source string and I couldn't find an English language option on Transifex.
=> Fix grammar error in module-cargorun

src/WorldView.cpp, src/text/TextureFont.cpp
I was seeing a crash quite frequently where it was trying to allocate space for millions of characters due to an infinite loop.
This handles the NaN cause of the string that looped, and attempts to avoid future loops.
I think that the TextureFont needs a bit more work and some nicer logic, perhaps avoiding some of the duplication of code in that class. However I'm not going to do that in this PR.
=> NaN in your numbers

configure.ac, src/LuaConsole.cpp, src/LuaConsole.h, src/Pi.cpp
This patch adds a new configure option --enable-remote-lua-repl. If that
is given, When starting a game (not in the menu), pioneer listens to
port 12345 (can be changed with -DREMOTE_LUA_REPL_PORT=...). Connect to
it (telnet 127.0.0.1 12345), and you can evaluate expressions like in
the in-game console. This can be used to interface an external lua IDE
to a running game.
At the moment, the code only works on Linux, but the changes for Windows
should be small (mostly including other header files). This is only relevant if
--enable-remote-lua-repl is given when configuring!
=> Add a TCP Lua console.

README.md
We still get very poor quality bug reports and always have to ask for the opengl.txt and output.txt files.
So I thought I'd update [the FAQ](http://pioneerwiki.com/wiki/FAQ#How.2Fwhere_do_I_report_my_bug.2Fcrash) a little bit and add this link directly too it.
=> Add a piece explicitly linking to the FAQ about bug reporting

scripts/nightly-build.pl
We've seen players trying to compile the build tar file, since it included the COMPILING file.
We've seen players looking for a README file.
Players don't need the SAVEBUMP file.
=> Buildscript update

.github/contributing.md, .github/issue_template.md, .github/pull_request_template.md
Please read, and suggest improvements.
Idea here was that we already have wiki-pages, that are easier to maintain than these templates, thus it links to relevant wiki-pages.
Especially for `contributing` file, this is linked to at the head of a new PR, and thus the info I include is what to consider before pressing "create pull request" button. For _how_ to contribute, we have the wiki, to which also the pioneer home page links.
So, any other "classic" questions to include in issue_template? 
_also, I decided to use lowercase filenames, since these reside in their own folder, and don't need to SHOUT to call attention to them, as README or COMPILING does._
=> use github templates

data/lang/ui-core/en.json, data/ui/MainMenu.lua, data/ui/Settings.lua, src/LuaEngine.cpp, src/OS.h, src/posix/OSPosix.cpp, src/win32/OSWin32.cpp
After numerous situations where the user cannot find their `Pioneer` folder with `config.ini`, `output.txt` and `opengl.txt` files in it I realised that of course we already have that information.
This adds a button to the settings screen that will ask the system to open the folder directly so they do not have to search for it.
I've only implemented the Windows call necessary as that's all I have access too right now.
=> Add button to Settings menus so user can open their Pioneer folder.

data/modules/CrimeTracking/CrimeTracking.lua
The crash happens because apparently empty
systems can have a lawlessness > 0
Closes #3788
=> Fix crash when jumping into empty system

data/libs/ui/NavButton.lua, data/modules/SearchRescue/SearchRescue.lua
This PR does three things:
1) It updates NavButton.lua to allow setting dynamic objects (such as ships) as nav targets.
2) It allows setting Search&Rescue target ships as nav targets directly either from the BBS ad or from the mission details screen. Before, only the closest planet was selected as nav target.
3) It moves the navbutton in the BBS ad to after mission acceptance, because only then will target ships actually be created.
I know, this changes the original philosophy of the Search&Rescue missions by basically eliminating the "search". But opposed to what I had thought, searching was never really any fun. Especially for out-of-system missions, where one had to go into the F2=>F6 system overview to find the ship (which was usually placed wrongly right on top of the sun of that …
=> Navigation button update to allow for dynamicBodies as nav targets (SAR and general)

data/modules/SearchRescue/SearchRescue.lua
Bug fix for #3797.
There were actually two things wrong right there (one pointed out by @walterar):
1) Missions were never closed if they were ever overdue until the player landed at the station where the original mission was accepted. Kind of a style choice to now terminate them wherever the player lands. But might be nicer to not clutter the mission screen with failed missions? What if the player never intends to return to the original station? Can't make them suffer forever... :)
2) If the player landed at a station in a different system while a SAR mission was active in the background the game could crash.
=> Search&Rescue: bugfix for #3797

src/Player.cpp
There is nothing preventing the navigation target to be the same as the combat target. Whether that is a good thing or not is not the goal of this patch, which is just to take this possibility into account when the target body is indeed removed.
My apologies for comitting on the master repo, but I don't have my SSH key on this computer and GH didn't let me do that on my (outdated) repo.
=> Fix nav and combat target removal cleaning

data/configs/GasGiants.ini, src/GasGiant.cpp, src/GasGiantJobs.cpp, src/GasGiantJobs.h
This varies when the Gas Giant GPU jobs are submitted to prevent them all being requested at once.
The intention is to avoid a large chug happening as all of the 6 cubemap faces are generated for every single Gas Giant in a star system.
I've also taken the opportunity to add different sized texture generation depending on the requested planet detail level, and to control the number of octaves from the config file.
The size of textures used on CPU and GPU can be controlled independently per-detail level (**5**) as can the number of octaves of noise used in the GPU generation.
This should generally improve the performance, but degrade the appearance, on lower detail settings.
=> Update GasGiant config, detail and initialisation timing

data/modules/SearchRescue/SearchRescue.lua
Mission income for the Search & Rescue missions has been adjusted to account for the recently increased variability in commodity/personnel delivery and pickup amounts. The reward is a combination of:
1) a flat fee based on general mission distance (same planet, same system, different system) with some random variability
plus
2) a fee based on necessary cabins (half the current cabin price times number of cabins needed) or commodity (ten times the commodity price).
=> Search&Rescue: adjust mission income

src/ModelViewer.cpp, src/NavLights.cpp, src/NavLights.h, src/Ship.cpp, src/SpaceStation.cpp, src/scenegraph/Billboard.cpp, src/scenegraph/Billboard.h, src/scenegraph/Model.cpp, src/scenegraph/Model.h
I've made some odd late-night programming decisions in the past but I don't know what made me put the responsibility for rendering NavLight billboards into the Scenegraph::Model class.
This fixes that questionable decision and moves the responsibility for rendering NavLight billboards from scenegraph/Model into NavLights itself.
=> Made NavLights responsible for their billboard rendering

.editorconfig
This is used by github when displaying code in browser
E.g. this fixes a very long standing issue when glancing through code on
github, be that for review or online source files: they insist on 8 char tabs,
while we use 4 char tabs.
This can also be used by any self-respecting editor (read: Emacs), but also by
lesser ones (read: vim), and the rest (atom, geany, netbeans, eclipse, xcode,
sublime, textmate, visual studio, etc.)
See http://editorconfig.org/ for full list, and more.
I bet @laarmen will be happy now!
Learned it from:
https://github.com/isaacs/github/issues/170#issuecomment-150489692
Also, the tab issue can be fixed/worked around through a chrome extension. For those using chrome, that is:
https://github.com/sindresorhus/tab-size-on-github
=>  Adding an editorconfig file to define coding style

src/LuaShipDef.cpp
Added annotation for three more attributes in ShipDef. It took me a while to find out these attributes are actually readily accessible through ShipDef. I decided to add the annotation so other "scripters" won't need to search in the code.
=> add annotations to ShipDef

src/LuaShip.cpp, src/Ship.cpp, src/Ship.h
This allows ship texture patterns to be set from lua. Together with the already present "SetSkin" method you can now recreate a specific look for a ship. This is important for persistence in scripts. For example, in Search and Rescue missions, if you leave a system and come back, the target ship will have a different look because the skin and pattern are created randomly when creating a ship. You can now specify them.
C++ experts like @laarmen, @impaktor and @fluffyfreak should take a close look at the additions I made here. I am a total C++ noob and may have easily made mistakes.
While I was at it I also annotated the SetSkin and GetSkin methods. I only stumbled upon them while digging through code looking for other things.
=> Set ship texture patterns from lua

src/CityOnPlanet.cpp, src/Intro.cpp, src/Ship.cpp, src/SpaceStation.cpp, src/scenegraph/Model.cpp
This PR does two things:
- Check that a model actually supports patterns before using them,
- Limit the range correctly by subtracting 1 from `GetNumPatterns()`
Thanks to @clausimu for discovering that this was wrong!
=> Model pattern range and status checking

src/scenegraph/Loader.cpp
Some additional optimisations applied upon loading using Assimp.
It makes the total size of `.sgm` files about 21MiB smaller.
It should reduce the sheer number of vertices along with potential other changes.
I have tested it with stations & taken a look at a number of ships but I think that @nozmajner might want to take a long look at the models and make sure that nothing obvious has been mangled.
=> Additional mesh optimisation

src/LuaShip.cpp
As discussed in PR #3814 this adds checking for `SupportsPatterns()` to the `LuaShip` function `l_ship_set_pattern`.
=> belt and braces approach to sanity checking for patterns

src/scenegraph/ModelSkin.cpp
A frequent comment since the random colour generation was changed is that the colours seem darker and less appealing.
The third parameter of `RandomColor::GetColors` controls the luminance and so I have set this to `LUMINOSITY_BRIGHT` instead of `LUMINOSITY_RANDOM`.
Black can still appear as a "colour" and is obviously not enhanced by this.
=> Brighter luminosity for random colours

src/GasGiant.cpp, src/GasGiantJobs.cpp, src/GasGiantJobs.h
I got tired of seeing a warning about `s_patchFaces` not being used, when it bloody well is, when digging through the build logs for gcc.
=> Use a function to access the s_patchFaces to silence a gcc warning

src/CargoBody.h, src/DynamicBody.h, src/HyperspaceCloud.h, src/Missile.h, src/ModelBody.h, src/Object.h, src/Planet.h, src/Player.h, src/Projectile.h, src/Ship.h, src/SpaceStation.h, src/Star.h, src/TerrainBody.h, src/graphics/dummy/MaterialDummy.h, src/graphics/dummy/VertexBufferDummy.h, src/graphics/opengl/MaterialGL.h, src/graphics/opengl/SphereImpostorMaterial.h, src/scenegraph/CollisionGeometry.h, src/scenegraph/Group.h, src/scenegraph/LOD.h, src/scenegraph/MatrixTransform.h, src/scenegraph/StaticGeometry.h, src/scenegraph/Thruster.h
add "override" to all functions where clang++ says it's missing
````
grep override * -R
````
before: 307
after: 445
=> add "override" to silence warnings in clang

configure.ac
set ARFLAGS to rcD (instead of rcu)
=> fix ARFLAGS to remove warning

data/lang/equipment-core/en.json, data/libs/Equipment.lua
NB: I originally did a PR for this about 5 yeas ago, so I finally got around to redoing it :)
The idea for these is that they cannot be purchased but that military or Police ships could be fitted with them so that escape is not an option, nor is chasing them through hyperspace a realistic one.
Obviously it also makes it possible for a black market in ships with them fitted, which are of dubious origins, to be created on the bulletin boards... though this PR does not implement that.
=> Added military drives from 5 to 9.

src/SectorView.cpp, src/galaxy/SystemPath.h
Whilst attempting to repeat [this bug](http://spacesimcentral.com/ssc/topic/5879-newcomer-some-feedback-and-a-problem/) I noticed that I was constantly finding different instances of the system `Liaphi`.
It's a really common one but I wanted the nearest to my current star system.
This patch attempts to always return not just the first exact match, but the one nearest to the players current system. Sadly it can only do this for those within the `SystemCache` and so if the one you're looking has been discarded you will find whichever one (*or none*) that it can.
=> Attempt to find the nearest matching exact name.

src/GeoPatchJobs.cpp, src/GeoPatchJobs.h
I had an idea to reduce the amount of work done in the QuadSplit jobs. 
Instead of generating 4 sets of patches that are `edgeLen + (borderSize * 2)`, it now generates a single large patch that is `(edgeLen * 2) + (borderSize * 2) -1` which eliminates the generation of the inner border data & the generation of one duplicate row and column of vertex data across the whole patch.
It then pulls the sub patches out of that larger soup of data which should reduce duplication and wasted generation of data.
New amount generated:
(55 * 2) + (1 * 2) - 1 = 111
111 * 111 = **12,321**
Old amount generated:
55 + (1 * 2) = 57
57 * 57 = 3,249
3,249 * 4 = **12,996**
Which is a ~5.19% decrease in the number of vertices generated.
I went ahead and did the calculation for the rest of the patch dimensions …
=> Terrain gen cleanup

src/GeoPatch.cpp
This is something that I should have done long ago.
We don't need the normals or color information once we've built the vertex buffer, so we can now discard it.
With the terrain details set to `Very High` and starting on Earth the mem drops from 620.5MB to 548.2MB
We could possibly discard the heights as well but I'd have to change some other logic so I'm just doing this part for now.
=> Simple reduction in memory usage.

data/ui/StationView/Lobby.lua
This is a workaround. Maybe this can be removed after transitation to pigui.
=> Avoid crash if player jumps to next system

src/graphics/opengl/Program.cpp
The shader attribute binding locations changed some time ago, this just updates them to match those in the glsl files.
These might actually be defunct now but updating them just in case.
=> Update attrib binding locations

contrib/PicoDDS/PicoDDS.cpp, src/GameConfig.cpp, src/GameConfig.h
These are backports, with fixes, from the [FreeBSD ports](https://github.com/freebsd/freebsd-ports/tree/master/games/pioneer/files) builds.
There's some discussion to be had here about whether they're necessary but they are innocuous enough that I thought it worth making a quick PR out of them.
Discuss. Review. Etc.
=> Freebsd patches

src/LuaSerializer.cpp, src/LuaSerializer.h, src/LuaUtils.cpp
I've added some output a bit more useful to the serializer crash thingy.
Also, I've added a way to shoot ourselves in the foot (feet) intentionally with the debug.makenull() function to create a NULL light userdata. That's quite useful to provoke a crash.
=> Enhance serializer crash output

contrib/imgui/examples/sdl_opengl3_example/imgui_impl_sdl_gl3.cpp
There seem to be problems with SDL_GetTicks(), which is *not*
monotonically increasing. This commit sets delta-t to 1/60 if it
is <= 0.
=> Set delta-t to 1/60 if it is <= 0.

data/modules/SearchRescue/SearchRescue.lua
This fixes a bug mentioned in #3852 (but is unrelated to #3852), whereby ships that don't have any patterns associated with them crash the game when used as SAR mission targets. It was an oversight by me initially. I thought I had checked to see that every (non-police) ship has at least one pattern. But the Bowfin fighter and the Deep Space Miner do not.
=> fix pattern selection if no pattern present

.editorconfig
It appears that most of our non-C++/Lua source files are using spaces for
indentation, (except Makefile.am). Added rules to accommodate that, and fix
wrong indentation in Changelog.txt when using github editor.
=> Ye, tabs be gone!

data/ui/StationView/Lobby.lua
Player cannot sell fuel if fuel is out of stock. This should fix it.
=> Sell fuel fix

data/lang/module-stationrefuelling/en.json
This fixes the english lang file for the autorefuel module, so the station doesn't talk about fuel fee, only docking fee. Translations will need to be updated on transifex.
Because since #3837 the stations won't fill your tanks, just greet you since they are greedy and want to sell you their precious Hydrogen. :) Which makes sense.
There was an imgui.ini file in the first commit, because my git-fu is still weak, but it should be removed now.
One design question that relates here: should anything happen if you don't have the money to pay for the docking fee? It's a very rare case anyhow, but not entirely pointless.
closes #3862
=> Docking fee Text update (since station won't refuel you)

src/NavLights.cpp, src/SpaceStation.cpp
This fixes #3873 where somehow the call to render the navlights had gone missing.
This meant that instead of being flushed at the end of each frame they were simply accumulating until the game exceeded the 2GB barrier on 32-bit processes.
=> Render the navlights for orbital stations

data/libs/ui/NavButton.lua, data/modules/SearchRescue/SearchRescue.lua
NavButton was causing a game crash when created without a valid target (for example when you click on it during a long hyperjump), as was the Search&Rescue script (when checking mission details during hyperjump).
This fixes both scripts.
=> fix navbutton crash without target

src/WorldView.cpp, src/WorldView.h
Fixes the sigc connections for the HUD toggle (tab key) and time accel keyboard shortcuts (PgDn, PgUp) not being disconnected in the WorldView destructor. WorldView is deleted and re-created each time a game is loaded or started, so invalid callbacks would accumulate.
Unlike my initial impression, all three invalid callbacks should be harmless, other than causing #3875. The HUD toggle has no effect unless `Pi::GetView() == this`. It's possible that there are other more dangerous orphaned connections in Pioneer, but I couldn't find any.
=> Fix orphaned connections in WorldView

src/graphics/opengl/VertexBufferGL.cpp, src/graphics/opengl/VertexBufferGL.h
Fixes a severe performance problem on at least some AMD GL drivers. To avoid potential undefined behaviour, the GL buffer code used to zero-fill the buffers on creation. This meant that a newly-created buffer was often written multiple times per frame, which causes a synchronization stall on some GL drivers even when the buffer wasn't used in a draw call.
To replace the undefined behaviour functionality, asserts were added to the Bind calls to check whether buffers are used before being written.
The two heading labels are forced to update every frame by the `UI::Label::Layout` function. `UI::Label::Draw` then creates a new vertex buffer and draws with it immediately. This patch works around the performance problem, but UI elements should not be updated unnecessarily. …
=> Remove GL buffer init fills, add init checks

src/gui/GuiTextLayout.cpp, src/text/TextureFont.cpp
TextureFont attempts to reserve capacity in vertex arrays, but it doesn't work in cases where the Populate functions are called with a vertex array that already contains vertices. `Gui::TextLayout` populates the vertex array word-by-word, so this happens routinely.
It's not a huge gain for WorldView, but it's significant when there's a lot of text on-screen. With the debug text output (the lower five lines use TextLayout), `TextureFont::PopulateMarkup` CPU usage drops from 8% to 5% here.
=> Optimisation: Reserve VA capacity correctly for Gui::TextLayout

src/modelcompiler.cpp
It's clear that there are some issues with the modelcompilers output when using multithreading so disable it for now.
This leaves the code in place for future re-use or fixing.
=> Disable the modelcompiler multithreading.

src/scenegraph/LOD.cpp, src/scenegraph/Node.h
`BinaryConverter::LoadNode` never sets `db.renderer`, but `Scenegraph::LOD::Load` uses it. Other scenegraph loaders use `db.loader->GetRenderer()` instead, which is valid.
Because `Scenegraph::LOD` only accesses its renderer parameter as a null-check, the only effect of this bug is to cause buildings to disappear in some release builds. Debug builds wipe allocated memory with a non-zero value and so don't trigger the problem.
=> Fix undefined renderer bug in SGM LOD loader

contrib/imgui/examples/sdl_opengl3_example/imgui_impl_sdl_gl3.cpp
The GL driver with the following string throws an INVALID_OPERATION on ImgUI's version 330 shaders. This fixes it by setting the shader version to 140. Shouldn't cause any issues elsewhere.
> OpenGL version 3.1 (Core Profile) Mesa 10.1.3, running on Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Desktop
Fixes #3881
=> Set ImgUI shaders to version 140 to work around junk Intel drivers

src/PiGui.cpp, src/PiGui.h, src/graphics/Renderer.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h
This make the `__FUNCTION__` and `__LINE__` usages mandatory for the `CheckRenderErrors` methods so we can track where they're called from.
It replaces the bespoke code in `SwapBuffers` with `CheckRenderErrors` as that was the only deviant.
Then removed the direct OpenGL calls from within `PiGui` (ping @ecraven) as well as adding some deduplication of the texture loading.
=> Render error check

src/ui/Label.cpp
The (new-)UI labels currently use static vertex buffers for text, but replace them each frame regardless of whether they were changed or moved. Writing to static vertex buffers is extremely slow on AMD GL drivers. It's so bad that the two WorldView labels (heading & pitch) drop overall frame rates by ~40% without this patch.
NVidia drivers probably don't care: Last time I checked, they simply ignored buffer hints, and if they did use a static buffer then they'd probably use it in a less retarded manner.
This is part-workaround, as the layout code shouldn't be causing the labels to be updated each frame when nothing changes. However, when flying, the labels would often need to be updated regularly anyway, so static buffers are inappropriate.
Fixes #3417, maybe. Patch #3878 also sped up …
=> Switch UI labels to dynamic VBs

data/lang/equipment-core/en.json, data/libs/Equipment.lua, data/modules/CargoRun/CargoRun.lua, data/modules/CrewContracts/CrewContracts.lua, data/modules/SearchRescue/SearchRescue.lua, src/LuaLang.cpp
Add missing token PASSENGER_CABIN to equipment-core.
Use l:get from now on to get the translation or nil (no error if an entry
doesn't exist)
If a translation doesn't exist, the missing token and the resource and language
code it was supposed to be in are shown:
error: [string "[T] @modules/CrewContracts/CrewContracts.lua"]:402: missing translation token: `NAVIGATOR' in resource `module-crewcontracts', language code `en'.
stack traceback:
[C]: in function '__index'
[string "[T] @modules/CrewContracts/CrewContracts.lua"]:402: in function 'cb'
[string "[T] @libs/Event.lua"]:34: in function '?'
[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>
=> Error on non-existing translations.

data/modules/CargoRun/CargoRun.lua
Since #3890 it is necessary to check translation with l:get() because not all branches have appropriate strings.
=> Check availability of translation string with l:get()

src/GameConfig.cpp, src/Pi.cpp, src/graphics/Graphics.h, src/graphics/WindowSDL.cpp, src/graphics/WindowSDL.h, src/graphics/opengl/RendererGL.cpp
Fixes #3888. It's a bit messy because there's no way to detect the faulty GL driver until the context has been created, which is currently a separate code branch. It also doesn't set the config parameter itself, to avoid adding a Pi.h dependency in RendererGL.
Another approach would be to move a bunch of init code out of Graphics.cpp and give RendererGL the responsibility for creating the SDL window. In this case, the SDL window can be immediately recreated without the forward compatibility flag after the faulty driver is detected. This would also clear up some of the hacks used for the null renderer.
Another issue is that the code only detects the known-faulty Intel driver. It's quite possible that other Intel drivers have the same fault, and in this case the user will be expected to …
=> Provide config flag and warning to work around Intel pointsprite bug

data/lang/quitconfirmation-core/en.json, data/ui/QuitConfirmation.lua
Also, this is not just relevant for keeping up to date with 2016 but also for
the year 2020 (if we're still here by then), when there will be a presidential
election one more time!
=> Keep quit confirmation messages modern and stylish

src/GasGiantJobs.cpp
This avoids the Intel GPU bug of trying to compress these textures and it avoids compressing them when they should be used raw anyway.
=> Use the gas giant textures RAW instead of Billboard.

data/modules/CargoRun/CargoRun.lua, data/modules/DeliverPackage/DeliverPackage.lua, data/modules/Pirates.lua, data/modules/Taxi/Taxi.lua
Closes #3902 
I did not touch the police pumpkinseed. Some say it could be a corrupt police officer or it's a stolen police craft.
=> Do not spawn unarmed pirates

src/Ship.cpp, src/ShipAICmd.cpp
Combined with #3912, removes the need to put the pad collision geometry far above the visible pad and associated non-obvious docking dependencies on ship geometry. Should remove any issues with specific ships having difficulty docking or suffering damage. Note that without #3912, most ships will not dock when this patch is used.
All new ships will need a tag_landing, with some static collision geometry extending down to the same height or below. If a ship doesn't have a tag_landing, 0.0 is used instead for the landing position, which should dock but be clearly incorrect. The Aabb is not used as a backup because it may disguise incorrect behaviour.
The 0.1m offset in ShipAICmd.cpp is a somewhat arbitrary epsilon value to ensure that the edge vs tri intersections are reliably detected, and …
=> Use tag_landing instead of Aabb for determining AI docking position

src/ShipController.cpp
nothing more, nothing less...
If you are in SetSpeed mode (flying and with autopilot enabled) if you hold the keys
to increase or decrease speed for more than 5 sec, you ask for this:
https://www.youtube.com/watch?v=ygE01sOhzz0
...So I put limits on playerController.cpp on what you could ask to autopilot
=> Add limits when using autopilot SetSpeed

src/Ship.cpp, src/Space.cpp, src/SpaceStation.cpp, src/SpaceStation.h
This PR is to correct a new bug, easily reproducible: you start at earth, take-off then try
to hit spaceport landing surface: you can pass through it :/
After last changes, ground station have no more two layers of collision mesh (one not flagged
and one flagged) but only a flagged flat surface.
This means less work for collision system, and also for modellers. More, this not rely on
eight of "mushroom-shaped" collision meshes and is definitely a step ahead.
But this means also you need to bounce (collide) with flagged surfaces if you're not trying
to dock (this is specific for planet starport), OR you need to pass through collision volume
when you aren't docking and you want to fly through the central hole of orbital stations..
To solve this I removed the collision checks for flagged …
=> Collision with docking surface entirely moved on SpaceStation

data/modules/TradeShips.lua
Solve #3913
...Seems LUA would know a distance to a "nil" object, but I don't
know: you need to ask @walterar , he did the work ;)
=> Avoid CTD when trade ship try to decide hyperjump

src/SpaceStation.cpp
This is to avoid a bug (...I put on code :( ...): when ships (even AI) are docking on
orbitals at high time step they remains stuck in "level ship" because,
if in time accel, their position change is less than the movement
of the station itself (due to its rotation).
So you need to jump directly out on the right stage.
=> Avoid jousting when docking on orbitals at high time steps

data/shaders/opengl/attributes.glsl, src/graphics/opengl/Program.cpp, src/graphics/opengl/VertexBufferGL.h
Shader attributes use explicit numbering and we match those numbers internally.
However these had gotten mismatched so this PR fixes them.
It's probably not caused a problem but it might have depending on the GPU drivers.
=> Resolve the mismatched attribute numbering

src/PiGui.cpp, src/graphics/Texture.h, src/graphics/VertexBuffer.h, src/graphics/dummy/TextureDummy.h, src/graphics/dummy/VertexBufferDummy.h, src/graphics/gl2/GL2FresnelColourMaterial.h, src/graphics/gl2/GL2Material.h, src/graphics/gl2/GL2RenderTarget.cpp, src/graphics/gl2/GL2Renderer.cpp, src/graphics/gl2/GL2Texture.h, src/graphics/gl2/GL2UIMaterial.cpp, src/graphics/gl2/GL2UIMaterial.h, src/graphics/gl2/GL2VertexBuffer.cpp, src/graphics/gl2/GL2VertexBuffer.h, src/graphics/opengl/GenGasGiantColourMaterial.h, src/graphics/opengl/RenderTargetGL.cpp, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/TextureGL.h, src/graphics/opengl/UIMaterial.cpp, src/graphics/opengl/UIMaterial.h, src/graphics/opengl/VertexBufferGL.cpp, src/graphics/opengl/VertexBufferGL.h, src/graphics/opengl/VtxColorMaterial.h, src/scenegraph/Label3D.cpp
This is some generic refactoring, fixing, cleaning of the VertexBuffer, IndexBuffer, Texture classes along wiht more `override final` usage etc.
- Exposing generic textureID accessor, 
- virtual Bind/Unbind methods, 
- override final, 
- naming tweaks 
- BufferData methods
=> Refactor the Vertex, Index, etc buffers

src/Intro.cpp, src/Ship.cpp, src/ShipType.cpp, src/ShipType.h, src/scenegraph/Model.cpp, src/scenegraph/Model.h, src/scenegraph/Node.h, src/scenegraph/Thruster.cpp, src/scenegraph/Thruster.h
This add customizable thrusters color for each model (partially close #961) and
also allow to choose customized colors *per direction*, as in screenshot.
...Ping @nozmajner to provide feedback about colors: mine are too
much psychedelic :D 
As you can see in sinonatrix.json, a structure in which each value is a channel
is used (standard "r", "g", "b" are used, values are [0,255] ).
Two global keyword are provided to choose the settings you wish to customize:
- `thruster_global_color` for global color
- `thruster_direction_color` to define colors per direction
Inside `thruster_global_color` you then have values for each channel,
inside `thruster_direction_color` you need to define a struct value for
direction(s) you will overwrite, like:
```
thruster_direction_color {
[keyword] : {
"r" : …
```
=> Thruster colors can be modified globally or per direction

configure.ac, src/LuaServerAgent.cpp, src/LuaServerAgent.h, src/LuaUtils.cpp, src/Pi.cpp, src/Pi.h, src/ServerAgent.cpp, src/ServerAgent.h
Remove the LDB thingy I wrote back in the days of 1719, and make the Server Agent an opt-in compile-time option.
Note that the agent will also be disabled in the Windows and Mac builds, but I haven't disabled the libcurl dependency for those yet.
The rationale for the server agent thing is quite simple : we don't use it, and the libcurl dependency is a pain because some distros ship with a SONAME of 3 by default (Debian) whereas others only ship the SONAME 4.
For LDB, well, it's just broken and unused.
I didn't actually test the build WITH the server agent, but the default builds fine, and doesn't crash in the first 10 seconds of gameplay.
=> Configure cleanup

src/Planet.cpp
This fixes #3946 by returning to the older PhysRadius calculation which was far less generous.
As a results some bodies, especially those with small differences in average and maximum height, will become more difficult to land upon.
Commit: _Return to the older PhysRadius calculation._
=> Fix PhysRadius calculation for low orbiting bodies.

osx/pioneer.xcodeproj/project.pbxproj
The Xcode project for Max OSX has been updated to include all the changes since the last package build (20170301). The new project will be used for creating the install package for Pioneer v.20170403.
=> Updated Xcode project for Mac OSX build (20170403)

src/ShipType.cpp
Correct the behavior when no customized global color thruster for a model is specified
Closes #3967
=> Bugfix for issue #3967 related to PR #3948

licenses/CC-BY-SA-3.0.txt
Used to be an abriviated version.
Closes #3970 
grabbed plain-text version from: https://creativecommons.org/licenses/by-sa/3.0/legalcode.txt
=> Update to full (correct) Creative Commons Attribution-shareAlike 3.0

src/SpaceStation.cpp
As seen by @jaj22 , this is the bugfix he asked for...
It's not tested but the meaning is: if a collision with docking surface happens,
then *probably* you want the ship bounced back...
Waiting for review
=> Ever damage ship when docking

src/text/TextureFont.cpp
Initialise the TextureFont to 0 to eliminate underlining even at high AA levels.
Fixes #2954 acceptably.
=> Initialise the TextureFont to 0

configure.ac
This allows to use with_server_agent variable.
Fixes #3955 pull request.
=> Fix name of option for server agent in configure.ac file

src/FixedGuns.cpp, src/FixedGuns.h, src/LuaObject.h, src/RandomColor.cpp, src/Ship.cpp, src/SpaceStationType.cpp, src/graphics/WindowSDL.cpp, src/graphics/dummy/TextureDummy.h, src/graphics/gl2/GL2FresnelColourMaterial.cpp, src/graphics/gl2/GL2FresnelColourMaterial.h, src/graphics/gl2/GL2GasGiantMaterial.cpp, src/graphics/gl2/GL2GeoSphereMaterial.cpp, src/graphics/gl2/GL2Renderer.cpp, src/graphics/gl2/GL2Renderer.h, src/graphics/gl2/GL2SphereImpostorMaterial.h, src/graphics/gl2/GL2Texture.h, src/graphics/gl2/GL2VertexBuffer.cpp, src/graphics/opengl/GasGiantMaterial.cpp, src/graphics/opengl/GeoSphereMaterial.cpp, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/VertexBufferGL.cpp, src/text/TextureFont.cpp
Fix all warnings for gcc and all but one for clang.
Clang warning is:
In file included from StarSystem.cpp:12:
In file included from ./../Pi.h:12:
In file included from ./../LuaSerializer.h:8:
./../LuaObject.h:241:30: warning: instantiation of variable 'LuaObject<StarSystem>::s_type' required here, but no definition is available
[-Wundefined-var-template]
LuaObject() : LuaObjectBase(s_type) {}
^
./../LuaObject.h:289:2: note: in instantiation of member function 'LuaObject<StarSystem>::LuaObject' requested here
LuaSharedObject(T *o) : m_object(o) {}
^
./../LuaObject.h:337:70: note: in instantiation of member function 'LuaSharedObject<StarSystem>::LuaSharedObject' requested here
Register(new (LuaObjectBase::Allocate(sizeof(LuaSharedObject<T>))) LuaSharedObject<T>(static_cast<T*>(o)));
^ …
=> Fix warnings

src/LuaObject.h, src/text/TextureFont.cpp
Does exactly as the title says: clang only warnings silenced on other platforms.
=> clang only warnings silenced on other platforms.

contrib/json/JsonUtils.cpp, src/GeoSphere.cpp, src/LuaObject.h, src/StringF.cpp
These two commits fix all remaining warnings for current clang and gcc.
=> Fix all warnings

configure.ac
=> Do not set ARFLAGS on Darwin

src/SpaceStation.cpp, src/SpaceStation.h, src/SpaceStationType.cpp, src/SpaceStationType.h, src/galaxy/CustomSystem.cpp, src/galaxy/CustomSystem.h, src/galaxy/StarSystem.h, src/galaxy/StarSystemGenerator.cpp
You can now use :space_station_type("new_ground") etc. to specify
the exact type of station model to use. The name is the json filename
without the extension.
=> Add :space_station_type to CustomSystemBody

data/lang/ui-core/en.json, data/pigui/game.lua, src/WorldView.cpp
Also remove redundant text (combat target speed / distance) that is shown
already near the reticule.
=> Add combat target pro- and retrograde indicators

osx/pioneer.xcodeproj/project.pbxproj
The Assimp library referenced from the MacOS Xcode project has been upgraded to version 3.2.0. From now on, the generated install packages for MaxOS X will include the new version.
=> Upgraded Assimp to v.3.2.0 in Xcode project

src/Player.cpp, src/Player.h, src/Ship.cpp, src/Ship.h, src/ShipCpanel.cpp, src/ShipCpanel.h, src/ShipType.cpp, src/ShipType.h, src/WorldView.cpp
Crush the ship if it can't take the pressure as, optionally, defined in the ship type.
To set different crush depths for ships add a parameter like, eg: `atmospheric_pressure_limit : 17.0`, to their ship definition. This defaults to 5 * Earths Atmosphere at sea level, aka 5 bar.
Titan should have a surface pressure of 1.45 bar, and should be viable for a ship landing.
Venus should have a surface pressure of 90 bar, and is totally out of landing!
PR formerly known as: "*Pop goes the weasel!*"
=> Simple atmospheric crush pressure

src/ShipCpanel.cpp, src/ShipCpanel.h
Fix #4013 crash.
There was an uninitalised and _mostly_ unused pointer hanging around, only used in an unused ctor and when saving.
=> Remove remaining legacy camera button

src/LuaBody.cpp
Entering certain systems (it seemed to be binary ones) caused Pioneer to crash with this message:
error: [string "[T] @pigui/game.lua"]:674: invalid order function for sorting
stack traceback:
[C]: in function 'sort'
[string "[T] @pigui/game.lua"]:674: in function 'displayOnScreenObjects'
[string "[T] @pigui/game.lua"]:746: in function 'fun'
[string "[T] @pigui/pigui.lua"]:42: in function 'window'
[string "[T] @pigui/game.lua"]:739: in function 'fun'
[string "[T] @pigui/pigui.lua"]:71: in function 'withStyleColors'
[string "[T] @pigui/game.lua"]:738: in function 'game'
[string "[T] @pigui/pigui.lua"]:83: in function <[string "[T] @pigui/pigui.lua"]:81>
I haven't coded in Lua before, but it seems the error is regarding the sorting function.
A quick google search revealed the sorting …
=> Fix for incorrectly implemented comparison function crashing Pioneer upon entering system

data/pigui/modules/fx-window.lua, data/pigui/pigui.lua, src/LuaPiGui.cpp
Add support for the missing modifier keys in lua.
Only run the main menu keys when pressed without any modifier (as a preparation for S-F1 etc. for time accelleration).
=> Support modifier keys in lua.

src/CameraController.cpp, src/FloatComparison.h, src/LuaShip.cpp, src/SectorView.cpp, src/Sfx.cpp, src/ShipAICmd.cpp, src/ShipAICmd.h, src/SystemView.cpp, src/galaxy/StarSystemGenerator.cpp
- Use explicit Json::Value::Int.
- Resize some snprintf buffers.
- Ignore -Wfloat-equal where necessary.
=> Fix all GCC 7.1.1 warnings.

src/SpeedLines.cpp
Incredibly minor change; less denser generation for speedlines, avoiding speedlines to look like they appear at the same relative location to the ship. Looks almost the same as before. Let's avoid making the area too large though, it also looks bad.
As you see I didn't touch the velocity-relevant parts.
=> Decreased density for speedlines

win32/vs2015/modelcompiler.vcxproj, win32/vs2015/pioneer.vcxproj
I noticed when switching back and forth between 32-bit and 64-bit with VS2015 that I would fail to link the 64-bit version if you'd already done that configuration in 32-bit.
So stop trying to link against 32bit library paths in 64-bit builds!
=> VS2015, 64bit linking fix.

src/Camera.h, src/Frame.h, src/Lang.h, src/LuaTable.h, src/Space.h, src/SpeedLines.cpp, src/galaxy/SectorGenerator.cpp, src/galaxy/StarSystem.h, src/graphics/VertexArray.h, src/graphics/opengl/RendererGL.cpp, src/gui/GuiContainer.h, src/scenegraph/Group.h, src/scenegraph/Model.h, src/scenegraph/StaticGeometry.h, src/ui/Container.h, src/ui/TextEntry.cpp
Mostly a case of doing the following.
- return Uint32, using `static_cast`, where appropriate
- cast to Uint32/Sint32/size_t where necessary
There are lingering 64-bit portability warnings but this reduces the bulk of them in vs2015 and hopefully will do on other platforms.
=> Cleaup 64-bit warnings in vs2015

configure.ac
This is to fix #4054
Update the configure.ac to handle assimp major versions greater than 3
=> Handle assimp major versions greater than 3

src/Ship.cpp
On gameplay side: this gives me another reason to not forget my wheels down, aside from the atmospheric effects.
Allows countdown to finish beforehand so player has time to retract it if he/she didn't already.
Fails to enter hyperspace if the gear is down at the moment the countdown finishes; plays the abort sound, continues flight status of FLYING.
On science side: a very slight shift in geometry and center of mass causes unpredictabilities for hyperjump calculations etc.
=> Fail hyperdrive when wheels are down

src/ui/Context.cpp
Changed an assert to an if check. It prevents the crash but there is still a UI issue.
It fixes #4059 in that it prevents a crash but it leaves the dropdown in the wrong state and you must double click it the subsequent time to reactivate it.
=> Avoid crash on ESCaping a UI Dropdown.

src/LuaBody.cpp
A continuation of #4053: it didn't account ordering guarantees expected by Lua sort, resulting in Lua "invalid order function" when comparing two gas giants.
=> Sort order fix

src/PiGui.cpp
Mouse pointer with no UI has little practical use, and just gets in the way of screenshots/capture.
=> Hide mouse pointer when GUI is not being drawn

data/lang/core/en.json
It changes "Fire laser" to "Fire weapon" in the key bindings options screen and
changes "Laser fire detected" HUD message to "Weapons fire detected".
Made with the builtin editor of github, but I'm not sure if it created the branch here or on my fork.
=> Change laser to weapon in some core en.json

data/modules/TradeShips.lua
Presumably, traders may have a nil starport, causing seldom graceful crashes.
=> Fix occasional nil dereference

data/lang/core/en.json, data/lang/ui-core/en.json, data/pigui/game.lua, data/pigui/modules/gauges.lua, data/pigui/modules/planetary-info.lua, data/pigui/modules/time-window.lua, data/pigui/pigui.lua, data/pigui/themes/default.lua, src/FixedGuns.cpp, src/LuaBody.cpp, src/LuaPiGui.cpp, src/LuaPlayer.cpp, src/LuaShip.cpp, src/Ship.h, src/WorldView.cpp, src/WorldView.h
Updated Screenshot:
Video: https://nofile.io/f/RmxMJxqKkWL/gauges.mp4
=> Add imgui gauges and planetary information 

src/graphics/opengl/RendererGL.cpp
I have extended the far clip plane to 100,000,000 units, and reduced the near plane to 0.001 units. In truth the near plane could probably go out even further than that but I've tested this and it works so am leaving it alone.
This fixes #4077 as the star is no longer clipped against the far plane, increasing the near plane keeps the range the similar and so avoids precision issues (_I hope_).
=> Fix Star/planet/gas giants popping into view.

data/modules/CrimeTracking/CrimeTracking.lua
For shooting or murdering ships, the victim would get the fine
of murder or piracy.
(Untested)
(bug reported on IRC by @nozmajner)
Semi-unrelated sidenote: there is no event trigger exposed to lua for missile fired.
=> Law-bugfix: No, the victim is not a criminal

data/lang/ui-core/en.json, data/ui/StationView/Lobby.lua, src/LuaSystemBody.cpp
This is "nice to have", as it differentiates stations a bit more,
and you become more aware of being in an orbital station.
I wanted to show it here, to see if this is something we want, before I start fixing the time format.
=> Orbital stations provide (some) orbit info in lobby

src/Ship.cpp
I don't want very noticable bugs so this is the workaround until we agree to change the AI behaviour a bit (AI shouldn't try to hyperspace as soon as it lifts off, it is illegal and annoying)
=> Workaround for issue #4098

src/SystemInfoView.cpp
Adds information on how surface acceleration on a particular body relates to Earth g.
=> Add Earth g comparison in system info view

data/systems/00_sol.lua, data/ui/MainMenu.lua
__Primary reason:__ make use of the `space_station_type()` from #3990
__Secondary reason:__ In 2014, when Nyankosensei made the new ground station, we
moved starting location from the more original Elite/Frontier/European start
of London, to L.A (#3485); because that's where the random number generator
happened to give us the new octagonal station. Well, now we can specify
explicitly the station type, so no reason to be in L.A. anymore (other than
celebrity spotting?).
Also, development contributions from US have been minimal, so why be there?
__Reason against:__ Unnecessary save bump (I suspect?), 25% of our downloads are
from US, last time I looked.
=> Move game start location for Earth back to London

src/Propulsion.cpp, src/Propulsion.h, src/Ship.cpp
The problem seems to have been caused by incomplete modification of the places that use the thrust values to calculate times, forces and other values.
The fix I've gone with adjusts the linThrust and angThrust instead of trying to modify everywhere that uses them.
This fixes #4100 and I've tested it with bespoke thrusters on the affected planet/system.
=> Fix autopilot getting being fed bad data.

data/ui/StationView/BulletinBoard.lua
Bulletin board splitted to 2 columns. I wanted to make a floating search field, but dont know how: [documentation](https://pioneerspacesim.net/codedoc/files/LuaBody-cpp.html) does not have references to ui elements. And [there](https://pioneerwiki.com/wiki/Scripting_and_Mission_Creation) no ui examples too.
=> Added search field to bulletin board tab

data/lang/module-stationrefuelling/en.json, data/modules/StationRefuelling/StationRefuelling.lua
'Welcome aboard' doesn't fit ground stations.
Use 'Welcome to' instead.
PS. The sum (here: $6.00) should probably not be split over multiple lines.
=> Use 'Welcome to' as greeting for Ground stations

win32/vs2015/collider/collider.vcxproj, win32/vs2015/galaxy/galaxy.vcxproj, win32/vs2015/gameui/gameui.vcxproj, win32/vs2015/glew/glew.vcxproj, win32/vs2015/graphics/graphics.vcxproj, win32/vs2015/gui/gui.vcxproj, win32/vs2015/jenkins/jenkins.vcxproj, win32/vs2015/json/json.vcxproj, win32/vs2015/lua.vcxproj, win32/vs2015/newmodel/newmodel.vcxproj, win32/vs2015/pioneer.vcxproj, win32/vs2015/sigcpp/sigcpp.vcxproj, win32/vs2015/terrain/terrain.vcxproj, win32/vs2015/text/text.vcxproj, win32/vs2015/ui/ui.vcxproj
Set the Enhanced ISA to Not Set from SSE2 on 64-bit builds where it's not valid.
=> VS2015, Fix 64-bit SSE2 flag warning

src/LuaShip.cpp, src/ShipAICmd.cpp
Fixes #4088.
Clamps orbit radius to 0.95x non-rotating frame radius, which prevents FlyAround from trying to do something impossible, bugging out and burning fuel.
Switched autopilot to use GetPhysRadius more generally, as GetPhysRadius now replicates the old autopilot behaviour. Effect radius now used as a minimum orbit radius rather than a multiplier. 
Results may be different in some high-gravity navigation edge cases, but I don't think any of them will be _worse_. 0.95 is a little marginal for maintaining an orbit with max time accel and large moonless planets (eg Venus) but the consequences aren't major if a ship does drift out.
=> Make orbit radius relative to GetPhysRadius, clamp to frame radius

src/collider/GeomTree.cpp
Why didn't I do a PR of this before? I thought I had!
I've been noticing the odd divide by zero which appears to be entirely possible from this function so checked before using the value.
=> Avoid division by zero doing AABB ray test

src/galaxy/StarSystemGenerator.cpp, src/galaxy/StarSystemGenerator.h
Check previous generated orbits to make sure we don't overlap.
It's enough to check only the `R1` condition of the generated "orbit" to prevent overlapping is it controls for the longitude of the station on the planet.
Fixes #4034
=> Fix cities overlapping

src/galaxy/StarSystemGenerator.cpp
Use fabs for double instead of abs for cross-platform compatibility.
Also limit iterations so that the loop will always break eventually.
fixes #4143
=> Use fabs for double instead of abs for cross-platform compatibility

src/GeoPatch.cpp
Spread the terrain skirts wider to avoid some [sparklies](https://www.katsbits.com/smforum/index.php?topic=762.0) due to parallel, edge-on triangles.
This widens the base of the skirts drawn around terrain causing the skirts of adjacent terrain patches to overlap and interpenetrate. This should prevent the occurrance of further terrain sparklies.
=> Spread the terrain skirts wider to avoid some sparklies

data/modules/TradeShips.lua
Makes things better, for now (their jumps may still be illegal, idk). Maybe we can add a delay so ships can travel even further away from the starport before jumping.
Gotta admit it is enjoyable watching the AI screw up :D
=> Stop tradeships crashing into landing pads while trying to hyperspace

src/galaxy/StarSystemGenerator.cpp
Allow (~10%) terrestrial planets to have ring systems.
Planets where the rings would overlap with the orbit of a Moon will have them removed again.
=> Allow planets to have rings.

src/Missile.cpp
Fixes #4155 
Belt-and-braces fix for crashes some time after a missile's target dies. The critical part is the one-liner in Missile::NotifyRemoved, which was an omission introduced when Missile was separated from Ship. The additions to StaticUpdate cause the AICmd object to be deleted once the target is dead and clear the thruster state, so the missile doesn't spin around at full power afterwards.
=> Fix missile death notifications, clear thrusters and AI on target death

data/modules/BreakdownServicing/BreakdownServicing.lua
Fixes #4158
Problem is the better the engineer the more the engine will break down and be
fixed,  spamming the player with "your drive was fixed" messages.
This bug must have been there for many years, but only noticable when player has a (good) Engineer, leading to more "true" dice rolls. So, the code used to do a dice roll at each jump for each crew member  and check if they should repair the engines, if yes/true, they repair it, even if it hasn't broken down, and even if warranty hasn't expired yet.
In addition, when the jumpcount is set back, it can reach negative values.
I also changed how probability approaches unity for breakdown after warranty expires.
A little plot to show how probability of engine breakdown increases after service warranty expired (about after 1 year):
Now let's …
=> Fix engineers constantly repairing engines, and negative jump counter

data/modules/StatsTracking/StatsTracking.lua
...instead use the methods in Character to determine when rank (e.g. 'HARMLESS' etc.) changes.
Fixes #4162 
100% untested, so need to verify there are no typos and works.
=> Don't hard code when combat rank changes in stats tracking module

src/LuaUtils.cpp, src/LuaUtils.h, src/Pi.cpp, src/utils.cpp, src/utils.h
Now _import tries to load by name, tries to load with ".lua" extension, then tries
to load from import directories and then relative by caller directory (if it
exists) with and without extension.
Imported files saves in the cache with full path key to avoid
duplicates.
New import should to work little slower than old, but it more
intuitive and support more variations.
Fixes multiinstance trouble, In future better to use import instead a dofile.
@ecraven you can to add own directories like "pigui" to load with import("pigui") here:
https://github.com/ColdSpirit0/pioneer/blob/320b16f84017d233e526121467bff2b54a7662d8/src/LuaUtils.cpp#L291
fixes #4124
=> _import() rework and fix for #4124

data/lang/module-breakdownservicing/en.json, data/modules/BreakdownServicing/BreakdownServicing.lua
When asking for service but without a drive (as in Bernards):
I split the intro message for "Break down and service" module, to separate the string that specifies the `drive` of the player, so that this sentence can be replaced by the "you don't have a drive" message.
=> Don't show 'None' for drive specs when asking to service engine

src/ShipController.cpp, src/ShipController.h
ShipController stored the mouse direction relative to the local frame orientation, so it was invalidated by frame switches. Easily demonstrated by flying out of Earth's rotational frame with the RMB held down.
This patch uses a mouse direction relative to root frame (identity) orientation instead, so it's not sensitive to frame switches. The externally accessible mouse direction (used to draw the mouse direction on the HUD) is translated to the local frame on call to maintain the previous functionality.
Because the mouse direction is no longer translated by planet rotation, there's a side effect where if you hover in an atmosphere with RMB held down (and no mouse movement), you'll maintain system-relative rather than planet surface-relative orientation. I can't see a practical situation …
=> Fix heading jump when switching reference frames with RMB held down

data/modules/Assassination/Assassination.lua
'FAILED' occurs when mission ship either lands or jumps, after taking off at
said mission time point.
But for some reason it looks like a spawned dock ship now will trigger a
`OnShipDocked` event, as the ship is spawned when the player enters the target
system, they will immediately get failed.
Closes #4154.
I'll remove the debug printout commits when I get confirmation this is
working, and ideally, we'll understand why this bug is triggered to begin
with, all of a sudden.
=> Don't fail assassins when entering mission system

data/pigui/modules/autopilot-window.lua
Autopilot currently doesn't have any icon for formation flying,
if indeed that is a nomenclature we want to use for the tooltip.
Closes #4163
Possibly, I'll update this if we get/want a "formation" icon.
=> Fix autopilot tooltip when (nav)targeting other ships

src/LuaPiGui.cpp
`pigui.withStyleVars()` did not worked with vector variables, attempt caused error. Now fixed, But no so clearly. Code needs to clean, because I dont know what types for what.
=> PushStyleVar now pushing also vector variables

src/SDLWrappers.h
Workaround for a crash bug in SDL 2.0.6, where SDL_FreeSurface doesn't work correctly when called with refcount >1. There's a [development patch for SDL](https://hg.libsdl.org/SDL/rev/a09c3f87a12f) but it may not hit release for a year or more.
This patch changes the behaviour of the SDLSurfacePtr wrapper to not call SDL_FreeSurface until the surface reference count reaches zero. As SDLSurfacePtr already adjusts the refcount manually, there should be no additional side effects with other SDL versions.
I don't fully understand the SDLSurfacePtr code, but this shouldn't make it any worse.
Works around the primary issue in #4174. There's other stuff in there so don't close it yet.
=> Don't call SDL_FreeSurface until refcount is zero

data/modules/SearchRescue/SearchRescue.lua
This fixes #4175. I'm now taking prospective hyperdrive size into account when selecting ships for passenger rescue missions. The crude way I did this before led to rare occasions where passenger cabins could not be fitted on the ship because of lack of space.
=> Fix SAR selection of ship sizes for missions. Fixes #4175.

generic-exec, pioneer
Symlink did not work by default from custom repo directory (not in /home/). Im think it fixes that problem.
Also you can to move, in example, `data/pigui/` and run `../../pioneer` from there.
=> Removed unnecessary symlink + pioner now executes from any place

src/PngWriter.cpp, src/graphics/gl2/GL2Renderer.cpp, src/graphics/opengl/RendererGL.cpp
We have a dependency on `libpng` but we also use `SDL_image`, this seems to work ok on Linux machines where there is a single global version of liubpng. 
However for the Windows (VS2015/et al) version we have different versions of libpng that are linked against and different version of the DLLs get loaded!
At time this causes screenshots to fail, along with several other uses and warnings which can interfere with development.
This is pretty nasty and given that there is a function in SDL_image to save PNG files it also seems unnecessary.
So this PR uses the `IMG_SavePNG` to save an image instead of doing all the work ourselves using libpng.
=> Begin removing direct libpng usage

scripts/build-osx.sh
This is the OSX binary build and upload script that I was using back in 2014. I've updated it for the current builds.
The script unfortunately still has local references specific to my dev machine (such as library locations), but I've tried to keep it as generic and straight forward as possible in the event someone else wants to take over OSX builds.
This PR also fixes #4181
=> OSX Binary Build script

data/systems/00_sol.lua
Adding a ground station to the moon, called Mariasurīru (Marius Rille, in japaneese, hopefully google translate got it right).
[It's at the location of that huge lava cave that the JAXA discovered with SELENE/Kaguya program.](http://www.isas.jaxa.jp/en/topics/001159.html). It's a quite nice looking place with a bunch of huge craters, the base is situated at a hillside.
=> Adding base to Moon (JAXA lava cave location)

data/modules/Assassination/Assassination.lua, data/modules/CargoRun/CargoRun.lua, data/modules/DeliverPackage/DeliverPackage.lua, data/modules/SearchRescue/SearchRescue.lua, data/modules/Taxi/Taxi.lua
This (very simple) pull request changes the assassination, cargo run, deliver package, and taxi missions to use rounded (whole dollar) reward amounts. It also changes the amount readouts to truncate the `.00` cent part. In my opinion this feels more "human" and cleans up the look of the BBS somewhat.
The rounding is *upward* in case anyone cares. Extremely slight modification in the player's favor but it's negligible in my opinion.
=> Rounded rewards

src/ModelViewer.cpp, src/NavLights.cpp, src/Pi.cpp, src/graphics/Drawables.cpp, src/graphics/VertexBuffer.cpp, src/graphics/VertexBuffer.h, src/graphics/gl2/GL2Renderer.cpp, src/graphics/gl2/GL2VertexBuffer.cpp, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/VertexBufferGL.cpp, src/gui/GuiLabel.cpp, src/gui/GuiScreen.cpp, src/gui/GuiTextLayout.cpp, src/gui/GuiTextLayout.h, src/text/TextureFont.cpp, src/ui/Label.cpp, src/ui/TextLayout.cpp
Refactor buffers to have a capacity and size so they can be reused instead of discarded.
The idea is to reuse Vertex/Index/Instance buffers when the data they're to be populated with is smaller than their current capacity. If the buffer is too small then it must still be discarded and a new one created.
This helps to avoid thrashing the drivers to create and destroy buffers all the time which can be very expensive.
This might alleviate performance problems on some ATi/AMD GPU drivers that have been reported in the past. Although we did a lot of work to fix those with @jaj22 already tuning up our OpenGL usage.
=> Refactor buffers to have a capacity and size

src/GZipFormat.cpp, src/GZipFormat.h, src/Game.cpp, src/Makefile.am
Doesn't change save version. Should still be able to load the previous
format. Looks for a GZip header when loading the game to determine
whether it is new or old format.
This just adds a GZip header to the save output by default. This makes
it possible to decompress using 'gzip' on the command line instead of
needing a custom tool.
=> Save as gzip-format file

src/Ship.cpp
Loading a savegame would leave alertstate cache values undefined possibly triggering an alert or postponing further checks hundreds of years into the future.
This fixes it, clearing the cache on load and adding a sanity check in UpdateAlertState()
=> AlertState cache cleared on load

data/ui/Settings.lua, src/LuaEngine.cpp, src/graphics/Renderer.h, src/graphics/dummy/RendererDummy.h, src/graphics/gl2/GL2Renderer.cpp, src/graphics/gl2/GL2Renderer.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h
Add the ability to query the maximum number of (MS)AA samples the GPU can support.
fixes #4192
@impaktor thanks!
=> Query the maximum (MS)AA samples

data/pigui/modules/time-window.lua
As an alternative to holding down the Ctrl key, you can also hold down the right mouse button & click to force time acceleration.
Should fix #4223
@joonicks how does that sound?
=> Force time acceleration if right mouse button is held down.

src/SectorView.cpp
zoomed out sectorview shows unexplored stars as gray instead of independent yellow.
=> UnexploredGray

src/Game.cpp, src/ShipType.cpp, src/SpaceStationType.cpp
For #4226. Makes the game abort on startup when it tries to load a ship-def or station-def that fails parsing. There should be a not-totally-useless error message written to stdout, or (on Windows) to output.txt.
Code structure is pretty bad (sorry).
=> Handle JSON errors in Ship Type, Station Type definitions

src/Factions.cpp, src/Factions.h, src/galaxy/Sector.cpp, src/galaxy/StarSystemGenerator.cpp
Adds a new command to use when creating custom factions, setting the faction for any individual starsystem or sector.
When creating custom factions, either when doing the Faction.New(), add a :claim(x,y,z,idx) or after the f = Faction.New() add rows of f:claim(x,y,z,idx)
f:claim(x,y,z) for every star in a sector,
f:claim(x,y,z,idx) for an individual starsystem
claims are checked before expansionrate claims
custom systems can not be claimed, only randomly generated ones.
fixes  #4231
=> Allow custom factions to make claims

src/LuaGame.cpp
programmer forgot the cached value "view" and calls the function again to get the value
=> Minimal slipup

data/libs/SpaceStation.lua, data/ui/StationView/Police.lua, data/ui/StationView/ShipRepairs.lua, src/LuaRand.cpp, src/LuaUtils.cpp, src/Random.h
Warning: This will change some procedurally generated stuff due to changing hash_random output and changing Rand seeding.
Tries to make hash_random a little less broken, and stop using it to seed another RNG. Also restricts the output range to 32-bit (signed or unsigned)... though there's a good chance that code is still buggy as I didn't test it thoroughly. Also adds comments explaining the numbers in the hash_random random-double code. Also makes it an error to pass nil as the input to hash_random.
I have not tested the Lua side changes. I have opened up the game and checked that Rand:New('some string') doesn't completely break and that calling util.hash_random rejects some out-of-range values.
=> Some hash_random related fixes

src/LuaBody.cpp
Fix #4249 by changing lua_pushinteger for lua_pushnumber to preserve value of seed
=> Change lua_pushinteger for lua_pushnumber to preserve value of seed

src/galaxy/CustomSystem.cpp
No longer do you have to calculate the values into a fraction and preprocess with the f() function.
Now all attributes that took f() values, also accept real numbers. It accepts both.
Extra addition: you can use radius_km() instead of radius() to set the radius value in kilometers instead of size relative to earth. The proper value will be calculated by the computer, which is how it should be.
Example from 00_sol.lua;
local ceres = CustomSystemBody:new('Ceres', 'PLANET_TERRESTRIAL')
:radius(f(074,1000)) -- 473km
:mass(f(15,100000)) -- 9.393e20 kg
:temp(168)
:semi_major_axis(f(27675,10000)) -- 2.7675 AU
:eccentricity(f(758,10000)) -- 0.075823
:inclination(math.deg2rad(10.593)) -- 10.593°
:rotation_period(f(3781,10000)) -- 9h
:axial_tilt(fixed.deg2rad(f(4,1))) -- 4°
Can now be changed to; …
=> CustomSystem input syntax adapted for easier data entry

src/SectorView.cpp
no more quick and dirty labels. made the point stand out from the background clutter with contrast background. centered the label and decreased the margins slightly. label no longer overlaps the star.
=> sectorview zoomout prettier homeworld labels

src/galaxy/StarSystem.cpp
if pioneer says the atmosphere is hydrogen, you can scoop it. but its not super easy. often you have to get down to 1-2km altitude at speeds of 1000m+/s... at nighttime you really have to have faith in your instruments
+ comment in SystemBody::GetAstroDescription to point out that changing the threshold values for hydrogen atmospheres needs to be adjusted in IsScoopable too.
=> Hydrogen scooping from small planets with hydrogen atmosphere

src/Ship.cpp
offending lines exist in UpdateFuel() already.
the exact same lines.
```
void Ship::UpdateFuel(const float timeStep )
{
GetPropulsion()->UpdateFuel( timeStep );
UpdateFuelStats();
Properties().Set("fuel", GetFuel()*100); // XXX to match SetFuelPercent
if ( GetPropulsion()->IsFuelStateChanged() )
LuaEvent::Queue("onShipFuelChanged", this, EnumStrings::GetString("ShipFuelStatus", GetPropulsion()->GetFuelState()));
}
```
=> Updatefuel code duplication

src/LuaSystemBody.cpp
to be used when systemview moves to lua, and for my mysterious explorer mod...
new attributes accessible:
metallicity
volatileGas
atmosOxidizing
volatileLiquid
volatileIces
volcanicity
life
hasRings
pretty much all(?) attributes you need to determine visual and textual descriptions of system bodies
=> access all(?) systembody attributes in lua

data/libs/SpaceStation.lua
Major imports should frequently be out of stock,
minor imports low or out of stock,
minor exports always in stock,
and major exports always plentiful stock
hydrogen should always be plentiful in stock regardless.
on average, a station will keep stock to a value of up to 100,000 money for each commodity.
=> New calculations for station commodity stocks

data/modules/TradeShips.lua
if a tradeship sets course for an uninhabited system and arrives, while the player goes to the same system, once both are in system, the game will crash.
in tradeships.lua, there is a codepath that takes ships to getSystemAndJump with trade_ships[ship].starport set to nil. getSystemAndJump dereferences that value without first checking and so it crashes.
also, another bug. tradeships would only trade in minor imports and minor exports because of a poorly written if then elseif chain. its fixed here.
plus a bit of reformatting and optimising.
fixes #4253
=> Tradeships getSystemAndJump checking (crash bug)

data/pigui/modules/ship-internals-window.lua, data/pigui/pigui.lua, src/LuaGame.cpp, src/LuaPiGui.cpp, src/WorldView.cpp, src/WorldView.h
Clicking on the low thrust indicator or pressing F8 now shows the slider
above the low thrust indicator. The slider can be used to adjust the
amount of thrust when 'low thrust' is active. Clicking the low thrust
indicator or pressing F8 again hides the slider.
=> Move LowThrust Setting to ImGui

src/Projectile.cpp
**Issue**
Projectile collisions against small objects are extremely unreliable when the firer has significant frame-relative velocity. To demonstrate, use the Earth start, thrust outwards for ~500km or so, turn engines off and then spawn a small ship at 100m (eg. `Space.SpawnShipNear("kanara", Game.player, 0.1, 0.1)`). Try shooting it at various ranges. Some will be more reliable than others (17m cycle).
This is caused by CollisionSpace not storing or using the velocity of target objects. Essentially it takes a snapshot of object positions and checks the same ray against each. For correct behaviour, you'd need to test a different ray against each target, because the target-relative velocity of the projectile would vary.
Using TraceRay with basevel+dirvel ray direction is particularly bad: …
=> Fudge-fix projectile ray tracing

data/fonts/OverlayFont.json, data/lang/ui-core/en.json, data/pigui/modules/hyperjump-planner.lua, data/pigui/pigui.lua, src/LuaEngine.cpp, src/SectorView.cpp, src/SectorView.h
Work in progress!
This adds a hyperjump route planner to the new sector map in PR #4204. This PR is currently based on that branch and not master (not ready for merge yet!). 
The planner (lower right):
The planner has functions for adding the currently selected system, removing jumps, reordering and a *very* simple 'auto-route' feature. The option to 'remove jump when completed' will automatically remove the first jump from the list if you hyperjump to that system.
In addition to adding the planner itself:
- Add lines for the current route to the sector map (yellow lines)
- Altered the display of the 'far' (faction colored boxes) view. Smaller boxes and slightly more transparent
- Lowered the font size used on the sector map (and a few other places like the auto pilot screen), which makes …
=> Hyperjump Route Planner

data/libs/Equipment.lua, src/LuaEngine.cpp, src/MathUtil.cpp, src/MathUtil.h, src/SectorView.cpp, src/SectorView.h, src/galaxy/SectorGenerator.cpp
The route planner (@The-EG) is great but it can be a little bit slow when you're plotting a route over hundreds of light years.
There's a few other minor optimisations that snuck in whilst I was doing stuff too.
=> Route planner optimisations

src/CityOnPlanet.cpp
Fixes #4274 by setting the user data on city created `Geom` objects.
ping @jaj22 @CampNowhere 
I think that this supercedes #4275 by fixing the root cause rather than treating the problem but it might be worth merging both and adding an error or warning about the cause of #4275 as a message.
=> Set the user data for city geom objects.

src/galaxy/CustomSystem.cpp, src/gameui/LuaFace.cpp
Some RNG seed values are being transferred using checkinteger from Lua to C. This gives different results on x86 vs x64 (because lua_Integer is a different type), and potentially maps half the uint32 seed range to the same value. Face and CustomSystem are the only examples I found but there may be others.
Achernar uses custom system seeds > INT_MAX, so that was already different on x86 vs x64. According to #4295, the face generator was generating the same face half the time since the Lua-side seeds were expanded to 32-bit in a previous patch.
=> Fix broken Lua->C seed transfers in Face & CustomSystem

src/galaxy/SectorGenerator.cpp, src/utils.h
Two sets of really low level optimisations:
- Avoid using isqrt at all wherever possible by using the square of the comparison value instead.
- Replace soft isqrt with cast from sqrt which is 7.3 to x15 times faster.
Suggested in a post-commit [comment](https://github.com/pioneerspacesim/pioneer/commit/208065b95a187c8da10f6bb47cfd7eb21f2bd3e8#commitcomment-27075091) by @joonicks 👍
=> Minor optimisations around avoiding isqrt

data/pigui/modules/hyperjump-planner.lua
Fixes #4302
Only initialize the hyperjump planner variables if
the player is not currently in hyperspace.
=> Fix crash when opening main menu in hyperspace (#4302)

data/lang/ui-core/en.json, data/pigui/modules/settings-window.lua
Volume sliders now actually alter the volumes (and mute buttons also work!).
Also corrected the spelling of 'prison' in the start at Barnard's Star description.
=> Fix new ImGui volume settings sliders

data/lang/ui-core/en.json
People seem to agree that 
1. negative speed relative target is most intuitive
2. but tooltip is counter intuitive
=> Clarify tooltip, regarding sign of approach to target, closes #4206

src/DynamicBody.cpp, src/DynamicBody.h, src/FixedGuns.h, src/Propulsion.h, src/ShipAICmd.cpp, src/ShipAICmd.h
I noticed this crash as I started looking into another bug, simply selecting the New Hope start location crashed the game immediately.
It turns out that it was attempting to use a `nullptr` as the value hadn't been set, instead it was being assigned too a locally created variable.
Simple mistake, simple fix.
Since the objects lifetimes are also managed by a `DynamicBody` but pointers to them are held within Ai Commands I've also made them `RefCounted` objects.
=> Fix startup crash, m_prop was null

src/Player.cpp, src/ShipCockpit.cpp, src/ShipCockpit.h
Fixes #4306 by making sure that the cockpit is activated if it is being used.
I cannot fathom how it used to work or what has gone missing, but this should put it right.
=> Activate the cockpit if it's being used

data/lang/module-easteregg-message/en.json, data/modules/EasterEgg/Message.lua
Back in the day, my computer couldn't play Duke Nukem 3D, so I'm making up for it now. As a good nerd, I research all secrets, references and Easter eggs on each level as I play through the game.
On episode 1, level 1, in the bathroom wall, [there's a number](https://en.wikipedia.org/wiki/867-5309/Jenny "Tommy Tutone - 867-5309/Jenny"). Apparently it's "the worlds most famous telephone number" according to Urban dictionary. So why not add it on rare* occasions to pioneer.
But to me, there's [another song](https://en.wikipedia.org/wiki/Dirty_Deeds_Done_Dirt_Cheap_(song) "AC/DC - Dirty deeds done dirt cheap") that mentions a telephone number that fits better in with Pioneer, so I just had to add it, complete with references to the lyrics.
Downside: the player might wrongfully think this is …
=> Add Easter egg advert, (shown on every 50th station)

.tx/config, src/LuaLang.cpp
When lua Lang.GetResource does not find a resource, it throws a lua error,
mentioning the exact missing file, and does *not* just silently return nil.
Partially fixes #4327.
=> Throw lua error when specific Lang is not found.

COMPILING.txt
I noticed that we didn't mention VS2017.
I broke the lines because that's what we did through the whole file. It's easier to read I think.
=> Add MSVC2017 to COMPILING.txt

data/modules/Advice/Advice.lua, data/modules/Assassination/Assassination.lua, data/modules/BreakdownServicing/BreakdownServicing.lua, data/modules/CargoRun/CargoRun.lua, data/modules/Combat/Combat.lua, data/modules/CrewContracts/CrewContracts.lua, data/modules/DeliverPackage/DeliverPackage.lua, data/modules/DonateToCranks/DonateToCranks.lua, data/modules/EasterEgg/Message.lua, data/modules/FuelClub/FuelClub.lua, data/modules/GoodsTrader/GoodsTrader.lua, data/modules/NewsEventCommodity/NewsEventCommodity.lua, data/modules/SearchRescue/SearchRescue.lua, data/modules/SecondHand/SecondHand.lua, data/modules/Taxi/Taxi.lua
Fixes crash if one loads game prior to introduction of specific module.
For example, loading old games after introduction of Combat module.
Signed-off-by: Paul B Mahol <onemda@gmail.com>
=> Check if loaded_data.ads exist too

src/Camera.cpp, src/graphics/Frustum.cpp, src/graphics/Frustum.h
Fix a bug whereby the billboards were not being drawn for planets once they had gotten far enough away for that to be an option.
We have an onscreen pixel threshold below which we render planets and other objects as billboard.
However I broke that rendering when I rewrote the billboard code back in Apr 3, 2016!
To fix this the commit uses the billboard shader and the onscreen pixel size for a planet.
Fixes #4190
=> Fix showing Pale-Blue-Dot and other planets again.

src/ui/EventDispatcher.cpp
The game kept crashing for me due to accesses to `target` in EventDispatcher. This fixes that problem.
=> Check for nullptr.

data/pigui/modules/settings-window.lua
Happens when you try to disable multisampling in settings screen.
=> fix crash if user disables AntiAliasing

data/pigui/game.lua, data/pigui/modules/autopilot-window.lua, data/pigui/modules/equipment.lua, data/pigui/modules/fx-window.lua, data/pigui/modules/radar.lua, data/pigui/modules/settings-window.lua, data/pigui/modules/ship-internals-window.lua, src/KeyBindings.cpp, src/KeyBindings.h, src/LuaEngine.cpp
Previously keys like missile fire: M would trigger when changing keys. Closes #538.
=> Do not toggle bindings when in settings view

src/SystemView.cpp
This inverts the vertical axis of the system map camera and makes it behave similar to the sector map camera.
=> Uninvert system map camera

src/galaxy/StarSystemGenerator.cpp, src/galaxy/StarSystemGenerator.h
StarTypeInfo does not need or use the additional information that each entry is a star.
Noticed this redundant information a while ago.
=> StarTypeInfo cleanup

src/SectorView.cpp
This fixes issue #4383 by bounds checking before removing an element.
=> Fix issue #4383

data/lang/ui-core/en.json, data/pigui/modules/settings-window.lua
Having mouse over tooltip for only half of the options in settings menu bugged me. Now, I'm just bugged by some of the tooltip starting with capital letter, and some with lowercase. Not sure what is the most sane? 
@fluffyfreak care to skim through the strings I've added and see that stuff does what I say they do?
Planet, City and Fractal detail all use the same generic description: 
```json
"DETAIL_DESC": {
"description": "tooltip description in settings menu",
"message": "Lower gives better performance, at cost of visual aesthetics"
},
```
There are still two options lacking description. Not sure what to put here.
- `Fullscreen` - does this have any impa**k**t on performance?
- `Starfield density` - does this have any impakt on performance?
=> Add additional tooltips to the settings menu

contrib/json/CMakeLists.txt, contrib/json/Makefile.am, src/Beam.cpp, src/Body.cpp, src/CameraController.cpp, src/DynamicBody.cpp, src/FixedGuns.h, src/Frame.cpp, src/HyperspaceCloud.cpp, src/JsonUtils.cpp, src/JsonUtils.h, src/LuaSerializer.cpp, src/Makefile.am, src/Projectile.cpp, src/Propulsion.h, src/Sfx.cpp, src/Shields.cpp, src/ShipAICmd.h, src/SpaceStation.cpp, src/scenegraph/Model.cpp, src/scenegraph/ModelSkin.cpp, win32/vs2015/json/json.vcxproj, win32/vs2015/json/json.vcxproj.filters, win32/vs2015/pioneer.vcxproj, win32/vs2015/pioneer.vcxproj.filters, win32/vs2017/json/json.vcxproj, win32/vs2017/json/json.vcxproj.filters
These files aren't part of the jsoncpp library and are custom for Pioneer. They also directly include various other Pioneer source files. It's awkward having dependencies flowing in both directions between contrib/ and src/. Unfortunately this isn't the only place we've done it.
I have tried to update the VC++ projects as necessary, but I haven't tested them. I have not updated the XCode project.
=> Move JsonUtils.h/cpp from contrib/json/ to src/

COMPILING.txt, nix/env.nix
This fixes #4411.
I decided to change the build instructions to mirror what I did (except that I added the `--pure` flag to `nix-shell`, which hides all unspecified software from the spawned shell), because I tested it this way and it worked (`load-env-pioneer` gives me a bunch of errors).
_EDIT by impaktor: fix so it autocloses 4411_
=> Fix for issue #4411

src/ui/TextLayout.cpp
Fixes #4418
Somehow a sentence with 4 words was being turned into a zero length vertex array buffer.
This just prevents this from being passed on.
=> Quick fix for 4418, disallow zero length buffers

data/pigui/modules/system-overview-window.lua
Guard against the target objects body member being `nil` in some systems.
Fixes #4422
=> Fix crash when changing distance sort choice

data/lang/core/en.json, data/pigui/pigui.lua
The patch removes the ability to activate the autopilot from the radial menu if the ship does not have an autopilot, it also adds a message stating the error to the player's comms menu, if there is some other place that the message should be I can fix it.
=> Fix for issue #4386

data/pigui/pigui.lua, src/FixedGuns.h, src/Projectile.h, src/Ship.cpp
This is just a cherry-pick of @fluffyfreak's fixes that were added to #4207.
Clamp percent value in pigui. Supply default ctors for FixedGuns and ProjectileData. Update all guns in UpdateGunsStats.
=> Miscellaneous fixes (from #4207) 

CMakeLists.txt
This avoids an error when USE_SYSTEM_LIBGLEW is OFF then ON from the
GUI of CMake.
Fixes #4409.
=> CMake: Make GLEW as external target when using the system one

data/pigui/pigui.lua
#4404 was a bit overzealous and meant that you need an autopilot just to request docking!
This removes that requirement.
=> The docking request does not require an Autopilot

data/lang/ui-core/en.json, data/libs/SpaceStation.lua, data/pigui/mainmenu.lua, src/SystemInfoView.cpp, src/galaxy/StarSystemGenerator.cpp
This PR bumps the tech level for stations based on both population and whether or not it's a homeworld for a faction.
More could be done here, taking into account the distance from the homeworld divided by the radius of the factions bubble for example.
Also found a mistake in the solar federation faction which has had Mars as it's homeworld since it was created! 👍
=> Mostly tech level changes

src/LuaShip.cpp, src/Missile.cpp, src/Propulsion.cpp, src/Propulsion.h, src/Ship.cpp, src/Ship.h, src/ShipAICmd.cpp, src/ShipType.cpp, src/ShipType.h
Add the option to cap the maximum acceleration for each thruster on a ship.
Can be set via the `<direction>_acceleration_cap` field in the ship.json.
If no such field is set for a thruster, it is not acceleration capped.
=> Acceleration cap

.clang-format, .travis.yml, scripts/clang-format.sh, scripts/pre-commit-hook.sh
Per my conversation on IRC, I have implemented a harness for clang-format, mostly adapted from Godot's implementation.
The general gist of it is that, when properly hooked up in `travis.yml`, it will check all changed files in a PR to ensure that they adhere to the code style of the project, generating an error in the CI check if they are wrongly formatted. This will happen alongside the existing code compilation check and an error here will not affect the compilation step.
As the Pioneer code base is wildly inconsistent in and of itself, I have attempted to set sane and compliant defaults for clang-format. However, some limitations of the tool are insurmountable via mere configs - for example, the alignment of pointers and references are both controlled by the same clang-format switch. I …
=> Added a clang-format harness.

data/modules/MusicPlayer.lua, src/LuaStarSystem.cpp
The systemIndex component was `-1` which was then being used as an index.
I have no idea why only I'm seeing this since it should be crashing everyone's games
=> SystemPath was not fully specified causing a crash

src/LuaBody.cpp, src/LuaObject.cpp, src/LuaObject.h, src/LuaRef.cpp, src/LuaSerializer.cpp, src/LuaSerializer.h, src/LuaSystemPath.cpp, src/scenegraph/LuaModelSkin.cpp
*Updated 2018-09-02*
I've only done very superficial tests.
This replaces some of the custom bytestream serialization of Lua objects to generate JSON values instead. Long term I don't like this because it's likely to be very slow (both on save and on load), but short term it means that much more of the save file can be examined and interpreted by a person with a text editor (after decompressing the save), which is potentially valuable for debugging save problems.
When saving it just outputs the JSON version. When loading it will prefer to load the JSON version if available, but can load bytestream serialised data (ie, existing saves from before this PR) otherwise.
Lua->JSON structure:
- nil -> null
- bool -> bool
- integer -> integer
- string -> string (will definitely break for strings …
=> Pickle Lua values to JSON

src/Beam.cpp, src/DynamicBody.cpp, src/Frame.cpp, src/Game.cpp, src/HyperspaceCloud.cpp, src/JsonUtils.cpp, src/LuaSerializer.cpp, src/LuaSerializer.h, src/ModelBody.cpp, src/Projectile.cpp, src/Propulsion.cpp, src/Sfx.cpp, src/ShipAICmd.h, src/Space.cpp, src/SpaceStation.cpp, src/galaxy/CustomSystem.cpp, src/matrix3x3.h, src/matrix4x4.h, src/scenegraph/Model.cpp
With the merging of #4207 saving has gotten a little bit slower. This reminded me of the fact that there's lots of save optimisations we left on-the-table after #3680 and #3684
So here's a couple of little changes that together reduce the size of (_already compressed_) save games by ~26%
~Also this absolutely breaks all existing saves and thus far I'm making no effort to prevent that.~
Contrary to my initial statement this should load most recent save games alright.
=> Save game optimisations

data/systems/custom/06_61virginis.lua, data/systems/custom/07_1orionis.lua
- Fix spelling error in Portuguese placename
- Use Scottish Gaelic spelling for Scottish Gaelic placenames
- Replace invented placenames with ones that work in scottish
- Carndow was a duplicate, so I replaced one of those with a new name
@SpifforOmnivore I am allowing edits from maintainers, in case you don't agree with my changes. Keep up the good work! :)
=> Some linguistic fixes for world names

src/FixedGuns.cpp, src/FixedGuns.h, src/Ship.cpp
Replace the gunmount system with multiple gun mount locations for front/rear guns.
This could be extended later to allow for multi-barrel ships/systems.
Intended to fix #4397 
Problems:
- legacy ships/mods do not support dual-fire weapons
=> Fix dual fire weapon origin problems

src/CameraController.cpp, src/Game.cpp, src/GasGiantJobs.cpp, src/MathUtil.h, src/Space.cpp
Does what it says on the tin and makes the hyperspace exit point be uncomfortably close to the systems hyperspace target star.
I'm actually going to say that this is ready for testing now. It needs people to go about the galaxy jumping from place to place. Some stars are already pretty close in, others far out.
Ready for testing and feedback.
=> Move Hyperspace exit locations into the heart of systems

src/Pi.cpp, src/Pi.h, src/galaxy/SystemPath.cpp, src/main.cpp
skipmenu was broken, and didn't do anything anyway.
-startat (-sa) allows you to give a SystemPath to start at, skipping the main menu:
./pioneer -startat=(0,0,0,0,18)
=> Remove option -skipmenu, add option -startat.

data/lang/quitconfirmation-core/en.json, data/pigui/mainmenu.lua
Fixes #4469.
Font size was much too large. Quit dialog needed a bit of spacing. Build number displayed fully.
=> Improve main menu styling.

contrib/imgui/examples/imgui_impl_sdl.cpp
Fixes #4481.
For some reason, the way the IMGUI implementation handles capturing the mouse causes it to snap to the center of the screen whenever we right-click. Additionally, the polling of global coordinates instead of window-local coordinates is causing #4481.
I plan on revisiting this to implement it correctly, but for now this fix should work just fine.
@fluffyfreak has cursorily confirmed that this change is functional on IRC.
@clausimu a sign-off that this PR doesn't cause any undue problems (e.g. when dragging outside of the window, etc.) would be appreciated if you have time.
=> Disable the SDL_CaptureMouse path in IMGUI code.

data/ui/InfoView/PersonalInfo.lua
It serves literally no purpose right now and might even mislead players into thinking that being a part of a military possible.
I wanted to delete the strings as well but I don't know if they are used somewhere else in the code or if they can be any useful in the future so I left them for now. Can delete them on your wish.
That UI window got a little empty for sure. Maybe we can fill that space with the crime statistics of the player. For example: 
- Wanted in Solar Federation. 5534 Cr fine for unlawful weapons discharge (x3).
4432 Cr fine for illegal hyperspace jump.
6622 Cr fine for black market activities (x2).
- Outlaw in Obsidian Horde.
(I'm not volunteering for now.)
=> Don't show military allegiance info for player

metadata/net.pioneerspacesim.Pioneer.appdata.xml
It will now be the same as the one in https://github.com/flathub/net.pioneerspacesim.Pioneer/.
Then, the one in the flathub repo can be removed.
=> metadata: Add version number to release in AppData

CI/appveyor/build.sh, CI/appveyor/prepare.sh, CMakeLists.txt, appveyor.yml, pioneer.iss.cmakein, pioneer.rc.cmakein
Hi,
This PR adds a few scripts that allows the AppVeyor CI to create Windows builds of Pioneer on each tag, PR or commit. This is really useful to make sure that Windows builds don't get broken in the development process. Besides, creating releases is now very easy, as one can just redistribute the installer generated by AppVeyor that corresponds to the tagged commit.
For now, the generated installer only contains a 64-bit version of the game, but it shouldn't be too hard to alter the script to pack both 32-bit and 64-bit versions in one installer (I don't have time anymore to do it myself) or alter the scripts to do additional things (like pre-compile the models).
To use the AppVeyor CI, visit https://www.appveyor.com/ and sign up with your GitHub account.
In the projects list, click …
=> Generate an installer for Windows in the cloud with AppVeyor CI

.travis.yml, scripts/build-travis.sh
Pinging @impaktor. This invokes the modelcompiler binary from the Travisfile directly, and updates the build scripts to use the new binary location produced by CMake.
=> Fixup Travis build script for CMake support.

CMakeLists.txt
This prevents the following error when git is found and the source directory is not a git repo.
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
=> cmake: Test for a .git directory.

autoformat, scripts/clang-format.sh
Now we copy `scripts/clang-format.sh` to `.git/hooks/pre-commit`. Rewrote the previous hook into a tool for automatically applying the clang-format changes, with color output.
We've got documentation for the hook / code style in [the wiki](https://pioneerwiki.com/wiki/Coding_Conventions), though it will need to be updated for the new way of using the hook files.
=> Update the clang-format hook, add an auto-apply script. 

src/win32/buildopts.h, win32/vs2017/collider/collider.vcxproj, win32/vs2017/modelcompiler.vcxproj, win32/vs2017/pioneer.vcxproj
Re-add buildopts.h in Win32 folder for VS only. Supply path too it in relevant project files.
=> Fix VS2017 buildopts

data/lang/ui-core/en.json, data/pigui/game.lua, data/pigui/modules/settings-window.lua, src/LuaEngine.cpp, src/Pi.cpp
Move the screenshot information (body, system, path) shown in the upper left corner after hitting TAB several times from lua. Add a setting to the settings window.
=> System info from c++ to lua. Add setting.

data/pigui/mainmenu.lua, src/Intro.h, src/LuaEngine.cpp
=> Add ship name and class to intro screen.

CMakeLists.txt
=> CMake: Require external modelcompiler when cross-compiling

CMakeLists.txt
Install only the *.sgm precompiled models, as when they are present, the other model files aren't needed.
=> CMake: only install precompiled models

scripts/clang-format.sh, src/modelcompiler.cpp
This PR adds logic to handle a custom, command-line specified data directory when the modelcompiler is being used as a build tool. The new syntax is `modelcompiler -b /path/to/data`.
CC @orbea
=> Make modelcompiler handle custom data dir

.travis.yml, scripts/clang-format.sh
This PR improves the clang-format hook (and the autoformat tool) to only consider staged files and to safely deal with files clang-format throws an error on, including misidentified files and deleted files.
=> Improve the clang-format hook and autoformat tool.

.travis.yml, CMakeLists.txt, scripts/clang-format.sh
I've updated our travis testing environment to test against Mac OSX 10.13 High Sierra and upgraded the linux test environment to Xenial 16.04. This has the fortunate side-effect of getting rid of the `pioneer-thirdparty` dependency, as well as reducing compile times and simplifying our travis setup. 
This should have no effect on Appveyor builds, and is ready for merge immediately.
=> Add OSX to travis test matrix, upgrade Linux tests to 16.04 Xenial

src/LuaEngine.cpp, src/LuaPiGui.cpp, src/LuaPiGui.h, src/Pi.cpp, src/PiGui.cpp, src/WorldView.cpp, src/WorldView.h
In testing using `PIONEER_PROFILER` defined and our intrusive profiler (_V-sync off, multiple runs, ctrl+shift+p ingame once terrain generated_) this reduces the load of `l_pigui_get_projected_bodies` from ~8% down to ~1% of CPU time.
@ecraven has suggested there are other ways of doing this so this PR might only be useful as reference.
=> PiGui profiling changes.

src/HyperspaceCloud.cpp
Fixes #4552, maybe.
When loading a saved game with an HS cloud that doesn't have an attached ship, the m_ship pointer is unintialized, causing an immediate crash in MSVC debug and undefined behaviour everywhere else. This patch sets the value of m_ship to 0 in this case.
=> Fix game load crash with unattached hyperspace clouds

COMPILING.txt
The documentation lacks the instruction of CMake build in Windows, but it is strict forward to do so in MSYS2. I have added a few lines to describe that.
=> Add instructions on building pioneer with CMake and MSYS2

src/WorldView.cpp
Fixes #4560.
Looks like a refactoring typo. Crashes on every game load, at least with asserts enabled. Otherwise possibly undefined behaviour.
I haven't tested any other behaviour but this prevents the crash at least, and the rest looks superficially ok.
=> Fix game load crash typo

data/lang/input-core/en.json, data/pigui/modules/settings-window.lua, data/pigui/pigui.lua, src/WorldView.cpp, src/ship/PlayerShipController.cpp, src/ship/PlayerShipController.h, src/ship/ShipViewController.cpp
(Finally!) added localization support to the new input system.
=> Properly translate and localize the bindings options view.

data/lang/module-searchrescue/en.json, data/modules/SearchRescue/SearchRescue.lua
This should fix #4547. The SAR missions now handle destroyed target ships without leaving a "zombie" mission in the player's mission roster.
If the target ship is destroyed by accident (i.e. gravity pull, etc), the player is commended for trying to help the target ship and payed 1/2 the agreed upon amount.
If the target ship is destroyed by the player, the mission source is very upset, the player gets punished by removing 2x the reputation he would have otherwise gotten, and, obviously, there is not payout. 
In both cases the mission is closed and removed from the player's mission roster. The player has to return to the mission source for this to take effect.
=> Gracefully handle destroyed target ships in SAR missions

data/pigui/mainmenu.lua
The refactoring in #4548 missed one instance of `Vector`; this causes a Lua panic as soon as the main menu is shown.
I hope I'm not racing against someone else's fix; as of this writing, I see no mentions of this in the issues.
=> Fix crash on main menu

data/pigui/pigui.lua
Not sure if we use rotated icons anywhere, but if we do, the users would be in for a surprise.
I searched all lua files for occurrences of the old Vector class, this should be the last leftover, but maybe someone can doublecheck.
=> Replace leftover lua Vectors with Vector2

src/Pi.cpp
The default is WITH_DEVKEYS=ON so the build error was not detected by
the autobuilders.
=> Fix build with WITH_DEVKEYS=OFF

src/Space.cpp, src/collider/CollisionContact.h, src/collider/Geom.cpp, src/collider/Geom.h
**Summary:**
1) Close the closed #2337 (as it is still reproducible in master) tweaking the physical engine
2) Add some friction when colliding so a DynamicBody (or more) will stop.
3) Decouple some includes
4) Address some warnings
**Know issue:**
It can't handle more than x1000 time-accel, at least on my PC.
If you would me to split this PR or to open an issue about a possible
improvement of that feature, let me know.
=> Friction and sinking

src/NavLights.cpp, src/NavLights.h, src/SpaceStation.cpp
Closes #4.
Issue #4 is one of our longest standing issues, having remained open for five years. It's also stupendously simple to fix, once you figure out which class owns the navlights for spaceports.
I've taken the suggested light colors and tweaked them a little (blue for landed, yellow for takeoff, green for landing, off for vacant), as well as setting custom blink patterns for each stage. I've tested this on Cydonia and Mars High, the former of which works perfectly, while the latter doesn't actually have any pad lights at all.
I've also changed the way we store the light groups by using a `std::map` instead of a vector of vectors - this simplifies things immensely and also provides an extremely minor performance boost.
=> Change landing lights according to #4, rework the NavLights class.

src/Space.cpp, src/galaxy/SystemBody.h
Calculate the Equatorial Radius for a body, use it when making the frame for a star.
This fixes #4402
@WKFO when testing this you can use your save game file **_BUT_** you will need to jump out of the system and back in again **because otherwise it just reloads the bad values from the save file**!
=> Use Equatorial Radius when making the frame for a star

data/pigui/views/tab-view.lua
Fixes the bug described in #4614.
New tab-view now checks every frame whether the new or old tabview should be displayed
=> Fix hiding/showing new tab-view

data/libs/ui/PiguiFace.lua, data/pigui/libs/table.lua, data/pigui/modules/info-view/01-ship-info.lua, data/pigui/modules/info-view/02-personal-info.lua, data/pigui/pigui.lua, src/LuaPiGui.cpp, src/Pi.cpp, src/pigui/LuaFace.cpp, src/pigui/LuaFlags.h, src/pigui/LuaModelSpinner.cpp, src/pigui/ModelSpinner.cpp, src/pigui/ModelSpinner.h, src/pigui/PiGuiLua.cpp
It's what it says on the tin. @fluffyfreak should probably review the rendering code and make sure I'm not doing something stupid, but otherwise this one's ready to go.
I've done something a little _special_ with the infoview - I've written it so that it's ready to be used in the new sidebar layout I've been hashing out with @nozmajner; all you've gotta do is turn `_OLD_LAYOUT` off and call it from a parent which handles the sizing. I'm going to further extend this with a few custom widgets to achieve the look of the prototypes, but that's for another PR.
@vakhoir on the first window opening, the tab-view wants to show the newUI tab underneath the pigui tab - I'm leaving you to figure out what's going wrong with that code.
=> Pigui Model Spinner, move ShipInfo to pigui.

src/pigui/LuaFlags.h
Only use the std::initializer_list as an initialiser, store values in a vector
fixes #4618 for me on Visual Studio 2019/2017
pinging @Web-eWorks
=> Bug fix LuaFlags initialisation problem

CI/appveyor/build.sh, CI/appveyor/prepare.sh
The version that's already installed works fine. The version that is
available in the package manager doesn't, for some reason.
Fixes #4623.
=> CI/appveyor: Don't re-install cmake

README.md
The current URL points to a page that does not exist.
=> README.md: Fix download URL

src/Space.cpp, src/Space.h
As title says, remove `virtual` on Space,
`emplace_back` in Prepare (thus no copy or move are needed),
and use `nullptr` instead of 0
...little by little...
=> Remove unused virtualization of Space and 'emplace_back' elements

src/Color.h
Fix a bug introduced in c19aab4e4 ("Color.h: Fix conversion from float
to u8"). The order of operations was wrong.
The resulting behaviour was broken transparency on menu items, and probably other things.
=> Fix transparency on menu items

CMakeLists.txt, buildopts.h.cmakein, src/posix/OSPosix.cpp
Use CMake to detect the availability of feclearexcept, feenableexcept,
fedisableexcept.
Fixes #4645.
=> Autodetect availability of FPE ops

pioneer
During the Autotools removal in #4511 and #4635, this file was somehow forgotten. Since it is more appealing to use than some opaque `(cd build && make) && build/pioneer`, this PR opts to keep the script and to adapt it to use CMake.
The tangentially related `bootstrap` file is left untouched.
=> Update pioneer wrapper script to use CMake

CI/appveyor/msvc/prepare.sh, CMakeLists.txt, msvc-defaults.cmake
Does a few things to get Visual Studio builds going.
- Enable multithreaded compilation for VS, 
- prevent it Optimizing the models per-build, 
- fix up the pioneer-thirdparty paths
=> Fix VS CMake

data/libs/Equipment.lua, src/Ship.cpp
It should behave as before, except that with wheels down the temperature is little more (it treble without any shielding).
From now on, an atmospheric shield value of 1 will halve the temperature,
which is quite straightforward.
EDIT: Ops, It seems actually "Atmospheric shields" automatically goes down if wheels are down...
I can do like that but I would ask if it's not too much: if a ship has wheels up and is travelling fast, then hitting the wrong button (landing gear) means that the ship will overheat and probably will explode. Is this right/wished?
=> Use an equation in order to calculate HullTemperature

CMakeLists.txt, cmake/Modules/FindGLEW.cmake
This will be used only when compiling under MinGW, since MinGW's GLEW
config script seems to be really broken.
Fixes #4662.
=> CMake: Ship Debian's FindGLEW.cmake script

src/CityOnPlanet.cpp
Make the ModelNameComparator const so avoid illegal const conversion
=> Fix ModelNameComparator illegal const conversion

data/lang/ui-core/en.json, data/libs/ui/PiImage.lua, data/pigui/libs/market.lua, data/pigui/modules/info-view/01-ship-info.lua, data/pigui/modules/info-view/02-personal-info.lua, data/pigui/modules/info-view/03-econ-trade.lua, data/pigui/modules/info-view/04-missions.lua, data/pigui/modules/info-view/05-crew.lua, data/pigui/modules/station-view/01-lobby.lua, data/pigui/modules/station-view/02-bulletinBoard.lua, data/pigui/modules/station-view/03-commodityMarket.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/modules/station-view/05-equipmentMarket.lua, data/pigui/modules/station-view/06-shipRepairs.lua, data/pigui/modules/station-view/07-police.lua, data/pigui/pigui.lua, data/pigui/themes/default.lua, data/pigui/views/station-view.lua, data/pigui/views/tab-view.lua, data/ui/InfoView.lua, data/ui/StationView.lua, data/ui/StationView/Lobby.lua, src/LuaPiGui.cpp, src/pigui/Image.cpp, src/pigui/Image.h, src/pigui/LuaImage.cpp, src/pigui/PiGuiLua.cpp
_EDIT by @impaktor_ [this](https://help.github.com/en/articles/closing-issues-using-keywords#closing-multiple-issues) closes #4624 closes #4651 closes #4654, fixes #4545
Like I mentioned in the previous pull request, I noticed the ui doesn't seem to rescale very well. We typically use code like this to scale to current resolutin:
`local mainButtonSize = Vector2(32,32) * (ui.screenHeight / 1200)`
It usually works well enough. but only within the same aspect ratio. Calculating these sizes has also been annoying, because the formula assumes 1920x1200 as the base resolution, and I usually work on 1600x900. So I wrote the `ui.rescaleUI = function(val, baseResolution, rescaleToScreenAspect)` function, which will automatically rescale any value, or all values in a table, using the relatively …
=> Improved UI resolution rescaling

.gitignore, src/HyperspaceCloud.cpp
When using the `HyperspaceCloud` JSON constructor, the graphic was not properly initialized, causing a null-pointer dereference and subsequent segfault.
Also updated the `.gitignore` to ignore files from CCLS and properly skip coredumps.
=> Properly initialize hyperspace cloud graphics when loading.

.travis.yml
Homebrew provides 3.0.0 for libsigc++ and 2.10.2 for libsigc++@2.
https://formulae.brew.sh/formula/libsigc++
https://formulae.brew.sh/formula/libsigc++@2
This hopefully fixes travis, lets see what CI says.
=> travis: Install libsigc++@2 instead of libsigc++.

data/lang/module-combat/en.json
I picked this up from one of WKFO's combat videos on [YouTube](https://youtu.be/i__2Q-pQRGY?t=11): just a simple spelling correction for the English version (equiped -> equipped).
I went through the rest of the file and could not find any more corrections.
=> module-combat (en.json): correct spelling

data/pigui/modules/station-view/01-lobby.lua, src/FaceParts.cpp, src/LuaManager.cpp, src/LuaUtils.cpp, src/LuaUtils.h, src/SectorView.cpp, src/graphics/TextureBuilder.cpp, src/graphics/TextureBuilder.h, src/pigui/Face.cpp, src/pigui/LuaFace.cpp
Profiling some unrelated behaviour showed that we had some expensive behaviour going on.
`SectorView` was doing a lot of work displaying labels even when labels weren't being rendered. When they were being rendered there was still a lot of needless work happening. This mostly just moves around some of the tests and checks so it can early out more often.
Second we were rebuilding the station managers face every single frame!
That was obviously very bad and could account for anywhere from 10% to 25% of a frames CPU time! Not only that but it was thrashing texture generation etc.
This was a little tricky to track down and I had to add some additional profiling code and a Lua utility function called `pi_lua_stacktrace` that let me see how the call came up through the Lua callstack.
I've added …
=> Optimise sector view and docked face generation

data/libs/ui/NavButton.lua
Fixes #4703.
The way the NavButton was written, it looks like it was not expected to be pressed in hyperspace. I added some extra checks that fix the issue. I tried to show the option is disabled in the UI as well,but the :Disable method doesn't seem to do anything.
One more thing that came up is a SIGABRT that's thrown when you're not in the main game view as the hyperjump begins (you can switch to a different window when it's in progress). I tried to find the source but it's a pain to debug. I'm pretty sure that's a relatively new issue (wasn't there a PR that let you jump with the sector map open?), but maybe it's something to do with my setup. Can someone test this?
=> Fix midhyperjump game crash

COMPILING.txt
A build from source is not successful without `libfreetype6-dev`.
This package is available in in the Debian stable repos as well as Ubuntu repos back to 16.04.
=> Missing Debian/Ubuntu Dependency

src/Game.cpp, src/Game.h, src/LuaGame.cpp
When starting a new Game offset the start time from the year 2000, specifically Friday, 31 December 1999 23:59:59 so that the date and time are exactly 1200 years from whenever they start the game.
This is only done when starting a new game, saved games are not affected.
When testing it today my starting date and time were: 3219, Nov 16, 14:47
=> Use system time at start

scripts/build-travis.sh
OSX cp doesn't allow use of -r or -t, -r can be replaced with -R and -t can be avoided
This was causing the OSX Travis build to fail to deploy, or at least failing to copy files
https://travis-ci.org/pioneerspacesim/pioneer/jobs/613081290#L1006
=> Fix OSX Travis deployment

README.md
http://spacesimcentral.com/forum/categories/pioneer is a broken link, I did some searching around the site and the new link to their Pioneer forum is http://spacesimcentral.com/community/pioneer/
=> Fixed broken player's forum link

src/Space.cpp
This adds a maximum distance to the hyperspace exit calculation to ensure that the exit point isn't exorbitant far away. Maybe fixes #4479 .
=> Add a maximum distance to the hyperspace exit calculation

pioneer.iss.cmakein
This makes sure that we don't have leftover files from an old install of
Pioneer inside the new install.
UNTESTED.
Suggested in bug report #4744.
=> Inno Setup script: Remove old Pioneer files before new install
