pioneerspacesim/pioneer

src/scenegraph/Label3D.cpp

Yes folks this is the result of not testing things properly, which I should know better.
Andy

Check we have a vertex buffer before using it.

---

.gitignore

Ignore any sgm files in the repository so that they don't get committed to it.

Ignore any sgm files in the repository

---

src/Ship.cpp
src/Ship.h

Only update the list of nearby ships for every ship once per second.
Split out of #3320

Ship nearby optimise

---

src/Pi.cpp
src/ui/Context.cpp

Clear the depth buffer so that it draws the UI fresh.
Trying to fix #3308 and fix #2779
Slight problem is that I can't test it, Linux users (@impaktor) please give it a try!

Fix the UI strange rendering.

---

src/graphics/Renderer.h
src/graphics/opengl/RendererGL.cpp

Fix issue #3340 by initialising the value 'm_numLights' in the renderer and resetting it to a sane value in the `SetLights` method.
Andy

Prevent issue #3340 assert

---

AUTHORS.txt

Needed after added Romanian characters, #3318.
@johnbartholomew mentioned the copyright line might be wrong. I added them nonetheless just so we can look at them while pondering the isse.

Update AUTHORS after font rename

---

data/modules/StatsTracking/StatsTracking.lua
data/modules/TradeShips.lua

Attempt to fix #887 which was recently confirmed and @walterar has done some debugging on.
@impaktor would this work? It seems like it should.

Attempt to avoid calling methods on a nil object.

---

SAVEBUMP.txt
data/libs/NameGen.lua
src/Game.cpp
src/scenegraph/LuaModelSkin.cpp

BUMPED s_saveVersion to 81
Removed defunct ModelSkin loader registration.
Added new author names to NameGen.
Cleaned up SAVEBUMP.txt

Do SAVEBUMP tasks.

---

src/scenegraph/BinaryConverter.cpp
src/scenegraph/MatrixTransform.cpp

Due to recent changes SGM files will need to be rebuilt.
Also a single small optimisation to avoid updating the transforms if a local matrix is the identity matrix.

Update the sgm file version

---

data/lang/ui-core/en.json
data/ui/Settings.lua
src/GameConfig.cpp

A little while back I fixed up the VSync code and set it to check the 'VSync' config option. However I didn't fix the UI handling of it so the only way to change it was by editing the options file manually.
This just puts the checkbox back into the options screen.
I haven't done a translation for it though, brains a bit too tired today to work it out so if anyone wants to tell me what I need to do then I'll do it :)

Enable vsync

---

configure.ac
src/Game.cpp
src/LuaPlayer.cpp
src/Orbit.cpp
src/Orbit.h
src/galaxy/GalaxyCache.cpp
src/galaxy/Sector.cpp
src/galaxy/StarSystem.cpp
src/galaxy/StarSystemGenerator.cpp
src/libs.h
src/scenegraph/LuaModelSkin.cpp
src/utils.cpp

For #3387 and #3399. I'm not sure if this fully fixes #3387, but it fixes a stack corruption (incorrect scanf format specifier) and memory access violation.

Crash bug fixes

---

src/CargoBody.cpp
src/SpaceStation.cpp

Init model label in SpaceStation and CargoBody LoadFromJson

---

src/LuaRef.cpp

Should fix #3412.
Note: This patch is totally untested! Please test before merging.

Lazily initialise `m_lua` in LuaRef::LoadFromJson

---

data/systems/00_sol.lua
src/galaxy/StarSystemGenerator.cpp

Also, a Low Earth Orbit station.

Allow custom stations to have realistic orbit heights

---

src/NavLights.cpp
src/text/TextureFont.cpp

Spam glorious spam, it comes in a tin can AAAAAAND our debug output log...
...but not anymore.

Remove output spamming messages.

---

src/Camera.cpp
src/Color.h
src/Sfx.cpp

Keep rendering stars and planets even though they are very very far away.
I was going through some old branches to clear them out and found this one. Thought it worth fixing up and submitting for review.
Andy

Render far away

---

src/ModelViewer.cpp
src/ModelViewer.h

Tidying up the modelviewer a little as part of another PR that I'm working towards.

Modelviewer refactor

---

src/Color.h
src/GeoPatch.cpp
src/SectorView.cpp
src/Space.cpp
src/graphics/Drawables.cpp
src/graphics/opengl/VertexBufferGL.cpp
src/text/TextureFont.cpp
win32/vc2013Express/pioneer.vcxproj

This just cleans up some warnings that I noticed in the Linux and Win32 builds about type casting etc.
It's not all of them, just the most verbose to start with.
Andy

Cleanup build warnings

---

Changelog.txt
data/lang/ui-core/en.json
data/ui/Settings.lua
src/Background.cpp
src/Background.h
src/GameConfig.cpp
src/LuaEngine.cpp
src/Pi.cpp
src/Pi.h
src/Space.cpp
src/Space.h

After many complaints to fix #3343 I've implemented a slider to adjust from 0% to 100% the number of stars in the star field.
Andy

Control how many stars in the sky

---

src/scenegraph/Animation.cpp
src/scenegraph/Animation.h

This is try and fix a [reported issue](http://spacesimcentral.com/ssc/topic/4639-landing-gear-behave/) by Gernot.
I'm not able to repeat the problem locally but I do remember this giving us some trouble at the time.
@walterar if you would like to test this change, perhaps you can supply Gernot with executables for him to try out?
Andy

Remove the animation Interpolate optimisation.

---

README.md

Markdown now supports a little gpl3 badge. Maybe we want it?

Add license badge to README, markdown now supports it

---

src/HudTrail.cpp
src/win32/OSWin32.cpp
win32/vs2015/modelcompiler.vcxproj

Modelcompiler fixes for vs2015 build

Modelcompiler fixes for vs2015 build

---

src/collider/Geom.h
win32/vs2015/pioneer.vcxproj

Updating to VS2015 shook out a couple of minor issues (warnings) so this just fixes them.

Miscellaneous warnings fixes

---

data/ui/StationView/CommodityMarket.lua

now supports buying more than one unit at a time,
with checks and warnings. will also display descriptions if they are
present (right now they are not)

commodityMarket rewrite

---

src/Game.cpp

This was at first only a thing about fixing missing braces, but it ended up a real fix \o/
See the commit log for the details. I wouldn't mind someone else's opinion, specifically @fluffyfreak since I don't know how to test because I don't even get what's the angular velocity length thingy. (I mean I get each word separately, but the three together...)

Small time acceleration limitation fix

---

data/lang/ui-core/en.json
data/modules/AutoSave/AutoSave.lua
data/ui/Settings.lua
src/LuaEngine.cpp

Since there were complaints of long stalls when docking / undocking, and people not making use of it anyway.
Note: this is untested!

Make Autosave optional

---

contrib/PicoDDS/PicoDDS.cpp
contrib/PicoDDS/PicoDDS.h
src/BaseSphere.cpp
src/GeoPatchJobs.h
src/KeyBindings.cpp
src/SectorView.cpp
src/SectorView.h
src/Ship.cpp
src/ShipCockpit.cpp
src/SystemInfoView.h
src/SystemView.cpp
src/WorldView.cpp
src/graphics/Drawables.cpp
src/graphics/Drawables.h
src/scenegraph/BinaryConverter.cpp
src/scenegraph/Loader.cpp
src/scenegraph/LuaModel.cpp
src/ui/Box.h
src/utils.cpp

This should cleanup all but one of the clang warnings and fix #3523

Clang warnings

---

win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters

Removed forms and formcontroller from vs2015 project

---

data/lang/ui-core/en.json
data/ui/StationView/CommodityMarket.lua

translation for CommodityMarket.lua - data/lang/ui-core/en.json

---

src/Pi.cpp
src/win32/Win32Setup.h

Fix the broken win32 cross compile.

---

src/Makefile.am
src/WorldView.h
src/ui/Container.h
src/ui/Slider.cpp
src/uitest.cpp

Cleaning up a few things that I found while working on new-ui-galactic-view. See commits for details.

Minor cleanup

---

data/facegen/readme.txt

Attempt to document the facegen directory structure

---

data/lang/module-searchrescue/en.json
data/modules/SearchRescue/SearchRescue.lua

My initial goal was to provide some incentive to the player to actually go and explore some of those beautiful uninhabited worlds and places in space you would normally not go. In addition, I also wanted to have to get close to the cool ship models. At least that is how the idea was born...
I have tried to make the framework of the script easy to add on to. What it currently does is provide seven different flavors (with several randomly adjusted sub-flavors) of search & rescue missions where you have to:
* deliver fuel to stranded ships
* deliver replacement crew
* pickup crew and passengers from damaged ships
at different locations, such as:
* same planet the ground base is on
* vicinity of the orbital base the player is docked with
* an uninhabited planet within the same system
* orbit …

Search & Rescue mission script

---

win32/vs2015/gameui/gameui.vcxproj
win32/vs2015/gameui/gameui.vcxproj.filters
win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters
win32/vs2015/ui/ui.vcxproj
win32/vs2015/ui/ui.vcxproj.filters

This just fixes up the vs2015 projects

Remove galacticview

---

data/lang/module-deliverpackage/en.json
data/lang/module-fuelclub/en.json
data/lang/module-newseventcommodity/en.json
data/lang/ui-core/en.json

Turkish translator found this typo.
I open this PR to collect any/all typos in the already translated strings. I don't want to merge this at the moment, since it might not be of enough severity to require re-translating all existing versions of this string, which are probably correct to begin with.
Also, maybe rob can do some magic to alleviate that, once he attacks #3324

Fix typo in language strings (possibly WIP)

---

data/ui/GalacticView.lua
src/graphics/Drawables.cpp
src/ui/LuaContext.cpp

Fixes for a couple of bugs noted on IRC.
* Comms messages in the HUD were visible through the galaxy map.
* There's a warning about marker_dot.png being non-power-of-two.
See commits for details.

Galactic view fixes

---

src/WorldView.cpp

Round 359.5 degrees up to 0 (=360) degrees

---

src/Ship.cpp
src/ShipAICmd.cpp
src/ShipAICmd.h

Launch ship if necessary at start of AIDockWith

---

src/GeoSphere.cpp

For #3574. I don't think these assertions are useful.

Remove incorrect assertion on max planet detail

---

src/Planet.cpp
src/graphics/Texture.h
src/graphics/opengl/RendererGL.cpp
src/scenegraph/ColorMap.cpp
src/text/TextureFont.cpp

This is to avoid another repeat of #3590 which was mostly caused by these.

Remove TextureDescriptor default constructor arguments

---

src/scenegraph/BinaryConverter.cpp

OMG, this is the dumbest n00b programming error I've made in a long time
Missed off the brackets for a multiline "if" statement.
Fix #3596

Fix for broken SGM file loading.

---

src/ui/TextLayout.cpp

Fix for missing or discoloured text, the buffer was not being updated if it already existed.
Partially fixes #3604

Missing text fix

---

src/gui/GuiLabel.cpp

We fail to notice that the size has changed or needs to change.
@walterar this should fix the rest of #3604

Fix bad text size.

---

src/Pi.h

Pi.h had some old method definitions without corresponding implementations.

Cleaning up Pi.h

---

src/GeoPatch.cpp
src/Pi.h

I was a bit too aggressive with the crack avoidance values.
Eased off the multiplier a bit to avoid terrain cracks at low-patch-detail levels.

Fix terrain cracks

---

src/Projectile.cpp
src/collider/CollisionSpace.cpp
src/collider/CollisionSpace.h
src/collider/GeomTree.cpp
src/collider/GeomTree.h

I had hoped to do more but the 'BVHTree'/'Geom'/'GeomTreem' defies refactoring.
This just removes a few unused pieces.

Remove IGNORE_FLAG etc

---

src/vector3.h

These changes are back-ported from a branch I'm working on.
They add useful operators and 2D element swizzle functions.

vector3 changes

---

AUTHORS.txt
src/Makefile.am
src/ModelViewer.cpp
src/ModelViewer.h
src/RandomColor.cpp
src/RandomColor.h
src/Range.h
src/scenegraph/ModelSkin.cpp
src/scenegraph/ModelSkin.h
win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters

This is all @robn [fault](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=221) ... weekend my arse.
So I found the [C# port](https://github.com/nathanpjones/randomColorSharped) of the original JavaScript evilness and thought to my self `Well, how long can that take?!?`, about an evening and a bit it turns out!
To see this in action I suggest building Pioneer as usual, using `-mv wave` as the parameter, picking pattern number 6 from it's dropdown, and then repeatedly clicking the `Random Colour` button to see what it throws up.
My only query regarding merging is about the license, it was MIT and so that's what I've put at the header instead of our our Pioneer GPL license for now. I didn't want to restrict it's use by others in some way but I can change that if necessary.
PS: sorry, …

RandomColor Port for better random colours

---

src/LuaShip.cpp
src/Ship.cpp
src/Ship.h

For @nozmajner to play with :)
@laarmen, @impaktor, @johnbartholomew I'm not sure if this is the right way to do this, should these just be properties of each ship instead?

LuaShip accessors for a ships position and velocity.

---

src/LuaShip.cpp
src/Ship.cpp
src/Ship.h

Revert position and velocity as Properties, expose as GetPosition and GetVelocity LuaShip functions.
This is how I'd prefer to fix #3678 @laarmen

Change to GetPosition and GetVelocity LuaShip functions.

---

data/systems/00_sol.lua

Back port some of Marcels hometowns mod, mostly seeds and the `mars.hmap`

Back port some of Marcels hometowns mod

---

data/libs/Equipment.lua
src/LuaObject.cpp
src/LuaUtils.cpp
src/LuaUtils.h

Hi,
This PR is a bit of a warmup for me. It adds a 'debug mode' to the Lua context to allow us to sprinkle consistency checks and asserts throughout the code without having the average user crash because a modder has had a creative way to use our APIs. Also, it will make available to the user/dev/whoever types in the Lua console/my dog all the cool shit I'm going to try to develop next.
PS: I also added a check when serializing Equipment, because that's how I roll.
PPS: I now realize it probably won't catch the bugs I was thinking about because metatables and whatnot, but hey, c'est la vie!

Lua debug tools, part one

---

osx/pioneer.xcodeproj/project.pbxproj

An update of the Xcode project that should resolve Issue #3685

Updated Xcode project to fix "missing vtable" error

---

src/LuaConstants.cpp
src/LuaConstants.h
src/LuaStarSystem.cpp

This should take care of #3688, at least for the crash part. We still need to export the legality part to Lua somehow.

Legal custom cargo

---

src/graphics/TextureBuilder.h

Sometimes there is no name, allow for that.

Textures can be anonymous

---

src/Pi.cpp
src/Ship.cpp
src/Ship.h

Register signal for rough landing to reset time compression.
Fixes #3683

Landing resets time compression

---

src/Missile.cpp

Or crashed, for that matter. Anyway, AIKamikaze will not try and fail to go after invalid bodies anymore.
Ping @fluffyfreak , because i'm guessing the methods I've introduced might be useful elsewhere but I don't know much about this area of the code.

Cancel a missile order when the ship has jumped

---

src/LuaShip.cpp

Change the Lua AIKill command to check how legit is its target

---

configure.ac

Add EXTRA_CXXFLAGS to CXXFLAGS for assimp's version check

---

data/lang/module-goodstrader/en.json
data/modules/GoodsTrader/GoodsTrader.lua

Closes #3732.
I'm not over-enthusiastic about it, either we merge it or we don't, either way we get to close #3732.
Also 100% untested, so no merge yet.

Add some flare for black market, through flavoured slogans.

---

data/lang/module-taxi/en.json
data/modules/Taxi/Taxi.lua

Closes #3739
I've tested each line in game, but not all lines together in the if-statement, since I did not want to find a mission to a non-unique system, but this should be fine, but maybe @Wuzzy2 like to try/test it.

Passenger warns when jumping to wrong system with right name

---

data/modules/SearchRescue/SearchRescue.lua

Fix SAR distances

---

osx/install_ports.sh
osx/pioneer.xcodeproj/project.pbxproj
osx/pioneer.xcodeproj/xcshareddata/xcschemes/GenGitVersion.xcscheme
osx/pioneer.xcodeproj/xcshareddata/xcschemes/pioneer.xcscheme
osx/pioneer/pioneer-Info.plist

Changed COMPILING.txt from executable to read/write

Update for compilation on OSX

---

src/ShipCpanel.cpp

F3/F4 now switch back to the world view, if they are already active.

Make F3/F4 toggle instead of activating the view.

---

data/lang/module-assassination/en.json
data/lang/module-cargorun/en.json
data/lang/module-deliverpackage/en.json
data/lang/module-searchrescue/en.json
data/lang/module-taxi/en.json
data/lang/ui-core/en.json
data/libs/ui/NavButton.lua
data/modules/Assassination/Assassination.lua
data/modules/CargoRun/CargoRun.lua
data/modules/DeliverPackage/DeliverPackage.lua
data/modules/SearchRescue/SearchRescue.lua
data/modules/Taxi/Taxi.lua
data/ui/StationView/ChatForm.lua

Added navigation button to onClick() and onChat()

---

src/Background.cpp
src/Background.h

I broke the star streaks in hyperspace about 15 days ago and no-one mentioned it?!?

Fix hyperspace star streaks

---

data/configs/Starfield.ini
data/shaders/opengl/starfield.frag
data/shaders/opengl/starfield.vert
src/Background.cpp
src/Background.h
src/graphics/Drawables.cpp
src/graphics/Drawables.h
src/graphics/opengl/VertexBufferGL.cpp

With the change to PointSprites for starfield we lost the varying colours, added these back with @walterar preferred colouring scheme.
I think it looks better :)

Restore Starfield colourisation

---

src/WorldView.cpp

prefix std:: to isnan so it builds on Linux

---

src/CityOnPlanet.cpp
src/CityOnPlanet.h
src/scenegraph/StaticGeometry.cpp
src/scenegraph/StaticGeometry.h

This adds support for "idle" animations on buildings in cities.
It also fixed the problem with instancing of `SceneGraph::StaticGeometry` which was caused by me being spectacularly stoopid!
When game paused looking at Itzalean from 8.43km away:
Windows nVidia 970 goes from 50fps to 229fps
Linux Xubuntu AMD MESA goes from ~21fps (_11fps to 21fps_) to 65fps

Animated city buildings, instancing improvement.

---

data/modules/SearchRescue/SearchRescue.lua

This patch ports a great idea from @walterar and his Scout+ version of the SAR mission script. It limits the target planets of stranded ships to those closest to the station where the request is made. Why request help from Los Angeles for a ship stranded on a moon orbiting Pluto if Pluto Research Base is much closer, right?
I did implement it a little differently though to have less of an impact on ad frequency (there is more effort to find a valid target in my version instead of just dropping the ad if a closer station is found).

Search&Rescue module: limit target planet distance

---

data/modules/SearchRescue/SearchRescue.lua

Very minor change. Reduces the use of the more expensive shipdefFromName() function.

Search&Rescue: minor code speedup

---

data/systems/01_epsilon_eridani.lua

New seed with more varied terrain and repositioned surface stations so that, for example: Itzalean, is where we want it to be.

New seed and new locations of star ports for New Hope in Epsilon Eridani

---

src/Camera.cpp
src/Camera.h
src/CityOnPlanet.cpp
src/CityOnPlanet.h
src/FileSourceZip.h
src/KeyBindings.cpp
src/Missile.cpp
src/Missile.h
src/Player.cpp
src/Player.h
src/Ship.cpp
src/Ship.h
src/ShipAICmd.cpp
src/ShipCockpit.cpp
src/ShipCockpit.h
src/gui/GuiLabelSet.h
src/vector3.h

This is just the results of me running CppCheck over the codebase and tackling the performance issues it lists.
Mostly issues around passing by reference instead of value and initialisation in construction. Nothing ina  tight loop that will actually hurt us.

Minor performance cleanup

---

src/Makefile.am
src/graphics/TextureBuilder.cpp
src/graphics/TextureBuilder.h
src/graphics/opengl/RendererGL.cpp
src/modelcompiler.cpp
win32/vs2015/modelcompiler.vcxproj
win32/vs2015/modelcompiler.vcxproj.filters

So a while ago @HybridDog asked if we could use threads to speed up the modelcompiler #3782 and I said no...
...so here's a PR where I have threaded the modelcompiler!
I'm not 100% sure that this is a great idea, I mean it is faster, *MUCH* faster on my 12-thread PC. However it does introduce a mutex into the texture cache that will not currently be useful in Pioneer.
On the plus side, it's one more thing out of the way of us eventually multithreading the loading, and other sections of the game engine thus speeding that stuff up.
In short, have a look, tell me what you think people.

Multi-Threading modelcompiler

---

.gitignore

Update the .gitignore file for more vs2015 files outputs

Update the .gitignore file for more vs2015 files outputs

---

data/modules/SearchRescue/SearchRescue.lua

This PR does two things:
1) Building on #3811, #3814 and #3817, ship skins and patterns are now actively set and recreated in SAR missions when reloading a game after saving or returning to a system with target ships. Before, the "look" of a ship was random and would change when the same ship was recreated (for example when leaving and returning to a system). This would lead to loss of immersion into the game for players.
2) While debugging this code I also found another bug where target ships for expired missions were not recreated when returning to a system, leading to a crash. Target ships are now created for as long as the mission actually exists (expired or not).

Search&Rescue: set ship look and bugfix

---

data/lang/equipment-core/en.json
data/libs/EquipSet.lua
data/libs/Equipment.lua
data/ships/wave.json
src/PropertiedObject.h
src/PropertyMap.h
src/Ship-AI.cpp
src/Ship.cpp
src/Ship.h
src/ShipType.cpp
src/ShipType.h

Quick and dirty implementation of thruster upgrades using the equipment system.
The idea being that the player can buy one of 3 levels of upgrade for their ship. You will always have thrusters, the basic package but you can upgrade them by the following (*example*) amounts:
- 10% improvement
- 20% improvement
- 30% improvement

Thruster upgrades

---

data/lang/module-cargorun/en.json

Fixed grammar error

---

data/ui/StationView/ShipMarket.lua

Calculate ship selling price including equipment and damage

Calculate selling price including equipment

---

data/modules/StationRefuelling/StationRefuelling.lua
data/ui/StationView/Lobby.lua

Attempt to remove the autorefuel.
This is WIP

Remove autorefuel

---

src/PiGui.cpp

Put imgui.ini into UserConfig.

Put imgui.ini into user config dir

---

contrib/profiler/Profiler.cpp
contrib/profiler/Profiler.h

This fixes #3846 without random distro hacking.

Arm asm fix

---

src/CityOnPlanet.cpp

Attempting to render instances of zero size causes an assert, it's also a complete waster of time!

Don't try to instance zero entries.

---

data/ui/StationView/Lobby.lua

Lobby: Disconnect the property listeners when the docked station changes

---

data/ui/StationView/Lobby.lua

Lobby.lua: Add missing return

---

data/libs/SpaceStation.lua
data/libs/utils.lua

See title. Allows for stack traces a bit more useful than the info output in #3852

Add a few fail-early checks in the space station methods

---

src/ShipAICmd.cpp

Prefix std:: to isnan

---

data/libs/Equipment.lua

Use l:get when unserializing equipment

---

src/Ship.h

As referred here:
https://github.com/pioneerspacesim/pioneer/pull/3900
I did the opposite

remove IsPlayerShip from Ship

---

src/ShipAICmd.h

Replacement for #3918 by @mike-f1

Destructor on AICmdKill ensure no gun fire

---

src/ShipAICmd.h

Update to working code

---

osx/pioneer.xcodeproj/project.pbxproj
osx/pioneer.xcodeproj/project.xcworkspace/contents.xcworkspacedata
osx/pioneer.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

Updated Xcode project for MaxOS X to include all the latest changes.

Updated MacOS Xcode project

---

src/ModelViewer.cpp
src/ModelViewer.h

Pressing "o" key lead to orthographic view

Close #2665: Orthographic view in modelviewer

---

osx/pioneer.xcodeproj/project.pbxproj

Updated MacOS Xcode project in preparation for creating the new install package.

Upgrade of Xcode project for Mac OSX build

---

data/libs/Equipment.lua

Slot name typo

---

data/lang/module-policepatrol/en.json
data/modules/PolicePatrol/PolicePatrol.lua

This spawns a random police patrol who scans for illegal cargo.
Makes smuggling a bit more riskier.

Police patrol

---

src/graphics/gl2/GL2Renderer.cpp
src/graphics/gl2/GL2Renderer.h

This adds support for screenshots when using OpenGL 2.1 and should fix #3976

Add screenshot support for OpenGL 2.1 renderer

---

src/RandomColor.cpp

Output message copy-n-paste fix

Output message copy-n-paste fix

---

src/RandomColor.cpp

Replace switch default with explicit list in RandomColor.

---

data/icons/icons.svg
data/lang/ui-core/en.json
data/pigui/game.lua
data/pigui/pigui.lua
data/pigui/themes/default.lua
src/LuaGame.cpp
src/LuaPiGui.cpp
src/Pi.cpp
src/ShipCpanel.h

Change by right-clicking onto the 3D radar.
Mouse wheel changes the scanning distance.
I'd be glad about any comments and suggestions.

Implement an alternative 2D Azimuthal Equidistant Projection Radar.

---

data/lang/ui-core/en.json
data/pigui/game.lua
data/pigui/pigui.lua
data/pigui/themes/default.lua

Add a transparent black background to text
Add tooltips to various indicators
Add Delta-V percentage and number to reticule

Text background, indicator tooltips, delta-v numbers

---

win32/vs2015/modelcompiler.vcxproj

Fixup the modelview linker inputs

---

src/ShipAICmd.cpp

Fixes #3996
Also, fuck Git and the way that it never works on Windows.
Was #4000

Fix sqrt exception

---

src/SpaceStation.cpp

Bugfix to avoid damaging ships when you have permission to dock and fly trough spacestation (#3997)

---

src/Pi.cpp
src/Pi.h
src/graphics/WindowSDL.cpp
src/graphics/WindowSDL.h

Restore the mouse position after RMB/MMB.

Restore mouse position

---

osx/pioneer.xcodeproj/project.pbxproj

The Xcode project for MacOS X has been updated to include all the latest changes since April 3 to date.

Updated Xcode project for MacOS X

---

src/DynamicBody.h
src/ModelBody.h
src/Ship.cpp

This is just tidying up.
I noticed whilst reviewing some other code that there were a few unimplemented methods declared in a couple of headers.
They're no used, referenced, or implemented anywhere in the codebase and they've been haning around since the initial first commit!
So I'm removing them.

Remove unimplemented method declarations.

---

src/DynamicBody.cpp
src/DynamicBody.h
src/Missile.cpp
src/Missile.h
src/Propulsion.cpp
src/Propulsion.h
src/Ship.cpp
src/Ship.h
src/ShipAICmd.cpp
src/ShipAICmd.h
src/enum_table.cpp

This is the start of an effort to remove the inheritance relationships and replace them by composition.

The Great Disinheritance: make Propulsion a component

---

data/ships/kanara.json
data/ships/pumpkinseed.json
data/ships/pumpkinseed_police.json
src/DynamicBody.cpp
src/DynamicBody.h
src/FixedGuns.cpp
src/FixedGuns.h
src/Ship.cpp
src/Ship.h
src/ShipAICmd.h
src/WorldView.cpp

Continue with what #3989 started.

The Great Disinheritance: Make FixedGuns a component.

---

data/lang/ui-core/en.json
data/pigui/modules/time-window.lua
src/LuaGame.cpp
src/ShipCpanel.cpp
src/ShipCpanel.h

Moved the time and time acceleration display to lua.

Move time and time accel window to lua

---

data/libs/Ship.lua

Added a missing import to data/libs/Ship.lua

Fixed a crash pumping fuel into full tank

---

data/configs/Speedlines.ini
src/SpeedLines.cpp
src/SpeedLines.h

Make the values for speedlines configurable via ini file located in `data/configs/Speedlines.ini`

Configurable Speedlines via ini

---

osx/pioneer.xcodeproj/project.pbxproj

- Fixed broken reference in Assimp library
- Updated Xcode project to include latest changes

Install package for OS X (July 2017)

---

src/LuaBody.cpp

Fix comparison for "most important" object.

---

src/graphics/gl2/GL2Renderer.cpp
src/graphics/gl2/GL2Renderer.h
src/graphics/opengl/RendererGL.cpp
src/graphics/opengl/RendererGL.h

Fix segfault when exiting Pioneer

---

data/pigui/game.lua
data/pigui/modules/fx-window.lua
data/pigui/modules/radar.lua
data/pigui/pigui.lua
src/LuaPlayer.cpp
src/LuaShip.cpp
src/ShipController.h

Setspeed indicator, larger hud size, more frame info

---

data/lang/ui-core/en.json
data/pigui/modules/fx-window.lua

Make all main menu button tooltips translatable.

---

data/ui/InfoView/CrewRoster.lua

Add missing flight state in crew rooster.

---

data/icons/icons.svg
data/pigui/game.lua
data/pigui/themes/default.lua
src/Game.h
src/LuaPlayer.cpp
src/Pi.cpp
src/Player.cpp
src/ShipCpanel.cpp
src/ShipCpanel.h

Show alerts near the reticule with imgui.

---

data/pigui/game.lua
src/LuaPlayer.cpp
src/Player.cpp
src/Player.h
src/ShipController.cpp
src/ShipController.h

Make Ctrl-clicking select the set-speed target.

---

src/Ship.cpp

Untested, uncompiled. Beware!
(I can test it tomorrow).

Silence GCC warning

---

data/models/ships/molaramsayi/molaramsayi_hi.dae

It seems I forgot to add the gun tags. Which made it to fire backwards for some reason (which might be useful to investigate).
So I added both front and rear gun point, but there's no indication of weapons on the model/texture yet. 
I've also added some billboard lights.

Adding gun and light tags to Mola Ramsayi.

---

data/systems/00_sol.lua

Move Brasilia slightly so that it stays where it should and doesn't get relocated across the world.

Move Brasilia a little bit

---

src/ObjectViewerView.cpp

Whilst tracking down #4094 I realised that I needed the SystemPath for a station on a planet, so I've added it to the `ObjectViewerView` (Ctrl+F10).

Add SystemPath to the ObjectViewerView.

---

data/systems/00_sol.lua
src/LuaFixed.cpp
src/ShipAICmd.cpp
src/galaxy/StarSystemGenerator.cpp
src/terrain/Terrain.cpp

Pull-requestified what @jaj22 said in #4099, and gave authorship / "blame" of commit to him.
Closes #4095, #4099, #4048

Fix Sol planetary asteroids masses being off by factor ~100

---

src/galaxy/StarSystemGenerator.cpp

Distribute stations by orbital shell, then by separation of orbits to better handle many stations.
Fix #4105

Fix orbital stations sharing an orbit.

---

.gitignore

Ignore all Pioneer x64 Visual Studio files

---

data/lang/module-policepatrol/en.json
data/modules/PolicePatrol/PolicePatrol.lua

Attack outlaws immediately and show no mercy.

Attack outlaws immediately

---

configure.ac

Set ARFlags for OSX builds. Fixes #4080

---

osx/pioneer.xcodeproj/project.pbxproj
osx/pioneer.xcodeproj/xcshareddata/xcschemes/GenGitVersion.xcscheme
osx/pioneer.xcodeproj/xcshareddata/xcschemes/pioneer.xcscheme

I've done these type of pull requests in the past (a few years ago) when building the OSX binary app bundle, and they have just been merged in.
If anyone wants to provide any feedback then please do so. All being well, I'll merge this in at a later date just before i release an OSX binary.

Bring the XCode project file up to date with the latest files and config.

---

src/posix/FileSystemPosix.cpp

For posix now, I'll test win32 and then will be possible to merge.

isFile check for ReadFile (fix for macos crash)

---

src/Ship.cpp

Hope this fixes #3512 once and for all :-)

Trigger onShipDestroyed on fatal crash into city

---

win32/vs2015/modelcompiler.vcxproj
win32/vs2015/pioneer.vcxproj

Remove references to libpng16.lib and zlib.lib from vs2015 project files

Part 2 of removing the libpng files

---

data/ui/MainMenu.lua
src/LuaEngine.cpp
src/Pi.cpp
src/Pi.h
src/main.cpp
src/utils.cpp
src/utils.h

Use './pioneer -skipmenu' or './pioneer -sm' to skip main menu and load game on Earth.
If all ok I can squash these commits.

Added -skipmenu/-sm flag

---

data/ui/MainMenu.lua
src/main.cpp

I also did a bit of cleaning up.
It's late, I'm tired, and on windows, so I can basically only tell you that it builds (and should work, of course ;-) )

Fix the MainMenu nil args crash

---

win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters

Added following files to the Pioneer project within win32/vs2015/pioneer.sln:
src/GZipFormat.cpp
src/GZipFormat.h
This fixes building on Windows within VS2015.

Add GZipFormat source files to VS2015 Solution

---

data/modules/TradeShips.lua

game crashes in tradeships.lua when entering an unexplored solar system
this = fix

tradeships.lua unexplored crashfix

---

win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters

Update to add missing versioningInfo files.

---

win32/vs2015/galaxy/galaxy.vcxproj
win32/vs2015/gameui/gameui.vcxproj
win32/vs2015/graphics/graphics.vcxproj
win32/vs2015/gui/gui.vcxproj
win32/vs2015/modelcompiler.vcxproj
win32/vs2015/newmodel/newmodel.vcxproj
win32/vs2015/pioneer.vcxproj
win32/vs2015/terrain/terrain.vcxproj
win32/vs2015/ui/ui.vcxproj
win32/vs2017/galaxy/galaxy.vcxproj
win32/vs2017/gameui/gameui.vcxproj
win32/vs2017/graphics/graphics.vcxproj
win32/vs2017/gui/gui.vcxproj
win32/vs2017/modelcompiler.vcxproj
win32/vs2017/newmodel/newmodel.vcxproj
win32/vs2017/pioneer.vcxproj
win32/vs2017/terrain/terrain.vcxproj
win32/vs2017/ui/ui.vcxproj

Add the lua contrib path to deal with Lua.hpp include changes

---

data/libs/Character.lua

Change **roll-play** to **RPG** (role-playing game).
roll-play :roller_coaster:
role-play :performing_arts:
role-playing game :unicorn: :european_castle: :game_die: :game_die:
:clown_face:

Comment fixup

---

Changelog.txt

in the nearview mode i think unexplored has always been gray

clarification of the unexploredgray patchnote

---

src/galaxy/StarSystem.cpp

m_averageTemp misconceptions taken care of. earth +15C is not an ice world, etc.
some source formatting for readability + comment

systeminfo temperature misconceptions

---

data/pigui/game.lua
data/pigui/modules/autopilot-window.lua
data/pigui/modules/comms.lua
data/pigui/modules/equipment.lua
data/pigui/modules/fx-window.lua
data/pigui/modules/gauges.lua
data/pigui/modules/planetary-info.lua
data/pigui/modules/radar.lua
data/pigui/modules/ship-internals-window.lua
data/pigui/modules/time-window.lua

someone forgot to add the headers on the new pigui

some forgotten copyright headers

---

src/ShipCpanelMultiFuncDisplays.cpp

no radar in hyperspace

---

src/CityOnPlanet.cpp

WIP
todo: introduce roads or maybe elevated maglev tracks
todo: introduce domes for non-atmospheric planets
todo: adding city flavors like contemporary/industrial/farmland/windfarm/solarfarm/etc...
todo: adding unique or rare buildings/monuments
with the code flattened and prepared, doing all that should be not-too-hard(tm)
the code already fixes tiny cities looking like a plus sign from above.
and the code should be a bunch faster.

CityOnPlanet rewrite: recursive to linear

---

data/modules/Mining.lua
src/CargoBody.cpp
src/Projectile.cpp

this code breaks out to lua the logic that detemines what you get when you blast away at an asteroid with a mining laser
original code spawned water, this code spawns coal ore instead
this is the bare code, my startup idea was to make a small chance of something rare spawning, like "strange crystal formation" which you could turn in somewhere for a reward, however if that should be integrated into the game or somehow split out as a module, I dont know.
also the name "SpawnMiningContainer" might be debated...though it does spawn a container with the returnvalue commodity.

Asteroid mining results controlled by lua

---

src/Pi.cpp

Minor fix to shipstat CSV output to assist with ship balance discussions.

Fix ship stat CSV output

---

data/pigui/modules/map-sector-view.lua
data/pigui/modules/planetary-info.lua
data/pigui/pigui.lua
src/LuaEngine.cpp
src/LuaPiGui.cpp
src/LuaPiGui.h
src/LuaStarSystem.cpp
src/LuaSystemBody.cpp
src/LuaSystemPath.cpp
src/SectorView.cpp
src/SectorView.h

This moves the entire sector view UI to lua. Search is interactive (and finds all systems that match nearby, not just the "best").
Left upper corner is the "Search" window, right upper corner is the "Factions" toggle.
Please comment on things that should be improved ;)

Move sector view (F2) to lua

---

win32/vs2017/modelcompiler.vcxproj

it was still using the old 2015 folders and libs

Modelcompiler fixes for x64 linking

---

src/SectorView.cpp

Remove unused variable and update the comment

---

src/CityOnPlanet.cpp
src/collider/Geom.cpp
src/collider/Geom.h

setuserdata for collision handling,
create building geom in a single call instead of three

cityonplanet setuserdata optimized

---

src/ModelBody.cpp
src/collider/Geom.cpp
src/collider/Geom.h

- Remove SetUserData, only allow via Geom ctor. 
- Cleanup class, cache pos when changed.

Updates to Geom class

---

src/galaxy/SectorGenerator.cpp

Correct the mistake that @joonicks pointed out.

Square the values now that the isqrt was removed.

---

data/modules/EasterEgg/Message.lua

EasterEgg: Call onDelete if removed

---

data/lang/module-combat/en.json
data/modules/Combat/Combat.lua

The player has to jump to an unpopulated or lawless system to do the job. Additional fuel is required to finish the mission in time. So a balanced ship between speed, firepower and protection is needed.

New mission: Combat

---

contrib/PicoDDS/PicoDDS.h
contrib/json/JsonUtils.cpp
contrib/profiler/Profiler.h
src/ByteRange.h
src/CRC32.h
src/Color.h
src/Pi.h
src/Range.h
src/scenegraph/Node.cpp

I'v found some unnecessary includes and formatting issues

Correct minor formatting/indentation

---

src/ByteRange.h
src/LuaPiGui.cpp
src/Serializer.h
src/win32/OSWin32.cpp

Inspired by starlings PR, just minor cleanup. Another branch incoming with some windows specific madness.

Cleanup minor warnings and header inclusion.

---

data/pigui/modules/saveloadgame.lua

* Do not attempt to show saved games if there is none yet
* Ignore case when user gives empty string for saving game
Signed-off-by: Paul B Mahol <onemda@gmail.com>

Fix various isuess when saving/loading games

---

win32/vs2015/terrain/terrain.vcxproj
win32/vs2015/terrain/terrain.vcxproj.filters

There has been some changes to the Terrain project, some files removed others added so this just needed a quick fixup and now VS2015 builds again!

Update changed files so vs2015 builds again

---

data/pigui/modules/saveloadgame.lua

Avoid using the _ variable
Cleanup the safe to use test

Small saveloadgame script cleanup

---

data/pigui/modules/autopilot-window.lua
data/pigui/modules/fx-window.lua
data/pigui/modules/map-sector-view.lua

Closes #4281.
Signed-off-by: Paul B Mahol <onemda@gmail.com>

Do not cut off information that was previously displayed

---

src/AmbientSounds.cpp
src/Sound.cpp

Closes #1057, #3804 and #1097.

Unbreak music fade in/crossfade

---

src/SystemView.cpp

Systemview

---

src/LuaPiGui.cpp

Fix misplaced ships in external view

---

data/modules/TradeShips.lua

Do not spawn docked ships without atmoshields in starports with atmosphere
Closes #2138.

Equip ships spawned planet side with atmoshields

---

src/CameraController.cpp
src/CameraController.h

With cursor key or with 4682 numpad keys.

Make it possible to change position of flyby camera

---

data/modules/SearchRescue/SearchRescue.lua

Fix crash if target ship is destroyed in middle of transfer.
Change mission location after completed transfer.

Fix spotted issues with SAR mission

---

src/CityOnPlanet.cpp
src/CityOnPlanet.h
src/GasGiant.h
src/GeoPatchJobs.cpp
src/GeoPatchJobs.h
src/GeoSphere.cpp
src/GeoSphere.h
src/MathUtil.h

Pass patch jobs the whole structure, breakdown within methods. 
Other very minor cleanup such as const and inline usage.

Cleanup PatchJobs code.

---

data/lang/equipment-core/en.json
data/libs/Equipment.lua
src/Ship.cpp

"Stolen" from @impaktor old branch.

Add heavy atmospheric shielding, allows easier fuel scooping

---

metadata/pioneer.appdata.xml
metadata/pioneer.desktop

These files will be used by Linux packagers to provide a proper
integration within the distributions.
As requested in the flathub PR: https://github.com/flathub/flathub/pull/531

Add .desktop and AppStream meta-data files

---

win32/vs2017/glew/glew.vcxproj
win32/vs2017/modelcompiler.vcxproj
win32/vs2017/modelcompiler.vcxproj.filters
win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters

Make visual studio build again after recent changes

Make visual studio build again after recent changes

---

win32/vs2015/glew/glew.vcxproj
win32/vs2015/modelcompiler.vcxproj
win32/vs2015/modelcompiler.vcxproj.filters

Fix vs2015 as well

---

AUTHORS.txt
COMPILING.txt
bootstrap

It appears I accidentally moved the change to AUTHORS into this PR. Oh well.
Update the `bootstrap` script to also generate CMake build files, and document it in `COMPILING.txt`.

Updated the tooling and info to include CMake.

---

win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters

Updated project files for new input files

---

CMakeLists.txt

@fluffyfreak This compiles just fine on my end. Please adjust as necessary to compile on Win32.

Update CMakeLists.txt to build the modelcompiler.

---

win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters
win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters

Update the visual studio projects for recent changes

---

src/galaxy/StarSystem.cpp

I changed some of the variable naming and tidied up the code name modification a bit. Cosmetic stuff mostly but it also avoids a nasty crash/exception on VS201X due to MS weirdness.

Cleanup ExportBodyToLua and the names it uses for output.

---

data/systems/02_local_stars.lua
data/systems/custom/10_ayizan_lacaille8760.lua
data/systems/custom/11_noril_wolf1061.lua
data/systems/custom/12_tau_ceti.lua

**Ayizan/Lacaille 8760**
Impoverished outdoor world
Solar Federation
More description and discussion on the [forum](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=578&start=10#p5843) :)

Custom systems continued

---

data/pigui/modules/saveloadgame.lua

Fixes #4456, typo / wrong language file used for localized string

---

data/systems/02_local_stars.lua
data/systems/custom/13_fomalhaut.lua

Federal military outpost
More info about Fomalhaut on the [forum](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=578&start=40#p5883)

Adds the Fomalhaut custom system

---

data/systems/02_local_stars.lua
data/systems/custom/14_sirius.lua
data/systems/custom/15_ross154.lua

More info about the system on the [forum](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=578&start=40#p5895) :)

Adds two custom systems

---

src/Background.cpp
src/Background.h
src/Color.cpp
src/Color.h
src/Game.cpp
src/Space.cpp

Display some of the nearest actual stars around you in addition to the randomly generated points.
This builds on a branch initially created by @ecraven.
Features:
- stars within 100 lyrs of players position (_~16,000 stars_)
- increases total and minimum number fo stars visible to 50k and 500k
- uses approximate real star colours

Partial Real Starfield Rendering

---

src/SystemView.cpp
src/SystemView.h

This brings animated zooming and rotation to the system view, similarly to those of the sector view.

Bring smooth transitions to system view

---

src/LuaUtils.cpp

Extend our `import()` to support Lua 5.2+ `require()` semantics - specifically, allow using `a.b.c` as a shortcut for `a/b/c.lua` or `a/b/c/init.lua`.
This change is seamless and does not require updating any existing code in either the C++ or Lua.
CC @ecraven for review / merge.

Support 'module.submodule' import syntax.

---

src/Ship.cpp

Fixes #4489 as suggested by @Web-eWorks
Tested and working. (At least I wasn't able to break it so far.)

Fix alert status not changing to red

---

src/Game.cpp
src/MathUtil.h
src/Space.cpp
src/Space.h

A few tweaks to the calculations of the hyperspace exit location,
inspired by fluffyfreak's recent changes from #4444.
This PR
- makes the calculations of exit direction and position mathematically more rigorous,
- places the hyperspace exit point further away from the system body,
though still in the centre of the system.
At two places in the code a vector orthogonal to a given vector in 3-dim space is needed. For this I added a function OrthogonalDirection() in MathUtil.h, which computes it in a mathematically save way.
The calculation of the exit distance is based on the mass and the radius of the star:
The distance is at least ten times the radius of the star and such that the velocity of a circular orbit at this distance is at most 100km/s. The second condition makes life easier for …

Adjust hyperspace exit calculations

---

src/LuaEngine.cpp
src/Pi.cpp
src/Pi.h
src/galaxy/Galaxy.cpp
src/main.cpp

Queue requests in response to UI events, never process them immediately.
Fixes #4502

Fixes crash on exit.

---

src/modelcompiler.cpp

Modelcompiler. Do not initialise SDL video and shutdown cleanly to avoid an access violation

Modelcompiler fixes, no video init, clean shutdown.

---

data/pigui/modules/map-sector-view.lua
data/systems/02_local_stars.lua
src/SectorView.cpp

Search for and show additional system names on map.

---

src/GeoPatchJobs.cpp

I was bad and didn't check this built in debug. Modified the asserts to be correct now.

Modified asserts to be correct now.

---

src/LuaPiGui.cpp

As the title says. Bug report passed along by @nozmajner, many thanks to him.

Fix an error preventing keybinding when joysticks are disabled.

---

CMakeLists.txt

Two commits to fix building of Pioneer under OSX.

Fix build under OSX

---

data/lang/ui-core/en.json
data/libs/ui/InfoFace.lua
data/ui/InfoView/PersonalInfo.lua
data/ui/StationView/ChatForm.lua
src/FaceParts.cpp
src/FaceParts.h
src/gameui/Face.cpp
src/gameui/Face.h
src/gameui/LuaFace.cpp

This is a manual face generator in the player personalInfo screen. It let's you pick and change each feature of the portrait. All other character portraits are still generated randomly (or "randomly").

Manual player face generator

---

data/pigui/mainmenu.lua

Hopefully I got this right, went by the comment in imgui.h
`// set next window size. set axis to 0.0f to force an auto-fit on this axis`
Fixes #4570

Autofit main menu

---

win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters
win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters

Updated vs201X projects for file changes

---

data/pigui/modules/hyperjump-planner.lua

Includes military hyperdrives in hyperjump-planer

Consider hyperdrive fuel type in the hyperjump-planer

---

data/modules/SearchRescue/SearchRescue.lua

Get an error in master:
```
Could not find model: sinonatrix_cockpit
error: [string "[T] @modules/SearchRescue/SearchRescue.lua"]:544: attempt to perform arithmetic on local 'pickup_crew' (a nil value)
stack traceback:
[string "[T] @modules/SearchRescue/SearchRescue.lua"]:544: in function 'calcReward'
[string "[T] @modules/SearchRescue/SearchRescue.lua"]:1333: in function 'makeAdvert'
[string "[T] @modules/SearchRescue/SearchRescue.lua"]:1984: in function 'cb'
[string "[T] @libs/Event.lua"]:34: in function '?'
[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>
```
...Thus I pushed the simpler solution.
It is quick and dirty: ~~not tested~~ and it should be checked if works for every mission

[Workaround to avoid CTD] Initialize variables to be integers

---

data/pigui/pigui.lua
data/pigui/views/game.lua
src/LuaVector.cpp
src/LuaVector2.cpp

Fix flight UI direction and vector indicators

---

data/pigui/modules/system-overview-window.lua

Adjusted position of the overview window button

---

data/pigui/modules/info-view/01-ship-info.lua
data/pigui/modules/info-view/02-personal-info.lua
data/pigui/modules/info-view/03-econ-trade.lua
data/pigui/modules/info-view/05-crew.lua
data/pigui/modules/station-view/01-lobby.lua
data/pigui/modules/station-view/02-bulletinBoard.lua
data/pigui/modules/station-view/03-commodityMarket.lua
data/pigui/modules/station-view/04-shipMarket.lua
data/pigui/modules/station-view/05-equipmentMarket.lua
data/pigui/modules/station-view/06-shipRepairs.lua
data/pigui/modules/station-view/07-police.lua
data/pigui/views/station-view.lua
data/pigui/views/tab-view.lua
data/ui/InfoView.lua
data/ui/StationView.lua

Same deal as with the Info View (#4573). Set up the Station View so each tab can be worked on separately.
Also moved the info-view logic to a tab-view object that can be also used by the station-view.

Start moving station-view to PiGui

---

src/Player.cpp
src/Player.h
src/Ship.cpp
src/Ship.h
src/collider/CollisionContact.h
src/collider/CollisionSpace.cpp
src/collider/Geom.cpp
src/collider/Geom.h

This is based on the old g-force system, I simply re-enabled it.
Then I made it damage the ship rather than just instantly `Explode()` it like it did previously!
There were some other warnings and they snuck in with the 2nd commit.
Fixes #4594

Basic Atmospheric heating re-enabled

---

src/Input.cpp
win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters
win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters
win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

Input.cpp needed the array header, fixup the project files

---

win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters
win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters
win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

Just another visual studio update

LuaColor files added to Visual Studio projects

---

data/pigui/modules/flight-ui/indicators.lua
src/LuaColor.cpp
src/LuaVector.cpp
src/LuaVector2.cpp

I've cleaned up some minor logic errors in LuaVector and LuaColor, as well as added more flexible construction syntax for the Vectors.
I've also complemented the manual assignment to vector components with a new syntax for setting all three components at once. I'm open to suggestions for a better syntax; vec(a, b, c) isn't exactly obvious, but it is compact.

Cleanup LuaVector and LuaColor implementations.

---

win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters
win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters
win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

Update VS201X files

---

data/lang/module-policepatrol/en.json
data/modules/PolicePatrol/PolicePatrol.lua

Fixes #4613. But be careful if you are going against multiple enemies. :-)

Do not tolerate piracy

---

README.md

Remove erraneous whitespace from README.md

---

README.md

Also, add link to windows nightly build, because it should be linked from _somewhere_ at least.
I'll squash the commits later, thought to keep separate if people protest against either change.
See what the logo looks like:
https://github.com/impaktor/pioneer/tree/add_badge

Add pioneer logo to README

---

.travis.yml
COMPILING.txt

Check whether this correctly runs the irc bot from travis.

test irc notification

---

data/pigui/modules/info-view/01-ship-info.lua
src/LuaPlayer.cpp

Uses methods from LuaPlayer.cpp to calculate acceleration and delta v.
Fixes also the atmo shield info.

Consider thruster upgrade

---

src/graphics/TextureBuilder.cpp
src/scenegraph/BinaryConverter.cpp
src/scenegraph/Serializer.h
win32/vs2015/modelcompiler.vcxproj
win32/vs2015/modelcompiler.vcxproj.filters
win32/vs2015/newmodel/newmodel.vcxproj
win32/vs2015/newmodel/newmodel.vcxproj.filters
win32/vs2015/pioneer.vcxproj
win32/vs2015/pioneer.vcxproj.filters
win32/vs2017/modelcompiler.vcxproj
win32/vs2017/modelcompiler.vcxproj.filters
win32/vs2017/newmodel/newmodel.vcxproj
win32/vs2017/newmodel/newmodel.vcxproj.filters
win32/vs2017/pioneer.vcxproj
win32/vs2017/pioneer.vcxproj.filters
win32/vs2019/modelcompiler.vcxproj
win32/vs2019/modelcompiler.vcxproj.filters
win32/vs2019/newmodel/newmodel.vcxproj
win32/vs2019/newmodel/newmodel.vcxproj.filters
win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

Fixes #4637 and also updates the visual studio project files (_whilst they're still around_)

Fixes loading old SGM models

---

data/systems/00_sol.lua

Fixes #4652 by marking the them as not having rings.
I checked all of the other bodies for rings, these were the only ones

Remove the rings from Venus and Ariel

---

CMakeLists.txt

No functional change, just code cleanup.

CMake: Fix indentation

---

src/ObjectViewerView.cpp

Added Axes drawing, usual Red/Green/Blue to help show orientation.
Also set objects to be slightly rotated so that it's easier to see them, especially useful for planets with rings.

Object Viewer

---

data/modules/SearchRescue/SearchRescue.lua

Fix for medical emergency mission

---

src/FaceParts.cpp
src/galaxy/Factions.cpp
src/graphics/TextureBuilder.cpp
src/graphics/TextureBuilder.h
src/pigui/Face.cpp
src/pigui/LuaFace.cpp
win32/vs2019/modelcompiler.vcxproj
win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

Since I'm still maintaining it I've updated the vs2019 project files.
Also added some more profiling code to find out how much face generation costs

Update vs2019 and profiling

---

data/ui/StationView/BulletinBoard.lua

Hang up chat on visibility change

---

pioneer

Fix boostrap to bootstrap

---

data/lang/ui-core/en.json

Update data/lang/ui-core/en.json: "% of max Δv".
Fixes #4684. See also original PR #4721.

HUD_DELTA_V_PERCENT: change message

---

src/graphics/opengl/RendererGL.cpp
win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

Usual visual studio housekeeping

Update vs etc

---

data/pigui/modules/saveloadgame.lua
data/pigui/modules/settings-window.lua

Fixes #4720 and fixes #4718
Had to test it on an old branch because of the DeleteFrame issue (I can't even start a new game as is), so maybe someone can double check, but it's pretty straight forward.
Come to think of it, maybe this can wait a day or two more for the merge. and I'll see if there are any other windows that should be modal.

Modal save/load window

---

data/pigui/views/game.lua

Game can again show no icons and no label,
show only icons or show both.

Restore a lost feature

---

win32/vs2019/collider/collider.vcxproj
win32/vs2019/galaxy/galaxy.vcxproj
win32/vs2019/gameui/gameui.vcxproj
win32/vs2019/glew/glew.vcxproj
win32/vs2019/graphics/graphics.vcxproj
win32/vs2019/gui/gui.vcxproj
win32/vs2019/jenkins/jenkins.vcxproj
win32/vs2019/lua.vcxproj
win32/vs2019/modelcompiler.vcxproj
win32/vs2019/newmodel/newmodel.vcxproj
win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters
win32/vs2019/profiler/profiler.vcxproj
win32/vs2019/savedump/savedump.vcxproj
win32/vs2019/sigcpp/sigcpp.vcxproj
win32/vs2019/terrain/terrain.vcxproj
win32/vs2019/text/text.vcxproj
win32/vs2019/ui/ui.vcxproj

Set the _ITERATOR_DEBUG_LEVEL to zero so that Debug mode is barely usable

VS make Debug usable for testing

---

data/pigui/libs/market.lua
data/pigui/libs/modal-win.lua
data/pigui/modules/autopilot-window.lua
data/pigui/modules/equipment.lua
data/pigui/modules/fx-window.lua
data/pigui/modules/radar.lua
data/pigui/modules/saveloadgame.lua
data/pigui/modules/settings-window.lua
data/pigui/modules/ship-internals-window.lua
data/pigui/modules/station-view/01-lobby.lua
data/pigui/modules/station-view/03-commodityMarket.lua
data/pigui/modules/station-view/05-equipmentMarket.lua
data/pigui/pigui.lua
data/pigui/views/game.lua
data/pigui/views/mainmenu.lua

Fixes #4755 closes #4765 
I created a class that keeps track of and draws modal windows, so each window can be open from any script without having to worry about what was opened before. It should make writing modals a bit more intuitive.

ModalWindow class that allows nesting

---

data/pigui/libs/market.lua
data/pigui/libs/modal-win.lua
data/pigui/modules/autopilot-window.lua
data/pigui/modules/equipment.lua
data/pigui/modules/fx-window.lua
data/pigui/modules/radar.lua
data/pigui/modules/saveloadgame.lua
data/pigui/modules/settings-window.lua
data/pigui/modules/ship-internals-window.lua
data/pigui/modules/station-view/01-lobby.lua
data/pigui/modules/station-view/03-commodityMarket.lua
data/pigui/modules/station-view/04-shipMarket.lua
data/pigui/modules/station-view/05-equipmentMarket.lua
data/pigui/pigui.lua
data/pigui/views/game.lua
data/pigui/views/mainmenu.lua
src/pigui/ModelSpinner.cpp

Added the Ship Market view.
Also contains a minor fix for the model spinner, and a fix for the alignment of the Request Launch button.
Based off the ModalWindow fix branch (#4767)

Ship market

---

data/lang/module-advice/en.json

Follows on #4796, where police was made non-persistent

Update in-game advice for how to avoid police in goodstraders

---

src/Background.cpp
src/Background.h
src/lua/LuaPiGui.cpp

We populate the background star field with stars, this should track the players position through the galaxy but it wasn't until this PR.
Fixes #4837

Starfield moving with player

---

src/Body.cpp
src/Frame.cpp
src/Ship.cpp
src/scenegraph/ModelSkin.cpp

This fixes the build issues we've had from #4839 with Visual Studio (_and maybe other compilers?_)
Fixes #4839

Get std::string explicitly from json

---

src/win32/OSWin32.cpp

Cleaned up GPU flags for AMD and comments.

Cleaned up GPU flags for AMD and comments

---

data/libs/Equipment.lua

̷R̷a̷i̷s̷i̷n̷g̷ ̷l̷o̷c̷a̷l̷ ̷d̷e̷l̷i̷v̷e̷r̷y̷ ̷r̷e̷w̷a̷r̷d̷s̷.̷
After countless protests across the galaxy, fuel prices are reduced again.

Reduce hydrogen price back to 1 credit

---

data/modules/Combat/Combat.lua

If the player saves the game during a combat mission, the timer is not restarted when the game is reloaded. It also sets the mission status in case the player overlooks the "Mission complete" message.

Restart mission timer on game start

---

src/Player.cpp

Clear SetSpeedTarget when jumping

---

src/lua/LuaMetaType.cpp
src/lua/LuaMetaType.h
src/lua/LuaObject.cpp
src/lua/LuaObject.h

This PR fixes some rough edges and bugs with LuaMetaType, and is a joint effort with @Gliese852. Many thanks to him for diving into the front lines on this!

LuaMetaType Fixes

---

data/lang/equipment-core/en.json
data/lang/module-advice/en.json
data/lang/module-assassination/en.json
data/lang/module-breakdownservicing/en.json
data/lang/module-newseventcommodity/en.json

Spelling and grammatical changes to:
- module-advice/en.json
- module-newseventcommodity/en.json
- equipment-core/en.json
- module-assassination/en.json
- module-breakdownservicing/en.json

Spelling Updates

---

data/pigui/modules/saveloadgame.lua

Shows the proper ship name in load window tooltip.

Show real ship name, not the internal name

---

data/modules/TradeShips.lua

Clear starports array if system has no population

---

data/pigui/modules/time-window.lua
src/ObjectViewerView.cpp
src/ObjectViewerView.h
src/Pi.cpp
src/View.h
src/fixed.h
src/galaxy/SystemPath.cpp
src/galaxy/SystemPath.h
src/pigui/View.cpp
src/pigui/View.h

Adds automatic pigui handler calling for `PiGuiView` - nothing Lua-side uses it *yet*, but will rectify that in a future PR.
Also rewrites ObjectViewer to use pigui, including adding some fixes to where invalid values might cause a segfault.

Port ObjectViewer to Pigui, Add Pigui Handlers for Views

---

data/libs/Equipment.lua

Feels more realistic when the upgrades are not visible at all tech levels.

Different tech levels for the thruster upgrades

---

src/lua/LuaDev.cpp

Since it seems that the planetary generator needs improvement, this tool can be useful later when debugging.
example of work:
```
> require 'Dev'.GalaxyStats(0,0,0,5,"PlanetsGravity")
Total number of planets with star ports: 1282
Number of planets by gravity on the surface:
0.000g .. 0.100g: 18.331% (235 planets)
0.100g .. 0.200g: 16.927% (217 planets)
0.200g .. 0.300g: 13.651% (175 planets)
0.300g .. 0.400g: 9.750% (125 planets)
0.400g .. 0.500g: 7.410% (95 planets)
0.500g .. 0.600g: 5.850% (75 planets)
0.600g .. 0.700g: 5.460% (70 planets)
0.700g .. 0.800g: 4.524% (58 planets)
0.800g .. 0.900g: 3.900% (50 planets)
0.900g .. 1.000g: 3.042% (39 planets)
1.000g .. 1.100g: 11.076% (142 planets)
------------------------------
Top 20 planets with max gravity:
1. Abundância : 1.000g (61 …
```

Add PlanetsGravity processor for GalaxyStats function in LuaDev.cpp

---

data/pigui/libs/forwarded.lua
data/pigui/modules/theme-debug.lua
src/lua/LuaPiGui.cpp
src/pigui/PerfInfo.cpp

So you remember that I said on IRC that I wasn't going to have any further bursts of inspiration today? Yeah, me neither. In my defense, I wasn't expecting this to be quite so easy.

Add theme color display/editor

---

data/modules/CargoRun/CargoRun.lua

Some minor bug fixes for the cargo run mission.

Some minor bug fixes

---

win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

Add src/Lua/LuaEngine.cpp & src/Lua/LuaEngine.h to pioneer.vcxproj

Fix VS 2019 Solution

---

src/SpaceStation.cpp

Needed to get master compiling again.

Fix ObjectType::SHIP reference (was Object::SHIP)

---

src/Input.cpp
src/Input.h
src/InputBindings.cpp
src/InputBindings.h
src/ModelViewer.cpp
src/Pi.cpp
src/SectorView.cpp
src/View.h
src/WorldView.cpp
src/lua/LuaConsole.cpp
src/pigui/PerfInfo.cpp
src/pigui/PerfInfo.h
src/ship/PlayerShipController.cpp
src/ship/ShipViewController.cpp

- Refactor InputFrame add/remove to support the console better.
- Remove the unneeded HandleSDLEvent virtual method on View.
- Fix a binding name mismatch issue.
- Add a (disabled) PerfInfo debug tab for debugging the input system.

Fix a few bugs with the Input system

---

data/models/misc/escape_pod/escape_pod.model
src/ModelViewer.cpp
src/ModelViewer.h
src/graphics/Graphics.cpp
src/graphics/Graphics.h

...that speaks for itself, I think!

Improve Modelviewer, add Tag display

---

.github/workflows/build-ci.yml
scripts/build-travis.sh
src/Input.cpp
src/Input.h
src/InputBindings.h
src/Pi.cpp

Move away from travis CI, use a Github Action to build and test.

Add github action build step.

---

data/lang/module-assassination/en.json
data/lang/module-cargorun/en.json
data/lang/module-combat/en.json
data/lang/module-deliverpackage/en.json
data/lang/module-searchrescue/en.json
data/lang/module-taxi/en.json
data/lang/ui-core/en.json
data/libs/Mission.lua
data/modules/Assassination/Assassination.lua
data/modules/CargoRun/CargoRun.lua
data/modules/Combat/Combat.lua
data/modules/DeliverPackage/DeliverPackage.lua
data/modules/SearchRescue/SearchRescue.lua
data/modules/Taxi/Taxi.lua
data/pigui/libs/text-table.lua
data/pigui/libs/text.lua
data/pigui/modules/hyperjump-planner.lua
data/pigui/modules/info-view/04-missions.lua
data/pigui/modules/info-view/05-crew.lua
data/pigui/modules/info-view/06-flightlog.lua
data/pigui/modules/system-view-ui.lua
data/pigui/views/game.lua
data/pigui/views/map-sector-view.lua
data/pigui/views/tab-view.lua
src/lua/LuaLang.cpp
src/lua/LuaPiGui.cpp
src/lua/core/Import.cpp
src/lua/core/Sandbox.cpp
src/pigui/LuaPiGui.cpp

@vakhoir if you're out there you can come back now, the worst is over! I took heed and decided not to redesign the missions display while porting it; this drastically reduced the workload involved. I'd say it took me 6-8 hours to do this, all told.
Some before/after screenshots to show off:
[Not strictly a "before", but funny nonetheless](https://imgur.com/PTWR8Xa)
After:
Need to fix up the translation strings (why is `GO_BACK` in five different module resources and not ui-core?!) and maybe look into right-aligned wrapped text, but otherwise it's good to go, and that's pretty much everything we had in newUI dead and gone.

Port Missions Display to PiGui

---

data/modules/MusicPlayer.lua
data/pigui/views/mainmenu.lua

Fix menu music not stopping when starting a game, and not starting again when returning to main menu.
Fixes #5041.

Fix menu music issues

---

contrib/PicoDDS/PicoDDS.cpp
src/GasGiant.cpp
src/GeoPatchContext.cpp
src/GeoPatchJobs.cpp
src/SpaceStationType.cpp

Quick drive-by contribution to fix compiler warnings in release builds.
Compiling tested with gcc + clang for release builds only.

Fix unused variables in release build

---

src/SystemView.cpp

Show surface starports in the system map

---

data/modules/SoldOut/SoldOut.lua

Fixes #5090 of template string after save/load

---

data/modules/SoldOut/SoldOut.lua

Fixes #5089 (I hope, @maxcrystal feel free to give it a try)

Fix soldout module using onDelete before it was defined

---

data/libs/autoload.lua
data/libs/utils.lua

I've also included a `math.sign` function in there, (and fixed documentation string for `utils.round`).
Ping @robothauler

Fix utils.round() to handle negative numbers as well

---

src/lua/LuaMetaType.h
src/lua/LuaShip.cpp
src/lua/LuaStarSystem.cpp
src/lua/core/Import.cpp
src/pigui/LuaRadar.cpp

Closes https://github.com/pioneerspacesim/pioneer/pull/5018
I tested this with both `-DUSE_SYSTEM_LIBLUA=ON` and `-DUSE_SYSTEM_LIBLUA=OFF` where the build succeeded for me.

Fix build with the system lua.

---

data/lang/module-scoop/en.json
data/modules/Scoop/Scoop.lua
src/CargoBody.cpp
src/CargoBody.h
src/lua/LuaBody.cpp
src/lua/LuaPiGui.cpp
src/lua/LuaShip.cpp
src/lua/LuaSpace.cpp

~~As you can see, this is not finished yet. Reward and mission time are not balanced so far.
Just to show something and play with the possibilities.~~
This module creates 4 mission types.
1. A debris field with cargo containers. The player has to pay for this information.
2. A debris field with illegal cargo. The player has to pay for this information.
3. A rescue mission. Pick up Rescue Capsules and land at a station.
4. Pick up a drifting container and deliver it to a ship in orbit around a star.
Additionally it creates random debris fields depending on population and lawlessness when entering the system.
I added an additional lua event to identify which cargo is related to which mission (2 similar missions) and for the NavButton.
Comments are welcome!

Scoop mission

---

contrib/miniz/miniz.h
contrib/profiler/Profiler.h

* Compile the game sucessfully on PPC64LE
There are quirks with graphics when the game starts which I will see if I could fix them or not in a separate PR

Support PowerPC 64 platform

---

src/Space.cpp

Sometimes surface ports move when terrain is generated because it is not suitable for their original position.  When serialized, the physical body saves its changed position, but the system body does not.
Therefore, upon subsequent loading, the position of the system body and the physical body may not coincide:
(In the picture, the player's ship has landed on Cydonia)
In this commit, the same mechanism is launched as during the initial generation of the relief, which displaces the system bodies to the right position.

Move the surface starport's system bodies on loading

---

data/pigui/modules/hyperjump-planner.lua
data/pigui/views/map-sector-view.lua

- Add icon for DRIVE_ACTIVE status
- Add checks when rebuilding the jump route
- Remove some unused vars
Fixes #5152

Fix crash in hyperspace with sector map opened

---

src/Intro.cpp

Add constexpr to PiRngWrapper::min/max()

---

data/lang/module-combat/en.json
data/modules/Combat/Combat.lua

Some small improvements for the combat mission

---

data/lang/module-cargorun/en.json
data/modules/CargoRun/CargoRun.lua

Do not pick up cargo if too late

---

src/perlin.cpp

deals with the issue #5200
I say "deals" because I have no idea why the value was that large in the first place...

Fix the floating point crash

---

data/lang/core/en.json
data/lang/ui-core/en.json
data/pigui/modules/comms.lua

Two strings seem to have been forgotten.
(Lang resources were not used at all in this module)

Add translations to comms log window

---

data/pigui/modules/comms.lua

Indicates who is saying what.
Related to #5180

Add sender to CommsLog

---

src/galaxy/StarSystemGenerator.cpp

instead building lists and sorting, just keep track of best match

unbloated best-match code

---

data/pigui/themes/default.lua
data/pigui/views/map-sector-view.lua
src/SectorView.cpp
src/SectorView.h
src/lua/LuaSectorView.cpp

Add polymorphic type SectorView::Label, for displaying different types of labels.
Implement two types of labels - for stars and for factions.
Add highlight colors to the theme.

Draw sector map labels with ImGui.

---

data/pigui/libs/forwarded.lua
data/pigui/modules/time-window.lua
src/lua/LuaPiGui.cpp

accessibility: open options by mouse actions
instead of needing keyboard + mouse

doubleclick pause for options

---

win32/vs2019/modelcompiler.vcxproj
win32/vs2019/modelcompiler.vcxproj.filters
win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

Yep, still maintaining this thing sometimes

Just cleanup the committed vs2019 solution

---

data/modules/Debug/DebugRPG.lua

if debug is open and you "end game", debugRPG goes boom
for @fluffyfreak

debugRPG no crash on end game

---

data/modules/PolicePatrol/PolicePatrol.lua

Do not scan the player's cargo if he is already in hyperspace

---

src/SectorView.cpp

Don't access imgui font until it's initialized

---

data/systems/00_sol.lua

Torvald's platform was added at the end of the list, so I moved it up, so it will shop up at the proper place on the atlas.
Fixes #5350

Moving Torvalds up in the order

---

src/Player.cpp
src/collider/GeomTree.cpp
src/collider/GeomTree.h
src/graphics/opengl/Shader.cpp
src/pigui/PiGui.cpp
src/pigui/PiGui.h
src/scenegraph/CollisionVisitor.cpp
src/sound/Sound.cpp

I ran Valgrind on the current version of Pioneer and spotted a few memory leaks. I tested by starting the game on Mars, launching the ship and quitting again.
Category|Before|After
-|-|-
definitely lost|9,115,591 bytes in 2,570 blocks|4,636 bytes in 495 blocks
indirectly lost|12,183,945 bytes in 38,957 blocks|58,829 bytes in 636 blocks
possibly lost|6,610,824 bytes in 604 blocks|96 bytes in 1 blocks
still reachable|371,281 bytes in 3,372 blocks|346,565 bytes in 3,368 blocks
suppressed|0 bytes in 0 blocks|0 bytes in 0 blocks

>20 MB of Memory Leaks

---

data/modules/SearchRescue/SearchRescue.lua
data/pigui/libs/commodity-market.lua

Some lua fixes

---

win32/vs2019/pioneer.vcxproj
win32/vs2019/pioneer.vcxproj.filters

This fixes up the Visual Studio 2019 project that I was supposed to be maintaining 🤣

Fix the vs2019 after long absence

---

src/lua/LuaSystemBody.cpp

fixes https://github.com/pioneerspacesim/pioneer/issues/5424

Fixes the crash when opening System View in hyperspace

---

src/SectorView.cpp

Easy fix for minor issue.
Fixes #5354.

Fixes #5354 - autoroute to wrong body in multiple star system.

---

data/libs/Game.lua
data/modules/Scoop/Scoop.lua
data/modules/SearchRescue/SearchRescue.lua

I. Fix for bug in scoop mission. All non tradable (custom) cargo was going to illegal goods list resulting in almost all junk to scoop.
II. Various Fixes and adjustments for Search & Rescue mission:
1. Added a check to make sure that the stranded ship has enough UP thruster power to take off. Fun fact: Natrix with half of fuel tank is not able to take off from 1G planet.
2. Revised passenger cabin availability check. My previous change for this was wrong - would not compile in c++ but in lua was ok as it was never called.
3. Target ship building function revised to produce viable ships more reliably. E.g. before a ship with 0 cargo space could be produced - it couldn't be refueled as 1t of fuel goes to cargo then from cargo to fuel tank.
4. Hyperjump delay of discarded ships changed from …

Scoop and Search and Rescue mission fixes

---

.github/ISSUE_TEMPLATE/config.yml
README.md
data/culture/gd.lua
src/RandomColor.h

Dev forum url moved

---

src/Beam.cpp
src/FixedGuns.cpp
src/Game.cpp
src/GasGiant.cpp
src/GasGiantJobs.cpp
src/Input.cpp
src/JobQueue.cpp
src/ModelViewer.cpp
src/NavLights.cpp
src/ObjectViewerView.cpp
src/Quaternion.h
src/Ship.cpp
src/Space.cpp
src/Space.h
src/SystemView.cpp
src/galaxy/Factions.cpp
src/galaxy/StarSystemGenerator.cpp
src/galaxy/SystemBody.cpp
src/matrix4x4.h

This pull request fixes some typos in code comments / documentation.

Fix a few typos

---

data/lang/module-scout/en.json
data/libs/EquipSet.lua
data/modules/Scout/Scout.lua

- Fixes #5502  scout not setting nav target when accepting mission
- Fixes #5501, mission target and mission return target mixed up
- Fixes #5503, after advert is converted to mission, the mission doesn't know if it's orbital or surface.
- Fixes #5504, for the same reason.
- Closes #5500

Fix scout bugs

---

src/lua/LuaShip.cpp

Fixes build with USE_SYSTEM_LIBLUA. Fixes #5525.

Fix path to lua.h

---

src/ShipAICmd.cpp

Fixes #5535. The problem is for systems with no star in the main frame of reference. Are they even valid?

Fix autopilot crash, when no mass in frame of reference

---

data/lang/module-combat/en.json
data/modules/Combat/Combat.lua

An explanation similar to the scout mission of how it works.
Related to #5499 
Addition to #5522

Combat mission explanation about special equipment

---

data/lang/module-secondhand/en.json
data/modules/SecondHand/SecondHand.lua

I just devised a method to mildly infuriate someone. Especially effective if you also had to sell the other one of whatever you tried to buy in order to fit a new one in. Chance of occurring, 1 in a 100. You don't really shop that much second hand so this would be really unlikely to happen during a game. :smiling_imp:

SecondHand - Disappointing outcome

---

data/pigui/modules/saveloadgame.lua

Also remove the popupOpened reference that seems redundant.

Allow double click on an item to load the saved game.

---

.github/actions/upload-appimage/action.yml
.github/workflows/build-ci.yml
scripts/CMakeBuildPresetsCI.json

Hi All,
I have updated the Yaml script to automate Appimage build.
It is very similar to other builds.
Feedback appreciated.
Please check my fork under releases for built appimage

added AppImage CI/CD script

---

src/lua/LuaSerializer.cpp

Quick tidy of the error message and the comment to make things easier for the uninformed.

Lua serializer comment error tweak

---

.github/workflows/build-ci.yml

This should make the build information parsed from the git ref of the build show on the main menu

Have MSVC Builds show branch information from git in the menu

---

metadata/net.pioneerspacesim.Pioneer.metainfo.xml

Fixed broken screenshots links in metainfo.xml file
Fixes #5747 issue

Fixed broken screenshots links

---

src/Background.cpp

If the user sets a small `AmountOfBackgroundStars`, a small diameter ball is scanned. So small that the number of tasks becomes comparable to the height of this ball, and rounding problems begin to appear.
Rethought the intervals for tasks a little, now it seems to be fairly uniform for such cases.
Also, if the user selects the number of stars to be 0, we simply do nothing.
Fixes #5777

Don't crash when there are few background stars

---

data/lang/core/en.json
data/lang/module-deliverpackage/en.json
data/lang/module-goodstrader/en.json
data/lang/module-newseventcommodity/en.json
data/lang/module-policepatrol/en.json
data/lang/module-scout/en.json
data/lang/module-searchrescue/en.json
data/lang/module-taxi/en.json
data/lang/ui-core/en.json

I've found a few spelling and grammar errors, I've fixed these in one commit. 
I also found a few uses of Commonwealth english, things like 'behavio**u**r'. I think it would make sense in-universe to keep these as there will be people from all sorts of brackgrounds, and some would use British forms of spelling and so on. I've made this a separate commit which can be ignored if these changes aren't desired.

A few spelling / grammar fixes

---

CMakeLists.txt
Changelog.txt
NEWS.md

Updated News and some Changelog stuff I've had lying about for a month or two.
I've also started a draft release.
First:
1. finish draft release
2. update this PR with the text from the finalized release
3. merge
4. publish release
5. (rebuild webpage, and do [the other stuff](https://dev.pioneerspacesim.net/contribute/making-a-release))

Update Changelog and NEWS for bug-fix release

---

data/pigui/modules/info-view/04-missions.lua

Fix crash in mission list in hyper space when combat mission

---

data/lang/module-combat/en.json
data/modules/Combat/Combat.lua

Proposal to close #5890
The texts are shown when "How will I be paid?" is clicked.

Better explanation of the combat mission due date

---

data/systems/03_bright_stars.lua

Add two additional names to Polaris

Add additional names to Polaris

---

data/lang/module-advice/en.json

Be compatible with new EquipSet v2 PR #5734

Update advice on hyper drive mechanics

---

data/lang/ui-core/en.json
data/modules/SearchRescue/SearchRescue.lua
data/pigui/modules/info-view/04-missions.lua

A small fix for the Search & Rescue mission.
I changed also the display for the remaining mission time. In my opinion this looks better than "0 Days" for short missions.

Ship pattern fix

---

data/modules/Assassination/Assassination.lua
data/modules/SecondHand/SecondHand.lua
data/modules/TradeShips/Trader.lua

Fixes #5904.
Fixes #5905.
Partially addresses #6023. The remainder of the issues in 6023 are paper-cut level and will be addressed after release.
CC @impaktor for changelog inclusion as I'm merging immediately.

Final cleanup fixes before release

---

data/lang/ui-core/en.json
data/modules/CargoRun/CargoRun.lua
data/modules/Combat/Combat.lua

Related to #6079. The area for the status is quite small. So too much text does not look good.

Show status "pending" if the mission has not yet been fully completed

---

contrib/lz4/CMakeLists.txt
contrib/nanosockets/CMakeLists.txt

Because otherwise the project is not built with CMake >= 4.0
Fixes #6122

Update minimum required version of CMake to 3.5

---

data/libs/SpaceStation.lua
data/modules/AutoSave/AutoSave.lua
data/modules/CargoRun/CargoRun.lua
data/modules/Combat/Combat.lua
data/modules/DeliverPackage/DeliverPackage.lua
data/modules/FindPerson/FindPerson.lua
data/modules/FlightLog/FlightLog.lua
data/modules/MusicPlayer.lua
data/modules/NewsEventCommodity/NewsEventCommodity.lua
data/modules/Scoop/Scoop.lua
data/modules/Scout/Scout.lua
data/modules/SearchRescue/SearchRescue.lua
data/modules/Taxi/Taxi.lua

Replace onShip*() with onPlayer*() events where functional
