pioneerspacesim/pioneer

src/Game.cpp
Restore symmetry of [`Begin`/`End`]`CameraFrame` during save/load routine and avoid potential memory leaks
=> Fix append of CameraFrame on saves

data/pigui/pigui.lua
Simple fix to the conversion of lat/lon from floating point values to degree/minutes/seconds format, which is done during output formating for the PlanetaryInfo window (bottom right in flight UI).
The old code only yielded minutes in the range of 0 to 29 where the missing range from 30 to 59 was somehow also mapped to 0 to 29, but "flipped". (Will add some examples)
AFAIK this bug existed already for some time (>=1 year) but was apparently not recognised yet.
=> Fix calculation of latitude and longitude for PlanetaryInfo

data/pigui/views/game.lua, src/LuaPiGui.cpp
Make ship indicators be displayed in game UI _only_ if closer than a certain distance, currently 1000 km.
This feature seems to have been gone since d90e14ec1 (5 May 2019, #4548). I went through the comments, but couldn't find a hint that it was dropped on purpose. Moreover, in `data/pigui/views/game.lua` the constant `IN_SPACE_INDICATOR_SHIP_MAX_DISTANCE` from the old code is still present, but not used anymore.
Hence my conclusion that the feature was lost by accident.
In my restore, I don't use a hard coded value for the maximum distance on the c++ side, but instead pass the value of `IN_SPACE_INDICATOR_SHIP_MAX_DISTANCE` (which is 1000km) in `game.lua` to `getProjectedBodiesGrouped()` as an additional parameter. Code-wise, this is similar to the current radar size being passed to …
=> Restore feature: maximum display distance for ship indicators

data/pigui/modules/autopilot-window.lua, data/pigui/modules/comms.lua, data/pigui/modules/ship-internals-window.lua, data/pigui/modules/system-overview-window.lua
@Web-eWorks edit: fixes #4468, fixes #4699
Did not dig deep, just solved the problem for 4 areas - CommsLog button, Overview button, Ship internals buttons and autopilot window buttons. Their parameters are not written or read from the file (imgui.ini), so the window is created exactly as needed for the buttons, and scroll bars do not appear.
Honestly, I don't see any reason to save the parameters of any windows to a file, since they are still calculated every time when rendering. Maybe it's better to disable it all.
=> fix issues #4468 or #4699 - unpleasant scrollbars

CMakeLists.txt
Let's you build pioneer with profiler also under cmake versions less than 3.12.
Thanks to @laarmen for pointing out that the command used so far,
`add_compile_definitions(PIONEER_PROFILER=1)`
actually is a cmake macro, 
> but only available in 3.12 and later, which was released in July 2018.
As it happens, I am still running Debian stretch (old stable), which has cmake 3.7.2. The new stable Debian "buster", released July 2019, has cmake 3.13.4.
=> CMake profiler build option: support older versions of cmake

data/pigui/modules/fx-window.lua, data/pigui/modules/system-overview-window.lua
Fixes #4719
Another try, this time commits are fine.
Now if the player is docked or we are not looking into space, the overview window function does nothing at all. In addition, I thought that button "Show Comms" should be removed when it does nothing, that is, when a player is not docked or landed.
=> Fix mission screen obscuring buttons

data/pigui/views/game.lua, src/LuaPiGui.cpp
Several fixes to the game UI handling of the in-space body indicators in order to improve their usability:
1. Remove the duplicate entry of the first/main body in the popup for a collapsed group of bodies
2. Adjust location and size of selection area when clicking on a body
3. Clicking on a collapsed navigation target clears the nav target
4. Ctrl-clicking on a body also selects it as the SetSpeedTarget
5. Never collapse the current combat target
6. Use the main body's coordinates to place the indicator of a collapsed group
7. If a collapsed group contains the nav target, this becomes the main body of the group 
These changes fix obvious bugs and also restore old functionality of the game UI as it was pre d90e14e (5 May 2019, #4548). As already mentioned in #4761, I went through the …
=> Improve usabiltiy of in-space body indicators

src/Orbit.cpp
If you start a new game, open the system map, and turn on the display of ships, you can see their flickering, which lasts several minutes. Then the situation seems to improve, but still some ships sometimes begin to flicker. Sometimes the ship begins to fly away with acceleration to infinity, sometimes it jerks back and forth. All this ruins the impression of the game, in my opinion.
The problem of the entire instability of the positions of the ships turned out to be that, to display them on the map, first the orbit parameters are calculated by their coordinates, and then their position is calculated again by these parameters. This is necessary in order to rewind time back and forth.
А simple solution for the present time would be to simply store the ship's coordinates inside the orbit at …
=> Fix / improve orbit calculations.

src/PiGui.cpp, src/PiGui.h
Fixes #4778
For all the talk in the issue, the fix seems relatively simple, the following description is also in the commit message:
Change the approach to checking if a font can handle a glyph. The original approach was to pass the valid glyph range to the constructor. When it's not found by ImGui we call AddGlyph where we check if it's valid for the font. In the event where ImGui couldn't handle a glyph that was defined as valid in the constructor, that led to constant re-baking of fonts. The new approach is to change m_ranges (which used to contain valid glyph ranges) to m_invalid_glyphs, which contains only invalid glyphs that we tried to add to the font but failed. The next time AddGlyph is called, we skip the font since it's unable to handle the glyph.
But I have to say, I'm not …
=> Fix on-demand glyph loading

src/Orbit.cpp
Sorry for not noticing this right away. When the ship takes off from the planet, the eccentricity of its orbit is for some time in the range 0.9999 .. 1 and turns into a hyperbole 1.0001. The velocity vector is directed from the planet, so a line is drawn that goes from the ship to infinity. It is not right. These changes solve the problem.
Everything seems to be taken into account now. Feel free to kick.
orbit with 0.9999 < e < 1.0001 forced to e = 1.0001 (hyperbola)
orbit with 0.9999 < e < 1      forced to e = 0.9999 (ellipse)
orbit with 1   <=   e < 1.0001 forced to e = 1.0001 (hyperbola)
In an elliptical orbit, when the eccentricity is fixed at 0.9999, and
the speed increases, the semi-major axis shrinks and the apocenter moves
toward the star. Therefore, a condition check has been …
=> Small additional improvements to orbit calculation

src/SystemView.cpp
Since the function Gui::Screen::Project does not cull points (and most likely should not), this must be done manually, as was done in the SectorView.cpp for labels:
https://github.com/pioneerspacesim/pioneer/blob/105d06e33fcb5b565e3431fc694525e0546a784e/src/SectorView.cpp#L399-L402
Checking z < 1 in the Normalized Device Coordinates discards points that are further than the zfar clipping plane, and beyond the center of the camera. The points between the center of the camera and the znear clipping plane remain. They may be needed.
With a severe zooming in, the coordinates of objects can become too large and fly out of the z-far plane. Therefore, it was done so that the z-far plane moved away proportionally. But with a severe zooming out, it z-far plane can become smaller than …
=> Minor improvements to System Map

data/pigui/views/mainmenu.lua
Simple additional feature for the continue button in main menu:
- Load the _quicksave file if the autosave option is _not_ activated (and _quicksave exists).
- If autosave _is_ active, then continue works as before and loads the autosave _exit file.
This added functionality could be handy whenever you are not using autosave.
In fact I did not use it for quite some time :)
=> Make continue button load _quicksave if autosave not active

CMakeLists.txt, COMPILING.txt, src/LuaPiGui.cpp
OK, I'm throwing this on the wall to see if it sticks.
Looking at pigui code, they finish their column-block with just a single `Columns(1)`
```c++
ImGui::Columns(3, NULL, false);
static bool selected[16] = {};
for (int i = 0; i < 16; i++)
{
char label[32]; sprintf(label, "Item %d", i);
if (ImGui::Selectable(label, &selected[i])) {}
ImGui::NextColumn();
}
ImGui::Columns(1);    // <--- THIS
```
So made second argument optional, defaulting to `""` (is this correct? It's default is `NULL` in ImGui), so we can do:
```lua
ui.columns(2, "Mycolumntest", true)
ui.text("row 1, col 1")
ui.nextColumn()
ui.text("row 1 1, col 2")
ui.nextColumn()
ui.text("row 2, col 1")
ui.columns(1)   -- <--- THIS
```
Also, added suggestion of how documentation could look like. I imagine we want to discuss what it …
=> PiGui docstrings and fix to ui.columns

data/lang/ui-core/en.json, data/pigui/modules/station-view/01-lobby.lua, data/pigui/modules/station-view/07-police.lua
This is my first pigui contribution. I hope to get some eyes on this, there's at least one "breaking issue" that needs fixing before merge (see below), that I haven't managed to figure out.
Other than that, it has all the same functionality as the original, which wasn't very flashy to begin with, since that was also something I barely managed to hack together.
So I'm sure the data here can be presented better, (e.g. remove gray color for crime record, use some collapsing header or similar instead), but the question is how much more work should be done before this is merged.
My plan was to do another PR after this where I add some sort of dialogue button as well, so the player can ask for missing persons (needed for #4746), but if this PR looks OK, I could attack the ShipRepair screen …
=> Police to pigui

data/lang/ui-core/en.json, data/pigui/modules/station-view/01-lobby.lua
I've been playing with the lobby (motivated by comments in other [PR](https://github.com/pioneerspacesim/pioneer/pull/4746#issuecomment-575055727)), trying to see how much of that code I can muster. So in experimenting, I added one more info sentence. 
(I imagine these Lobby-sentences, sort of how the pilot annonuces the weather when you land at a new airport)
I'm doing this as WIP, because maybe wording can be better (suggestions?), or I find other stuff to add to it.
Possibly we'd also like to add information about how many ships are currently
docked, as this only shows the total capacity.
=> Add number of total docking pads at station to lobby

data/lang/module-cargorun/en.json, data/modules/CargoRun/CargoRun.lua
TL;DR: adding another custom cargo to cargo missions (ping @robothauler)
Finest [self-sealing stem bolts](https://memory-alpha.fandom.com/wiki/Self-sealing_stem_bolt) in the sector!
Referenced in sci-fi culture as a gadget with unclear use, in several Star Trek DS9 episodes, here being the first occurance:
https://www.youtube.com/watch?v=V51xKPcyreY
=> Silly time! We need stem bolts, and self sealing ones!

data/pigui/modules/station-view/06-shipRepairs.lua
OK, so I've done the ship repair shop as well. The original had this silly option, to either repair 1 percent-point, or all the damage. I replaced it with a slider.
I'm posting a screenshot with two different styles of hull integrity progress bars, the default ImGUI (yellow), and the pigui gauge (the "pioneery"), please tell me what you think, @nozmajner.
- I'm thinking if it's possible to make certain stations be authorized service shops for ships from certain manufacturers. Would give a discount on repairs. (HA! compare that to real "licensed" repair shops, they charge x2 the price!)
- The original Frontier you did both hull and engine maintenance in the ship repair shop, but engine "health" is in the _BreakdownService_ module, so not available to the station screens. Either way, all …
=> Move ShipRepair screen to pigui

data/pigui/views/station-view.lua
=> Fix unused/free cabins shown in station footer being wrong

data/modules/GoodsTrader/GoodsTrader.lua
Idea: one should be able to recognize the trustworthy black market merchants,
by them being persistent to each station. So you learn to recognize the name
of the market, e.g. "Honest Jim".
However, if _both_ police and the _true_ black market merchant are persistent,
you will recognize the name of both, so now you need to remember _which_ was
the fake one.
I much prefer the way it was in Frontier: the undercover police had a new name
every time you docked, so when returning to a station you would only recognize
one of the trader-names.
=> Make police non-persistent in Goodstrader

data/pigui/views/station-view.lua
Before:
```Cabins: 50% - 1 used / 2 free```
After:
```Cabins: 33% - 1 used / 2 free```
=> Fix incorrect cabin usage percentage

data/modules/GoodsTrader/GoodsTrader.lua
I believe when I rebased #4796, after #4775 was merged today, I didn't notice that the `faceseed` wasn't used for the GoodsTrader character.
Closes #4810
=> Make faces in goodstrader persistent

.github/FUNDING.yml
Add Sponsor button to github, which redirects to
https://pioneerspacesim.net/page/donate/.
=> Add Sponsor button to github

data/lang/ui-core/en.json, data/pigui/modules/map-sector-view.lua
This is shown in sector view, and was previously just returning the all caps
English constants.
=> Add ship jump status to translation strings

data/icons/icons.svg, data/pigui/modules/info-view/03-econ-trade.lua, data/pigui/themes/default.lua
Updating the icons.svg with a few icons that will be needed for future PRs by @impaktor @Gliese852 @Web-eWorks 
Some of the icons are by Gliese852 (I don't know how I tag as author for the PR)
I've also named all icons in the file with them names from the default.lua for consistency.
I've also changed the display nav target data icon from the reticule from the crosshair to that google-maps like pin. I've added that pin for the BBS set destination as nav target function as well.
I've also removed the old apoapsis and periapsis icons in favor of the new ones. They weren't in use anyway.
=> Adding icons for future PRs: BBS, systemview, imgui migration, bar

src/pigui/PiGui.cpp
- When hiding the flight-ui with double TAB (i.e. `Pi::DrawGUI==false`), prevent a change of Pioneer's custom mouse pointer back to the system default pointer (fixes #4762)
- This also fixes a bug with Pioneer crashing occasionally after TAB-toggling the flight-ui off/on (fixes #4812)
As mentioned in https://github.com/pioneerspacesim/pioneer/issues/4812#issuecomment-591087280, the fix is to comment out three lines of code which change an imgui mouse setting:
<details>
```
#if 0 // Mouse cursors are set via the OS facilities.
// See also below.
if (!Pi::DrawGUI) {
ImGui::GetIO().MouseDrawCursor = true;
}
#endif
```
</details>
In fact, a few lines below an analogous change was already made in 5824d0a by @Web-eWorks:
<details>
```
#if 0 // Mouse cursors are set via the OS facilities.
// We …
```
=> Prevent change of Pioneer's mouse pointer when hiding HUD

data/pigui/views/game.lua, data/pigui/views/mainmenu.lua, src/Player.cpp, src/Player.h, src/lua/LuaPiGui.cpp, src/ship/PlayerShipController.cpp, src/ship/PlayerShipController.h
I noticed a few issues that remained after #4764:
- In certain (rare) situations it is possible that two clusters of bodies are displayed very close to one another, closer than the cluster size. The problem is not the algorithm which groups the bodies into clusters, but the fact that after creating the clusters, when the bodies of each cluster are sorted according to their importance, the most important body becomes the new main body. That is, the clusters remain unchanged, but the main body which is used to put the body icon on screen might not be the centre of the cluster anymore.
As an example, in the following savefile Ceres and Jupiter are very close together on screen and cause the described problem: [debug_grouped.gz](https://github.com/pioneerspacesim/pioneer/files/4209073/debug_gr …
=> Some fixes to the handling of in-space bodies in flight-ui

.clang-format, autoformat, scripts/build-travis.sh, scripts/clang-format.sh, src/GasGiant.cpp, src/Planet.cpp, src/graphics/Renderer.cpp, src/graphics/Renderer.h, src/graphics/Stats.cpp, src/graphics/Stats.h, src/graphics/Texture.h, src/graphics/TextureBuilder.cpp, src/graphics/TextureBuilder.h, src/graphics/dummy/TextureDummy.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/TextureGL.cpp, src/graphics/opengl/TextureGL.h, src/pigui/Image.cpp, src/pigui/PerfInfo.cpp, src/pigui/PerfInfo.h, src/pigui/PiGui.cpp, src/scenegraph/ColorMap.cpp, src/text/TextureFont.cpp, src/vector2.h
I've implemented a visualizer for our texture caching system that allows inspecting each of the textures stored in the cache (currently only works on Texture2Ds), as well as added performance tracking for memory usage and number of cached textures.
I eventually want to separate the texture cache into a two-stage indirect cache instead of lumping everything into the same `std::map`; among other reasons, I'd like to remove the static mutex in `TextureBuilder` and instead lock on the specific texture cache bucket we're assigning the texture to.
I've also updated our clang-format script to avoid leaking the generated patch file, and make it easier to manually run the formatter.
Most of this PR has been developed on the terrain-texturing branch, but I've endeavored to cut out everything not …
=> Texture Cache Visualizer and Memory Usage Tracker

data/libs/Equipment.lua
_Recommendation: (Please ignore the tables - they're there for the nerds, and make this PR look intimidating, there be plots for the lazy)_
Trading in pioneer has been, more or less broken from the start. "Broken" in the sense that the profit from commodity trading compared to the work input in relation to mission rewards and expenses (ships, equipment) is much too low.
Pioneer is still basically a Frontier clone (but with ships replaced, and galaxy not 2D flattened). Since trade worked fine in Frontier, relative missions and ship/equipment prices, which I've played a lot, I thought the first (or "zeroth") step to improve Pioneer's trade is to model it on Frontier's, to make it at least as good as their system.
To first diagnose the problem in Pioneer, I wrote a little [commodity …
=> Significantly update commodity prices!

data/pigui/pigui.lua, src/lua/LuaPiGui.cpp
I'm using this in my [debug commodity branch](https://github.com/impaktor/pioneer/tree/debug_commodity_prices), please review, as I wrote some code that didn't quite work, and then @ecraven helped by writing the code below, but I renamed all the variables, and added doc string, because I think they were sub-optimally named.
I also added some default variables, if user doesn't specify any explicitly themselves.
After thumbs up on this, I can add `plotLines()` in the same commit, as it's just copy paste, I think.
=> Add histogram to pigui

.github/workflows/clang-format.yml, .travis.yml, autoformat, scripts/clang-format.sh
This change splits our clang-format step out into its own check, makes it a bit easier to run clang-format (for several reasons including that it's included into the default Github Actions image...), and allows us to more clearly see when there's an actual error with the build instead of clang-format complaining that you haven't adhered to the proper syntax.
=> Move clang-format to Github Actions

.github/workflows/clang-format.yml, data/pigui/libs/modal-win.lua, data/pigui/views/game.lua, data/pigui/views/mainmenu.lua, scripts/clang-format.sh, src/Input.cpp, src/Input.h, src/ModelViewer.cpp, src/Pi.cpp, src/graphics/Renderer.cpp, src/graphics/Renderer.h, src/pigui/PiGui.cpp, src/ship/PlayerShipController.cpp, src/ship/ShipViewController.cpp, src/ship/ShipViewController.h
See the commit messages for detailed information; this PR resolves a blocker for #4821 and fixes #4783.
In short, this PR removes the global, always-on mouse capturing when holding mouse buttons and replaces it with more intelligent, extensible handling via `Input::SetCapturingMouse()`.
I've cleaned up mouse cursor handling as a follow-on to #4827, and fixed the input deadlock that was possible to enter as a result of the change to how we draw modals.
=> Improve Mouse Capture Handling

data/pigui/libs/modal-win.lua
The issue #4832 was actually solved with #4842, but this PR removes unnecessary registration of the Modal Window handler in the game and mainMenu modules, which lead to modal being drawn several times (which doesn't seem to hurt anything, but you never know what it could lead to down the line)
=> Cleanup Modal Window manager registration

data/pigui/libs/commodity-market.lua, data/pigui/modules/station-view/03-commodityMarket.lua
Fixes #4826
A small issue possibly introduced with the fix to #4797. The method that updates the commodity market message was called before the selected item was set on the object, and so the message was always lagging.
To avoid confusion of what the Refresh method actually does, the selection clearing has to be done explicitly, and has been moved to the appropriate StationView tab.
=> Fix Commodity Market Message Lag

src/Input.cpp, src/Input.h, src/ModelViewer.cpp, src/ModelViewer.h, src/Pi.cpp, src/Pi.h, src/core/Application.cpp, src/core/Application.h, src/core/GuiApplication.cpp, src/core/GuiApplication.h, src/lua/Lua.cpp, src/lua/LuaBody.cpp, src/lua/LuaEngine.cpp, src/lua/LuaPiGui.cpp, src/lua/LuaPiGui.h, src/main.cpp, src/pigui/PiGui.cpp, src/pigui/PiGui.h, src/pigui/PiGuiLua.cpp, src/pigui/PiGuiLua.h, src/pigui/PiGuiSandbox.cpp, src/pigui/Widgets.cpp, win32/vs2019/pioneer.vcxproj, win32/vs2019/pioneer.vcxproj.filters
I've re-implemented the ModelViewer in PiGui, using the GuiApplication class and the Input system to simplify a fair amount of the handling.
To accomplish this, I've done a fair amount of refactoring:
- `PiGui` is now `PiGui::Instance`, and all of the static drawing methods have been moved out of the class, opening up the possibility to add more C++-side widgets for both Lua and C++ to use.
- `PiGui::Instance` is now only responsible for handling ImGui - all Lua-side initialization is handled by `PiGUI::Lua::Init()` instead.
- As an addenda, the (separate) PiGUI namespace will be merged into the (new) PiGui namespace in a future PR; I didn't do that here because I was focused on other work.
- `PiGui::Instance` has its renderer dependency injected by its owner rather than relying on …
=> Refactor the ModelViewer to use PiGui

src/GeoPatch.cpp, win32/vs2019/pioneer.vcxproj, win32/vs2019/pioneer.vcxproj.filters
Build fix for Visual Studio.
Also reordered the terrain split test, removed the `canSplit` test as it's always true, inverted the logic, and renamed a temporary to make things clearer.
Added some comments.
=> Build fix and comments

src/GasGiant.cpp
Each buf contains an array of `Color`s, therefore the type of `T` in `unique_ptr<T>` must be `Color[]` instead of `Color`.
=> Fix UB related to allocation/free mismatch

COMPILING.txt
`homebrew/games` was deprecated, and the `pioneer` formula was migrated into core: https://formulae.brew.sh/formula/pioneer
COMPILING.txt should reflect this.
=> Remove homebrew/games mention from COMPILING

data/pigui/modules/system-view-ui.lua, data/pigui/pigui.lua
Orbit planner buttons changes the value all together when using left and right arrow buttons. This is obviously unintended.
* _Thrust_ controls must be independent one each other, and should continuously increase/decrease the value until mouse button is released
* _Time factor_ control must be independent from other controls, but a _step-on-click_ behavior is expected -- i.e. the factor is increased/decreased once per click
~~`PiGui::ButtonImageSized` uses the texture id as the button id. However, left and right arrow buttons share the same texture, leading to this issue. This maybe could be happening with other buttons as well.~~
@Gliese852 clearly showed that the issue was related to the ID of the tooltip, nothing related to `PiGui::ButtonImageSized`.
I am not sure this issue have been …
=> Decouple planner buttons

data/systems/custom/19_starsend.lua
Adding a custom system, Star's End, to a remote region of Milky Way. (The 'opposite side' of the disk)
- Star's End is a Foundation reference, the vague name for the supposed location of Second Foundation. Since we have Terminus in the middle of the galaxy, I thought the name would be suitable.
- Cobol --> Kobol is the name of the lost, ancient birthplace of mankind in Battlestar Galactica series, which is discovered by the human diaspora some time after the fall. Also, you know, COBOL.
- Yodagobah --> Dagobah is the name of Jedi Master Yoda's remote exile planet in Star Wars universe.
Pioneer-wise lore is:
> A special team of ambitious colonists sent out during the fall of Haber Corporation in secrecy has picked this small system as their new home. With intentions to expand the …
=> New custom system

data/pigui/libs/equipment-market.lua
Sorry for rapid and major changes to the PR.
We now get full money back when selling a commodity, as opposed to equipment.
fixes #4858
=> Remove price reduction when selling commodities

data/systems/02_local_stars.lua
Gliese 664 is 36 Ophiuchi C.
https://en.wikipedia.org/wiki/36_Ophiuchi (see "other designations")
Yet they were treated as separate star systems (because I think GJ catalogue treats them as such) and were sitting on top of each other in the sector map.
36 Ophiuchi B was nonexistent altogether. It has been added too.
=> Merge 36 Ophiuchi & Gliese 664 into a single star system

src/lua/Lua.cpp, src/lua/LuaCall.h, src/lua/LuaConsole.cpp, src/lua/LuaMetaType.cpp, src/lua/LuaMetaType.h, src/lua/LuaObject.cpp, src/lua/LuaObject.h, src/lua/LuaPushPull.h
If you've not been following my progress on IRC, let me introduce this PR before I get down to the changes.
For quite some time, I've been stymied in my efforts to make sweeping changes to the structure of the codebase by several factors. The largest of these factors has been (obviously) the code hierarchy and the extreme degree of interconnection between seemingly disparate concerns.
This PR doesn't do anything about that.
This PR is aimed at fixing the *second* largest factor, that being the reams of boilerplate one must write to expose a struct with five public members to Lua. Given a struct like so:
```C++
struct MyAwesomeStruct {
bool aBooleanValue;
SomeLessAwesomeStruct sadStruct;
int anIntegerValue;
void ThisDoesSomething();
float AwesomeGetter();
};
```
The code required to bind …
=> LuaMetaType + LuaObject 2.0

data/lang/commodity/en.json, data/lang/core/en.json
Radioactives are mostly useful and should be paid for.
Radioactive waste mostly isn't and... you get the idea.
(I think it has been that way before, maybe it changed during pigui conversion project, idk)
Commodity "hand weapons" are called "small arms" in market but "hand weapons" in system economy data (and, in turn, trading computer). I changed all into "small arms", as it is in the commodity market.
=> Commodity name clean-up

src/pigui/PiGui.cpp
Before PR -> After PR
When a character appears in the text, that is not in the default font face, it is looked up in the spare faces of the font. Moreover, the default range also began to be baked from the spare face. I made that *only* characters that are not in the default face are baked from the spare face.
To visually see what is this all about, start a new game and click on Toliman in the sector map. In it's description there is an "α" (alpha) symbol, this leads to a complete change of the font face. This PR fixes this issue.
Fixes #4807
=> Prevent unwanted font face changes

src/core/Log.cpp, src/libs.h
Catch and silently ignore fmt::system_error exception when using fmt::print on stdout and stderr. This will occur if there is no console (ie. for Windows builds).
Set SIZET_FMT to "%zu" on all builds now, fmt does not understand the MSVC "%Iu" format.
This and https://github.com/pioneerspacesim/pioneer/pull/4887 should get Pioneer building and running for x64 again in Visual Studio.
Fixes #4888
=> Update SIZET_FMT and catch fmt::system_error exception

data/pigui/pigui.lua, src/lua/LuaPiGui.cpp
I (think I) need this for some experiments I'd like to do on #4795.
I added this code the fastest and easiest way I know, so I'm not betting my life on this code. Especially not:
- where in LuaPigui.cpp it's best to have the functions? Do we even have any convention?
- I hardcoded in the `ImGuiTabBarFlags_None` flag, because 1. I don't know what it does, 2. it wasn't exposed in lua from before and I didn't care to implement exposing a whole tab-flag-thingy, 3. it seems to be what I want for now / I don't know the alternatives
- when we expose the functions in pigui.lua, I do camlecase, with starting letter lowercase.
(mouse cursor is removed by screen-shot program, so only tool tip shows)
=> Add support for IMGUI tabs in pigui

data/pigui/modules/hyperjump-planner.lua
When the amount of fuel changes on the ship, the function of rebuilding the route strings is called, because colors can change there. The function uses a pointer to the player, which is calculated when the planner window is displayed. If the window never been shown, a reference to the null pointer occurs and the game crashes.
=> Fix crash in-flight if hj-planner has never opened

CMakeLists.txt, CMakeSettings.json, COMPILING.txt, msvc-defaults.cmake
This requires https://github.com/pioneerspacesim/pioneer-thirdparty/pull/29
Update SIGCPP_LIBRARIES to use debug version for debug builds
Fix variable name reference in post_build command
Output executables to the root dir when doing MSVC build
fixes #4658 
With this, the cmake build should work again in MSVC for both Release and Debug.
I added the output dir thing so that you can run debug pioneer from within Visual Studio without having to move files around or attaching it manually. 
I may be using it differently, but when I open the CMakeLists.txt in MSVS (File->Open->Cmake) and build, it outputs everything under out/ without this change.
=> Fix MSVC cmake build (#4658)

src/Frame.cpp
Change != to ==, the rest is the satisfaction of the clang-format.
FrameIds are stored in order and loaded in order. In this case, the id of the last loaded Frame should always be 1 less than the size of the container.
Fixes #4898
=> Fix Crash when Loading Saves on Debug Build

src/Space.cpp
Just rigidly set a lower limit of 1.1 * radius of the star.
Fixes #4869
=> Fix that sometimes player ends HJ inside a star

data/modules/BreakdownServicing/BreakdownServicing.lua
This sets the hyperdrive last service date to the game start date for new games. Currently, the hyperdrive service date is still set to Jan 1 3200 for new games:
Currently, that means that new games start with a hyperdrive that is 19 years out of service! 
A new game after this change:
Also in regards to the likelihood of the hyperdrive breaking:
Perhaps I'm particularly unlucky, but it would seem that a breakdown becomes fairly likely above 15 jumps after the service period ends. Just doing some quick testing, I got the drive to break 4 times in a row (out of 4 test runs) in the 13-17 jump range. I don't think this is necessarily bad, but it's not anywhere close to the maximum in BreakdownServicing.lua (255), and the likelihood of a random number being less than 0.0588 (~ 15/255) seems …
=> Set hyperdrive last service date to game start date for new games.

data/lang/ui-core/en.json, data/pigui/libs/message-box.lua, data/pigui/modules/hyperjump-planner.lua, data/pigui/modules/map-sector-view.lua, src/SectorView.cpp, src/SectorView.h, src/SystemInfoView.cpp, src/galaxy/SystemBody.h, src/lua/LuaRef.h, src/lua/LuaSectorView.cpp, src/lua/LuaStarSystem.cpp
- clear route strings when enging the game, otherwise, when the game restarts, a segfault occurs
- it turns out that a hyper jump is possible not only to the stars, but also to the "substellar objects", but they do not return in the method `GetStars`. Since a specific body should be shown in the route planner, implemented an additional method `GetJumpable`, that gets all the bodies available for jumping `(IsJumpable == true)`, and this is synchronized with what you can click in the systeminfo view
- also I had to change the route check, now it’s not the star index that is checked, but just the path (this check is performed for multisystems, so that only the specific body that registered in the route is always selected)
- fix that the "remove jump" button continued to remove jumps even …
=> Fix some things with regards to the sector map

data/pigui/modules/saveloadgame.lua
Resized the Load/Save game window to something that looks a bit more reasonable. Also resized the buttons and updated both sizing to use ui.rescaleUI.
Removed bindingButtonSize  and mainButtonSize since they don't seem to be used in this module (I think these are leftovers from when Save/Load was in the same module as main menu).
fixes #4674
=> Resize Load/Save Window (#4674)

src/lua/LuaMetaType.h
Fixes https://github.com/pioneerspacesim/pioneer/issues/4939
This header should not be included here and does not seem to be needed. It was probably accidentally included in commit 
https://github.com/pioneerspacesim/pioneer/commit/e80d11ee18165127c8710c3bd17acb168726075a.
=> Fix the build with USE_SYSTEM_LIBLUA.

src/FrameId.h, src/core/Log.cpp, win32/vs2019/fmt/fmt.vcxproj, win32/vs2019/modelcompiler.vcxproj, win32/vs2019/pioneer.vcxproj, win32/vs2019/savedump/savedump.vcxproj
This should get 32bit builds working again for Windows (using VS2019).
Remove const operator uint32_t() from FrameId (fixes duplicate member declaration on 32bit - fixes: #4899):
See conversation in https://github.com/pioneerspacesim/pioneer/issues/4899. I removed the uint32_t operator instead of size_t because it will not compile without size_t. This needs to be tested for Linux builds.
Remove calls to fmt::print from WriteLog instead of catching an exception:
Per conversation: https://github.com/pioneerspacesim/pioneer/pull/4890
Linker/Library options cleanup:
The 32bit pioneer-thirdparty libs are named a bit differently than the 64bit ones...
=> Cleanup Win32 Build (VS 2019)

src/DynamicBody.cpp, src/DynamicBody.h, src/Planet.cpp, src/Ship.cpp
Fix the error in calculation of drag force basis components.
Leads to reduction of the overall drag on significant angles of attack, as can be seen from the first look.
=> Atmospheric flight fix

src/lua/LuaDev.cpp
To collect statistics on star systems in a given area.
It does not get in the way, and may even be useful.
example using from lua console:
```
require 'Engine'.GalaxyStats(0,0,0,5, "CountSystemNames CountSystems CountPopulation")
```
This will output statistics for a cube with a center 0,0,0, and a "radius" of 5 (in sectors)
the content of statistics is determined by the names of "processors", at the moment they are available 3. Each processor receives a link to each system in given cube, and generates a report.
=> Add function GalaxyStats to the LuaEngine.cpp

CMakeLists.txt, src/BaseSphere.cpp, src/NavLights.cpp, src/Sfx.cpp, src/Shields.cpp, src/galaxy/GalaxyGenerator.cpp, src/graphics/TextureBuilder.cpp, src/gui/Gui.cpp, src/sound/Sound.cpp
This adds more profiling calls to better profile the startup phase. Turns out Sound.cpp eats a fair chunk loading all of the sounds in the game up front, something that we might want to run in a background thread at some point... Food for thought!
Also added non-interfering optimizations to the Debug build configuration after reading [this blog](https://mropert.github.io/2019/08/03/fifty_shades_of_debug/). Haven't noticed a *huge* difference, but every little bit counts. Ideally I'd like to ensure we enable inlining explicitly inline-declared functions, but I don't know of a GCC flag for that one.
=> Add more profiling points

data/libs/Equipment.lua, data/libs/Ship.lua, data/pigui/modules/hyperjump-planner.lua, data/pigui/modules/system-view-ui.lua, src/AnimationCurves.h, src/Game.cpp, src/SectorView.cpp, src/SectorView.h, src/SystemView.cpp, src/utils.h
<strike>
Since the camera is not tied to the ship, but to the frame of the ship, when the frame changes, the information in the camera becomes irrelevant. If the worldview is active, it is quickly updated, but if the worldview is not active, an accident occurs.
This patch fixes a crash when hyper jumping with an open info screen.
Many variables of type CameraContext are called camera, and this seems to be confusing because there is also a type Camera, and variables of this type, also called "camera" or something like that.
</strike>
_The problem with info screens was resolved in #4941_
Fixes #4901
**System map:** add a check to see if we are in hyperspace
**Sector map:**
- move the drawing of the player's indicator from `DrawNearSector` up to `Draw3D`
- calculate the interpolated position …
=> No more crashes when hyperjumping

win32/vs2019/pioneer.vcxproj, win32/vs2019/pioneer.vcxproj.filters
Multiple files moved between src/ <-> src/ship/
src/View.cpp and src/pigui/View.cpp were being compiled to view.obj. This caused some weird linking issues: symbols from one would always be missing, but which one depended on what file was compiled last. 
Changed src/pigui/View.cpp to compile to pigui/view.obj
=> Fix VS2019 Solution

data/pigui/baseui.lua, data/pigui/libs/forwarded.lua
Looks like I missed a variable being defined when I split the PiGui Lua modules apart, breaking 2D radar. 
`ui.oneOverSqrtTwo` and `ui.standardGravity` are now defined again in pigui/baseui.lua.
Fixes #4965
=> Define ui.oneOverSqrtTwo (fixes 4965)

src/JobQueue.h, src/graphics/RenderTarget.h, src/graphics/opengl/GLDebug.h, src/graphics/opengl/RenderTargetGL.cpp, src/graphics/opengl/RenderTargetGL.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h, src/graphics/opengl/TextureGL.cpp, src/graphics/opengl/TextureGL.h
Refactor the renderer to use an offscreen buffer as the primary render target instead of the window surface. Among other benefits, this means that we don't need the windowing system to give us a 24-bit depth MSAA window surface; as long as the GPU is able to render to those textures we'll be fine.
This is required for later postprocessing work; we need to resolve the MSAA before we do image post processing (we'll probably go the tonemap-resolve-inverse-tonemap route as that seems to be pretty standard).
It also lays the groundwork for 32-bit reverse-Z depth buffer (in fact, the clever among you will notice that the renderer is looking for `ARB_clip_control` and creating a `DEPTH_COMPONENT_32F` depth buffer!) This should allow us to drop the logarithmic depth hack, speeding up our shaders …
=> Use an offscreen buffer as the primary render target.

src/Space.cpp, src/Space.h
~~Add a `bunch` class, which is essentially a vector, but removal from the middle occurs in O(1), thanks to the swap-delete idiom. But this changes the order of the elements.~~
Remake the container for bodies in space from `std::list` to `std::vector`, and removing an element from the middle is done by moving the last element to its place.
=> Better container for bodies in space

data/libs/FlightLog.lua
Flight Log no longer crashes the game if you try to create a custom entry while in hyperspace or in orbit around a system barycenter. Fixes #4917
=> Fix Flight Log crashes

CMakeSettings.json, COMPILING.txt
- Update COMPILING
The instructions for using the Visual Studio CMake build should hopefully be a bit more clear now. They now reflect the fact that build configurations are already setup and don't have to be changed (also see next point).
(@macksting - if you get a chance, I'd love to know if this makes more sense)
- Fix CMakeSettings.json
A somewhat recent update changed how Visual Studio read this file, and the change was breaking. This should now work properly _and_ I've added a super luxurious newline at the end, too.
- Add x64-Profiling build configuration
Pre-configured to build with profiling enabled.
=> Update MSVC CMake configuration and instructions

data/configs/Starfield.ini
I think the bigger star size on the starfield is too excessive, it clashes with the HUD, and isn't really feel like they are brighter stars.
So I've decreased the _brightnessApparentSizeFactor_ from 0.5 to 0.3
(Enlarge the screenshots to see the effect properly:
I think they look much better at 03. They are more subtle, but in a nice way:
Original 0.5:
At 0.4 they are still a bit too much in my opinion
At 0.1, they aren't visible most of the time:
And as a bonus, at 2.0, we turn [Olbers' paradox](https://en.wikipedia.org/wiki/Olbers%27_paradox) on it's head:
=> Decreasing the max star size to 0.3

CMakeLists.txt
Set the GLEW_NO_GLU build flag to avoid pulling in <gl/glu.h> when
including <gl/glew.h>, as it otherwise adds a dependency we don't
actually need.
=> CMake: Avoid libGLU dependency

data/modules/SearchRescue/SearchRescue.lua
This fixes the last comment of #4551. When a SAR mission ship is destroyed the script tries to establish if it was the player's fault or not. But IsPlayer() is not defined for bodies other than ships. This should fix this issue. The save-file attached to the bug report runs fine now.
I was not able to reproduce the other comments in this bug report (crash after trying to deliver crew). Maybe this got fixed together with #4601? Also, the attached respective save file does not load, which makes it hard to pinpoint if the problem was solved.
=> Fix SAR crash where IsPlayer() is falsely called by non-ship body

data/modules/Combat/Combat.lua
Fixes #4983 
Unfortunately, ships with a default hyperdrive 1 sometimes can't reach the destination because of the loaded equipment. So I removed all the equipment too.
=> Draft: Combat mission: Select all ships with a default hyperdrive

CMakeLists.txt
> [2020-11-11 20:55:14] <sturnclaw> The-EG: if you could look into hiding all of the Compressing: messages from appveyor that'd be appreciated; they're seriously polluting the build log.
Done.
=> Silence Inno Setup compressing messages

CI/appveyor/msvc/build.cmd, CMakeLists.txt
> [2020-11-15 16:21:31] \<sturnclaw\> The-EG: could I ask you to suppress warning C4506 in MSVC/Windows CMake?
> [2020-11-15 16:21:35] \<sturnclaw\> It's a bit... spammy
> [2020-11-15 16:24:24] \<sturnclaw\> The-EG: also this https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_MESSAGE.html
The C4506 warning is now disabled project wide for the MSVC CMake build, and the appveyor build should no longer have the cmake 'install' messages.
=> MSVC CMake Updates

data/pigui/modules/time-window.lua, data/pigui/views/mainmenu.lua, src/lua/LuaLang.cpp
This fixes #5007.
- Fix the time accel buttons not working correctly in Polish
- Fix the main menu's weird approach to loading from two lang resources
- Refactor the way we handle missing translations; log a warning and return a placeholder string
=> Fall back to an empty resource if translation isn't found

data/pigui/libs/buttons.lua, data/pigui/modules/info-view/01-ship-info.lua, src/lua/LuaPiGui.cpp
Change font to medlarge, same as all (most?) other screens in ship info, and add documentation strings. 
(These commits keep getting merge conflicts in #4967, so I'll split them out to their own PR, and update that pr accordingly)
=> Small fixes, medlarge font in shipinfo view

README.md
Travis badge is dead - long live github actions.
Waning: I think there's something missing to get this to work properly. Probably obvious to @Web-eWorks who is well versed in GA.
=> Update build badge to github actions

win32/vs2019/collider/collider.vcxproj, win32/vs2019/galaxy/galaxy.vcxproj, win32/vs2019/gameui/gameui.vcxproj, win32/vs2019/glew/glew.vcxproj, win32/vs2019/graphics/graphics.vcxproj, win32/vs2019/gui/gui.vcxproj, win32/vs2019/jenkins/jenkins.vcxproj, win32/vs2019/lua.vcxproj, win32/vs2019/modelcompiler.vcxproj, win32/vs2019/newmodel/newmodel.vcxproj, win32/vs2019/pioneer.vcxproj, win32/vs2019/profiler/profiler.vcxproj, win32/vs2019/savedump/savedump.vcxproj, win32/vs2019/terrain/terrain.vcxproj, win32/vs2019/text/text.vcxproj, win32/vs2019/ui/ui.vcxproj
Minor changes to fix the vs2019 paths for finding sigc++
=> Minor changes to fix the vs2019 paths for finding sigc++

data/lang/ui-core/en.json, data/libs/EquipSet.lua, data/pigui/modules/info-view/03-econ-trade.lua, data/pigui/modules/info-view/04-missions.lua, data/pigui/modules/info-view/05-crew.lua, data/pigui/views/tab-view.lua, src/pigui/PiGuiSandbox.cpp
Working with this, I think there's a lot of stuff that's overlapping with "ship info". I'd suggest "ship info" only show the static info on that ship's stats, and equipment, and this "economy & trade view" shows all the stuff about cargo, fuel, interna-tank mass, and range. Possibly, this could be outside the scope of this PR.
Also, I had a wrestling match against the colorselectbutton since, in my estimation, it makes no sense, in how it tints the button, but for now, it's some kind of deactivated when landed (one cannot jettison when landed). I got the feeling I was using the wrong function, since it's not doing what I want, which is what the name suggestes it's supposed to do. Theme-issues.
I remember playing with this in june/july, and finding some inconsistency  in how we define …
=> Move Economy & Trade -view to pigui

data/pigui/libs/chat-form.lua, data/pigui/modules/info-view/04-missions.lua, data/pigui/views/map-sector-view.lua, src/SectorView.cpp, src/SystemView.cpp, src/SystemView.h, src/galaxy/SystemBody.h, src/lua/LuaSystemBody.cpp
- fix segfault in the system map if a centered ship is removed
- reset the system map view if the centered ship is hidden
- if the mission target is a specific systembody, when you press the "set as nav target" button, the sector map is set to the correct star of the multiple system
- shrink the searchbar window in the sector map when nothing is shown on it
=> Some map fixes

data/pigui/libs/forwarded.lua, src/lua/LuaPiGui.cpp, src/pigui/PiGui.h, src/pigui/Widgets.cpp
With its help, you can precisely select the amount of something, either by clicking and moving the mouse, or by clicking on the arrows, or by entering from the keyboard.
Also moved the theme import from baseui.lua to wrappers.lua because I needed to use color there.
=> Add IncrementDrag widget

data/lang/commodity/en.json
Replace "nuclear waste" with "radioactive waste"
(I'm keeping one "nuclear" as in "Created by nuclear reactors, and military hyperdrives")
Closes #5054
OK @gunchleoc?
=> Nuke the nukes - be consistent and call it 'radioactive waste'

CMakeLists.txt, src/posix/FileSystemPosix.cpp
When models are installed on the system, the modelcompiler would use
these instead of the local ones found in the "data" folder. However,
the *.model files are not installed on the system, so the
modelcompiler would end up not compiling anything.
Fix this by returning only the local "data" folder files in
FileSystemPosix.cpp if the PIONEER_LOCAL_DATA_ONLY environment variable
is set, and set this environment variable in CMake when the
modelcompiler is called.
=> CMake: Fix modelcompiler not compiling anything

src/MathUtil.h, src/SectorView.cpp, src/SectorView.h, src/galaxy/Sector.cpp, src/galaxy/Sector.h
Build all of the lines into a single buffer once, render as necessary and offset using the transform.
Resolves part of #5030 rendering
- https://github.com/pioneerspacesim/pioneer/blob/b5e21686269c7efcadcc2301169147e6f7ca04e7/src/SectorView.cpp#L751 this needs some kind of spacial bucketting!
- Added a sector selection optimisation to avoid generating sectors we then discard `Info: SectorView::AutoRoute, nodes to search = 5253, earlied out sector distance from line: 109870 times.`
- Avoided a bunch of sqrt operations by using the square distance.
- Tried to reserve some of the vectors and other stl structures.
=> Optimise route rendering

src/lua/LuaMusic.cpp
I haven't got the slightest idea why no argument to loop isn't treated as such, but adding a default seems to fix #5049 
It looks like otherwise the related code in SoundMusic.cpp gets a repeat = true (line 53 I think).
¯\_(ツ)_/¯
=> Fix ambient music looping

data/pigui/libs/equipment-market.lua
1. The third argument to bought/sold wasn't passed, instead the member variable was used directly in the body, also shortened the code a bit.
2. When selling/buying from ship equipment market, it defaulted to -1 units, should be 1.
I've tested ship equipment market and commodity market (both buying/selling 1, 10, units and also negatively priced commodities), and goodstrader on the BBS.
Closes #5071
=> Fix equipment market widget not updating stock properly

data/lang/ui-core/en.json
Moving rotation from RMB to MMB throws player off balance at first
exposure. The rotate button has also proven to be un-intuitive, based on
player feedback. Hope this helps, if even a minuscule bit.
Change tooltip in sector view:
"Rotate view" -->  "Hold down to Rotate view"
=> Clarify tooltip to reduce confusion

data/libs/SpaceStation.lua
When doing #5059 (adverts for sold out commodities, where I choose an imported commodity and zero out its stock, and offer twice the price on the BBS), I noticed a lot of the available stock for imported commodities at stations was already at 0t. This jumps out at me. First I assumed it was my code going crazy, such that what is zeroed out on one station, is zeroed out on _all_ stations, but no, this is the actual behaviour on master.
I think seeing 0t of stock of a commodity should be a "wow" moment, triggering the player to check the BBS for adverts for soldout commodities, or to see this "imbalance between supply and demand" when a news event has occurred that alludes to huge event affecting the market in a system.
One should be able to buy also imported goods, even if usually is a bad …
=> Reduce probability for imported goods to be sold out

data/lang/module-donatetocranks/en.json, data/modules/DonateToCranks/DonateToCranks.lua
New pigui chat-form did not support explicitly setting seed, giving new face every time the advert is clicked. Fixed it by having the same charracter for each instance of a BBS. (These adverts are not fix to station over time).
The comms that was used before, is rendered to world view, so messages (e.g. "note enough money", or "thanks") sent there are not seen. Update message in chat box instead, making it more of a dialogue. Also, now the advert closes itself when the player has donated.
There is currently no way the player to know:
1. How close they are to next jump in reputation status, nor,
2. Difference between different donation organizations (some are more cranks than others)
With this, each donation indicates how much money is needed to gain next level of reputation. Thus, it …
=> Donate to crank improvements

data/pigui/libs/text-table.lua, data/pigui/modules/info-view/01-ship-info.lua
- Localize table headers
- Fix ragged layout by using text instead of textWrapped. The textWrapped function really needs a width parameter, but we have sufficient space on this screen at 800x600 resolution and I didn't want to dig this deep into it.
Tested with Scottish Gaelic and Hungarian - in my experience, if it fits these 2 languages, it fits.
Before:
After:
=> Localize header strings on ship information screen

src/SystemView.cpp, src/SystemView.h
If you turn on the ships in the system map, turn off the system map and jump into another system, then pointers to the ships from the previous system remain in `m_projected`, which cause the a segfault. Now clear this when switching from view.
=> Fix SIGSEGV on switch to system map after HJ

.github/workflows/build-ci.yml, CMakeLists.txt
This should cause the GitHub actions builds to trigger on all pushes to master, which is how the appveyor and travis builds worked, in addition to any PRs that have cpp/h source changes.
This should get our build badge working again, *and* have the nice side effect of having an unofficial build of master always available: the latest artifacts will be available here -> https://github.com/pioneerspacesim/pioneer/actions?query=workflow%3A%22Build+Pioneer%22+branch%3Amaster
Also, I've turned the 'installing' messages from CMake back on. Since Github actions has separate sections for each step, and creating the installer is one of those steps, the install messages shouldn't be an issue with reviewing the logs. And, it's helpful to see if things are being included/excluded from the installer. …
=> Trigger Build Pioneer github action on pushes to master

.tx/config, data/lang/module-soldout/en.json, data/modules/SoldOut/SoldOut.lua
In frontier one would often have the habit to check the BBS for special "WANTED" adverts before selling the commodity on the market exchange. Especially if the station had 0t in stock.
This module selects a major import and with a fairly low probability (for now 10% adds one advert, and zeros out the stock of that commodity in the commodity market).
There's only one flavor because this advert will be rare, so slight rewording of it will not make a difference.
This is in some way similar to #2753, but that one announces where the market is sold out globally, to all neighboring systems, (and offers a larger multiple than x2), where as this advert is as brief as can be.
Advert uses "$" icon for now (could alternatively use the shopping cart icon)
Please don't look at the code, it's messy
=> BBS advert for soldout commodity

data/libs/SpaceStation.lua, data/modules/TradeShips.lua, data/pigui/libs/commodity-market.lua
This should maybe be shown in a separate column (but green/blue icons would look strange here?), and could be placed better,
but it's a start.
It feels like the if-else statement to check if something is import/export keeps popping up everywhere (tradeship, spacestion, here, system econ view). Feels like there should be a method that gets that information for us somewhere? 
At least which numbers for price modification should be the threshold for major/minor export import? 
- system econ view sets 4/10 for minor/major
- Tradeship lua: 2/10 for minor/major 
- Spacestation: 2/10 for minor/major
- commodity market (this PR): 2/10
=> Show import/export in commodity description in commodity market

src/SectorView.cpp
This function was used to prevent the indicators from overlapping the stars.
Now they just move a little beyond the stars.
=> Remove SetDepthRange calls from SectorView.cpp

data/libs/SpaceStation.lua, src/posix/FileSystemPosix.cpp, src/scenegraph/MatrixTransform.h, src/scenegraph/Model.cpp, src/scenegraph/ModelSkin.cpp
Our savefiles are truly too large. Not only are we storing completely redundant data about MatrixTransform nodes that will immediately be overwritten by the animation system, but we're also storing every last detail about every market in the system regardless of whether we've been there or not.
On top of removing redundant save data from the C++ side, we now only create a station's market when we actually land there, which removes one of the biggest hogs of save data. How big, you ask? Uncompressed, our savefiles dropped from 2MB to ~500KB, and compressed they dropped from 350KB to 75KB. I've tested on a Mars start after taking off and landing at Mars High to generate a representative sample of the average in-system activity a player might have.
This has a nice side effect of making …
=> Significantly Slash Savefile Sizes

.github/workflows/build-ci.yml
This should attempt building the VS Solution anytime the cmake builds are triggered. This is solely intended to help us find when the solution breaks before it gets into master.
*Note*: as of right now, the solution *is* broken in master, so this check will fail regardless (I've fixed it in the Radar PiGUI PR along with those changes).
edit: do not merge yet, I have renamed Pi.cpp -> Pi_.cpp to test the builds, I will force push to remove that later.
=> Add GitHub Action for building VS 2019 Solution

data/systems/02_local_stars.lua, data/systems/custom/08_61cygni.lua, data/systems/custom/09_delta_eridani.lua, data/systems/custom/10_ayizan_lacaille8760.lua, data/systems/custom/11_noril_wolf1061.lua
Following in the wake of #5052, I saw that @SpifforOmnivore has left comments in the system definition what the system's names should be once we have alternative naming scheme in place, which we do, since some time ago. This aims to do the wishes of original author. 
@SpifforOmnivore please have a look and see if it's OK with you.
Also, Cennet is turkish? And Azeri is a language? (ping @WKFO)
=> Make use of system's alternate names, as original author intended

data/pigui/libs/chat-form.lua, data/pigui/libs/forwarded.lua, data/pigui/libs/text-table.lua, data/pigui/libs/wrappers.lua, data/pigui/modules/fx-window.lua, data/pigui/modules/settings-window.lua, data/pigui/modules/system-view-ui.lua, data/pigui/views/game.lua, data/pigui/views/info-view.lua, data/pigui/views/map-sector-view.lua, data/pigui/views/station-view.lua, data/pigui/views/system-info-view.lua, src/lua/LuaPiGui.cpp, src/ship/ShipViewController.cpp
**Fixes #5040:** `ui.getColumnWidth()` appears to be ignoring some window padding, which was causing incorrect behavior. Now we query for `ui.getContentRegion().x` which isn't quite correct either but works without unduly wrapping at all sizes.
**Fixes #4981:** this was a simple matter where we weren't updating the camera's position when the controller didn't have input focus. I also added a bit of code that should help to prevent the cursor from getting stuck in hidden mode.
**Fixes #5065:** dead simple, just needed to tell Pioneer to save the binding when changing the checkbox.
**Fixes #5055:** this was broken for several reasons - the tooltip was being used as the button ID, so clicking on any of the buttons wasn't switching the view correctly. I took the chance to simplify the logic a …
=> Small UX fixes

data/libs/utils.lua, data/modules/Assassination/Assassination.lua, data/modules/BreakdownServicing/BreakdownServicing.lua, data/modules/CargoRun/CargoRun.lua, data/modules/Combat/Combat.lua, data/modules/CrewContracts/CrewContracts.lua, data/modules/DeliverPackage/DeliverPackage.lua, data/modules/DonateToCranks/DonateToCranks.lua, data/modules/SearchRescue/SearchRescue.lua, data/modules/SecondHand/SecondHand.lua, data/modules/Taxi/Taxi.lua
This has been bugging me for many years: prices are not "even". Consider getting $24,441 for an assassination, or $1114 for delivering some cargo.
So I made a function that rounds input `x` to closest number `N` (could be float, e.g. 0.5), and returns `N` if input is below it, else `x`. I'm sure someone will now tell me we already have this function, or it's standard in Lua, - I'm all ears. (so to explain the title: we can think of this PR as reflecting how the market prefers to price in increments corresponding to some space coin)
I'm demonstrating it here, for those who prefer visual explenation:
I'm also including a commit to reduce prevalence of the Donate to free software advert, on request of @Web-eWorks. Worth noting: I think the flying spaghetti monster one is more silly, (so …
=> The future belongs to COINS!

src/sound/AmbientSounds.cpp
There is not much to explain. For example if you rough-land on Earth's surface it plays some water sound, and we want this sound effect to stop once the player is airborne, not when they fly out of the atmosphere.
Partially f i x e s #5113
=> Stop planet ambient sound once player gets off the ground

src/galaxy/SystemBody.cpp, src/galaxy/SystemBody.h
In case the systembody does not have a jumpable parent.
This can happen if it revolves around several stars at once.
At the moment this situation leads to a segfault.
Fixes #5112
=> Add search for the geometrically closest jumpable

.github/workflows/build-ci.yml, .github/workflows/clang-format.yml, scripts/clang-format.sh
This is triggered by #5105, where my local and the remote system clang-format disagrees. Also, when we build linux version, I think we're more likely to be compatible with player's system, using ubuntu 20, rather than 16.
=> Update buildscripts to use Ubuntu 20.04

src/Background.cpp, src/Pi.h
Limit the radius searched for stars and mix it from the minimum to the desired radius depending on the star density.
Fixes #4990
=> Blend the radius searched for stars based on desired density.

src/SystemView.cpp
Small fix to segfault when opening the system map during a hyperjump
fixes #5096
=> Do not try to GetStarSystem from hyperspace

Changelog.txt, src/galaxy/SectorGenerator.cpp
Duplicate and extend the Frontier naming to create a hybrid, semi-replicate Doomdarks naming system, add naming fragements based on Japanese Katakana.
Then pick between all four possibilities when naming a star system.
Fixes #4866
Things to consider:
- swearwords http://www.youswear.com/?language=Japanese
- ~~lack of randomness sometimes "anda"~~
=> Add alternative naming schemes

src/ship/PlayerShipController.cpp
Fixes #5136, code as suggested by @Web-eWorks
=> Don't persist signals past destruction of object they're attached to

data/shaders/opengl/multi.frag, src/Camera.cpp, src/WorldView.cpp, src/graphics/Graphics.cpp
As promised, this was pulled out of #5156 to be applied to master. This PR contains a fix for planets and gas giants clipping out of the view, and also a fix for the unreported issue of persistent bright-spot acne on our models, most noticeable on the fuselage of the Pumpkinseed (but prevalent pretty much everywhere).
Closes #5145.
These screenshots are identical loads of the same save (including camera position/zoom), showing the difference with this change applied.
=> Fix GasGiant clipping and bright spots on models

src/Pi.cpp, src/sound/Sound.cpp, src/sound/Sound.h
While trying to prevent sounds from playing after the game was ended, Pi.cpp accidentally(?) stopped music player from playing as well, which meant no death music would play as the tombstone spinner appeared. Now it works as intended; sound effects stop, but music is not stopped until death view is closed and the program returns to main menu (at which point menu music starts).
I made this a separate PR from #5093 so that only the fix can be merged if one desires.
=> Fix death music not playing over tombstone screen

data/pigui/modules/flight-ui/gauges.lua, data/pigui/modules/master-alarm.lua, src/lua/LuaBody.cpp
...instead of just the player. So you can calculate the pressure around any object in atmosphere, not just the player ship.
EDIT: The main motivation for this PR is that it fixes the traffic control giving wrong pressure data.
=> Modify GetAtmosphericState() to accept any two bodies

data/lang/ui-core/en.json, data/libs/Player.lua, data/pigui/views/station-view.lua, src/lua/LuaPiGui.cpp, src/lua/LuaShip.cpp
Me, on April 12th, 2014:
> Yes, I've been meaning to look into this just this weekend.
Well, here it is, fixes #2863 (I'm also including a spelling fix commit)
=> Fix Legal footer always being "clean" in station view

data/lang/module-advice/en.json, data/lang/module-rondel/en.json, data/modules/Advice/Advice.lua, data/modules/PolicePatrol/Rondel.lua, data/modules/Rondel/Rondel.lua
I know the title makes it sound stupid (why would you stop the players from entering a system?), but hear me out. I noticed a red spot on the sector map and found this Haber system in the middle of SolFed territory.
```
-- Copyright © 2008-2020 Pioneer Developers. See AUTHORS.txt for details
-- Licensed under the terms of the GPL v3. See licenses/GPL-3.txt
-- example of a custom system directly specifying a faction
local s = CustomSystem:new('Rondel',{'STAR_M'})
:faction('Haber Corporation')
:short_desc('Military Listening Post')
:long_desc([[A hidden dagger pointed at the heart of the Federation]])
:seed(1824351)
s:add_to_sector(-1,6,2,v(0.007,0.260,0.060))
```
It looks like someone made this system just as a custom system example (no starports, no defined planets etc.), but I thought it …
=> Restrict entry to Rondel system

contrib/profiler/Profiler.cpp, data/pigui/views/tab-view.lua, src/Frame.cpp, src/ModelBody.cpp, src/ModelViewer.cpp, src/Ship-AI.cpp, src/Ship.cpp, src/Ship.h, src/Space.cpp, src/lua/LuaPiGui.cpp, src/scenegraph/BinaryConverter.cpp, src/scenegraph/BinaryConverter.h, src/scenegraph/Loader.cpp, src/scenegraph/Model.cpp, src/scenegraph/Model.h
This is primarily merging in the work I did to make the tradeships PR (#4984) feasible from a performance perspective. I've added in a few other commits from unmerged branches that made sense and cleaned up the codebase a little bit.
This prevents model animation interpolation from being run when active animations aren't being played, which was the number one performance hog with many ships in a system. It also cleans up a fair amount of C++-to-Lua overhead that was being run every `StaticUpdate` tick.
This PR also removes unneeded code in the TabView and remembers the last tab the user was on in the Comms and Info windows.
=> Improve performance with many ships in one system

src/Space.cpp
Save games could fail to load due to the body index being written as `(Uint32)-1`.
Handle getting an out-of-range / SDL_MAX_UINT32 value when trying to find a body by returning `nullptr` instead.
This allows savegames to load despite this issue.
The issue itself is caused by the `AICmdFlyAround` having a pointer to a `Body *m_obstructor` that it does not own and is not refcounted. This can be destroyed before/whilst saving, which fails to find the body (_'cos it's gone_), the GetIndexForBody returns `(Uint32)-1`, and upon loading it crashes.
I would like to have fixed the actual cause by this COVID19 vaccination has hit me like a bus and I feel like I've got flu.
So posting this as-is for possible merging, comments, and suggestions. Either other can fix it, or it can wait until my brain …
=> Warn about loading dead bodies, but handle safely.

win32/vs2019/pioneer.vcxproj, win32/vs2019/pioneer.vcxproj.filters
Add PrecalcPath files and once again lament the lack of wildcard filesnames in VS
=> Add PrecalcPath files to VS2019

data/pigui/views/map-sector-view.lua
Systems with shared names should be unique to imgui in selection menu
Fixes #5188
=> Enable selecting star search results with duplicate names

data/modules/NewsEventCommodity/NewsEventCommodity.lua
When debugging SpaceStation.lua in #5173, I got sucked in for a number of hours when I discovered that the News Event in the load file provided by the @jimishol clearly wasn't working anymore. There were two "news events" in the save file I was given, I played the "drought news":
_"Severe` drought has ruined the crop in the {system} system ({sectorx}, {sectory}, {sectorz}). System wide famine is feared."_
which supposed to increase price of grain 10 fold and put stock to 0 in the commodity market, but it didn't seem to change anything on the commodity market.
It was like the `equipmentStock` table in `SpaceStation` was reset, but updating it just didn't work.
I eventually figured out the `equipmentStock` table is keyed on the `EquipType` i.e. the _memory address_ of the table(!), which is …
=> Fix NewsEvent not doing it's thing after save/load cycle

COMPILING.txt, README.md
With the sale and subsequent takeover of freenode, the development team no longer uses that IRC network for collaboration. Update links to point to libera.chat instead.
As an additional note, http://pioneerspacesim.net/irc needs to be updated to redirect to a KiwiIRC join link for the new irc channel instead of pointing to freenode's webchat app.
=> Switch to Libera.Chat in Readme.md

contrib/profiler/Profiler.cpp, contrib/profiler/Profiler.h, src/Background.cpp, src/CityOnPlanet.cpp, src/Game.cpp, src/Input.cpp, src/JobQueue.cpp, src/NavLights.cpp, src/Pi.cpp, src/Pi.h, src/Space.cpp, src/SpaceStation.cpp, src/TerrainBody.cpp, src/collider/Geom.cpp, src/core/Application.cpp, src/core/Application.h, src/core/GuiApplication.cpp, src/galaxy/Factions.cpp, src/galaxy/GalaxyCache.cpp, src/galaxy/GalaxyGenerator.cpp, src/galaxy/SystemBody.cpp, src/graphics/Frustum.cpp, src/graphics/Graphics.cpp, src/graphics/opengl/RendererGL.cpp, src/pigui/Radar.cpp, src/scenegraph/Group.cpp, src/scenegraph/MatrixTransform.cpp
"Congratulations, you're a real profiler now!"
This PR adds support for capturing profile zone start/end events, storing them in a buffer, and writing them to disk in Speedscope Json format for inspection in [Speedscope](https://speedscope.app). This is the "missing link" in our profiling capabilities, the ability to dig into the sequential nature of what's happening in a frame and visually see what functions are taking significant amounts of time.
In the process of doing this, I've removed appx. 2000 'unhelpful' profiling calls from the startup phase; these are functions that on average consume <1 microsecond per call and overall have very little contribution to the overall time. I've also dug in a bit and removed 4000+ of these small profiling calls from the average in-game frame …
=> Add zone-based profiling support

contrib/lua/CMakeLists.txt, src/lua/CMakeLists.txt, src/lua/LuaShip.cpp
Don't depend on hardcoded paths to the Lua library in contrib/.
=> Fix build with WITH_SYSTEM_LIBLUA=ON

contrib/profiler/Profiler.cpp, src/FaceParts.cpp, src/JobQueue.cpp, src/JobQueue.h, src/Pi.cpp, src/Pi.h, src/SDLWrappers.cpp, src/collider/Geom.cpp, src/galaxy/Sector.cpp, src/galaxy/StarSystemGenerator.cpp, src/sound/Sound.cpp
Absolutely not finished, this is a horrendous hack that just so happens to work perfectly on my end.
- I've added profiling to worker threads started by the job system, so now they show up in the profiler output and we can see just how long they stay idle.
- I've also made `Sound::Init()` do it's sound and music loading in a background thread using the Job system, which has a few ramifications: FileSystem will need to be reviewed to ensure it's thread-safe, and if we want to play music at the main menu (or even earlier) then we need some way for the main thread to block until a certain group of jobs are finished (which sounds like a task for JobSet to me!).
At the moment there's absolutely no synchronization here, so if the background thread were to theoretically take an entire minute to …
=> Improve Startup Times via Threading

src/core/OS.h, src/main.cpp, src/posix/OSPosix.cpp, src/win32/OSWin32.cpp
Without this change, Windows would automatically apply a scaling factor
for Pioneer which prevented the game from using the full resolution.
Mark Pioneer as DPI-aware so that Windows won't mess in our business.
=> Mark Pioneer as DPI-aware on Windows

data/modules/NewsEventCommodity/NewsEventCommodity.lua, src/lua/LuaFormat.cpp
This fixes a bug in Greek, where names of the month can't be parsed
After this fix, month is shown, and not `{date}`:
=> Add Format.DateOnly() to lua side

data/lang/module-cargorun/en.json, data/modules/CargoRun/CargoRun.lua
Requested by @impaktor some time ago for the cargo run module.
Player with smaller ships can now choose a smaller amount of cargo. The advertisement remain in the BB with the rest of the cargo.
=> Negotiate amount of cargo

Changelog.txt, data/lang/ui-core/en.json, data/libs/utils.lua, data/modules/DonateToCranks/DonateToCranks.lua, data/modules/TradeShips/Debug.lua, data/modules/TradeShips/Trader.lua, data/pigui/libs/array-table.lua, data/pigui/libs/forwarded.lua, data/pigui/modules/fx-window.lua, data/pigui/modules/info-view/01-ship-info.lua, data/pigui/modules/info-view/06-flightlog.lua, data/pigui/modules/settings-window.lua, data/pigui/modules/system-econ-view.lua, data/pigui/views/game.lua, data/pigui/views/tab-view.lua, src/Input.cpp, src/Input.h, src/ModelViewer.cpp, src/core/GuiApplication.cpp, src/graphics/opengl/RendererGL.cpp, src/lua/LuaPiGui.cpp, src/lua/LuaVector2.cpp, src/lua/core/Sandbox.cpp
This is a maintenance PR to clean up a few outstanding bugs and prep a release before we merge the renderer rewrite and other PRs that make major changes and take the master branch unstable.
- Partially resolves (but doesn't close) #5158 by ensuring the edit button stays on screen.
- Fixes #5162 with better error tracking that catches when MSAA is unavailable for whatever reason.
- Fixes (partially) #5149, adds an error dialog that displays an error has occurred and prompts the player to report the issue.
- Fixes #5179.
- Fixes #5104. There are further issues with first-person navigation, but now it doesn't crash.
=> Fix low-hanging bugs in prep for mid-year release

data/lang/module-cargorun/en.json, data/modules/CargoRun/CargoRun.lua
Improvement of #5164
This restores the "How much mass" question and moves the "Is the amount of cargo negotiable" button below that.
=> Restore the "How much mass" question

src/SectorView.cpp, src/SectorView.h
During manual movement in the sector map, when the option is enabled, the closest star to the map viewing position is automatically selected. But the search is performed only in the sector containing the original position, so the wrong star may be highlighted. This commit fixes this defect, now the search is performed in an increasing (if necessary) range, and the really closest star is found.
Also, fixed that the star was not automatically selected when animating "by inertia", but only when a key was pressed.
=> Improve automatic star selection in the sector map

README.md
I also tested a badge for all downloads, it says 27k, not sure if that's all clones, or what? This badge shows linux + windows downloads from latest release.
same as sum of output from: 
```
curl -s https://api.github.com/repos/pioneerspacesim/pioneer/releases | egrep '"name"|"download_count"'
```
=> Add download counter badge

data/modules/SoldOut/SoldOut.lua
Fixes #5251 by closing the form, so player can not sell when amount=0.
=> fix crash from selling when amount=0

src/lua/LuaPiGui.cpp
Hello! :)
- AddBezierCurve has been renamed to AddBezierCubic in [4d8e839dd](https://github.com/ocornut/imgui/commit/4d8e839ddf3786f11390002b86218419311843fb)
- ImGuiInputTextFlags_AlwaysInsertMode has been renamed to ImGuiInputTextFlags_AlwaysOverwrite in [287bd9b98](https://github.com/ocornut/imgui/commit/287bd9b98488d5f7bc0f730904af7f0c842971eb)
=> Replace obsolete imgui functions

src/collider/CollisionSpace.cpp
The height of that tree can fluctuate very much, starting from log2(n) and ending with n (n is the number of objects in space).
When traversing the tree, an array (for the stack) is used, the size of which is fixed, because we do not want dynamic allocations in this case, but must be at least the height of the tree.
We can limit the height of the tree, since a leaf can contain multiple objects.
It seems the height of the tree in the game almost never exceed 20.
So I took the number 38 (with a margin), it seems almost never the height of the tree will be limited, and at the same time we are insured against UB in all cases.
Fixes #5245 
ADD:
I would like to add that I checked the program's work with the height limit of 5, everything seems to work stably, while the tree height (excluding the …
=> Increase and limit the height of the BvhTree (for collision geoms)

data/models/ships/skipjack/skipjack_hi.dae
Fixes #5177 
The gun tag was just `tag_gunmount` instead of `tag_gunmount_0`
The tag was picked up properly upon buying/switching ship, but would not work after a reload. The weapon sound is audible, but nothing fired. Which might be good to investigate though. This PR fixes the gun not firing after a reload.
=> Fixing Skipjack gun tag not having a _0 at the end

data/pigui/modules/comms.lua
Two commits concerning the comms terminal.
* When new messages are pushed to the comms terminal they are eventually presented hidden after the old messages. Solved by showing the new messages on top. Pizzazz!
Fixes https://github.com/pioneerspacesim/pioneer/issues/4688
* When the small window reaches its five maximum line a scrollbar appears to the right. Scrollbar removed.
Pictures of the comms log messages propagating top to bottom and with scrollbar with five messages.
=> Commsfixes

data/modules/SoldOut/SoldOut.lua
When illegal commodities get in SoldOut module, double their nominal
price makes no difference as black markets sells already at double
that price.
We double the doubled price when commodity is illegal.
=> Illegal commodities nominal price x4

src/Ship.cpp
speed and density factored in to how much is scooped hasnt changed, only the threshold where it starts scooping
scooping is still non-trivial
Fixes #5237
=> make fuel scooping less of a suicide

src/Color.h, src/HyperspaceCloud.cpp
Fix the hyperjump edges being solid by providing an alpha value.
I added a new c'tor for Color4ub to take a Color4ub and override the alpha value
Fixes #5261
=> Fix the hyperjump edges being solid by providing an alpha value

src/Color.h, src/galaxy/CustomSystem.cpp, src/lua/LuaBody.cpp, src/lua/LuaCall.h, src/lua/LuaColor.cpp, src/lua/LuaMetaType.cpp, src/lua/LuaMetaType.h, src/lua/LuaObject.cpp, src/lua/LuaObject.h, src/lua/LuaPushPull.h, src/lua/LuaRef.cpp, src/lua/LuaSerializer.cpp, src/lua/LuaSerializer.h, src/lua/LuaSystemPath.cpp, src/lua/LuaVector.cpp, src/lua/LuaVector2.cpp, src/pigui/LuaModelSpinner.cpp, src/scenegraph/LuaModelSkin.cpp
This PR removes the old text-based Lua pickling and serialization entirely, and fixes a long-running bug where an attempt to serialize out a non-LuaWrappable userdata object was impossible and would cause a segfault. Now, object serialization operates in a type-erased fashion, allowing userdata objects of all sorts to be serialized to Json from a Lua context with only a single function call to register the serialization hooks.
This PR also includes several major improvements to the LuaMetaType framework for efficient Lua binding of C++ objects - now it supports binding generic C++ functions (like ImGui methods), as well as directly registering meta-methods in several different ways and first-class support for registering constructors. The internals of the binding framework have been …
=> Refactor Lua Serialization

src/lua/LuaSpace.cpp
After placing the ship on the route, the possibility of a collision is checked.  In case of a possible collision, its position is changed to avoid this. It turns out that this calculation worked incorrectly, because the `FromVectors` function creates a matrix using vectors as
columns, and in the further calculation it is assumed that vectors are rows.
Also removed unnecessary `Frame` object retrieval by `FrameId`.
This video shows that now everything is working as it should (at least in the video). The dangerous trajectory that was originally shown in red, the new safe trajectory is shown in blue, and the alternative trajectory (also safe, but on the other side of the obstructor) in gray.
https://user-images.githubusercontent.com/18342621/131369271-f4b4a4fb-f1df-49ea-8e7b-0c0929afd538.mp4 …
=> Fix PutShipOnRoute function

data/libs/Game.lua, data/libs/SpaceStation.lua
This PR addresses a problem very astutely noticed by @jimishol in the economic and trading simulation portion of the game - once the player acquires a ship with ~80t of cargo space, the trading gameplay loop of Pioneer is effectively over. All commodities in the game have the exact same maximum profit for a single trade run, and the only variance is in how much hull space is required to make that exact same amount of money.
This means that once you have found an export/import run for Precious Metals, you have hit the maximum profit ceiling in trading. Sure, you can run a second commodity at the same time in a larger hull, but that costs more fuel, takes more real player time, usually requires a second chain of hyperjumps, and the profit margin is much lower than your primary commodity.
I …
=> Make (Bulk) Trading Profitable Again + Station Restocking

data/pigui/libs/wrappers.lua, data/pigui/themes/default.lua, data/pigui/views/mainmenu.lua
This PR is a minor set of fixes to the comms window background opacity (closes #5286) and quit message popup window. We use more consistent typography in the quit menu, and the buttons are properly centered and positioned now.
=> Change CommsWindow opacity, adjust Quit message window

data/lang/module-fuelclub/en.json, data/modules/FuelClub/FuelClub.lua, data/pigui/libs/chat-form.lua
Members get refueled every time and can sell the internal fuel over and over again.
This PR prevents that and limits the refilling to once a day after takeoff.
=> FuelClub: Refuel internal fuel tank only once a day

data/modules/BreakdownServicing/BreakdownServicing.lua
The 'Breakdown Servicing' character changes face in between chats. This is because `Character.New()` is called from the `onChat` function and somehow doing it with a persistent seed doesn't give persistent result. I don't know why that doesn't work. Instead I simplified the code a bit by generating the character on `onCreateBB`.
=> Fix mechanic not being persistent

src/SectorView.cpp
This is what the problem looked like:
https://user-images.githubusercontent.com/18342621/149637366-41b7c987-573d-4fcc-b5ba-b01c0c6bbb5a.mp4
=> Fix clicks falling through buttons in sector map

data/modules/Advice/Advice.lua
In screenshot above, I've made a for-loop over all advises, just for demonstration purpose.
@Web-eWorks was there any other module that I should fix? I see you already fixed the SoldOut module.
=> Make "Travellers Advice" module work with new revamped BBS

data/pigui/libs/wrappers.lua, data/pigui/modules/info-view/01-ship-info.lua, src/GameConfig.cpp, src/SystemView.cpp, src/SystemView.h, src/View.cpp, src/core/OS.h, src/posix/OSPosix.cpp, src/win32/OSWin32.cpp
Yet another "microfixes" PR in a long tradition of the same, it does what it says on the tin. Going to leave this open for a little bit to collate small QOL fixes I find.
* Default to the user's environment language code when no config file exists. Fixes #3723.
* Fix lua error when changing ship type. Fixes #5322.
* Fix asserts / issues with ui.isAnyWindowHovered / ui.tabBarFont.
* Fix segfault when accessing invalid renderer ptr. Fixes #5328. Fixes #5329. Probably fixes #5330.
=> Small pre-release QOL fixes

data/libs/utils.lua, data/pigui/baseui.lua, data/pigui/libs/text.lua, data/pigui/libs/window-layout.lua, data/pigui/modules/flight-ui/system-overview.lua, data/pigui/modules/system-overview-window.lua, data/pigui/modules/system-view-ui.lua, data/pigui/views/map-sector-view.lua, src/SectorView.cpp, src/Space.cpp, src/SystemView.cpp, src/SystemView.h, src/graphics/RenderState.h, src/graphics/opengl/RenderStateCache.cpp, src/lua/LuaSystemBody.cpp, src/lua/LuaSystemView.cpp
This PR adds the System Overview widget (the body list in the top right of the world view) to both of the System Map view modes. It also refactors out the layout code from both the Sector Map and System Map into a single reusable module for creating full-screen UIs.
It also changes the focus-object interaction in the SystemView to use double-clicks instead of single-clicks; this may be a slightly controversial change, but having selection state decoupled from focus state is fairly useful when interacting with the overview widget.
This is likely the last of the work branches I have outstanding to be merged into the release, nothing else is close enough to done to be a viable candidate.
=> Add System Overview Widget to System Map view

data/pigui/modules/flight-ui/system-overview.lua, data/pigui/modules/fx-window.lua, data/pigui/modules/system-view-ui.lua, data/pigui/themes/default.lua, src/SystemView.cpp, src/SystemView.h, src/lua/LuaSystemView.cpp
https://user-images.githubusercontent.com/18342621/151628791-8cb893e5-f909-4324-91ff-b471011a7ed7.mp4
- show icons for asteroids and orbitals only
- show switch button to atlas-view in top row
- don't show grid, L-points and ships buttons in atlas mode
- fix mouse panning and zooming
- add a button to hide the overview window
- correct overview-window size in worldview
- fix that when you click on the planet if the ship is centered, the view is reset
- show ground stations around the planet when hovering or clicking on it
- generate only one popup (and not for each object)
=> Slight fix/improve atlas-view

src/Orbit.cpp, src/Space.cpp, src/SystemView.cpp
- fix the assertion when hyperjumping with the system map enabled
- fix that sometimes a body with a radial orbit disappears from the system map
=> System map fixes after play-testing

src/Game.cpp
The GetBodyForPath function was called (from GetHyperspaceExitParams) before Game::m_state = State::NORMAL was set, so it returned nullptr. Therefore, the first non-gravpoint body was always set as the base body for exit.
(This led to the fact that in the multiple system the star "A" was always chosen, regardless of the player's choice in the sector map.)
=> Fix getting exit parameters from hyperjump

data/modules/NewsEventCommodity/NewsEventCommodity.lua
Since Game.time does not start when new game starts, in order to check if 6 months have passed since start of a new game, the oldest deptime from FlighLog is used instead.
=> Gets new game's start time from FlightLog to be compared with minTime

contrib/atomic_queue/defs.h, contrib/profiler/Profiler.h
1. Add `__riscv` to `USE_CHRONO` check, like other architectures.
2. Merge https://github.com/max0x7ba/atomic_queue/commit/4e559dabe28e57ee27cb45c8297e1e387beed1d3
=> Add riscv support

data/modules/MusicPlayer.lua
Fixes #5362  hopefully.
Ping @Keeper1st .
=> Fix docked music not playing

src/lua/LuaObject.cpp
This PR is a quick (but complete) fix to the use-after-free bug @Gliese852 found as a result of the new PropertyMap implementation - now when we delete the underlying C++ object, we also clear the pointer to the property map that's stored in the Lua handle's meta-data uservalue table.
=> Fix use-after-free with PropertyMap pointer

data/modules/Debug/TestComponent.lua, data/modules/Debug/TestSerialization.lua, licenses/zlib.txt, src/Body.cpp, src/Body.h, src/BodyComponent.cpp, src/BodyComponent.h, src/DynamicBody.cpp, src/DynamicBody.h, src/FixedGuns.cpp, src/Game.cpp, src/Missile.cpp, src/Missile.h, src/Pi.cpp, src/Player.cpp, src/Ship.cpp, src/Ship.h, src/ShipAICmd.cpp, src/ShipAICmd.h, src/ShipCockpit.cpp, src/WorldView.cpp, src/lua/LuaBody.cpp, src/lua/LuaBodyComponent.h, src/lua/LuaObject.cpp, src/lua/LuaObject.h, src/lua/LuaSerializer.cpp, src/lua/LuaSerializer.h, src/lua/LuaShip.cpp, src/ship/Propulsion.cpp
Fixes #5385.
This PR introduces something I've had sitting in a work branch for several months now: a move towards a composition-based object model rather than a strict inheritance model.
I've added fully-serialized C++ components that can be queried and composed at runtime; other than a need to register a serializer in some sort of centralized fashion the composition functionality is usable at any time by any piece of code without needing to know the concrete type of the body object it is operating on. The ship FixedGuns and Propulsion variables have been migrated to use this new system, although some further work is required to handle querying these components from Lua in a sane manner.
I've also added the ability for Lua to associate arbitrary tables with Body objects as components - …
=> Add BodyComponent system

data/shaders/opengl/grid.frag, data/shaders/opengl/grid.shaderdef, data/shaders/opengl/grid.vert, data/shaders/opengl/gridsphere.frag, data/shaders/opengl/gridsphere.shaderdef, data/shaders/opengl/gridsphere.vert, src/ModelViewer.cpp, src/ModelViewer.h, src/graphics/Drawables.cpp, src/graphics/Drawables.h
They say a picture is worth 1000 words... I've improved the grid rendering in the ModelViewer to support infinite zoom level-of-detail, different grid colors for primary and secondary grid increments, arbitrary line width, and smooth antialiasing. I've also implemented a spherical grid for rendering planetary surface information in the SystemMap.
I'll leave you with these pictures and turn it over to @Gliese852 to use the new grid rendering in the SystemMap:
=> Better Grid Rendering

data/libs/Game.lua, data/libs/utils.lua, data/meta/Body.lua, data/meta/Game.lua, data/meta/Lang.lua, data/meta/StarSystem.lua, data/meta/SystemBody.lua, data/meta/SystemPath.lua, data/meta/Vector.lua, data/meta/_Core.lua, data/pigui/libs/rescale-ui.lua, data/pigui/modules/comms.lua, src/lua/LuaBody.cpp
At the great expense of possibly further reducing the lifetime of my keyboard from all of the furious typing, I've added a significant amount of documentation to the `utils` Lua module and added type information "meta files" for several foundational Lua classes defined in C++.
I've also added a helper `utils.class` function which normalizes the LuaObject constructor paradigm with lua-defined classes for less confusion; and refactored the `utils.take` and `utils.reverse` methods to avoid table copies and properly carry out their function.
The new type-information files live in the `data/meta` directory and are simply specially-formatted Lua files containing function and class prototype declarations marked up with EmmyLua syntax that a lua language server can understand. These files are …
=> Improve Lua documentation, add static type analysis definition files

src/Background.cpp
The background star arrays used for multithreaded starfield generation allocated enough memory for all stars, but did not have their sizes expanded for randomly-generated star points, resulting in those points not being visible and asserts when writing into the array.
This ~~should fix~~ fixes #5387!
=> Fix writing into reserved area of background star arrays

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
This generates a menu when trying to open a new issue, with re-direct links to FAQ,, manual, dev-forum for feature requests, transifex for lanugage contributions.
~I'll admit~, I have ~not~ read the [documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for this fully, but rather lazily copy-pasted from another repo:
- Click "new issue" on [this repo](https://github.com/magit/magit/issues), and you see what I'm aiming for
=> Have fancy bug reporting with redirection to wiki/manual/forum

data/libs/utils.lua, data/meta/_Core.lua, data/pigui/libs/wrappers.lua, data/pigui/views/game.lua, data/pigui/views/tab-view.lua, src/core/Log.cpp, src/lua/LuaManager.cpp, src/lua/LuaUtils.h, src/lua/core/Debug.cpp, src/lua/core/Import.cpp, src/lua/core/Sandbox.cpp
This PR adds a few utility functions to vastly improve the quality of debugging information we're able to collect in the event of a Lua error or crash.
I've added `debug.dumpstack(level)` which performs a verbose trace through the callstack, recursively dumping the contents of parameters and locals in each stack frame to a string. This allows the state of the program at the point of the error to be inspected to attempt to determine what is responsible for the crash, as well as providing a little more context as to what events lead to the crash in question.
The `ui.pcall` utility has been updated to automatically log a stack dump if an error was triggered. A short callstack will still be displayed in the UI where appropriate, but the full stack dump will be written to `output.txt`.
C++ …
=> Improve error reporting and debug printing utilities

data/modules/SearchRescue/SearchRescue.lua
Small changes to the search and rescue mission code which fixes two bugs in the refueling mission.
If the mission requires the player to deliver more hydrogen to the stranded ship than the player has in his cargo hold (e.g. if the players cargo hold is too small to load all needed hydrogen), the player is now able to deliver the hydrogen in multiple passes, i.e., deliver hydrogen, fly back to a space port to get more hydrogen, deliver the additional hydrogen, get more hydrogen if needed, and so on, until finished. 
Before the fix, the stranded ship would only accept 1t of additional hydrogen in the second and every subsequent pass, even though more hydrogen was available. Now all hydrogen in the cargo space is used in every pass.
This fixes #5238.
The second bug was that, if the player …
=> Search and Rescue: fix refueling mission

data/modules/TradeShips/Events.lua, src/ConnectionTicket.h, src/SectorView.cpp, src/SectorView.h, src/SystemView.cpp, src/SystemView.h, src/WorldView.cpp, src/WorldView.h, src/lua/LuaConsole.cpp, src/lua/LuaConsole.h, src/lua/LuaRef.cpp, src/ship/PlayerShipController.cpp, src/ship/PlayerShipController.h
- create a wrapper for `sigc::signal`, automatically disconnected in the destructor
- fix bug in `LuaRef::Unref` causing leaks
- clear the log of tradeships after the end of the game, so that links to ships do not hang in it
=> Some improvements and fixes in data management

src/CargoBody.cpp
=> Fix #5406: broken scoop mission

CMakeLists.txt, COMPILING.txt, src/DateTime.cpp, src/core/Log.cpp, src/core/Log.h, src/scenegraph/DumpVisitor.cpp, src/scenegraph/Loader.cpp, src/scenegraph/Loader.h, src/scenegraph/LoaderDefinitions.h, src/versioningInfo.cpp
Assimp 5.1.0 changed the `mTicksPerSecond` field for Collada animations from `1.0` to `1000.0`, breaking some assumptions made by the Pioneer model loader.
This PR resolves that, enables support for importing GLTF files with animations, and refactors Pioneer's to-console and to-file logging to provide more information about the source of messages and to correctly handle log messages that do not contain a trailing newline (finally!).
NOTE: to avoid having to add significant amounts of extra code to ensure imports function correctly across three major versions of assimp, we now require assimp v5.0.1 or greater as a compile-time and runtime dependency. This should only be an issue on Ubuntu 18.04 LTS, where you will need to find some way to install libassimp5 as it's not present in the …
=> Fix animation import issues with assimp >= 5.1.0

src/lua/LuaInput.cpp, src/lua/LuaPiGui.cpp
Joystick axis values were left in an uninitialized state if a valid axis table was not present, causing undefined behavior. This broke assigning nil to an axis to clear it.
CC @Gliese852.
=> Fix joystick axis reporting invalid joystick value when cleared

CMakeLists.txt, data/pigui/modules/flight-ui/reticule.lua, src/Ship.h, src/ship/PlayerShipController.cpp, src/ship/PlayerShipController.h, src/ship/Propulsion.cpp, src/ship/Propulsion.h
First issue was undefined icon for kill rotation in lua code for the HUD reticule. The result was assertion and killing the HUD permanently.
The second thing was that handling of rotation damping on/off was completely removed with some recent refactoring. I brought it back using logic from 20220203.
=> Fixes #5403 kill rotation killing HUD and bringing back possibility to turn rotation damping off

data/modules/MusicPlayer.lua
Reported on IRC. Just adding one more condition to check on track end.
Please excuse the commit description.
=> Fix MusicPlayer crashing when music ends on sector view while in hyperspace

data/modules/LifeSupport.lua, src/Ship.cpp, src/Ship.h
Variable in C++ was different then the equivalent in lua, then the name from c++ was used in lua. To prevent such mistakes I made them the same.
=> Fix life support

src/DynamicBody.cpp, src/DynamicBody.h
When ship docks with space station on  autopilot it often generates pairs of big torque and force values that mostly cancel each other in normal flight. Problem starts with docking because when the flight state is changed to DOCKING which translates to m_isMoving==false for DynamicBody then the last unprocessed m_torque and m_force are stored. Those unconsumed torque and force values are later processed after undocking sequence completes and ship switches to FLYING state. This often results in catastrophic rotation + linear movement with ship just throwing forward thruster for few  seconds. In many cases it is fatal. I have attached a savegame - those torque and force values are serialized. It can be used for reproducing the result - just load the save and press F5 to undock. You can also …
=> Fix catastrofic rotation after undocking from space station.

src/Ship.cpp
Ship without laser cooler installed ever -> no property laser_cooler_cap ->  Ship::UpdateGunsStats defaults to 1
Buy laser cooler -> lua bumps laser_cooler_cap from non existence to 2
Sell laser cooler -> lua decreases laser_cooler_cap from 2 to 0 -> Ship::UpdateGunsStats sets cooling boost to 0 -> no cooling
I am not sure if what I propose is the proper way to fix it. Maybe all ships should have it's base laser_cooler_cap defined and buying the cooler would bump it up or down from lua. Maybe it should be defaulted in Ship constructor. Maybe it should be defaulted somewhere in lua. What I've done is certainly easiest and I think consistent with original code intent.
=> Fixes #5348 - no gun cooling after selling laser cooler

src/FixedGuns.cpp, src/FixedGuns.h, src/WorldView.cpp
1. Removal of lead calculation for beam weapons. They become deadly!
2. I tried to improve the lead calculation a bit. I have a save file where I have 0 speed relative to a trader ship that is 2.3 km away and unable to hit it because the target is accelerating. Adjustment for target acceleration helps with this.
3. There was this FIXME for doubled lead angle. The problem was that the Fire function was rotating shooting direction that was already rotated giving twice the needed angle..I think. Anyway the additional transformation in the Fire function was unnecessary.
=> Fixes #5360 - lead calculation changes

data/configs/buildings/default.json, data/modules/Debug/DebugShipSpawn.lua, data/modules/Debug/DebugShipSpawn.moon, src/CityOnPlanet.cpp, src/CityOnPlanet.h, src/GameConfig.cpp, src/GeoSphere.cpp, src/Pi.cpp, src/SpaceStation.cpp, src/core/Log.cpp, src/lua/LuaShip.cpp
This PR finally finishes implementing the work that joonicks started a very long time ago. It reworks Pioneer's city generation code to be faster, support more natural and intentional building placement, massively improves the code quality and maintainability, allows many parameters to be data-driven, and fixes several major bugs with city generation.
I've included a sample default configuration, with plenty of comments in the code explaining how the algorithm works and what effect the various inputs in the configuration have on the generated result. Feel free to tweak the config further or add entirely new configuration files - when a city is generated it will pick a random configuration from the `data/configs/buildings/` directory.
The default city configuration creates cities anywhere …
=> Rewritten and Improved City Generation for Spaceports

src/CityOnPlanet.cpp, src/ModManager.cpp
This PR simply improves the mod development workflow slightly, by enabling the game to load mods from filesystem directories in the mods folder as well as zip files. It also fixes an overlooked bug in the city rework that prevented the city definition JSON files from being modded via the .json.patch method.
=> Load mods from directories as well as zip files

data/lang/input-core/en.json, src/Sensors.cpp, src/Sensors.h, src/Ship-AI.cpp, src/Ship.h, src/ShipAICmd.h, src/Space.cpp, src/Space.h, src/ship/PlayerShipController.cpp, src/ship/PlayerShipController.h
There is a target selection key defined in the configuration, but it has no binding.
This is a proposal for implementation for it. It uses target list from Sensors.cpp.
The friend or foe identification is supposed to rely on relations which seem not to be implemented at the moment, I decided that checking if the target has active AI command KILL on the player is a good indication of being hostile. This improvement also turns ship speed lines to red for foes.
The selection works by picking nearest hostile if no combat target is selected. Next key press should select next hostile target according to distance. If the furthest hostile is selected next key press will deselect combat target. So it is more like toggling. It works only within distance used in Sensors so 100km.
**EDIT**
The …
=> Implementation of target selection.

src/Ship.cpp
It is the same issue as with laser cooling booster. When the property was set to 0 after selling the shield energy booster it was not defaulted to 1 as when it was unset in a new ship.
=> fixes #5356 - no shield recharging after selling energy booster

CMakeLists.txt, data/factions/001_Solar_Federation.lua, data/lang/ui-core/en.json, data/libs/SpaceStation.lua, data/meta/Constants.lua, data/pigui/modules/info-view/01-ship-info.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/modules/system-view-ui.lua
Fixes #5343 - missing ship cabin capacity info and space station tech level.
I have only realized that @Web-eWorks is already assigned to this issue when I was about to create the PR, sorry about that..
The change for the ship cabin capacity was quite easy but I need some feedback if it is ok as it is or some rephrasing is needed.
With tech level it was a bit more complicated. Tech level was calculated only when real SpaceStation body was created and is not know in SystemBody objects. SystemBody knows only seed that can be used to calculate the techLevel but it is rather complex operation including RNG.
The lua windows work somewhat surprising to me, their contents are recalculated each time frame. So recalculating tech level of selected body each frame did not seem to be a good idea. So …
=> Fixes #5343  Missing info

data/icons/icons.svg, data/pigui/modules/flight-ui/indicators.lua, data/pigui/themes/default.lua
Draw nav target icon differently for starports that are behind the frame body.
Demo: https://www.youtube.com/watch?v=7KSaPZqU9eA
The math may not hold too well with ground ports on concave-shaped asteroids but it still would be better than not having it at all IMHO.
=> Check spaceport being behind a body while drawing nav target indicator

src/ShipAICmd.cpp
Now this is some funny bug. For some time I thought that the ships spawning in the combat missions were running away from me because I bought this big gun.
The truth is that when a ship gets AI command kill, if it is further then 16 km away it executes first the AICmdFlyTo and this command completes only on specific condition that the ship arrives at a point 15 km in front of target. This condition is almost never fulfilled if the player is actively perusing the hostile ship.
Additionally when the player is closer then 15km to the hostile, it still tries to fly to this point 15 km away from the player. Effectively it looks like it is running, always facing away.
I have attached a save file with a hostile Natrix in front of me. If you load it will be running away, unless you stop and wait …
=> Fix hostiles running away.

data/lang/module-donatetocranks/en.json, data/modules/DonateToCranks/DonateToCranks.lua
Improving immersion in 'Donate to Cranks' by adding some faction info as string variables (faction name and the names of the police and military forces) and some new flavours to make use of them.
I tried to make the string interpolation in just one place but failed at that so it's now done in onCreateBB and onGameStart separately.
=> Donate to Cranks - incorporate info from factions

data/lang/module-stationrefuelling/en.json, data/modules/StationRefuelling/StationRefuelling.lua
Fixing a line that I managed to miss from https://github.com/pioneerspacesim/pioneer/pull/4116
Use 'landing fee' for ground stations and not 'docking fee' when low on cash.
=> Correct message on low cash on landing/docking

data/pigui/modules/flight-ui/indicators.lua
fixes #5448
Turns out when I added the orbital stations into the code I reordered the if conditions in a way I shouldn't have.
(Not all navTarget's have 'path's, but if the navTarget is a station, it and it's parent should both have 'path's.)
@robothauler if you have a save file or you encounter a similar situation, maybe you could try reproducing the error with this correction?
=> Fix HUD disappearing a second time

data/modules/AutoSave/AutoSave.lua, data/modules/TradeShips/Core.lua, src/Pi.cpp
Since the autosave at the end of the game was triggered by the `onGameEnd` event, it was randomly queued among other subscribers to this event. This resulted in (at least) an accidental loss of all TradeShips module data during autosave when exiting the game.
Among other options, I chose to create a separate `onAutoSaveBeforeGameEnds` event, as this seems to me the most straightforward and clear.
Fixes #5427
=> Ensure autosave before the onGameEnd event fires

data/meta/CoreObject/Ship.meta.lua, data/meta/Serializer.lua, data/meta/Timer.lua, src/lua/LuaSerializer.cpp, src/lua/LuaTimer.cpp, src/lua/LuaTimer.h
The first of several PRs being split out from the Scout Mission branch. Don't expect a long shelf-life before merge.
This PR refactors the LuaTimer implementation to use a sorted C++ queue to store a list of "timeouts" rather than walking an unordered Lua table to see if a timer is ready to fire yet. This should improve worst-case per-frame performance of the timer implementation, though it does make the worst-case insertion performance of queuing a new timer `O(log N) + O(N/2)` instead of a classic hashtable insert `O(log N)`. ~~If this does prove to be an issue in the future with many 100s of timers being created each second, another approach might be a sorted intrusive-linked-list.~~ EDIT: that's not an option because of the `O(N)` search time to find an insertion point...
LuaTimer has …
=> Improve LuaTimer performance

data/libs/autoload.lua, data/libs/utils.lua, data/meta/Vector.lua, data/pigui/libs/buttons.lua, data/pigui/libs/forwarded.lua, data/pigui/libs/item-card.lua, data/pigui/libs/ship-equipment.lua, data/pigui/libs/text.lua, data/pigui/libs/wrappers.lua
Another PR split from the Scout Mission branch. Don't expect a long shelf life before merge.
This PR improves the "equipment item card" UI paradigm used in the ship equipment display widget and breaks it out into its own generic `UI.ItemCard` class for any module to use. It also adds a helper to draw a "blank" item card (e.g. an empty item slot), and improves the ability of surrounding elements to layout correctly relative to the space it takes up.
This PR also includes a slightly opinionated change that unifies all "basic tooltips" set with `ui.setTooltip()` to use a consistent font size regardless of the font size active when the tooltip is set. You can override this by using the custom- tooltip facilities as needed, but this change fixes several very glaring paper-cuts with a tooltip …
=> Add ItemCard UI Helper

data/libs/SpaceStation.lua, data/meta/CoreObject/Body.meta.lua, data/meta/CoreObject/Player.meta.lua, data/meta/Engine.lua, data/meta/Rand.lua, data/meta/StarSystem.lua, data/meta/SystemPath.lua, data/modules/Debug/DebugShipSpawn.lua, data/modules/Debug/DebugShipSpawn.moon, data/modules/Scoop/Scoop.lua, src/lua/LuaStarSystem.cpp
Expect a short shelf-life before merge.
This PR adds more type information to Lua autocomplete files, fixes one unreported UI error when pumping fuel in hyperspace, and adds a debug utility to hyperjump to the star selected in the Sector Map. As usual, this debug button is present in the Ship Spawner for lack of a better place to put it right now, and requires the player to be undocked. It ignores maximum range and fuel costs, and can happily hyperjump you directly to Sag A* if you scroll long enough to get there...
This also adds two new attributes to LuaStarSystem to avoid having to generate a potentially expensive Lua table just to query the number of bodies or spacestations in a system.
=> Miscellaneous fixes and improvements

data/shaders/opengl/label.frag, data/shaders/opengl/label.shaderdef, src/Background.cpp, src/Input.cpp, src/Input.h, src/ModelViewer.cpp, src/ModelViewer.h, src/Pi.cpp, src/Pi.h, src/Quaternion.h, src/core/Application.cpp, src/core/Application.h, src/core/TaskGraph.h, src/matrix3x3.h, src/scenegraph/Label3D.cpp, src/scenegraph/Loader.cpp, src/scenegraph/Loader.h, src/scenegraph/Parser.cpp, src/sound/Sound.cpp, src/vector3.h
This PR is a general catch-all of various "engine" changes I've made over the last 5 months or so.
The headlining feature is an improved shader for the Label3D model node. I've added anti-aliasing to the SDF font rendering to avoid the persistent jagged edges that showed up even with MSAA enabled. This is most visible on ships as their ID number.
I've also made a change to flush the renderer's command buffer "early" before the UI is drawn, to avoid crashes caused by a resource in the command buffer being deleted by model code. This isn't a perfect solution, but it gets the crashes out of the way for now without costing much (if any) performance.
This PR also includes a new "hierarchy" tab for the ModelViewer, which shows the computed node structure of the loaded model. It's not 100% …
=> Improve label rendering, fix crash when changing model flags

data/pigui/libs/text.lua, data/pigui/modules/flight-ui/system-overview.lua, src/lua/LuaInput.cpp
Fixes #5457. Fixes #5463.
This PR introduces a new `Input.GetMouseCaptured()` method, which is a more general-purpose accessor than `Player:GetMouseActive()`. This allows it to be used in map screens, etc. which capture the mouse when dragging buttons, as well as when piloting the ship.
=> Fix error setting tooltip in main menu, fix error in hyperspace

data/pigui/libs/buttons.lua, data/pigui/libs/commodity-market.lua, data/pigui/libs/face.lua, data/pigui/libs/ship-equipment.lua, data/pigui/libs/text-table.lua, data/pigui/libs/text.lua, data/pigui/modules/comms.lua, data/pigui/modules/info-view/02-personal-info.lua, data/pigui/modules/info-view/03-econ-trade.lua, data/pigui/modules/info-view/04-missions.lua, data/pigui/modules/info-view/05-crew.lua, data/pigui/modules/info-view/06-flightlog.lua, data/pigui/modules/sidebar/cargo.lua, data/pigui/modules/station-view/01-lobby.lua, data/pigui/modules/station-view/02-bulletinBoard.lua, data/pigui/modules/station-view/03-commodityMarket.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/modules/station-view/06-shipRepairs.lua, data/pigui/modules/station-view/07-police.lua, data/pigui/views/game.lua, src/lua/LuaPiGui.cpp
This PR is technically still a bugfix!
This fixes several issues related to font sizing and consistency of font choices in the info and station screens, fixes an overlap between the ScanManager window and the cargo widget, as well as fixing an issue where the comms log did not scale with the rest of the UI, resulting in incredibly tiny comms messages on 4k screens.
I've made a few opinionated changes to UI element layout to fix minor issues and improve readability, like in the Ship Market screen.
I've generally brought the UI elements in line to use the semantic font size breakpoints I've been gradually introducing over the last year - now there are 'details', 'body', 'heading' and 'title' sizes for both Pionillium and Orbiteer, with the various screen code using those breakpoints as …
=> Font Consistency and Other Bit-Twiddling

data/pigui/modules/saveloadgame.lua, src/FileSystem.cpp, src/Input.h, src/Pi.cpp, src/Pi.h, src/lua/LuaDev.cpp, src/lua/LuaTimer.cpp
- Fix an issue where hovering over a save with a ship not present in the game files (new, deleted, or modded) would cause a lua error in the menu.
- Fix the "mouse capture bug" in all of the map screens (caused by incorrect return type of `input->GetMouseButtonState`).
- Fix an assert that was triggering in debug builds for some time, replaced with a conditional branch to handle the assert case.
- Fix a stack overflow inadvertently introduced when I reworked LuaTimer. Fixes #5473.
=> More crash fixes!

src/SpaceStationType.cpp
The bay index assigned to pads was dependent on order of tags in the model file, which can vary depending on the exporter used to generate the model. This caused a mismatch between what was displayed on the UI and which tag was used as the 'landing location'. Instead, the bay index is now determined (correctly) from the `_bNN` portion of the tag name.
Fixes #5408.
=> Fix station pads being assigned wrong bay indicies

.github/workflows/build-ci.yml, .github/workflows/clang-format.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.1.0
> - Use @actions/core `saveState` and `getState`
> - Add `github-server-url` input
>
> ## v3.0.2
> - Add input `set-safe-directory`
>
> ## v3.0.1
> - Fixed an issue where checkout failed to run in container jobs due to the new git setting `safe.directory`
> - Bumped various npm package versions
>
> ## v3.0.0
>
> - Update to node 16
Still using v2 of `actions/checkout` will generate some warning like in this run: https://github.com/pioneerspacesim/pioneer/actions/runs/3992876243
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more …
=> Update actions/checkout in GitHub Actions workflows to v3

data/economy/commodities/high_tech.json, data/economy/commodities/industrial.json, data/lang/ui-core/en.json, data/libs/Economy.lua, data/libs/SpaceStation.lua, data/libs/utils.lua, data/meta/SystemBody.lua, data/modules/Debug/DebugCommodityPrices.lua, data/modules/NewsEventCommodity/NewsEventCommodity.lua, data/pigui/libs/commodity-market.lua, data/pigui/modules/flight-ui/system-overview.lua, data/pigui/modules/system-econ-view.lua, data/pigui/modules/system-overview-window.lua, data/pigui/modules/system-view-ui.lua, data/pigui/views/mainmenu.lua, data/pigui/views/map-sector-view.lua, src/galaxy/StarSystemGenerator.cpp, src/galaxy/SystemBody.h, src/lua/LuaEconomy.cpp, src/lua/LuaPiGui.cpp, src/lua/LuaStarSystem.cpp, src/lua/LuaSystemBody.cpp
...Feature freeze can't catch me if I type fast enough!
In all seriousness, this is a down-to-the-wire PR delayed by a round of sickness and a PC rebuild, but one that may prove to be one of the bigger features of the patch. This PR completely rebalances the economic system of Pioneer, providing a (perhaps too generous) 40-50% profit margin for savvy pilots who can sniff out the perfect pair of systems and stations to trade between - but punishes traders who get too complacent with seriously diminishing returns for running the same route too often.
The headlining feature of this PR is of course the "dynamic" economy for stations - we now have a proper supply-and-demand economic system where each station has its own set of commodities produced and consumed (and associated quantities for …
=> Dynamic Station Economies

.github/workflows/build-ci.yml
Updates the `actions/upload-artifact` action used in the GitHub Actions workflow to its newest major version.
Changes in [actions/upload-artifact](https://github.com/actions/upload-artifact):
> ## v3.1.2
> Update all `@actions/*` NPM packages to their latest versions
> Update all dev dependencies to their most recent versions
>
> ## v3.1.1
> - Update actions/core package to latest version to remove `set-output` deprecation warning
>
> ## v3.1.0
> - Bump @actions/artifact to v1.1.0
>   - Adds checksum headers on artifact upload
>
> ## v3.0.0
>
> - Update default runtime to node16
> - Update package-lock.json file version to 2
Still using v2 of `actions/upload-artifact` will generate some warning like in this run: https://github.com/pioneerspacesim/pioneer/actions/runs/4018749627
> Node.js …
=> Update actions/upload-artifact in GitHub Actions workflows to v3

src/FileSystem.h, src/GasGiantJobs.h, src/collider/GeomTree.cpp, src/lua/LuaRef.cpp, src/lua/LuaRef.h, src/scenegraph/Model.cpp, src/ship/ShipViewController.cpp, src/text/DistanceFieldFont.cpp, src/text/DistanceFieldFont.h, src/utils.h
I've run AddressSanitizer, LeakSanitizer, and ThreadSanitizer on the code (as well as a brief pass with Valgrind) to clean up any possible issues or errors that might have been introduced without notice.
This PR fixes, in total:
- 1 read-past-end bug (in DistanceFieldFont.cpp)
- 2 uninitialized variable accesses (in scenegraph/Model.cpp and ship/ShipViewController.cpp)
- 3 memory leaks, of varying severity between a few hundred bytes and 600kb
=> Fix uninitialized variables, memory leaks

data/libs/Economy.lua, data/libs/FlightLog.lua, data/modules/AutoSave/AutoSave.lua, data/modules/Scout/ScanManager.lua, data/pigui/modules/autopilot-window.lua, data/pigui/modules/ship-internals-window.lua, data/pigui/modules/station-view/01-lobby.lua, data/pigui/modules/system-view-ui.lua, data/ships/bowfin.json, src/GeoPatch.cpp, src/GeoPatch.h, src/GeoPatchJobs.h
Unsure how much more bugfixing will be finished before Pioneer Day, so have an early batch. I'll try to get to the other reported issues with the Scout Mission etc.
- Fixes #5420: the global version attribute was being reset on game end, causing invalid data to be saved. The entire flight history log was discarded on load.
- Fixes #5458: added a separate button state for "autopilot control". Not using a separate language string due to time reasons.
- Fixes: #5479: this was caused by order of autosave handler relative to other `onShipDocked` handlers. I've deferred autosave by one frame to ensure all handlers run before saving.
- Fixes: #4123: autosave is now made before undocking, rather than after.
- Fixes #5470: this was caused by the autosave running before BBS / markets are generated …
=> Fixes, bowfin update, terrain rendering fixes

data/libs/Equipment.lua, data/libs/Ship.lua, data/pigui/modules/info-view/02-personal-info.lua, data/pigui/modules/info-view/03-econ-trade.lua, data/pigui/modules/sidebar/cargo.lua, data/pigui/modules/station-view/02-bulletinBoard.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/modules/system-econ-view.lua, data/pigui/views/mainmenu.lua, data/ships/skipjack.json, src/lua/LuaBody.cpp, src/lua/LuaPlayer.cpp, src/ship/PlayerShipController.cpp
Fixes #5512, by refreshing the BBS if the player tries to click on a negative-time ad. A more in-depth fix will need to be deferred to the next patch.
Fixes #5511, prevents an erroneous overwrite of the CrewRoster table on game start. Also generates enough crew to take off with the starting ship, in case we or others setup a start with a ship requiring multiple crew members.
Fixes #5508, displays orbital distance relative to sea-level-radius of the body rather than body's surface. Provides a true "distance to surface" display.
Fixes #5521, increase Skipjack sensor slots to 3 to make it an "exploration" themed medium courier.
This PR also adjusts the parameters of the expensive orbital scanner to provide a generally faster scan rate than a cheap scanner, and make it a little bit more …
=> Fix small errors, adjust orbitscanner balance

data/lang/module-combat/en.json, data/modules/Combat/Combat.lua
Reduce confusion by always indicating that the target area has been reached.
Closes #5499
=> Show info when the target area is reached

win32/vs2019/pioneer.vcxproj, win32/vs2019/pioneer.vcxproj.filters
Updates VS2019 for the changes in #5460 adding the nanosockets and headtracker files
Whether or not VS2019 is kept around it is now up to date.
Tested all profiles build
FAO @Web-eWorks
=> Update VS2019 for nanosockets and head tracking

data/modules/SearchRescue/SearchRescue.lua
Possible some other mission types missing this?
=> Add "set hyper target button" to SAR mission

data/lang/ui-core/en.json
Removing dead strings in ui-core.
These strings exists only in the lang files and most of them also don't have any reference to them on searching the Pioneer GitHub site. Some exempts below:
Reference to the last action involving the "Arms of the Milky Way " strings: https://github.com/pioneerspacesim/pioneer/issues/3583
`COMPACT_RADAR` removed here: 04195598386c873a9468a668d3fe0a8b44f7d84f
=> Remove dead links in ui-core

data/pigui/modules/flight-ui/indicators.lua, src/ShipAICmd.cpp, src/ShipAICmd.h, src/lua/LuaSpace.cpp, src/ship/Propulsion.cpp
I have been trying to fix autopilot crashing into planets/stars and some cases of overshoots. This is the result of my work so far.
Those saves are two examples of situations when autopilot crashes the ship that are now avoidable:
[testPlanet.gz](https://github.com/pioneerspacesim/pioneer/files/10468907/testPlanet.gz)
[testStar.gz](https://github.com/pioneerspacesim/pioneer/files/10468908/testStar.gz)
The main change is moving the CheckSuicide function call that detects the potential crash to AICmdFlyTo instead of AICmdFlyAround. I have changed the calculations in this function as well as the recovery action taken by the autopilot.
Previously in any dangerous situation the recovery was putting rear of the ship in direction of center of the planet and try to accelerate on main thruster …
=> Autopilot tweaks

.github/ISSUE_TEMPLATE/config.yml, .github/contributing.md, Quickstart.txt, README.md, doxygen/mainpage.dox, metadata/net.pioneerspacesim.Pioneer.appdata.xml, src/lua/LuaServerAgent.cpp, src/scenegraph/Model.h
Wiki has moved, we're deprecating old URL.
I've changed some of the wiki links to point to the https://dev.pioneerspacesim.net/ dev docs.
The link in src/scenegraph/Model.h points to a removed wiki page (New Model), I've pointed it to [model system](https://wiki.pioneerspacesim.net/wiki/Model_system) instead. (Is that right?)
=> Update all links to the wiki, to point to new (sub)domain

src/lua/LuaTable.h
This PR provides typedefs suitable for `std::iterator_traits` in lieu of using the deprecated `std::iterator` class (which only provided those typedefs anyways).
CC @laarmen.
=> Update LuaTable for deprecated std::iterator

src/lua/LuaPushPull.h
- Convert to fixed width types, which work the same way on 32 and 64 bit archs and cover all variable width types such as int and size_t
- Replace deprecated luaL_checkunsigned with luaL_checkinteger
Fixes #5527
=> Convert integer pi_lua_generic_{push,pull} to fixed width types

src/Ship.cpp
Autopilot objects can store dangling pointers to bodies from the previous system. After arriving to a new system, this may lead to a crash.
Fixes #5242
Fixes #5258
Fixes #5443 
Fixes #5554
4 issues with 1 line! Yay!
=> Clear autopilot before hyperjumping

src/core/Property.cpp
Flatpak and Fedora packages are built with this flag, and it was causing a crash on save. Also [encountered by manolollr](https://github.com/pioneerspacesim/pioneer/issues/5387#issuecomment-1172784841) in #5387.
=> Fix out-of-bounds index uncovered by -D_GLIBCXX_ASSERTIONS

data/libs/Equipment.lua
In Frontier, military drives had roughly half the mass of standard drives. Fixes #5576.
| CLASS | REGULAR |   MIL (old) |   MIL (new) |
|-------|---------|-------|-------|
|     1 |       2 |     3 |     1 |
|     2 |       6 |     7 |     3 |
|     3 |      11 |    12 |     5 |
|     4 |      25 |    28 |    13 |
|     5 |      60 |    63 |    29|
|     6 |     130 |   128 |    60 |
|     7 |     245 |   196 |   135 |
|     8 |     360 |   285 |   190 |
|     9 |     540 |   400 |   260 |
I pulled the exact numbers from my hatt. If anyone has any suggestions for a better way, I'm all ears.
I think the idea is with a small ship you should be able to go roughly one hyper class higher, by choosing military drives.
=> Make military drives have lower mass than their regular counterpart

src/ShipAICmd.cpp
Approximately once every one and a half in-game years (for the Sol system), the following state may occur:
- some ship is directed towards the planet
- it has AICmdFlyTo command active
- its target is on course
- gravity, respectively, is directed along the the ship, and accelerates it
- its reverse thrusters are _weaker than gravity_
- it has zero speed
The combination of these circumstances leads to the fact that both coefficients in the calculation of the head vector are equal to 0. A vector of zero length is passed to Propulsion, where it is normalized and SIGFPE occurs.
Fixes #5516
It would be nice to do a thorough reworking of the autopilot here. For example, to ban ships from flying and stopping with their nose down in gravity, it looks strange. @azieba you worked next to this code …
=> Prevent zero length direction vector

data/pigui/modules/station-view/02-bulletinBoard.lua
Include ad title in search on the bulletin board.
Motivation: I just found it more practical/correct after interpreting an earlier search result as a wee bit odd.
=> Include ad title in bulletin board search

data/lang/equipment-core/en.json, data/libs/Equipment.lua, data/pigui/modules/equipment.lua
Implement hover over messages for the ECM and ECM Advanced.
* The message is just `Electronic countermeassure` and `Advanced electronic countermeassure`. This harmonizes with the messages for the missiles above which just state the missile types.
* The hover over message for the missiles capitalize the first letters on all words and this PR doesn't. Which one is preferred?
Fixes https://github.com/pioneerspacesim/pioneer/issues/5215
=> Mouseover messages for the ECM and the Advanced ECM systems

src/Player.cpp, src/Player.h
So the reason this squeaky metal sound has been mistriggering was _probably_ (keyword: probably) that I used GetLastForce() which includes the gravity force, which is a body force and shouldn't be added to the metal strain calculation. Also I got rid of the array of 20 last jerk values because that was a safeguard against single-frame thruster spikes of the autopilot and flight assist. Now that we only use atmospheric acceleration, it should no longer be needed.
In addition, I made the triggering acceleration limits quite higher and the volume lower.
Needs playtesting and a sanity check from someone other than me.
=> Fix + nerf metal creaking sfx

src/lua/LuaConsole.cpp
Fixes https://github.com/pioneerspacesim/pioneer/issues/5287, fixes #5598.
Escaping out of the Lua console on keypress created issues since the key was then released in another window and escape key release action performed. Fixed by exiting Lua console on escape key release instead of press.
=> Fix issue on quitting Lua console

src/Lang.cpp, src/Lang.h, src/LangStrings.inc.h, src/Pi.cpp, src/lua/LuaLang.cpp
Refactor the C++-side Lang:: APIs to be more efficient with less string copies.
This is a minor prerequisite change for my editor branch and will be merged quickly.
=> Use std::string_view for C++ Lang handling

src/Pi.cpp, src/ship/PlayerShipController.cpp, src/ship/ShipController.cpp
Clang 15+ / GCC 13+ leave us no choice but to disable floating point exceptions. Their auto-vectorization optimizations load invalid values and will cause FPEs even when fp-strict is enabled.
Reference #5601.
@d3rp please confirm this PR fixes the issue on GCC 13.
=> Disable runtime floating point exceptions

data/pigui/modules/new-game-window/widgets.lua, src/Game.cpp, src/Game.h, src/SectorView.cpp, src/Space.cpp
Fixes those problems:
https://github.com/pioneerspacesim/pioneer/pull/5561#issuecomment-1693207911 - segfault on load savegame
https://github.com/pioneerspacesim/pioneer/pull/5561#issuecomment-1693800474 - name and money overlap
There are also explanations in the commit messages.
The first commit is not really needed to fix these problems, but I think it would be better if we see a load error on a failed load rather than a segfault.
=> Some fixes after sector map refactoring and new start menu added

CMakeLists.txt, Modelviewer.txt, scripts/build-travis.sh, src/ModelViewer.cpp, src/ModelViewer.h, src/Pi.cpp, src/Pi.h, src/core/Application.cpp, src/core/Application.h, src/core/GuiApplication.cpp, src/core/GuiApplication.h, src/editor/CMakeLists.txt, src/editor/EditorApp.cpp, src/editor/EditorApp.h, src/editor/EditorDraw.cpp, src/editor/EditorDraw.h, src/editor/EditorWindow.cpp, src/editor/EditorWindow.h, src/editor/ModelViewer.cpp, src/editor/ModelViewer.h, src/editor/UndoStepType.h, src/editor/UndoSystem.cpp, src/editor/UndoSystem.h, src/editor/ViewportWindow.cpp, src/editor/ViewportWindow.h, src/editor/editormain.cpp, src/lua/LuaUtils.h, src/lua/core/Sandbox.cpp, src/main.cpp
This pull request adds the basic foundations to support an editor / mod tools pipeline for Pioneer. A new editor binary contains the modelviewer, and provides a framework for common editor paradigms. A fully-functional undo system is provided, as well as various helpers for rendering edit interfaces for various property types.
On its own, this PR does little but change the invocation of the modelviewer from `pioneer -mv` to `editor -mv`, but sets the foundation for several branches that will be landing soon which improve the content creation experience for Pioneer, the most notable of which is the new System Editor tool.
**TODO:**
=> Editor Binary and Prerequisites

AUTHORS.txt, contrib/portable-file-dialogs/pfd.h, data/libs/autoload.lua, src/Background.cpp, src/Background.h, src/FileSystem.h, src/Intro.cpp, src/ModManager.cpp, src/ModManager.h, src/NavLights.cpp, src/Pi.cpp, src/Space.cpp, src/SystemView.cpp, src/SystemView.h, src/core/StringUtils.cpp, src/core/StringUtils.h, src/editor/EditorApp.cpp, src/lua/Lua.cpp, src/main.cpp
Catchall PR with useful commits not directly related to the System Editor coming out of that branch.
In brief:
- Cleanup `Background::StarField` so it actually does what it says on the tin.
- Expand `ModManager` functionality to allow querying and disabling mods.
- Added Portable File Dialogs for editor usage, has a very nice API to wrap what is otherwise a horrible platform-specific mess.
- Migrate `autoload.lua` into the "minimal" Lua state configuration (for LuaNameGen and other lightweight Lua utilities to run outside of the main Lua state).
- Replace (most of) our various string-splitting helper functions with a generic interface to iterate string fragments and collate them into a vector-like container.
- There are several hand-written re-implementations of the same functionality …
=> Expand ModManager, add System Editor prerequisites

src/Input.cpp
Some mice (like mine) have an x and y axis on the wheel.
Ignore mouse wheel events that are x-axis only (so therefore have a y-axis value of zero).  The behavior of my (Microsoft) mouse is that pushing left and right on the wheel repeatedly call mouse wheel y events as long as it's held.  We were interpreting these as always being mouse wheel down events, causing my clumsy fingers on the mouse wheel to zoom very quickly out in the third person ship view, sector view and so forth.
=> Ignore x-axis only mouse wheel events

data/pigui/modules/station-view/01-lobby.lua
Fixes #5585
The problem was with this line in `refuelInternalTank` in `data/pigui/modules/station-view/01-lobby.lua`:
`station:AddCommodityStock(Commodities.hydrogen, -math.ceil(mass))`
`math.ceil` is rounding number up, so if this number is negative(ex. -2.3) it will be rounded to -2 because it is nearest value that greater or equal to -2.3. So the solution is to change above mentioned line to:
`local commodityChangeAmount = mass < 0 and math.floor(mass) or math.ceil(mass)
station:AddCommodityStock(Commodities.hydrogen, commodityChangeAmount)`
[Accepted answer by Guffa(albeit it's for javascript, but works the same way)](https://stackoverflow.com/questions/26335076/math-ceil-not-working-with-negative-floats)
=> Fix for -10% and +10% buttons in station's lobby

data/modules/FuelScoop.lua, src/Ship.cpp, src/Ship.h
Fuel scooping was:
1) based on random numbers
2) not aware of time acceleration
3) inefficient if rate was too high (which is still unlikely to happen without time acceleration)
4) not working properly (see https://github.com/pioneerspacesim/pioneer/issues/5237)
Instead of this, I suggest:
1) accumulate hydrogen at rate based on speed and pressure
2) replace strict speed/pressure requirement (I think it's likely being able to scoop even at sparse atmospheres even when flying fast enough)
=> Fuel scooping rework

data/libs/SpaceStation.lua
Fixes #5582 
This happened, because `transientMarket` in `SpaceStation.lua` was never linked to `stationMarket` in `Economy.lua` after loading the save. Adding `createCommodityStock(station)` in loop `for station,list in pairs(loaded_data.shipsOnSale) do` in the `onGameStart` event will make sure to do that for every station player has visited in the system.
**Update**
Changed to a more clean-looking solution.
=> Fix for commodity market in stock and demand reset

src/ShipCockpit.cpp
Fixes #5621
This happened, because there was no check in this statement in `void ShipCockpit::Update(const Player *player, float timeStep)`: 
`if (m_icc == nullptr)`,
if current `CameraController` is really `InternalCameraController`. Because of that, this statement in `inline void ShipCockpit::resetInternalCameraController()`:
`m_icc = static_cast<InternalCameraController *>(Pi::game->GetWorldView()->shipView->GetCameraController());`,
would cast current `CameraController` to invalid type if it was not `InternalCameraController`, which is undefined behaviour.
Added check at the start of `Update` if current view is exterior to ensure that current `CameraController` is really `InternalCameraController`.
=> Fix for glued cockpit

data/lang/ui-core/en.json, data/pigui/libs/text.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/themes/default.lua
When you are in the ship market we now color the different specifications and have an indicator arrow next to them to show if the ship being viewed is an improvement or not over the current one:
=> Compare specs of your current ship to those in the ship market and highlight changes

data/libs/CargoManager.lua, data/modules/Scout/ScanDisplay.lua, data/modules/Scout/ScanManager.lua, src/Game.cpp, src/Ship.cpp, src/Space.cpp
**UPDATE**
As suggested by @Web-eWorks, first solution changed to wrap `totalCargo` and `usedCargo` around this check (ex. for `totalCargo`) in `function CargoManager:Constructor(ship)`:
```
if not self.ship:hasprop("totalCargo") then
ship:setprop("totalCargo", self:GetTotalSpace())
end
```
so this properties will not be reinitialized by `CargoManager`'s constructor, because after saving the game, this properties will be already stored in the ship and will be unserialized during loading the game.
`self.ship:UpdateEquipStats()` was not needed since it's called internally from C++.
While testing more, another bug was found, `maxHyperspaceRange` wasn't properly initialized after loading the game.
This happened, because in this line in `void Ship::UpdateLuaStats()`:
```
if (hyperclass) { …
```
=> ScanManager improvements and ship properties fixes

data/pigui/modules/info-view/05-crew.lua
The wording of the commands `Dock at current target` and `Destroy enemy ship` has been changed. They will immediately display `There is nobody else on board able to fly this ship` when there is only a commander on board.
=> Wording change for commands in the "Crew Roster" window

data/pigui/views/mainmenu.lua
Fix for when menu music not started to play after exiting back to main menu.
**Update**: moved `MusicPlayer.playRandomSongFromCategory("menu", true)` from `if else` check.
=> Fix main menu music not starting to play after exiting back to main menu

data/pigui/libs/face.lua, data/pigui/views/tab-view.lua
Added "NoScrollWithMouse" flag for tab-view (personal info and comms upper left corner buttons) and character info (char name, occupation and char's face) so now they can't be scrolled with mouse.
**Edit**: disables this behaviour:
https://github.com/pioneerspacesim/pioneer/assets/69468517/3a678c0b-cdfc-4055-b348-c890b8a61372
=> Disable scrolling for tab-view and character info

data/pigui/modules/settings-window.lua, data/pigui/views/game.lua
The pause menu now sets the last time acceleration that was before it was opened. Its behavior will be the same as when setting up time acceleration without pressing `CTRL`.
Changed behaviour of `Close` button in `settings-window.lua`. Now it will not set time acceleration and not enable input bindings.
**Edit**:
https://github.com/pioneerspacesim/pioneer/assets/69468517/c89d445d-5624-4e12-8cb7-5e4e5421308b
**Update**: deleted bit about forcing time acceleration through `Ctrl+Click` `Close` button.
**Update2**: deleted `settingsMenuWasOpened`. It was not needed.
=> Pause menu sets last time acceleration after closing

src/graphics/opengl/RenderTargetGL.cpp, src/pigui/PerfInfo.cpp
=> Calm down -Werror=return-type

data/pigui/modules/settings-window.lua, data/pigui/views/game.lua
**Changes**:
1. Queuing of events `onPauseMenuOpen`/`onPauseMenuClosed` is moved to `ui.optionsWindow:open()` and `ui.optionsWindow:close()` respectively. This was made to ensure queuing of this events no matter where this window was opened or closed;
2. Added `ui.optionsWindow:changeState()` method to group `ui.optionsWindow:open()` and `ui.optionsWindow:close()` into one;
3. Temporarily moved `Input.EnableBindings(false)` from `onPauseMenuOpen`, because when the game is paused, lua events are not processed. Because of this, game will still read input bindings if pause menu was opened, while time acceleration was `paused`. This fixes it.
**Bonus**:
Save button will be blocked if player is hyperspacing.
**Update**: formatting correction, removed two tabs on an empty line in …
=> Update for pause menu

src/Game.cpp, src/Space.cpp, src/Space.h
Fix the undefined behaviour when addiing bodies during the update loops that iterate through them
The undefined behaviour comes because when we add an item to the vector, it could have to reallocate to grow the backing storage and therefore the end iterator becomes potentially invalid.
Defer adding bodies until the end of an Space update tick.
A few game related scenarios (emerging from hyperspace, saving a game and loading a game) require this update to be invoked too.
I've been playing with this locally for a while and have yet to find any new issues.
=> Space bodies deferred addition

data/pigui/modules/system-view-ui.lua, src/editor/system/GalaxyEditAPI.cpp
In the System Editor the surface gravity is presented as acceleration  m/s^2.
* Compute value of 'g' as is done in [system-view-ui.lua](https://github.com/pioneerspacesim/pioneer/blob/23b6700a16a788ced5ae7ea11283489e05cfcd0d/data/pigui/modules/system-view-ui.lua#L810)
* Format change - add space between value and 'g'.
* Add the last decimal of standard gravity to it's full 9.80665.
=> Compute value of g-force in system editor

src/galaxy/SystemBody.cpp
surfaceGravity_g is implicitly divided by and explicitly multiplied by.
Remove it from both numerator and denominator.
L = g/H (specific heat)
gM/RL = gM/R(g/H) = gMH/Rg = MH/R
=> Simplify SystemBody::GetAtmPressure

data/libs/Ship.lua, data/meta/CoreObject/Body.meta.lua, src/Body.cpp, src/Body.h, src/enum_table.cpp, src/enum_table.h, src/lua/LuaBody.cpp, src/lua/LuaPlayer.cpp, src/lua/LuaShip.cpp
**Update**:
Rewrite of `GetAltitudeRelTo`:
1. This function is moved to body class to support this functionality in C++ code;
2. This function is used in the LUA version of `GetAltitudeRelTo`, `GetGroundPosition` and `GetGPS` for consistency in calculating altitudes;
3. This function supports the choice of which height to calculate (sea-level, above-ground).
Other change:
`GetGPS` is moved to `LuaShip.cpp` to support this function for other ships, not only the player.
Fixes for this issues:
1. `GetAltitudeRelTo` using player pos no matter what first argument is passed;
2. `GetGroundPosition` returns nil when not in the rotating frame of ref;
3. `GetGPS` sometimes return different height than `GetAltitudeRelTo`;
4. Access violation when trying to access `frameBody`, `frameRotation` and …
=> Fixes and changes for functions in LuaBody/Player/Ship

data/meta/Constants.lua, data/meta/FileSystem.lua, data/modules/AutoSave/AutoSave.lua, data/pigui/modules/saveloadgame.lua, src/enum_table.cpp, src/enum_table.h, src/lua/LuaFileSystem.cpp, src/lua/LuaFileSystem.h, src/lua/core/Sandbox.cpp
I'd like to be able to use lua standard `io` functionality as it's familiar to people who know lua and also easy to find examples and documentation on - and we don't have to build our own version.
However, this needs to be carefully sandboxed so we don't allow scripts and mods to run wild on a users machine.
So this will look to add the `io` module but redact and modify it as appropriate to keep it safe.
Keeping it safe means only allowing access to the user and data folders and the data folder can only have read only access.
Remaining todo list (at the time of writing):
- Unify and standardize the filenames across the API to accept a uri-style schema so you prefix a path with either `user://` or `data://` to indicate where you want to work.
- Do all FileSystem implementation in C++ …
=> Lua io and FileSystem uri changes

src/Sfx.cpp
Fix for this error, because `Sfx::Sfx(const Json &jsonObj)` was trying to get `pos` and `vel` keys from passed `jsonObj` itself, when it should get it from `jsonObj[sfx]` object.
This happened randomly when loading the save.
=> Fix assertion failed in Sfx::Sfx(const Json &jsonObj)

src/perlin.cpp
For fun yesterday, I ported FastNoise2's Simplex Noise implementation as a competitor to our Simplex `noise()` function taking advantage of SIMD operations. Unfortunately, the overhead required for a SIMD-capable version of the Simplex algorithm almost outweighs the benefit of calculating an additional double-precision noise value per function call.
As part of that work, I found an alternate way to express the truth table in our `noise()` implementation that replaces the complicated if-block with a series of bit operations. This caused our current noise function to be almost as fast as the SIMD version of the algorithm, mostly due to the significantly fewer operations involved in computing the Simplex gradient terms in our existing version.
On my machine, compiling for SSE2, this provides …
=> Improve Simplex Noise Performance

.github/actions/upload-linux/action.yml, .github/workflows/build-ci.yml, CMakeLists.txt, scripts/CMakeBuildPresetsCI.json, scripts/build-release.sh, scripts/package-release.sh
This PR does a wee refactor of our Linux build scripts to ensure we're correctly generating and uploading release artifacts. It moves the release generation steps into a reusable action file, which is important for the other half of the PR.
This PR enables SSE4.2 support by default for our Linux x64 build type. SSE4.2 has been available and supported in mainstream x86/64 processors for over a decade now, so it makes sense to formally require SSE >= 4.2 for our builds (and allow the compiler to perform automatic optimization and vectorization to take advantage of these instruction sets).
GCC's documentation doesn't specify whether I need to manually add all of the SSE version flags or if `-msse4.2` implies previous SSE versions. If someone is more familiar with the semantics GCC provides …
=> Build with SSE4 / AVX, fix build artifact generation

.github/workflows/build-ci.yml, .github/workflows/clang-format.yml, CMakePresets.json, src/editor/ModelViewerWidget.cpp, src/editor/ModelViewerWidget.h
This PR refactors some of our CI build scripts and CMake tooling files to support using the `Ninja` generator on Linux instead of Make, which allows us to automatically invoke parallel builds everywhere including our CI runners.
As a result, the CI build should be able to take advantage of all vCores provided to the execution environment, leading to a hopeful build time improvement.
I've also fixed the `clang-format` CI failures by upgrading the runner to a version that provides a newer `clang-format` binary - we were stuck on v11 for CI while developers are on significantly newer versions (my system has v16) and the config files are *not* backwards compatible or well-versioned at all.
For compatibility with VSCode, I've bumped the `CMakePresets.json` version number to v3 - this requires …
=> Improve CI Setup and Performance

src/Aabb.h, src/Frame.cpp, src/Frame.h, src/collider/BVHTree.cpp, src/collider/BVHTree.h, src/collider/CollisionSpace.cpp, src/collider/CollisionSpace.h, src/collider/Geom.cpp, src/collider/Geom.h, src/core/macros.h, src/graphics/Drawables.cpp, src/graphics/Drawables.h, src/scenegraph/Model.cpp, src/vector3.h
This PR refactors our CollisionSpace broadphase collision acceleration structure to be significantly more efficient. With no intersections (the usual case for the root frame of a system), the broadphase queries run approximately 3.5x to 4x faster.
I no longer have the performance numbers for this branch due to how many intervening PRs I've needed to merge, but the broadphase cost wasn't a significant performance sink to start with (on the order of 0.3-0.5ms / frame in the Sol system) so don't expect a huge FPS boost - this is mostly attacking low-hanging fruit which would have been a greater problem further down the line.
I've not yet tried to apply this optimization to our narrow-phase BVHTree implementation - I have a different idea which involves using single-precision floats and …
=> Improve BVH Broadphase Performance

src/Space.cpp, src/lua/LuaSerializer.cpp
Fixes #5653
Fix for the issue when objects which are not in space were corrupted on save, because their `lua` components wasn't saved. 
For this, `m_bodyIndex` vector is used instead of `m_bodies` to not miss any bodies that are currently exists in the game.
Incompatible with old saves.
**Update**: fix index mistmatch between `Json` `bodyArray` and `for` loop in `LuaSerializer::SaveComponents` and `LuaSerializer::LoadComponents` when adding `luaComponents` object, since `for` loop in `LuaSerializer` is starting from one, but values to `bodyArray` is added through `push_back`, so they are starting at zero.
**Update2**: rebase.
**Update3**: `break` in `for` loop in `LuaSerializer::SaveComponents(Json &jsonObj, Space *space)` is changed to `continue`, because if …
=> Fix lua components corruption on save

data/libs/Event.lua, data/libs/autoload.lua, data/meta/_Core.lua, data/pigui/baseui.lua, src/Game.cpp, src/Pi.cpp, src/Ship.cpp, src/lua/Lua.cpp, src/lua/LuaEvent.cpp, src/lua/LuaEvent.h, src/lua/LuaPiGui.cpp, src/lua/LuaPushPull.h, src/lua/LuaTable.h, src/lua/core/Import.cpp, src/pigui/LuaPiGui.cpp, src/pigui/LuaPiGui.h
I had a long description typed out, then Github decided to eat it. As a result you get the short description instead.
This PR adds C++17-based template parameter pack overloads to push multiple values to Lua, refactors our Event module, and adds a separate UI event queue which is updated at all times - even in the menu and while the game is paused.
Hooking into the new queue is easy:
```lua
ui.Events.Register("onGamePaused", function()
print("I've been paused!")
end)
```
You can create your own event queues, too!
```c++
pi_lua_import(l, "Event");
LuaRef eq = LuaTable(l, -1).Call<LuaRef>("New");
// ... make it available to Lua somehow
// Queue events using the familiar LuaEvent API
LuaEvent::Queue(eq, "myShinyEvent", ...);
// Make sure to call _Emit regularly or events won't be processed …
```
=> Refactor Event Queues

src/main.cpp
97828a9ed634b6cb889867e48241df1072e6b810 removed the ability to dump the galaxy data. I needed the data for statistical analysis for balance purposes. Debugging missing global dependencies was quite frustrating, but now we can dump galaxies again.
Note: dumping the galaxy opens and closes a gui window. I am not sure why this happens, but any galaxy dump is better than no galaxy dump.
=> Re-add the galaxy dump function

src/scenegraph/Serializer.h
Amend the Scenegraph serialization interface to more correctly handle the unaligned reads required by the SGM data structure layout. While the unaligned reads are in practice not an issue, this provides some future proofing against future compiler "improvements" (read: backwards compatibility breakages) and means the code is more portable to architectures like ARM64 which have a hardware requirement of aligned reads.
Closes #5687.
=> Avoid misaligned read when loading SGM files

src/graphics/opengl/CommandBufferGL.cpp
By compiling with sanitisers enabled I have detected a number of places where we run into undefined behaviour. The patch for the first is in #5692 (thanks to Web-eWorks). This is a patch for the second issue I detected.
1. `mat->m_pushConstants.get()` is sometimes null.
2. I set a breakpoint in a debugger and it turned out that  `s->GetConstantStorageSize() == 0`
3. [The behaviour of memcpy(dst, src, count) is undefined if either of the pointers is null **even if count == zero**](https://en.cppreference.com/w/cpp/string/byte/memcpy)
Fix: add a null check.
Here is how I compile with sanitisers.
1 Make sure `build/` does not exist (because cmake does not update CXXFLAGS for build directories that have already been populated). Alternatively: build in `build-with-sanitizers/`
2. …
=> Fix undefined behaviour in CommandBufferGL.cpp

data/libs/SpaceStation.lua, data/meta/Space.lua, data/modules/Assassination/Assassination.lua, data/modules/BulkShips.lua, data/modules/Common/ProximityQuery.lua, data/modules/SearchRescue/SearchRescue.lua, data/modules/System/Explore.lua, data/modules/TradeShips/Debug.lua, data/modules/TradeShips/Flow.lua, src/lua/LuaBody.cpp, src/lua/LuaBody.h, src/lua/LuaPiGui.cpp, src/lua/LuaSpace.cpp, src/pigui/LuaFlags.h
Stemming from discussion on IRC, this PR exposes the BodyNearFinder functionality as `Space.GetBodiesNear()`, refactors `Space.GetBodies()` to be significantly more efficient with all current callsites, and provides an initial prototype of a ProximityTest module for the use of mission modules.
All GetBodies* function callsites now pass a classname (the same as would be used with `:isa()`) instead of a filter function. This moves the ObjectType filtering inside of C++ where it can be significantly more efficient than calling a Lua filter function for every object iteration (which internally called back into a C++ accessor function... sigh).
On the topic of efficiency, there is an unimplemented further optimization where we can potentially convert ObjectType into a bitfield to enable O(1) …
=> Add Space.GetBodiesNear(), ProximityQuery module

data/meta/Constants.lua, data/models/stations/orbital_station/station_docking_A.dae, data/models/stations/orbital_station/station_docking_B.dae, src/AnimationCurves.h, src/ModelBody.cpp, src/Player.cpp, src/Player.h, src/Ship.cpp, src/Ship.h, src/ShipAICmd.cpp, src/SpaceStation.cpp, src/SpaceStation.h, src/SpaceStationType.cpp, src/SpaceStationType.h, src/enum_table.cpp, src/enum_table.h, src/matrix4x4.h, src/scenegraph/CollisionGeometry.h, src/scenegraph/Loader.cpp
If you fly in or launch from the orbital station on autopilot - everything works as before, I just improved these animations a little. But if your autopilot is off, you can fly into the station and land manually.
Since the station is rotating, it is recommended to turn on the "Follow orientation" mode, then the ship will compensate for the rotation of the station. Although, you can land completely manually.
In order not to hit anything, when manually starting from the orbital, the "cruise-up" mode is automatically turned on. It seemed to me that it works well in other places too - when launching from a ground station or from the surface - you are slowly ascending at a speed of 2 m/s.
In fact, this is a quite large refactoring of SpaceStation and SpaceStationType, as a result of which it …
=> Docking with orbital in manual mode

data/modules/Assassination/Assassination.lua, data/modules/CargoRun/CargoRun.lua, data/modules/Combat/Combat.lua, data/modules/DeliverPackage/DeliverPackage.lua, data/modules/MissionUtils.lua, data/modules/Scoop/Scoop.lua, data/modules/Taxi/Taxi.lua
This is an attempt to simplify delivery times so that they can be better balanced if necessary.
I have used the DeliverPackage module as a basis and fitted the other with one factor.
The combat module is now better for ships like the Bowfin.
I have also added a "local part". This should calculate much better delivery times for large systems.
If no location is specified, a distance of 1AU is assumed.
**Now the local deliveries:**
I took the average flight time of a Xylophis from 'System Administration Resting' to 'OPLI Pax' as the basis for the local deliveries. approx. 2 days for 1AU.
Finally, the due time is rounded to 1h or 1/4h. In addition, the advert is deleted after half of the calculated travel time. Makes more sense in my opinion.
=> Simplified travel times

src/GasGiant.cpp, src/Pi.cpp, src/PngWriter.cpp, src/PngWriter.h, src/graphics/Renderer.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h
This fixes #4671
Also, somewhat more optimal and safer, given the old code appears to be copying most bytes 3/4 times and then copying 2/3 bytes off the end of the image, if I read it correctly.
As a side effect screenshot images are a bit smaller now too.
=> Remove transparent backgrounds from screenshots

data/pigui/themes/default.lua
I've changed the coloring of better stats from green to a saturated blue to provide much more contrast for colorblind folks. The red-green pairing can be really hard to distinguish. This pairing should provide better contrast to all four types of color blindness.
I've added two new colors to the theme:
compare_worse - kept the orange-ish red of warning_300
compare_better - added a saturated blue of similar lightness. Could have gone brighter, but then it competed with the white.
And changed the market lines to use these new colors. These could then be used on the eqipment market later too.
(I've also just created an Accessibility tag on github)
Before:
After:
=> Making ship market comparison colors colorblind friendly

data/shaders/opengl/lib.glsl, data/shaders/opengl/planetrings.frag, data/shaders/opengl/planetrings.vert, src/Planet.cpp
All rings are assumed to be icy
1) Each object in ring is darker depending of its phase
(like Moon phases)
2) Each object shines brightly if sun is behind the ring
(lot of low angle specular reflections)
3) Each object shines brightly if looking from the sun
(simulating high geometric albedo > 1.0)
=> improve planet rings shaders

data/modules/TradeShips/Debug.lua, data/modules/TradeShips/Events.lua, data/modules/TradeShips/Flow.lua, data/modules/TradeShips/Trader.lua, src/lua/LuaSpace.cpp
This PR is an attempt to fix cluttering hyperclouds around stations and rare illegal jumps almost at the planet's surface. Now `TradeShips` behaviour when undocking looks like this.
For orbital stations:
1. Undock;
2. Fly to limits of current orbital station;
3. `OnAICompleted` event fires, tell ship to fly to current system's star;
4. Assign task to check distance between current orbital station and ship, if distance is large enough, make the jump.
For ground stations;
1. Undock;
2. Tell ship to fly to current system's star;
3. Assign task to check altitude between current orbital station's parent and ship, if altitude is high enough, make the jump.
The distance and altitude will be selected from a random interval of 20,000 - 240,000 meters.
Demonstration:
1. Undocking and jumping from …
=> TradeShips hyperjump code change

src/lua/core/Import.cpp
=> Fix  assert on startup when calling back on an empty string

src/collider/BVHTree.cpp, src/collider/CollisionSpace.cpp
The CollisionSpace partition sort algorithm had a degenerate case where the contents of a single-element array would always be assigned to the disabled bucket, regardless of if it was enabled or not. This resulted in the player being unable to collide with any static Geom if it was the only active ship in the physics frame.
I've fixed that, and in the process made the sort algorithm a bit simpler.
Fixes #5705. Note that the saves linked in that issue are not compatible with the current master branch.
=> Fix player being unable to collide with Stations if only ship in Frame

.github/workflows/build-ci.yml, CMakeLists.txt, pioneer.rc.cmakein
This is needed for the FILEVERSION constant because it only accepts numeric values, and now our version can be not only numerical.
Please note that I did not change this line:
```
VALUE "ProductVersion",     "@PROJECT_VERSION@"
```
=> Add BUILD_DATE variable for windows builds

data/lang/ui-core/en.json, data/pigui/modules/settings-window.lua, data/shaders/opengl/basesphere_uniforms.glsl, data/shaders/opengl/gassphere_base.frag, data/shaders/opengl/geosphere_sky.frag, data/shaders/opengl/geosphere_terrain.frag, data/shaders/opengl/geosphere_terrain.vert, data/shaders/opengl/lib.glsl, data/shaders/opengl/planetrings.frag, data/shaders/opengl/rayleigh.glsl, data/shaders/opengl/rayleigh_accurate.frag, data/shaders/opengl/rayleigh_accurate.shaderdef, data/shaders/opengl/rayleigh_accurate.vert, data/shaders/opengl/rayleigh_fast.frag, data/shaders/opengl/rayleigh_fast.shaderdef, data/shaders/opengl/rayleigh_fast.vert, data/shaders/opengl/sRGB.glsl, src/BaseSphere.cpp, src/Camera.cpp, src/GasGiant.cpp, src/GeoSphere.cpp, src/GeoSphere.h, src/SectorMap.cpp, src/galaxy/AtmosphereParameters.h, src/galaxy/SystemBody.cpp, src/galaxy/SystemBody.h, src/graphics/Drawables.cpp, src/graphics/Drawables.h, src/lua/LuaEngine.cpp
Experimental shaders for atmospheres on terrestrial planets.
TO-DO list:
=> realistic Rayleigh/Mie atmospheric scattering

data/libs/Event.lua, data/modules/Scout/ScanManager.lua, data/modules/Scout/Scout.lua, data/pigui/views/map-sector-view.lua
As an unintended consequence of #5671, two modules were inadvertently overwriting their previously-registered event handlers by dint of not conforming to the existing usage pattern of one handler per event per file. This pattern was made a requirement to support hot-reloading of registered event handlers, but I didn't realize we had some existing code which broke that pattern before I merged the PR.
This PR fixes an issue reported at least once on Discord where scan missions were unable to be completed after loading a saved game with an in-progress scan. I don't believe it's yet been reported over here.
=> Fix orbital / surface scan missions being unable to be completed

data/pigui/modules/hyperjump-planner.lua, data/pigui/views/map-sector-view.lua, src/SectorView.cpp
The planned hyperspace route, with all stops is saved along with the save game, and restored on load.
=> Save and load the current planned hyperjump in the save file

data/libs/Equipment.lua, data/meta/SystemBody.lua, data/modules/Scout/Scout.lua, data/systems/custom/00_sol.json, src/editor/system/GalaxyEditAPI.cpp, src/galaxy/StarSystemGenerator.cpp, src/lua/LuaSystemBody.cpp
This PR resolves an oversight/issue introduced with the System Editor series of PRs which resulted in randomly-generated gas giants not correctly computing an atmospheric density and the Sol system gas giants not having explicitly-set atmospheric densities.
This additionally fixes #5677 and partially addresses #4222 by defining the surface level for gas giants (which corresponds to the physical collision sphere below which a ship cannot pass) as being the "upper cloud deck" level. The density at cloud deck level is estimated using the expression `2𝑒 * density at 1 bar`, based on real-world data published by NASA regarding the solar system gas giants. I've correspondingly introduced a new generation expression for gas giant surface density using bounds fitted to real-world gas giant …
=> Fix missing gas giant atmospheres

.github/actions/upload-linux/action.yml, .github/workflows/build-ci.yml, .github/workflows/clang-format.yml, .github/workflows/naturaldocs.yml, CMakePresets.json, COMPILING.txt, src/Game.cpp, src/editor/EditorApp.cpp, src/editor/EditorApp.h, src/lua/LuaBody.cpp
Catch-all bugfix PR, part of my annual microfixes series.
- Fixes #5683 by defaulting all builds to use the Ninja generator per discussion on IRC. Documented the package requirement in COMPILING.txt.
- Fixes #5673 - GPS coordinates are consistent across rotating and non-rotating frames.
- Fix error message about missing language resource `.json` file on editor startup
- Fixes #5709 - Accidentally left a dangling pointer to a stack (de)allocated variable. Oops!
Potentially more fixes to come before merge...
=> Microfixes

.github/workflows/build-ci.yml
#5731 works fine for refspecs in the form `refs/pull/XXXX/merge`, but fails for `refs/heads/<branch>`. I suspect this is because of an erroneous quote character being passed through the `echo` command.
=> Fix MSVC CI build on non-PR refs

data/modules/BreakdownServicing/BreakdownServicing.lua
Supposed to print time since last maintenance of engines.
Fixes #5752
I'm not sure why the code was structured the way it was, but it was written like that for NewUI (did it not refresh as imgui does?)
Tested it's correct for ship with and without engines to service, as well as when you service, and click advert again.
=> Fix 'nil' in hyperdrive Maintenance BBS advert

CMakeLists.txt, COMPILING.txt, NEWS.md
This saves our release announcements to a new NEWS.md file. Alternative PR title could have been: appease @laarmen 
Note to @Gliese852 @Web-eWorks @laarmen 
- Please check the new section in COMPILING file that I've copy-pasted from latest release announcement if this is correct & good?
- Please note the first paragraph in NEWS.md specifying what the file is about, also a nod towards package maintainers. 
If this is merged, we/I should also update the https://dev.pioneerspacesim.net/contribute/making-a-release page with how to deal with the new file after release.
=> Add documentation to make life for package maintainers easier

src/Background.cpp, src/galaxy/SystemPath.h, src/matrix4x4.h
- really do early out
- rotate coordinate system from galaxy (Z-up) to scene (Y-up)
- more fairly distribute the number of stars among tasks - these are spherical segments
- do not overlap task ranges
- calculate the average of the median brightnesses, and use the same value in all pieces
Fixes #5414
=> Fix star background generation

data/pigui/modules/info-view/04-missions.lua
When listing table of all player's accepted missions, local deliveries all have distance "0 ly". Switch to AU instead.
Fixes #5755
- do we have AU units defined elsewhere that I should use, or defining it in the local file is good?
- under which circumstances would `mission.location:GetSystemBody()` return nil, and what should one display in that circumstance?
=> Local missions should list distances in AU rather than Ly

src/Game.cpp, src/Space.cpp, src/Space.h, src/collider/CollisionSpace.cpp
This makes combat impossible if travelling at speed
Fixes #5695 and Fixes #5741
Revert initial change that fixed adding items to the vector whilst iterating it but introduced the frame lag and instead fix in a simple way.
=> Fix projectiles being added a frame behind where they are fired and beam weapons not able to hit

data/modules/FlightLog/FlightLogEntries.lua, data/pigui/modules/info-view/06-flightlog.lua
=> Fix crash when deleting a flightlog entry

src/Space.cpp, src/galaxy/CustomSystem.cpp
If a custom system body had a rotational period of exactly 0 days, when visiting the system it would create a rotational frame for that body with infinite angular velocity. As a result of math operations on Inf / NaN values, the rotation matrix for that frame would contain NaN values which caused the distance between the reference body and that body to compute as NaN. This lead to a nil value being returned from `Space.FindNearestTo()` in `SearchRescue.lua:1063`, which caused the error the user is likely to see.
Fixes #5745.
This PR also contains a fix for an issue where sector indices for JSON custom systems were being loaded from the wrong array locations. The system linked in the issue report above is actually supposed to be in sector `5, 0, 2`, but was loading into sector `5, 2, 0`.
=> Fix error in SearchRescue.lua in custom systems

src/galaxy/CustomSystem.cpp
Prior to the merge of the System Editor and associated system generation refactor, all gas giants had a fixed 14.0 kg/m3 atmospheric surface density value which overrode the value of `m_volatileGas` and thus many Lua custom systems never set the atmospheric density parameter, which resulted gas giants in custom systems (e.g. Sol, Noril, etc.) missing scoopable atmospheres.
Sol was resolved by manually editing the gas giants to set density to real-world values; this PR follows up and adds an additional "fixup" step when loading legacy Lua custom systems that generates "missing" atmospheric density values for gas giants.
**Testing Steps:**
Visit Noril C and attempt to scoop it for fuel. It should have an atmospheric density > 0 before you crash :wink:
=> Generate atmospheres for gas giants in legacy custom systems

src/editor/EditorApp.cpp, src/editor/EditorApp.h, src/editor/EditorIcons.h, src/editor/system/SystemEditor.cpp
Per discussion on IRC and various bug reports we've received, this PR implements a "welcome screen" frontend when launching the editor binary without any command line arguments to select the specific editor mode to open.
CC @nozmajner for testing on Windows.
=> Editor Welcome Screen

data/lang/core/en.json, data/libs/SpaceStation.lua, data/libs/autoload.lua, data/libs/utils.lua, data/meta/Color.lua, data/meta/Rand.lua, data/pigui/baseui.lua, data/pigui/init.lua, data/pigui/libs/buttons.lua, data/pigui/libs/commodity-market.lua, data/pigui/libs/forwarded.lua, data/pigui/libs/gauge.lua, data/pigui/libs/icons.lua, data/pigui/libs/text.lua, data/pigui/libs/wrappers.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/themes/default.lua, data/pigui/views/tab-view.lua, src/Player.cpp, src/Player.h, src/lua/LuaPiGui.cpp
This PR is a bit of a catch-all arising from development of #5734 and contains most of the feature-agnostic commits from that branch.
In no particular order:
- Improved the Lua runtime library with several new utilities for operating on tables
- Added a new `utils.proto` helper function for working with a prototype-based object model
- Fixed an error when attempting to interpolate a non-string object into a string
- Fixed a long-running bug with `utils.print_r` which caused it to print incorrect information about recursive tables (tables that have already been printed)
- Fixed default forwarding constructor for `utils.inherits` - you can now receive arguments from the default `.New()` constructor of a subclass.
- Fixed #5765
- Made most PiGui methods available to Lua autocomplete through …
=> Misc cleanup, fixes, and Lua function library improvements

data/modules/FlightLog/FlightLog.lua, data/pigui/modules/new-game-window/class.lua, data/pigui/modules/new-game-window/flight-log.lua, data/pigui/modules/new-game-window/helpers.lua, data/pigui/modules/new-game-window/recovery.lua
Although the flight log is now a single list, it still has the same three types of entries. Therefore it can still be shown without changing the GUI in the start menu, where 3 sections (entry types) are shown separately, depending on the combobox.
It is now possible to determine the log entry type only by the object type, which becomes available after full deserialization. But I would not want to do this, including reusing the actual code from the game, since it may change over time. Information about the object type is contained in the `lua_class` field, which is lost when the save tree is unpickled. In order to save this information, and at the same time not change anything radically in the unpickled tree, it was decided to put all type names into one separate subtable in the save tree, …
=> Add a recovery reader for the v90 flight log

.github/workflows/build-ci.yml
This inadvertently got missed during the last set of CI updates - this PR updates the Windows `upload-artifact` Github Action to use version 4 of that action, which is more efficient and provides much faster upload speeds (and also addresses the deprecation notice from using v3).
This also normalizes the Windows artifacts to be retained for 14 days after a build - given that we're generating >1GB of artifacts from each build and there's little need to download a pre-built archive of a past build, it doesn't really make sense to retain builds for the default of 90 days. Binaries uploaded to Github Releases are not affected by this change - they're stored separately and will be retained permanently (for as long as the release exists).
=> Update Github Upload-Artifact action for Windows CI

src/Camera.cpp, src/DeathView.cpp, src/Input.cpp, src/Intro.cpp, src/ObjectViewerView.cpp, src/Pi.cpp, src/SectorMap.cpp, src/Sfx.cpp, src/ShipAICmd.cpp, src/WorldView.cpp, src/core/GuiApplication.cpp, src/core/GuiApplication.h, src/editor/EditorApp.cpp, src/editor/system/SystemEditor.cpp, src/editor/system/SystemEditor.h, src/graphics/Graphics.cpp, src/graphics/Graphics.h, src/graphics/RenderTarget.h, src/graphics/Renderer.h, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h, src/lua/LuaConsole.cpp, src/lua/LuaPiGui.cpp, src/lua/LuaSystemView.cpp, src/scenegraph/Billboard.cpp, src/scenegraph/LOD.cpp
At long last, we have the technology to resize a window at runtime. ~~It only took three years by my count.~~
This PR provides support for resizing the editor window using the titlebar / window corners (or any other OS-provided method to resize a window). It also fixes some bugs along the way, adds some more FIXME comments (no delve into the dungeon of the code is complete without at least one new FIXME), and sneakily adds an option to resize the main game window as well - though none of the UI currently resizes along with it.
This PR fully deprecates and deletes Graphics::GetScreenHeight/Width, replacing usage with the Renderer::GetWindowHeight/Width methods instead. In a lot of cases, the original use of the function was suboptimal at best, and future work should be done to refactor …
=> Resizable Editor Window

src/ShipAICmd.cpp
- Fix that sometimes ships get stuck the moment they start to dock.
- ~~Fix that during a long free flight the autopilot constantly corrects the course towards the target and this leads to unnecessary fuel consumption.~~ **Сan't reproduce**
- ~~Add a simple queue for docking with the station in order to somewhat reduce the probability of a collision of ships~~ **It didn't work out that easy, let's postpone**
~~Also in order to find out which ships are in a given frame, I implemented the `Frame::GetBodiesInside` function, and for its work - the `CollisionSpace::GetGeoms` function.~~
=> Fix that sometimes ships get stuck the moment they start to dock

data/modules/LifeSupport.lua, data/modules/System/OutOfFuel.lua, data/modules/TradeShips/Events.lua, data/modules/TradeShips/Flow.lua, data/modules/TradeShips/Trader.lua, src/lua/LuaShip.cpp, src/lua/LuaTimer.cpp
Collected the simplest, but quite effective fixes so that when you stay in one system for a long time, there is no noticeable drop in performance.
Fixes #5735
(taking into account that #5127 and #5785 are merged)
~~Although at least there remains the problem that occasionally the tradeship runs out of fuel; repairing it probably requires serious intervention in the autopilot, or the creation of evacuation ships, for example.~~ **just explode them**
=> Fix the accumulation of zombie traders and some other unnecessary things

data/libs/CommodityType.lua, data/meta/Serializer.lua, data/modules/Debug/TestSerialization.lua, src/Game.cpp, src/lua/LuaSerializer.cpp, src/lua/LuaSerializer.h
This PR adds support for serializing "persistent objects", i.e. objects that will always be created at runtime. References to these persistent objects are transparently replaced with references to the "live" copy of the persistent object when loading a saved game, unless that persistent object is no longer present (i.e. incompatible saves) in which case the persistent object is "revivified" from the savefile.
This is a difficult concept to explain, but if you're familiar with how commodity types function currently (where saved copies of a commodity type instance are replaced with the commodity type instance that was created at startup) this is an identical concept but with less manual work required.
The primary goal of this system is to migrate equipment items to use this rather than …
=> Add Lua "Persistent Object" Serialization

src/editor/system/GalaxyEditAPI.cpp, src/editor/system/SystemEditorHelpers.cpp
- Fix the tab key not working to confirm certain fields in the system editor (the changed value wasn't being written back to the datastructure unless the enter key was pressed). Fixes #5746.
- The initial state of the system editor didn't display edit fields for a body's population and agricultural index, as they're overwritten by random values when the system is loaded. Those fields are now shown but left disabled with a notice until the fields are honored by the system loading code.
=> System Editor Fixes

src/JsonUtils.cpp, src/galaxy/CustomSystem.cpp
This PR addresses a platform-specific issue where on Windows a fixed-point fractional part greater than 0.5 was being silently truncated when loaded from JSON files. This is most likely the cause for starport positions to be completely incorrect on Windows specifically.
This PR also addresses the log warnings about negative inclination values coming from legacy Lua-based systems until such a time as we convert all such systems to JSON.
Fixes #5792, fixes #5744.
=> Fix incorrect position of starports

data/libs/SpaceStation.lua, src/Background.cpp, src/galaxy/StarSystemGenerator.cpp
Small collection of bugfixes for the upcoming release.
- Fixes #5764 - I broke this by trying to do the gravpoint mass summation pass piece-wise.
- Fixes #5770 - Since stars are rendered in Z-up space, need to compute the direction of hyperspace star "streaks" in Z-up space as well.
- Fixes #5784 - The commodity market already prevented you from selling more items than there was station demand; added a simple filter to prevent other code from putting a commodity market in an invalid state of negative supply/demand.
=> Fix invalid binary orbits, hyperjump streaks falling down, negative commodity demand

src/lua/LuaSerializer.cpp
Fixes #5797 - the issue was inadvertently caused by the lack of compatibility testing with existing v90 savefiles. The fix is quite simple, and savefiles created in the 20240203 release should be fully loadable with this PR merged.
Testing appreciated, of course.
=> Fix backwards save compatibility with v90 saves

data/pigui/modules/autopilot-window.lua
This PR resolves an issue with the positioning of speed limiter buttons, where the `sameLine` call was restoring the start-of-line cursor position in a way that resulted in overlap between the buttons and the speed limiter itself.
The result is as it should be:
Fixes #5800.
=> Fix speed limiter button positions

data/ships/coronatrix_police.json
Now it picks the correct model, with the police texture. I've also added parentheses around the Police in the name to get it consistent with the other police ships (although they should never pop up on the market)
=> Police Coronatrix texture fix

data/modules/SearchRescue/SearchRescue.lua, data/pigui/modules/station-view/02-bulletinBoard.lua
Related to #5399 regarding the 34m issue.
The distance to a ship on the surface is not absolutely correct. I ignored it. :-)
=> Use variable "dist" for the distance in the BB if specified

data/pigui/modules/new-game-window/location.lua
It turned out that the index of the system body in the path does not always coincide with its index in the save file, because when saving there is a separate indexing.
In addition, if there are gravpoints in the system, the numbering of physical bodies and system bodies also differs, what was not taken into account.
(This led to errors when recovering the location.)
Fortunately, the physical body (planet or station) has a reference to the serializable index of the system body (`index_for_system_body`), and this way the reliable connection can be found.
=> Fix location recovery

src/graphics/opengl/RendererGL.cpp
Ignore an error from GLEW in order to run natively under Wayland (instead of going through XWayland) on Linux.
Pioneer can be forced to run with Wayland like this: SDL_VIDEODRIVER=wayland ./pioneer
=> Renderer: Support running under Wayland

CMakeLists.txt
=> Do not install libfmt by default

src/vector3.h
=> Include <algorithm> for std::max

src/core/macros.h
=> Include stdlib.h instead of alloca.h for alloca(3) on FreeBSD

SAVEBUMP.txt, src/DynamicBody.cpp, src/ship/PlayerShipController.cpp
=> Fix loud white nosie after mouse steering

src/Input.h
I've adopted the [pioneer-git](https://aur.archlinux.org/packages/pioneer-git) repo in AUR (Arch Linux User) repository, that tracks our master branch. As such, I note the package is currently not building:
```
[ 15%] Building CXX object CMakeFiles/pioneer-lib.dir/src/HyperspaceCloud.cpp.o
[ 16%] Building CXX object CMakeFiles/pioneer-lib.dir/src/Input.cpp.o
In file included from /tmp/src/pioneer-git/src/Input.cpp:4:
/tmp/src/pioneer-git/src/Input.h: In member function ‘void Input::Manager::GetMouseMotion(int*)’:
/tmp/src/pioneer-git/src/Input.h:206:22: error: ‘copy_n’ is not a member of ‘std’; did you mean ‘copy’?
206 |                 std::copy_n(mouseMotion.data(), mouseMotion.size(), motion);
|                      ^~~~~~
|                      copy
make[2]: *** …
```
=> Fix missing include

data/meta/CoreObject/Player.meta.lua, data/pigui/modules/info-view/04-missions.lua
Existing code was attempting to get the system's path from a SystemPath object instead of a star system directly. Fixed that and provided some additional type information for working with the nav/combat/hyperspace target methods on LuaPlayer.
Fixes #5822.
=> Fix mission list error when opened during hyperspace

data/libs/SpaceStation.lua, data/modules/SearchRescue/SearchRescue.lua, data/pigui/modules/new-game-window/class.lua, data/pigui/modules/new-game-window/crew.lua, data/pigui/modules/new-game-window/ship.lua, data/pigui/modules/new-game-window/widgets.lua, data/pigui/modules/station-view/06-shipRepairs.lua, src/scenegraph/Label3D.cpp
This PR fixes #5838, and in the process fixes a number of spots where ship labels either were not appearing or may have been incorrect prior.
- Ship labels now display and update in the new game start window. Modifying the ship label adjusts it on the craft as well, if the craft has a properly-named label node.
- Ships on sale in a space station now display their labels on the craft if the craft model supports labels.
- The paint shop technically appeared correct but would have resulted in the same missing label bug when saving and loading after applying the paint.
- SearchRescue spawned ships will continue to show labels (they technically were painting a label on the ship hull and then attempting-but-failing to clear it).
CC @Gliese852 - I've made minor changes to the new game window …
=> Fix lots of missing ship labels

data/lang/module-scout/en.json, data/modules/Scout/Scout.lua
It's come to my attention that currently no ships in the game can approach the surface of Venus, yet we generate surface scan missions there anyways. Luckily, that's a quick fix.
I've also thrown in a new section of warning text to surface scan mission ads mentioning the target body's atmospheric pressure and surface gravity when those are potentially a factor limiting the player's ability to carry out the mission.
I've chosen to treat this as an informational notice only rather than preventing the player from accepting the contract to both reduce the amount of code required and also provide maximum flexibility to the player.
This PR can be used with existing saves, though you'll have to re-generate BBS ads by jumping to a different system to clear existing missions to Venus.
=> Improve surface scan missions on high-pressure worlds

data/pigui/modules/system-econ-view.lua
In the system/sector map economy widgets, we should sort commodities by their translated names rather than the I18N key. This was a hold-over from when the economy widget was a debug tool only.
Fixes #5844.
=> Sort commodity names by translated string

.github/workflows/build-ci.yml, CMakeLists.txt, cmake/InstallPioneer.cmake
Potential fix for DLLs not being copied into the release archive for Windows builds. Not sure what broke this, as it was working at least a few months ago if not sooner.
=> Fix DLLs not being installed on Windows builds

data/modules/Debug/DebugRPG.lua, data/modules/Scoop/Scoop.lua, data/pigui/libs/ship-equipment.lua
This PR contains multitides:
Class 2 military drives require "MILITARY" tech level, which under the hood is interpreted as tech-level 11 (because that's how Frontier implemented it). Higher military drives are available at higher tech levels. Code had a bug where in stations of higher tech level than "MILITARY", you could only buy military drive of class 1, 3, and 4, but not military drive class 2.
I note there's equipment that has "tech level = 11" set, that is technically the same as tech level "Military". Seems to be the way I did it in #3505, so looks intentional, but not sure what the reasoning was.
I saw the bug when watching the "Pioneer - Frequently Failing" play through of the game (last screenshot from Poseidon in orbit around Neptune, level 12 station):
Don't generate "Unknown …
=> Fix Military Drive 2 not for sale & tweaks

data/pigui/views/map-sector-view.lua, src/Background.cpp, src/SectorMap.cpp, src/editor/system/GalaxyEditAPI.cpp, src/editor/system/GalaxyEditAPI.h, src/editor/system/SystemEditor.cpp, src/galaxy/StarSystem.cpp
This PR fixes #5857 - the primary issue was that `StarSystem::m_stars` wasn't being properly populated when creating a new system and adding stars to that system. As a consequence, the game thought there were no stars within the generated system and that exposed a host of bugs related to rendering and processing a system without stars.
I've fixed most of the bugs related to a lack of stars which I found, but didn't perform an exhaustive search to see if there were any I missed in other parts of the game or UI.
I've also fixed a problem which lead to hilariously out-of-range values being set for a system's position within its sector when creating a new system "from scratch". As usual, just another variable which didn't get initialized properly.
=> Fix custom systems with zero stars

data/modules/NewsEventCommodity/NewsEventCommodity.lua
Demand mechanics was never ported into News Event module, thus when there's a large demand for something at a station, the demand could still be very low, preventing player from selling. Also, we don't want to accumulate price/stock/demand at each "OnDock" event.
EDIT: I'll open this as WIP, for feedback, the first and last commits, that both attempt to fix the above bug should be squashed, as first does it wrongly, I believe.
Also I've added a debug tab, which allows generating (random) news. Usually news only spawn +6 months into the game, and only when jumping / in hyperspace.
=> Fix demand at News Events not being used

data/meta/Constants.lua, data/meta/CoreObject/Body.meta.lua, data/meta/FileSystem.lua, scripts/scan_enums.py
Lua-LS released a new `@enum (key)` annotation in version 3.7.0 which much better supports "string constants" as enum values. Functions which take an EnumStrings constant as a parameter will have full autocompletion for the list of constant values which make up that string enumeration, and the language server will render a diagnostic if an inappropriate enumeration value is used in that function call.
Note that at current, the effect of this change is limited to a very small subset of callsites where a) the function being called takes an EnumStrings constant, and b) full type information is available for the object the function is being called on.
=> Improve Lua type checking for string enums

data/lang/module-easteregg-message/en.json, data/modules/EasterEgg/Message.lua
Want the BBS to feel real?
Well, now we have people who shit post! (as an Easter Egg)
This is another branch I've been sitting on for 4 years. I got inspired when watching this video, [_Why did a TIME TRAVELLER need this old IBM computer?_](https://www.youtube.com/watch?v=Jzj-mmo7qjw&t=7m20s), about [John Titor](https://en.wikipedia.org/wiki/John_Titor) which is part of Internet lore. Basically, he posted on BBS forums claiming to be a time traveler from the future, and he had knowledge of things yet to pass, like computer before their release. There's even a Japanese [series](https://en.wikipedia.org/wiki/Steins;Gate_(TV_series)) that reference it.
=> Add Easter egg.story about time traveller 

data/pigui/modules/sidebar/cargo.lua
Closes #5860 feature request by @syonfox (I was going to close it anyway, as we don't do feature requests on the issue tracker, but figured I might as well implement it, low hanging fruit). 
Note: just appending "all" to the tooltip hardcoded. Dunno if we keep it, and put it in ui-core, or remove. Not obvious to me why the `tooltips` are passed as arguments to this function?
```lua
transfer_buttons(amount, min, max, tooltip_reduce, tooltip_increase)
```
=> Add "jettison all" buttons to cargo sidebar menu

data/modules/Debug/DebugCommodityPrices.lua
- Fix standard deviation lacking a `sqrt`
- Add filtering on `purchasable` goods on/off (sadly we can't buy the fuzzy little Quibbles on the commodity market)
- Add some collapsing headers UI stuff when selected a commodity, for bling bling
- Added some info on commodity at current station (if docked). I used this for #5859, and might need it again. It's not über-pretty, but oh, well `¯\_(ツ)_/¯`
=> Fix debug commodities tab

src/editor/system/SystemEditor.cpp, src/pigui/PerfInfo.cpp
Whilst debugging #5885 and #5830 today I wanted a quick way of getting a dumped system into the system editor so I've added a 2nd button to the Perf-Info screen which already allowed dumping the JSON to the output log.
Instead it now generates a JSON file which can be directly loaded into the system editor for viewing / modification and outputs it into the users pioneer directory where screenshots, savefiles, etc folders are located.
This should also make it easier for people to create custom systems based on generated ones they've found interesting to make that process a little easier.
=> Added Perf-Info button to Dump a system to systemeditor compatible JSON

.github/workflows/build-ci.yml, CMakeLists.txt, cmake/TargetArchitecture.cmake
This PR addresses some slightly over-zealous feature enablement from the previous release cycle that we are not yet materially using. The build system now only defaults the USE_SSE42 flag to 'on' if we're compiling for a non-ARM64 target, and we no longer enable utilization of the `lzcnt` instruction for SSE4.2 builds - it was introduced in the Haswell microarchitecture alongside AVX2 and as such has been moved to that build option.
I've also added feature-test flags for the build script to use in the future to detect whether we're compiling for an ARM64 target or an Intel target (and whether we're compiling for 32 or 64-bit x86 architecture).
=> Don't build against lzcnt by default and enable USE_SSE42 only on Intel architecture

data/pigui/modules/system-econ-view.lua
To be coherent with the legal commodity list, the first icon must be for local system and the second for distant system.
That what this commit does.
Fixes #5876
=> Invert illegal commodities icons in the Economy & Trade view. Fix #5876

src/Intro.cpp
Fix PiRngWrapper to use the full range of the random object. std::shuffle expects the range provided by max().
See explanation [here](https://github.com/pioneerspacesim/pioneer/issues/5659#issuecomment-2300720284).
Fixes https://github.com/pioneerspacesim/pioneer/issues/5659
=> Fix intro screen ship randomness

data/libs/SpaceStation.lua
There is an infrequent issue where the BBS will show up empty on a game reload as SpaceStation.adverts[station] is missing. This fix will cause the BBS to repopulate itself but only from those modules that impements onUpdateBB(). It will not solve the underlying cause.
Addresses #5886
=> Repopulate BBS if empty

data/lang/ui-core/en.json, data/libs/Legal.lua, data/libs/utils.lua, data/pigui/modules/station-view/07-police.lua
I found this 4 year old branch. I figured I could fix it up and PR it.
This aims to show more clearly what rules the player need to be weary of. Changes:
- Put existing police stuff in "Crime record" tab
- New tab, lists legal offenses, and the fine at the station
(Never mind my [Evarchart](https://forum.pioneerspacesim.net/viewtopic.php?f=8&t=382) facemod)
=> Station Police view has tabs: 1. crime records, + new: 2. rules & regulations

data/modules/Debug/DebugCommodityPrices.lua, data/modules/Debug/DebugRPG.lua, data/modules/Debug/DebugShipSpawn.lua, data/modules/Debug/DebugShipSpawn.moon, data/modules/NewsEventCommodity/NewsEventCommodity.lua, data/modules/TradeShips/Debug.lua, data/pigui/libs/wrappers.lua, data/pigui/modules/theme-debug.lua, data/pigui/views/debug.lua, src/Pi.cpp, src/pigui/PerfInfo.cpp, src/pigui/PerfInfo.h
I've converted the PerfInfo debug tabs to use icons rather than names, made the debug tabs themselves hot-reloadable, and improved the amount of data shown in the performance plots displayed in the performance section. Frame graphs now display the last 5 seconds of frame timings (up from 1s), and have both a recent "instantaneous average" and whole-graph average. Memory graphs (which have a sample rate of 1Hz instead of ~60Hz) now show the last five minutes of memory usage for a more complete picture.
The PerfInfo window is easier to read and use at smaller window sizes, and can be collapsed completely to only display the current FPS while flying around the world as a built-in FPS counter.
I've also made the counters slightly cheaper to update in most cases, which should entirely offset …
=> Improve PerfInfo debug window

data/lang/ui-core/en.json, data/pigui/modules/system-econ-view.lua, data/pigui/themes/default.lua
Per comments from @bszlrd / @impaktor, this PR modifies the system-wide economy display widget to clarify that it's not displaying the actual market data for any specific station within the system.
Closes #5882, closes #5836.
This also addresses https://github.com/pioneerspacesim/pioneer/pull/5865#issuecomment-2306520959 - the color breakpoints chosen for the tabs didn't get updated when the theme colors were changed.
=> Clarify system-level economy display

src/editor/EditorWindow.cpp, src/editor/EditorWindow.h, src/editor/ViewportWindow.cpp, src/editor/system/GalaxyEditAPI.cpp, src/editor/system/SystemEditor.cpp, src/editor/system/SystemEditor.h, src/editor/system/SystemEditorHelpers.cpp, src/editor/system/SystemEditorHelpers.h, src/editor/system/SystemEditorModals.cpp, src/editor/system/SystemEditorViewport.cpp, src/galaxy/StarSystem.h, src/galaxy/StarSystemGenerator.cpp
Continuing on from the discussion in #5892, this PR cleans up some generation bugs in binary systems which caused the orbits of stars to change once edited (due to orbital parameters not being written back to the body), and adds a new "regenerate system from seed" functionality to quickly generate new variants of the edited system. It also addresses a unit conversion issue in body radius display when using Earth Radius as a unit.
Due to data plumbing issues, regenerating a system can only be done for a full-procedurally generated system or a "partially random" system sourced from the `local_stars` database of systems with randomly generated contents.
https://github.com/user-attachments/assets/cb859248-1401-43f9-8bb7-56ec3c35cb0b
=> Add ability to reroll random systems to System Editor

data/libs/SpaceStation.lua
This is a fixup from #5894 / a005ad4
Instead of updating the BBS it should be created if SpaceStation.adverts[station] is missing.
Addresses #5894
Addresses #5886
=> Create BBS if empty

data/modules/Assassination/Assassination.lua, data/modules/CargoRun/CargoRun.lua, data/modules/DeliverPackage/DeliverPackage.lua
The already existing function GetNearbyStationPaths() in MissionUtils is used to find the stations in nearby systems.
This also increases the probability for systems with more stations. Not too bad IMHO.
=> Simplified random station selection for delivery missions

data/pigui/modules/saveloadgame.lua
Fixes https://github.com/pioneerspacesim/pioneer/issues/5917
A refactor of the load/save UI in commit
7b6a79700682124d29351fb83562778eaf5a2da4 introduced a bug preventing the "savefiles" directory from getting created, and causing an error-popup whenever the directory was attempted to be accessed by the LUA UI.
The bug was resetting a variable to an unexpected value which then caused the "sort" algorithm to throw an error. This was resolved by ensuring that the variable always had a valid value for the sort algorithm.
=> fix(savegame): fix savefiles directory not being created (#5917)

data/libs/NameGen.lua
* Add separate name formats for asteroids
* Occasional Roman numerals to planet names
* Add new station names/functions
* Add occasional random station number
What planet name isn't improved with a Roman numeral?
Numbers to spice up station names
The smaller bodies gets their own set of name formats
Can there be more than one instance of the same number. Yes. Same name and number? Not likely, but yes. This is what I could come up with in a short amount of time that made a reasonable improvement in the naming of bodies. I think this could be improved further if the pioneer universe was populated with companies/entities that placed their assets, ships and stations, in the systems and that had it's own decals, naming schemes etc.
Core Drilling Station? Yes, they are an efficient way to …
=> NameGen - Spice up the station names

data/models/stations/orbital_station/orbital_station_2-10k.model, data/models/stations/orbital_station/orbital_station_2-2k.model, data/models/stations/orbital_station/orbital_station_2-5k.model, data/models/stations/orbital_station/orbital_station_2-5k10k.model, src/Camera.cpp, src/Camera.h, src/ShipCockpit.cpp, src/SpaceStation.cpp, src/SpaceStation.h, src/scenegraph/BinaryConverter.cpp, src/scenegraph/BinaryConverter.h, src/scenegraph/Loader.cpp, src/scenegraph/LoaderDefinitions.h, src/scenegraph/Model.cpp, src/scenegraph/Model.h, src/scenegraph/Parser.cpp
Makes ships that are inside stations (as defined on the model file using tags and a series of new parser commands) have increased ambient light and reduced direct lightning, fixing the issue of black ships on eclipsed stations (Issue #4399).
TO-DO:
Demo: https://www.youtube.com/watch?v=D56iUkvpOac
=> Add interior lighting to stations

data/libs/Player.lua
Fixes #5935
Bug introduced in 99b0acdb9843d65fbb6f19e720c3e59a5abec86e, the 'onEnterSystem' event needs to check whether the ship which entered the system is the Player.
=> fix: only reset view to WorldView when Player enters system

data/libs/utils.lua, data/pigui/modules/saveloadgame.lua, src/Pi.cpp, src/SaveGameManager.cpp, src/SaveGameManager.h, src/editor/EditorApp.cpp, src/lua/Lua.cpp, src/lua/Lua.h, src/lua/LuaEngine.cpp, src/lua/LuaGame.cpp, src/lua/LuaManager.cpp, src/lua/LuaManager.h, src/main.cpp
##' Bugs / Feature requests
Attempts to fix #5929 
The idea is to run this expensive task in an asynchronous job and notify the Lua side once it is completed. This is to prevent the stutter from occurring every time the SaveGameStats API is called from Lua.
The code was modified to call the expensive part of the SaveGameStats API (loading and parsing the game file) into a Job. Once finished, the data is marshalled into a LuaTable and a LuaEvent is triggered to pass the data to the Lua side.
The Lua side registers an Event listener, which parses the data and updates the SaveGame cache entry for the data.
Practically, this is achieved by the following changes :
* add a job manager to the LuaManager class which can run any job on
the Lua job queue.
* add a LoadGameToJsonJob implementation in …
=> refactor: run SaveGameStats in a job

src/posix/FileSystemPosix.cpp
Closes #5942
I've not reproduced the bug described in the issue above, but implemented the changes proposed and tested restart, and it creates a new pioneer config folder (for me under `~/.local/share/`)
=> Fix $HOME/.pioneer randomly created on Linux

data/modules/LifeSupport.lua
If there is no cargo bay life-support module installed, scooping certain cargo cannisters should degrade their contents.
This PR randomly turns live animals into animal meat, fertilizer, or even rubbish. Slaves are turned into fertilizer or rubbish.
=> feat: degrade scooped cargo requiring cargo life support

src/GeoSphere.h, src/lua/LuaMetaType.cpp, src/lua/LuaMetaType.h, src/lua/LuaObject.cpp, src/lua/LuaSpace.cpp, src/lua/LuaUtils.h, src/lua/core/Sandbox.cpp, src/pigui/LuaModelSpinner.cpp, src/pigui/LuaPiGui.cpp, src/pigui/PiGuiSandbox.cpp, src/scenegraph/Serializer.h
Thanks to @WickedSmoke (IRC) for pointing out that the debug builds were broken when "-DDEBUG" is specified as part of the build.
Specifically, "DEBUG" enables the "LUA_DEBUG" symbols, and these no longer compile in the current codebase. This patch fixes the compilation errors, but, notably, now cause runtime problems such as:
```
Pioneer/src/lua/LuaVector.cpp:240: lua stack difference is 1, expected 0
```
This patch also replaces all instances of checking "DEBUG" with checks against "NDEBUG" instead, as the latter is part of the C/C++ language standards and thus independant of any particular build system.
=> Fix builds which use "-DDEBUG"

data/pigui/modules/radar.lua
Similar to auto-zooming on ships, add the capability for the radar to auto-zoom on cargo containers. This is very useful when scooping multiple cargo containers in an area, as otherwise the radar is liable to zoom out to max-zoom-range in-between scooping containers. This makes it very difficult to lock on to the next container.
TODO: 
The radar should be switchable between auto and manual modes, with the manual mode being controllable by the keyboard/joystick. 
A radar mode and range indicator might also be useful to add.
In future, different radar equipment could provide different ranges and/or capabilities.
=> Improvement: Radar auto-zoom on cargo cannisters

data/libs/Passengers.lua
This PR contains the following fixes:
- fix(Passengers): fix boolean expression in Passengers:EmbarkPassenger
The precedence of a boolean expression is invalid, with the unary 'not' operator being evaluated before the arithmetic expression. This results in a comparison between a boolean and a number, which gives a runtime error.
This is fixed by refactoring the overall expression to remove the 'not' operator.
- avoid a nil dereference if hull can't fit any cabins in Passengers:GetMaxPassengersForHull
When generating certain types of missions, the logic attempts to fill a ship with passenger cabins. Under the new system it's possible that a hull can't fit any. Add a sanity check to ensure we never dereference a nil cabin.
=> fix(Passengers): fix crash bugs in Passengers introduced by equip-v2

data/lang/ui-core/en.json, data/pigui/libs/commodity-market.lua
Fixes #5903 
Replace the "Price" column with a "Buy Price" and "Sell Price" column. This reflects what the user of the commodity market actually needs to know, instead of delegating this information until after the user has started buying or selling a particular commodity.
Also right-aligns all numbers in the table, and middle-aligns the column headings for a much more readable table.
**Before:**
**After:**
=> Add Buy and Sell prices to the Commodity Market

data/models/cockpits/default_cockpit/default_cockpit.model
Fixes #5960 
I do have the normal map, I forgot to include it, it seems. But its effect is negligible, and the file is 6mb, so I'd rather remove it. (Or I could add it if you peeps think it should be there, could also reduce its 4k size).
=> Removing normal map from default cockpit materials

data/meta/Input.lua, data/modules/Debug/TestInput.lua, data/pigui/libs/forwarded.lua, data/pigui/modules/autopilot-window.lua, src/Input.cpp, src/Input.h, src/lua/Lua.cpp, src/lua/LuaInput.cpp, src/lua/LuaInput.h, src/lua/LuaPiGui.cpp, src/lua/LuaUtils.h, src/lua/core/Import.cpp, src/pigui/LuaPiGui.cpp, src/pigui/LuaPiGui.h, src/pigui/PiGuiSandbox.cpp
Since the Input subsystem was written, we've had partial support for interacting with it from Lua code. Over time, those capabilities have been expanded, but have remained strictly read-only.
This PR changes that, providing a proper way for Lua code to register input bindings, make those bindings active and able to receive input, and listen for input events coming from those bindings.
Now, Lua code can register Action/AxisBindings at startup, create an InputFrame to make those bindings active, push that frame when appropriate, register callbacks to be called from C++ when the input binding is activated, and then pop the input frame when the bindings should no longer be receiving input.
This PR does *not*:
- Provide support for Lua to add an Action/Axis binding to an InputFrame owned by …
=> Fully expose InputBindings to Lua

data/pigui/libs/radial-menu.lua, data/pigui/modules/flight-ui/reticule.lua, src/WorldView.cpp
Add a keybinding to open the target radial menu. The bind is empty by default as per the other target radials.
This allows keyboard controls to fly to, orbit, or dock with the current frame object or nav target, as appropriate.
=> feat(ui): add keybinding for target radial

CMakePresets.json, contrib/profiler/Profiler.cpp, src/Frame.cpp
Two minor changes:
- Disable the profiler in Debug builds on Linux because you shouldn't be profiling in Debug. The rationale for this is that Debug will behave very differently than Release builds and so the Profiling build is Release + Profiling tools.
- The 2nd is a compilation fix for MSVC under Profiling or Debug builds where a runtime string was being passed into a Profiling macro which failed to build. I tried a number of things to utilise it but it's the only example in the codebase so switched it out.
=> Linux de-profile and msvc compilation fix

data/pigui/modules/new-game-window/class.lua
Although setting up and even loading the correct equipment from the start variant does not yet work, there is no crash when choosing a different starting position.
Thanks to @fluffyfreak
Fixes #5969
=> Fix the ability to start from all start positions

CMakeLists.txt, contrib/profiler/Profiler.cpp, data/pigui/modules/station-view/04-shipMarket.lua, src/graphics/opengl/MaterialGL.cpp, src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h, src/graphics/opengl/UniformBuffer.cpp, src/graphics/opengl/UniformBuffer.h, src/graphics/opengl/VertexBufferGL.cpp, src/scenegraph/StaticGeometry.cpp
Another general collection of "fix" commits.
This PR adds additional profiling information to the renderer, and resolves an "early serialization" point which required the previous frame's rendering to be ~mostly complete before starting to record commands for the current frame.
I don't expect any significant performance increase from this PR, except in the case of extremely GPU-bound devices where you might see an improvement of up to a few milliseconds in frame-time, as more CPU work is able to be overlapped with the previous frame's GPU execution time.
This change does fully enforce the existing invariant that you must call `Renderer::SetLights()` *before* attempting to record a draw command using a lit material. An assertion will be thrown in debug mode if this invariant is broken.
It …
=> Allocate light data UBO from per-frame allocator, misc. fixes and cleanup

src/Player.cpp, src/sound/AmbientSounds.cpp, src/sound/Sound.cpp, src/sound/Sound.h, src/sound/SoundMusic.cpp, src/sound/SoundMusic.h
These commits cleanup the Sound and SoundMusic interfaces to allow plugging in an alternative backend (e.g. OpenAL) simply by switching out sound/Sound.cpp.
This pull request does not address the make file changes required to actually do this.  However, a working proof of concept can be found on [my repository](https://codeberg.org/wickedsmoke/pioneer/commits/branch/faun).
Future work could include:
- Adding a music crossfade method (to allow reducing the five mutex locks used in the SDL implementation down to one).
- Moving common backend code to it's own file.
=> Sound Cleanup

data/pigui/modules/radar.lua
By placing all of the radar drawing routines into a window, the mouse wheel is captured and is not passed back to the world view.
The work to add manual zoom to the 3D radar (#5958) failed to get this to function properly as the wrong API was used for setting the center of the 3D radar. Using 'setCursorScreenPops()' instead of 'setCursorPos()' has the 3D radar background being drawn properly  when placed inside a window.
~~TODO?: When zooming the 3D radar with the mouse, the mode is switched from automatic zoom to manual zoom, but there is not way (using the mouse) to switch the radar back to automatic zoom. Should there be? One option could be that zooming past the maximum zoom automatically switches back to auto-zoom, but testing shows that this is too easy to do accidentally.~~
-> …
=> feat(radar): capture mouse wheel for zooming radar

data/pigui/modules/info-view/06-flightlog.lua
Fixes #5986 
Should not modify an object while it is being iterated over..
----
Trivial to test: open the flight-log, add a couple of custom entries, then try to delete them.
=> fix(flightlog): fix crash when removing a flight log entry

data/ships/vatakara.json
Since they are essentially the same model apart some windows, Vatakara can use the malabar_shield. I believe the wrong data was from the Notion export autopulating the shield field
Fixes #5989
=> Updating Vatakara to use the shild mesh of the Malabar

src/Pi.cpp, src/Sfx.cpp
Fixes #5881 
It looks like we had the texture atlas selection inverted so it was playing from the "end" of the atlases animation.
I say "inverted" and "end" but these are slightly arbitrary because we define what they should be. However starting at the top-left is a reasonable convention and not an arbitrary point within the texture atlas, progressing to the top-left which is how it was behaving.
This is a handy test atlas with numbers in each slot so you can change `Sfx.ini` to point to it, and then instead of the explosion you can see the numbers counting up.
[test_atlas.zip](https://github.com/user-attachments/files/18241664/test_atlas.zip)
Taking the above test-atlas you could see it counting down from 30 to 0, which I think most people would find odd.
There was also an issue with it …
=> Fix billboard atlas animation playing order and frame count

src/graphics/Stats.cpp, src/graphics/Stats.h, src/graphics/opengl/RendererGL.cpp, src/pigui/PerfInfo.cpp
Extend the information shown about Instanced Draw Calls to include the total number of instances actually drawn by them.
I'm not sure about the formatting of the display `80 | 813 Instanced Calls` so would welcome feedback.
Maybe it should be `80 (813 total) Instanced` or something? There's not a lot of space available.
=> Display how many instanced objects are drawn

data/libs/Ship.lua, data/modules/Debug/DebugShip.lua, data/modules/MissionUtils/ShipBuilder.lua, data/modules/Scoop/Scoop.lua, data/pigui/libs/notification.lua, src/galaxy/StarSystemGenerator.cpp
- Fix ships spawned without enough threat value for the base hull receiving no equipment (fixes #6006)
- Fix assertion when spawning more police than a station has pads (no linked issue)
- Fix assertion when pressing the missile fire keybind with no installed missiles (fixes #6007)
- Fix assertion when hovering a notification (fixes #6004)
- Fix randomly-generated starports not having a population (fixes #5955).
The last one is the most interesting. Starports defined in custom system files exist when `PopulateStarSystemGenerator::PopulateStage1()` is called, but randomly-generated starports are only added afterwards, in `PopulateAddStations()`. This lead to a lack of actual population onboard those stations, which at current only manifested in a lack of paintshops outside of fully-custom …
=> Fix several minor bugs

data/lang/equipment-core/en.json, data/lang/ui-core/en.json, data/libs/EquipType.lua, data/modules/Equipment/Internal.lua, data/modules/Equipment/Weapons.lua, data/pigui/libs/equipment-outfitter.lua, data/pigui/modules/new-game-window/class.lua, data/ships/molaramsayi.json, data/ships/sinonatrix.json, data/ships/sinonatrix_police.json
WIP PR to add (placeholder) equipment and descriptions for all slot sizes.
Fixes #5950 , #5951
(Feel free to reserve a set of equipment, work on it, and push to this PR)
----
- translations: add a bunch of missing weapon hardpoint translation entries
- ships: fix fuel-scoop slot for the Sinonatrix (and Police variant) and the Mola Ramsayii; they were missing the "hardpoint":true flag on the slot, preventing it from accessing the correct translation string.
- equipment outfitter:
- added an optional "flavourtext" which can be supplied for equipment. This should be a longer description of the equipment. Possibly useful, but mostly for adding some background and lore into the game itself.
- fixed showing equipment stock levels
- added showing equipment stock levels in the equipment tab
- …
=> feat(equipment): add equipment for all size slots

data/libs/EquipSet.lua, data/libs/EquipType.lua, data/libs/Event.lua, data/libs/HullConfig.lua, data/libs/utils.lua, data/meta/ShipDef.lua, data/modules/Debug/CheckShipData.lua, data/modules/Debug/DebugLoader.lua, data/modules/Debug/DebugShip.lua, data/modules/Equipment/Internal.lua, data/modules/MissionUtils/ShipBuilder.lua, data/pigui/libs/equipment-outfitter.lua, data/pigui/libs/notification.lua, data/pigui/libs/ship-equipment.lua, data/pigui/modules/new-game-window/class.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/views/debug.lua, src/Pi.cpp, src/lua/LuaShipDef.cpp
This PR tackles one of the last outstanding issues with the equipment system, by introducing the concept of a required or "non-empty" equipment slot. Required slots must have a default item, and do not support being left empty.
As part of this work, I've written a front-end and framework to run arbitrary validation passes at game load time, and a set of validation functions for ship JSON definitions.
This allows us to have a much higher level of confidence in the data that's being exported from Notion, and significantly reduces the workload required to test individual ships and catch common errors (like missing language strings).
This PR also gives the `default` field a proper use now; when purchasing a ship, slots will be prefilled with the default items specified in the ship JSON. This …
=> Add support for required slots, validate shipdefs on startup

data/factions/079_Tolisian_Scientific_Community.lua, data/modules/Debug/CheckShipData.lua, data/pigui/views/debug.lua, data/pigui/views/mainmenu.lua, src/Background.cpp, src/galaxy/StarSystemGenerator.cpp
- Fixed a (potential) issue where the main menu doesn't know how to find the ship its displaying if the name of the model doesn't exactly match the name of the shipdef.
- Amended some validation warnings/errors to shuffle around their severity.
- Fixed a rogue trailing quote in the Tolisay faction name.
- Fixed #6022.
- Fixed #5880.
- Fixed #6012.
As is traditional for my microfix PRs in the weeks leading up to release, this is getting merged quite quickly.
=> More bugfixes and improvements

data/libs/EquipType.lua, data/libs/Ship.lua, data/meta/CoreObject/Ship.meta.lua, data/modules/Debug/DebugShip.lua, data/modules/Equipment/Weapons.lua, data/pigui/modules/equipment.lua, src/Missile.cpp, src/Missile.h, src/Player.cpp, src/Player.h, src/Ship.cpp, src/Ship.h, src/ShipType.cpp, src/ShipType.h, src/lua/LuaShip.cpp, src/ship/GunManager.cpp, src/ship/GunManager.h
Alternative title: finally fixed a bit of the mess that is missile handling in this game.
This PR rewrites how missiles get their "data", i.e. all parameters used in-flight. Missiles still reference a special ShipType file (one of the `missile_*.json` shipdefs), but we're no longer constrained to only four missile types any more!
What's more, Naval and Smart missiles now actually do more damage than regular guided missiles (as one would expect), and missiles in general got a bit better about detonating close to the target rather than at a 100m+ standoff.
As a quick perusal of `Missile.cpp` and `data/modules/Equipment/Weapons.lua` will show, most meaningful parameters for missiles are now defined in "data" rather than code, allowing mods to introduce new missile equipment and making it …
=> Improve Naval and Smart missiles

data/lang/ui-core/en.json, data/libs/EquipSet.lua, data/libs/EquipType.lua, data/libs/HullConfig.lua, data/libs/Ship.lua, data/meta/CoreObject/Body.meta.lua, data/modules/Debug/CheckShipData.lua, data/modules/Debug/DebugRPG.lua, data/modules/Equipment/Hyperdrive.lua, data/modules/MissionUtils/OutfitRules.lua, data/modules/MissionUtils/ShipBuilder.lua, data/modules/MissionUtils/ShipTemplates.lua, data/modules/SearchRescue/SearchRescue.lua, data/modules/TradeShips/Events.lua, data/modules/TradeShips/Flow.lua, data/modules/TradeShips/Trader.lua, data/pigui/modules/hyperjump-planner.lua, data/pigui/modules/info-view/01-ship-info.lua, data/pigui/modules/info-view/03-econ-trade.lua, data/pigui/modules/station-view/01-lobby.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/views/map-sector-view.lua
Redesigns the hyperdrive fuel use and duration-per-distance-travelled equations to implement the [redesign](https://dev.pioneerspacesim.net/design-document/hyperdrive-redesign) we've discussed and accepted.
This PR also converts hyperdrives to use an internal fuel reservoir rather than pulling directly from the cargo bay, and allows transferring fuel between the main tank and the hyperdrive reservoir. This enables fractional fuel usage in jumps - no longer will jumps of differing lengths use the same amount of fuel!
As part of this effort, about 50% of the capabilities of the planned fuel management UI were implemented; the fuel management will be left at this level until we get further time (after the upcoming release) to implement the full management interface.
This PR fully implements …
=> New hyperdrive algorithms and internal hyperfuel tanks

data/shaders/opengl/planetrings.frag
Urgh, `texture2D` is deprecated, it's replacement `texture` is the one to use.
Bug made possible by nVidia drivers just working despite that 🤦 always catches me out.
A big thankyou to `Natrix BQ-3566 pilot` from the Discord channel for pointing it out.
=> Replace `texture2D()` with `texture()`

cmake/TargetArchitecture.cmake
It's how BSD systems spell x86_64, so it's also PIONEER_TARGET_INTEL.
=> Add amd64 architecture

data/modules/Equipment/Types.lua
In `Types.lua`, the function `OnLeaveHyperspace()` currently adjusts the level of stored fuel without  calling `SetFuel`. The result is that the mass of the hyperdrive's fuel reserve does not decrease when fuel is used. To verify this, start a new game and jump anywhere; the reported mass of the hyperdrive will remain at 8.0 for a Mars start. The hyperdrive can gain a considerable amount of mass over time as the player refuels.
The fix is to call `SetFuel` in `OnLeaveHyperspace()` rather than adjusting `storedFuel` directly.
=> SetFuel after hyperjumps

src/BaseSphere.h, src/GasGiant.cpp, src/GeoSphere.cpp
This is a bit of tidying up, dealing with the old comment `//XXX no need to calculate AP every frame` by calculating the atmosphere parameters only once.
It does mean bumping the BaseSphere size from 48 bytes to 128 bytes but that can't really be avoided.
No visual or gameplay differences
=> Store AtmosphereParameters in BaseSphere, calculate with material setup

src/editor/CMakeLists.txt, src/modelcompiler.cpp
I noticed a bug/issue when trying to convert a single model to SGM format. It would only output the SGM to the full filepath if I specified `inplace` or some other 3rd parameter.
I've changed this to always find the full filepath regardless of having extra parameters.
The `Editor.exe` was also being output to a folder which meant I couldn't debug it from MSVC so for MSVC builds it now output to the CMAKE_SOURCE_DIR like the game and other tools.
=> Change modelcompiler single model filepathing, change Editor location for MSVC

src/graphics/opengl/VertexBufferGL.cpp
The lighting on the models that use a normal map were not looking correct and the normal map had no effect on lighting.
I setup a test shader that did a dump of a_tangent and it was always (0, 0, 0) which explained why the normal calc in the fragment shader was incorrect.  I then did a dump of a_uv1 and it had the tangent data.  I swapped the locations of a_tangent and a_uv1 in attributes.glsl and the lighting on normal mapped models now looks correct , to me :).
After some digging I found that attributes.glsl and Program.cpp have tangent at location 5 but the vertex buffer layout in VertexBufferGL.cpp (line 23) has tangent at index 4.
So by putting a_tangent in location 4 the lighting is now correct for models using a normal map
=> Fix  lighting on models that use normal maps

src/BaseSphere.cpp, src/BaseSphere.h, src/GasGiant.cpp, src/GasGiant.h, src/ObjectViewerView.cpp, src/Pi.cpp, src/TerrainBody.cpp, src/TerrainBody.h, src/graphics/Drawables.cpp, src/graphics/Drawables.h, src/lua/LuaEngine.cpp
Whilst doing something else I found that the Icosphere::Generate method wasn't reserving space for the indices it generates, and it was also miscalculating the number of vertices it would generate.
I spent some time trying to figure out a nifty formula to calculate those values and then realised I could just build a table of 11 entries for each of the valid subdivision we allow instead.
I have also increased the BaseSphere use of subdivision to 5 (from 4) for smoother atmospheres.
EDIT:
Made the `BaseSphere::m_atmos` into a static so it's only created once and used throughout the games lifetime instead of creating a new one for every single planet with an atmosphere. Making the icosphere generation faster is good, but avoiding doing it altogether is better still!
=> Make Sphere3D/Icosphere reserve space better

src/savegamedump.cpp
I was trying to use the `savegamedump.exe` to extract the JSON for a few save game file when debugging a crash issue reported on Discord. It refused to load the file and I realised that it was looking in the root of the userfiles location. However the savegames are actually saved in the sub-directory `savefiles`
~~This is a `draft` PR because I wonder if there's a better way to do the pathing. Otherwise I've tested it and it all works~~
I've tested it and it all works
=> Read/write save games from/to the savefiles folder

src/graphics/opengl/RendererGL.cpp, src/graphics/opengl/RendererGL.h, src/win32/OSWin32.cpp
Some minor tweaks I had laying around:
- Microsoft are annoying and Windows 11 is detect based on build number 🤦 
- We've actually been requesting an OpenGL 3.2 context since late 2020, so change the renderer description
- Output the OpenGL version and adapter info to the `output.log` file for easier error reporting
=> Detect Windows 11, update GL Renderer name

data/modules/Equipment/Hyperdrive.lua, data/pigui/libs/equipment-outfitter.lua
fix #6039
RE #6046 
This PR addresses two related issues:
* The `MILITARY` tech level causes a GUI crash in `renderCompareRow()` in `equipment-outfitter.lua` because it assumes a numeric value.
- Fix: If the tech level is `MILITARY`, in `renderCompareRow()`, skip the level comparison (if applicable) and render the level as the police shield icon (see screenshot).
* In `equipment-outfitter.lua`, `stationHasTech()` currently interprets `MILITARY` as tech level 11, making `MILITARY` equipment available in tech level 12 stations (e.g., Torvalds Platform).
- Fix: If the tech level is `MILITARY`, interpret the level as 11 as before, but only pass the check if the station's level is also 11. In addition, change the tech level for the S3 and S4 military drives to `MILITARY`.
=> Fix MILITARY tech level display and availability.

src/lua/LuaObject.cpp
In the serialization of the Lua objects there is a system of "one definition", when all subsequent mention of the object only refer to it. It is vital that the full definition meets before the rest of the refs to the object, otherwise an error occurs.
The same objects can now meet in different lua components, and this means that we must ensure the order of processing procedure during saving and loading.
fixes #6064
=> Sort lua components during serialization

.github/workflows/build-ci.yml
We need to update these, as github will deprecate them shortly (April?).
option is: 
- ubuntu 22.04
- ubuntu 24.04
- ubuntu-latest
=> Update ubuntu version 20.04 -> 22.04 for build

data/lang/ui-core/en.json, data/pigui/modules/station-view/06-shipRepairs.lua
Add a button to randomize the colors in the Paint Shop
It randomizes:
* All colors to different values (top image)
* Two colors the same value
* All colors the same value (bottom image)
=> Paint Shop - Randomize colors

data/pigui/modules/new-game-window/ship.lua
`ui.beginTable()` returns false if the OS window is minimize (as an optimization), need to consider this.
fixes #6040
=> Fix crash at alt-tab in the start menu equip tab

data/modules/Scout/Scout.lua
In response to https://github.com/pioneerspacesim/pioneer/issues/5760 where the BBS over time lose balance as some modules take over. Especially the Scout module keeps adding missions in excess of the demand. This is a quick fix to soften the issue and with this PR the missions balance out at around ~30 missions per station if none is take by the player.
The fix works by creating fewer adverts for Scout missions. One sixth of previous rate.
I haven't tested this other than sitting at Cydonia for 9 months and watching the mission list build up.
Here is what it looks like on master when the missions build up while not doing anything.
```
Number of ads per module after...
~2 months            ~4 months
------------------------------------------------------
Assassination               10 …
```
=> Balancing the Scout mission ads

data/libs/SpaceStation.lua, data/meta/Components/GunManager.meta.lua, data/modules/Equipment/Internal.lua, data/modules/Equipment/Types.lua, data/modules/Equipment/Weapons.lua, data/modules/FuelClub/FuelClub.lua, data/modules/GoodsTrader/GoodsTrader.lua, data/modules/SecondHand/SecondHand.lua, data/pigui/libs/chat-form.lua, data/pigui/libs/commodity-market.lua, data/pigui/modules/flight-ui/reticule.lua, data/pigui/modules/saveloadgame.lua, data/pigui/modules/station-view/02-bulletinBoard.lua, data/pigui/modules/station-view/04-shipMarket.lua, data/pigui/modules/system-econ-view.lua, data/pigui/modules/system-overview-window.lua, data/pigui/themes/default.lua, src/ship/GunManager.cpp
Missing the mark of a "hotfix" by about a month, this branch accumulates a number of fixes for items reported on the issue tracker.
- Fixes #6049 (display explicit size of item in addition to name).
- Fixes #6038.
- Fixes #6077.
- Fixes #6101.
- Fixes an unreported issue where double-clicking a save slot while saving the game attempted to quickload rather than quicksave.
- Fixes an unreported issue where you couldn't click on the second body of the same name in a system outliner (e.g. New Hope, New Hope).
- Fixes #6091.
- Mitigates #6099 by allowing ship follow modes to be disengaged even when out-of-range of the target.
- Fixes #5966.
- Fixes #6057. This includes a hack to force the default/0-th weapon group to disable the only-fire-with-target behavior, so as to match existing behavior …
=> Somewhat lukewarm fixes

data/pigui/modules/info-view/01-ship-info.lua
The ship info screen shows always 0 atm if no atmospheric shield is installed.
=> Fix pressure limit value if no atmo shield is installed

data/modules/SearchRescue/SearchRescue.lua, data/pigui/libs/wrappers.lua, data/pigui/views/game.lua, src/lua/LuaPiGui.cpp
Fixes #6041 by making all interactions properly clear the `PARTIAL` state flag after a successful transfer and triggering the start of a new interaction when the player takes off from the surface of a planet as well as undocking from a starport.
Fixes #6119 - it can be argued whether draggable popups (the ImGUI default) are actually a "bug" but at least the behavior is consistent with "user expectations" now.
=> Fix interrupted SAR missions, draggable popups in worldview

data/modules/CrewContracts/CrewContracts.lua
Introduce onUpdateBB to the CrewContracts module.
Some points:
* It's unclear to me what happens when a character is deleted when it's busy in an interview (onChat) but I believe another character gets removed (the next in line) instead when the character is employed and taken off the list. In any case the crew ad update doesn't seem to interfere with the onChat action with a candidate and it can be employed and will show up on the payroll.
Fixes https://github.com/pioneerspacesim/pioneer/issues/5510
=> CrewContracts - onUpdateBB

data/pigui/modules/info-view/03-econ-trade.lua
Fixes https://github.com/pioneerspacesim/pioneer/issues/6127, where you can pump back fuel when a hyper jump has been initiated.
=> Fix hyperspace fuel cheat

data/lang/module-findperson/en.json, data/modules/FindPerson/FindPerson.lua
The player has to find a person or a person with a ship and hand over a message. Which means hopping from station to station. Then return, or transport the person back. The ideas are taken from https://forum.pioneerspacesim.net/viewtopic.php?f=3&t=487. I tried to add some surprises like pirates firing missiles or mercenaries who try to intercept if close to the planet.
Unfortunately, merging this will cause two issues.
1. ~~The missile launch is not detected. No warning.~~ ~~No police action.~~
2. Close to a station, the mercenary can fire what he can. But the player is immediately attacked by the police.
While 2. can be solved later. ~~It would be great if someone can take care of 1. e.g. play a warning sound and trigger an event so that other modules can take action.~~
=> New mission: Find person

data/modules/System/Explore.lua
If you enter an unexplored system, your handy ship computer will go into exploration mode and try and map out what bodies are in the system. This doesn't work if you start a new game in an unexplored system (https://github.com/pioneerspacesim/pioneer/issues/5672).
There are options to give a path to a system when launching Pioneer from the command line but this always crash for me.
You can test the fix by patching the start menu with the path to an unexplored system where mars used to be.
```
diff --git a/data/pigui/modules/new-game-window/class.lua b/data/pigui/modules/new-game-window/class.lua
index 8314e82f0..5ea2e5f14 100644
--- a/data/pigui/modules/new-game-window/class.lua
+++ b/data/pigui/modules/new-game-window/class.lua
@@ -26,7 +26,7 @@ local profileCombo = { items = {}, …
```
=> Explore system on game start

data/lang/ui-core/en.json, data/libs/Legal.lua, data/modules/CrimeTracking/CrimeTracking.lua, src/Ship.cpp
~~_I hesitated a bit to submit this because of the overly harsh reaction if you happen to press the ecm button while taking off, but this is the same for all crime, dumping waste or firing a weapon. You will be terminated._~~
Updated: The effective range of the ban is now the same as the effective range of the ECM, 4 km.
I think there could be some more around this like a couple of the lights going out on the platform or the BBS being out of order the next time you land there. ECM should be used responsibly.
=> ECM crime - Don't use your ECM near a station

data/icons/icons.svg, data/pigui/themes/default.lua
Also adding them to the theme:
map_checkmark = 322,
about_questionmark = 323,
map_selectsystem = 324,
=> Adding new icons for sector map and about

src/SpaceStationType.cpp, src/SpaceStationType.h
These station types will not be selected by random generation and will only be used when explicitly specified by name in a custom system definition.
This is controlled with the `"custom_only"` key in the station.json file.
=> Support "custom only" station types

src/SectorView.cpp
Fixes #6142
When setting the hyperspace target, a check is in place which skips updating the target if it is in the same system as the current target.
This prevents changing the destination star in a multi-star system for the next jump. No such check exists when editing a jump further along a route.
The fix is to modify the check and only skip the update if the new hyperspace target is identical to the current target and not just whether they are in the same system.
**TEST:**
1. Download the save-game attached to the bug.
2. Load the save-game
3. Enter sector map
4. Click on "Dequ B" in the "Route Jumps" list
5. In the system information panel, click on "Dequ A"
6. In the system information panel, click on "Dequ B"
7. Initiate Hyperjump
8. Arrive in the vicinity of Dequ B
If the same …
=> fix: select star for hyperspace target

data/meta/Engine.lua, data/pigui/modules/settings-window.lua, src/Input.cpp, src/Input.h, src/core/IniConfig.cpp, src/core/IniConfig.h, src/lua/LuaEngine.cpp, src/lua/LuaInput.cpp, src/lua/LuaLang.cpp
This PR does two (mostly) related things:
- It prevents the config file from being written to disk on every toggle of a setting, only actually writing to disk when the settings menu is closed and there was a change in state.
- It moves the input bindings settings into their own `[Input]` section within the config file, preventing them from stomping (or being stomped by) actual user settings.
As we now have a generic settings interface for mods to read/write their own arbitrary settings, I consider it important to move the input bindings into their own section for the reason outlined above. It also has the nice side-effect of making config files neater and easier to read and debug.
Existing user-configured input bindings can be migrated with a simple cut-and-paste to the new `[Input]` …
=> Save settings to disk when closing the settings window

data/pigui/libs/radial-menu.lua
Implement a long-running TODO item in the target radial popup menu.
When the target is a departure hyperspace cloud and the player has a hyperspace cloud analyzer fitted, add a target option to set the players' hyperspace target to the destination system of the cloud.
TODO Items:
----
Update route planner:
Trying to `require` the hyperjumpPlanner directly results in an error "too many C levels".
Possibly we can expose the hyperjump-planner via a "gettter" on the system map object or otherwise have a small utility class for managing hyperspace jumps. Basically it should be possible to do everything which the player can do manually using the interface via an API. This could be useful for various missions.
There should also be a helper function to convert a SystemPath object into one which …
=> feat(ui): target radial support hyperspace clouds

data/lang/ui-core/en.json, data/libs/Mission.lua, data/modules/Assassination/Assassination.lua, data/modules/CargoRun/CargoRun.lua, data/modules/Combat/Combat.lua, data/modules/DeliverPackage/DeliverPackage.lua, data/modules/FindPerson/FindPerson.lua, data/modules/Scoop/Scoop.lua, data/modules/Scout/Scout.lua, data/modules/SearchRescue/SearchRescue.lua, data/modules/Taxi/Taxi.lua, data/pigui/libs/chat-form.lua, data/pigui/libs/radial-menu.lua, data/pigui/modules/info-view/04-missions.lua
I adopted the solution from the assassination module by simply overwriting mission.location.
In order not to change the mission description, I had to rename some variables.
If no defined return location is specified, the organization and, if necessary, the faction will be displayed.
Closes #6185
=> Show the return location in the mission list, if avaiable

data/pigui/modules/flight-ui/reticule.lua, src/lua/LuaPlayer.cpp, src/ship/PlayerShipController.cpp, src/ship/PlayerShipController.h
Probably a slightly more thorough solution to the problem of #6081. 
If earlier this problem was solved through the opportunity to manually turn off the follow mode, even when it is too far for it, now it is turned off automatically. Also, a different maximum range is assigned for different modes. For follow position mode, this is 1000 km, since it can be convenient for intercepting the ship. For the follow orientation mode, it is 10 km, since it makes little sense over long distances, and the ship most likely cannot correctly follow the rotating target.
Also along the way fixed some warnings in `PlayerShipController`.
=> Improve the follow modes for too far ranges
